Repository corona-warn-app/cwa-app-android, pull requests merged in 2020-07, with the labels that each got.

#787 Fix: Tracing clickable row switch
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
Labels: maintainers, ui

#795 Prevent automatic risk calculation in manual mode on app start
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/TracingViewModel.kt
Labels: maintainers

#612 Fix for switches not working on slide (Fixes #607)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsNotificationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataBindingAdapters.kt
  Corona-Warn-App/src/main/res/layout/include_settings_switch_row.xml
Labels: maintainers, ui

#797 Background Priority Texts
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#798 Background Priority - additional Strings
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#750 Turkish Translation
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/assets/privacy_tr.html
  Corona-Warn-App/src/main/assets/technical_tr.html
  Corona-Warn-App/src/main/assets/terms_tr.html
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#799 Fix Exception inside RetrieveDiagnosisKeysTransaction to avoid Error Dialogue
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
Labels: maintainers

#803 Fix: Added same like for the other languages
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers

#757 Add an animated exposure notification status icon
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_main.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataBindingAdapters.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_main.xml
  Corona-Warn-App/src/main/res/raw/ic_settings_tracing_animated.json
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataBindingAdaptersTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelperTest.kt
Labels: maintainers, ui

#800 Background Priority Service
  Corona-Warn-App/src/deviceForTesters/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/AndroidManifest.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/SettingsRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsBackgroundPriorityFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SettingsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ExternalActionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/PowerManagementHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelper.kt
  Corona-Warn-App/src/main/res/drawable/ic_settings_background_priority_disabled.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_background_priority_enabled.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_background_priority.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/ExternalActionHelperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelperTest.kt
Labels: maintainers

#801 Correct rounding of active tracing days
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/TimeVariables.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeAndDateExtensions.kt
Labels: maintainers

#804 Streamlined background worker
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundWorkHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundWorkScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalOneTimeWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalPeriodicWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalTimeCalculator.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/worker/BackgroundConstantsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/worker/BackgroundWorkHelperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalTimeCalculatorTest.kt
Labels: maintainers

#807 Update THIRD-PARTY-NOTICES
  THIRD-PARTY-NOTICES
Labels: maintainers

#794 Added contentDescription containing 'button' via formatters for screen readers (EXPOSUREAPP-1542)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_main.xml
  Corona-Warn-App/src/main/res/layout/include_risk_card.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelperTest.kt
Labels: maintainers, ui

#850 1.0.6-SNAPSHOT
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/deviceForTesters/java/de.rki.coronawarnapp/TestForAPIFragment.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_for_a_p_i.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/TimeVariables.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/keycache/KeyCacheRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/TracingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CachedKeyFileHolder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalOneTimeWorker.kt
  Corona-Warn-App/src/main/res/layout/fragment_main.xml
  Corona-Warn-App/src/main/res/layout/include_risk_card.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/CachedKeyFileHolderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelperTest.kt
  THIRD-PARTY-NOTICES
Labels: maintainers

#854 Version 1.1.0
  Corona-Warn-App/build.gradle
Labels: maintainers

#862 Lottie added
  Corona-Warn-App/src/main/assets/technical_de.html
  Corona-Warn-App/src/main/assets/technical_en.html
  Corona-Warn-App/src/main/assets/technical_tr.html
Labels: maintainers

#865 Technical documentation update with new lib Lottie
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/assets/technical_de.html
  Corona-Warn-App/src/main/assets/technical_en.html
  Corona-Warn-App/src/main/assets/technical_tr.html
Labels: maintainers

#863 version bump to 1.2.0-SNAPSHOT
  Corona-Warn-App/build.gradle
Labels: maintainers

#864 Feature/new error message
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ExceptionReporter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ReportingConstants.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/exception/reporting/ReportingConstantsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelperTest.kt
Labels: maintainers

#848 New animated icon for dark mode
  Corona-Warn-App/src/main/res/raw-night/ic_settings_tracing_animated.json
  Corona-Warn-App/src/main/res/raw/ic_settings_tracing_animated.json
Labels: maintainers, ui

#843 Enhance the stale data risk card if in manual mode
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RiskLevelTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RiskLevelTransactionTest.kt
Labels: maintainers

#849 Added explanation for location usage in onboarding flow (EXPOSUREAPP-1620)
  Corona-Warn-App/src/main/res/drawable/ic_location.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_tracing.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#827 Fix issue where test result is not spoken when refresh button is hit (EXPOSUREAPP-1540)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result.xml
Labels: maintainers

#802 Translation update
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelper.kt
  Corona-Warn-App/src/main/res/drawable/ic_location.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_background_priority_disabled.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_background_priority_enabled.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
  Corona-Warn-App/src/main/res/raw-night/ic_settings_tracing_animated.json
  Corona-Warn-App/src/main/res/raw/ic_settings_tracing_animated.json
  Corona-Warn-App/src/main/res/values-ar/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/exception/reporting/ReportingConstantsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataBindingAdaptersTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/worker/BackgroundWorkHelperTest.kt
Labels: maintainers

#791 Fix/submission error dialog
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionResultPositiveOtherWarningFragment.kt
Labels: maintainers

#853 Implemented a location state within connectivity helper (EXPOSUREAPP-1618)
  Corona-Warn-App/src/main/AndroidManifest.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/SettingsRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SettingsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ConnectivityHelper.kt
Labels: maintainers

#870 Open source libraries notice change
  Corona-Warn-App/src/main/assets/technical_de.html
  Corona-Warn-App/src/main/assets/technical_en.html
  Corona-Warn-App/src/main/assets/technical_tr.html
Labels: maintainers

#868 Changed proto field name
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/applicationconfiguration/ApplicationConfigurationService.kt
  Server-Protocol-Buffer/src/main/proto/applicationConfiguration.proto
Labels: maintainers

#866 Translation Update
  Corona-Warn-App/src/main/res/values-ar/strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers

#884 Replace lorem ipsum with translation texts
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#893 Release 1.1.1
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/device/java/de.rki.coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de.rki.coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/assets/technical_de.html
  Corona-Warn-App/src/main/assets/technical_en.html
  Corona-Warn-App/src/main/assets/technical_tr.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_risk_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
  Corona-Warn-App/src/main/res/layout/include_risk_details_period_logged_card.xml
  Corona-Warn-App/src/main/res/layout/include_risk_details_period_logged_progress.xml
  Corona-Warn-App/src/main/res/layout/include_setting_tracing_period_logged.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#882 Added a dialog to Onboarding for background restricted apps (EXPOSUREAPP-1758)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsFragment.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, ui

#901 Reset singletons after app reset (EXPOSUREAPP-1750)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/AppDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/ExposureSummaryRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/RiskLevelRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/keycache/KeyCacheRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/tracing/TracingIntervalRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataRetentionHelper.kt
Labels: fix-sprint1, maintainers

#902 Dev accessibility changes (EXPOSUREAPP-1540, EXPOSUREAPP-1541, EXPOSUREAPP-1542)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result.xml
  Corona-Warn-App/src/main/res/layout/include_submission_tan.xml
  Corona-Warn-App/src/main/res/layout/include_submission_test_result.xml
  Corona-Warn-App/src/main/res/layout/include_test_result_card.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: fix-sprint1, maintainers

#904 Added new error strings for invalid tan's in de/en/tr (EXPOSUREAPP-1745)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: fix-sprint1, maintainers

#903 Fixed tracing stop announcement and added missing links in terms and conditions (EXPOSUREAPP-1693, EXPOSUREAPP-1798)
  Corona-Warn-App/src/main/assets/terms_de.html
  Corona-Warn-App/src/main/assets/terms_tr.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
Labels: fix-sprint1, maintainers

#879 Added location state in tracing card screen (EXPOSUREAPP-1757)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelper.kt
  Corona-Warn-App/src/main/res/drawable/ic_settings_illustration_location_off.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, on hold

#898 Certificate pinning for download server (EXPOSUREAPP-1841)
  Corona-Warn-App/src/main/res/xml/network_security_config.xml
Labels: maintainers

#880 Translation Update
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#897 Stop notification when App is at End of life
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundWorkScheduler.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransactionTest.kt
Labels: maintainers

#914 Removed lorem ipsum references in translation files
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#915 Added en translation for background dialog
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#878 Dev into staging 1.2.0-SNAPSHOT release
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/assets/terms_de.html
  Corona-Warn-App/src/main/assets/terms_tr.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/AppDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/ExposureSummaryRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/RiskLevelRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/keycache/KeyCacheRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/tracing/TracingIntervalRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataRetentionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundWorkScheduler.kt
  Corona-Warn-App/src/main/res/drawable/ic_settings_illustration_location_off.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result.xml
  Corona-Warn-App/src/main/res/layout/include_submission_tan.xml
  Corona-Warn-App/src/main/res/layout/include_submission_test_result.xml
  Corona-Warn-App/src/main/res/layout/include_test_result_card.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/xml/network_security_config.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransactionTest.kt
Labels: maintainers

#922 Change of German term from 'Ortungsdienste' to 'Standortdienste'
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers

#909 Translation update
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#935 Translation Updates to Staging
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#944 Energy optimized and manual check warning dialogs (EXPOSUREAPP-1853)
  Corona-Warn-App/src/device/java/de.rki.coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ExternalActionHelper.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: fix-sprint2, maintainers

#942 fix: prevent overlapping texts for some languages (EXPOSUREAPP-1950)
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_main.xml
  Corona-Warn-App/src/main/res/layout/fragment_main.xml
Labels: fix-sprint2, maintainers

#936 Fix: Crash caused by Submission Duplicated IDs (EXPOSUREAPP-1875)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result.xml
Labels: fix-sprint2, maintainers

#943 Fix status priorities when bluetooth, location services or more are disabled at the same time (EXPOSUREAPP-1908)
  Corona-Warn-App/src/deviceForTesters/java/de.rki.coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/TracingStatusHelper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/TracingStatusHelperTest.kt
Labels: fix-sprint2, maintainers

#947 Added key retrieval logic in app's onCreate to include Googles WakeUpService
  Corona-Warn-App/build.gradle
  Corona-Warn-App/libs/play-services-nearby-18.0.2-eap.aar
  Corona-Warn-App/libs/play-services-nearby-18.0.3-eap.aar
  Corona-Warn-App/src/deviceForTesters/java/de.rki.coronawarnapp/TestForAPIFragment.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_for_a_p_i.xml
  Corona-Warn-App/src/main/AndroidManifest.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundWorkHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundWorkScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalOneTimeWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalPeriodicWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisTestResultRetrievalPeriodicWorker.kt
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: fix-sprint2, maintainers

#937 Text updates for risk-exposures on low-risk level card (EXPOSUREAPP-1737)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: fix-sprint2, maintainers

#951 Fix - Adjusted isBackgroundJobEnabled to consider battery optimization
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ConnectivityHelper.kt
Labels: maintainers

#950 Fix looping background restricition notification in onboarding (EXPOSUREAPP-1962)
  Corona-Warn-App/src/device/java/de.rki.coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ConnectivityHelper.kt
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, ui

#956 Updated base file with en update, deleted ru and ar for this release
  Corona-Warn-App/src/main/res/values-ar/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#957 Dev 1.2.0 to Staging
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/NotificationHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundWorkHelper.kt
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers
