Repository corona-warn-app/cwa-app-android, pull requests merged in 2020-10, with the labels that each got.

#1266 Solve unreliable tests
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/util/security/VerificationKeysTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentSetup.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/TimeVariables.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/calendar/CalendarView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/interoperability/InteroperabilityConfigurationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CWADebug.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/environment/EnvironmentSetupTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/TimeVariablesTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/PaddingToolTest.kt
Labels: 1.5.0, maintainers

#1271 Release 1.5.x house keeping 🧹
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/AppConfigModuleTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/interoperability/InteroperabilityConfigurationFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/security/EncryptionResetToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/security/SecurityHelperTest.kt
  Corona-Warn-App/src/test/java/testhelpers/extensions/CoroutinesTestExtension.kt
Labels: 1.5.0, maintainers

#1272 Remove manual set of screen orientation (Related to #779)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
Labels: maintainers

#1268 Update README.md
  README.md
Labels: maintainers

#1276 Interoperability: Make Changes to User Consent Text (Initial Onboarding) (EXPOSUREAPP-2938)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.5.0, legal, maintainers

#1278 Legal Textchange: Key Upload - Warn others (EXPOSUREAPP-2925)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.5.0, legal, maintainers

#1280 Legal Textchange: Exposure Logging Screen (EXPOSUREAPP-2923)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.5.0, legal, maintainers

#1281 Legal Textchange: Home Screen - FAQ Section (EXPOSUREAPP-2922)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.5.0, legal, maintainers

#1282 Legal Textchange: Initial Onboarding (EXPOSUREAPP-2920)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.5.0, legal, maintainers

#1283 Legal Textchange: Test Result Screen (EXPOSUREAPP-2918)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.5.0, legal, maintainers

#1284 Legal Textchange: Info Screen (EXPOSUREAPP-2917)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.5.0, legal, maintainers

#1288 Updated exposure tracing title (EXPOSUREAPP-2923)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.5.0, legal, maintainers

#1285 Legal Textchange: New Eula (Nutzungsbedingungen) (EXPOSUREAPP-2951)
  Corona-Warn-App/src/main/assets/terms_de.html
  Corona-Warn-App/src/main/assets/terms_en.html
  Corona-Warn-App/src/main/assets/terms_tr.html
Labels: 1.5.0, legal, maintainers

#1287 Interoperability: Changes to Data Privacy (EXPOSUREAPP-2954)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: 1.5.0, legal, maintainers

#1275 Interoperability: Make Changes to User Consent Text (Key Upload) (EXPOSUREAPP-2942)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.5.0, legal, maintainers

#1291 Submission result request handling fix (EXPOSUREAPP-3001)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
Labels: 1.5.0, maintainers

#1289 Follow up: Initital onboarding 3rd & 6th paragraph (EXPOSUREAPP-2920)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.5.0, legal, maintainers

#1292 Improve low storage error formatting (EXPOSUREAPP-2745)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ExceptionReporter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/FormattedError.kt
Labels: 1.5.0, enhancement, maintainers

#1293 Show the correct error if the initial app config download fails (EXPOSUREAPP-2747)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/AppConfigProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/AppConfigStorage.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/AppConfigProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/AppConfigStorageTest.kt
Labels: 1.5.0, bug, maintainers

#1279 Legal Textchange: Cross Country Exposure Logging Screen (EXPOSUREAPP-2924)
  Corona-Warn-App/src/main/res/layout/fragment_interoperability_configuration.xml
  Corona-Warn-App/src/main/res/layout/include_interoperability.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.5.0, legal, maintainers

#1277 Interoperability: Delta Onboarding (EXPOSUREAPP-2931, EXPOSUREAPP-2919)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.5.0, legal, maintainers

#1223 Interoperability: Submit days since onset of symptoms, Add 15th key to transmission risk vector (EXPOSUREAPP-2748, EXPOSUREAPP-2686)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/DaysSinceOnsetOfSymptomsVector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/DaysSinceOnsetOfSymptomsVectorDeterminator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/DefaultKeyConverter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ExposureKeyHistoryCalculations.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/KeyConverter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/SubmissionModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/Symptoms.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/TransmissionRiskVector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/TransmissionRiskVectorDeterminator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisInjectionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeAndDateExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/DaysSinceOnsetOfSymptomsVectorDeterminatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/ExposureKeyHistoryCalculationsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/TransmissionRiskVectorDeterminatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/TimeAndDateExtensionsTest.kt
  Server-Protocol-Buffer/src/main/proto/keyExportFormat.proto
Labels: 1.5.0, maintainers

#1269 Improve API test fragment and environment switching (DEV)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/DebugOptionsState.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/EnvironmentState.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/GoogleServicesState.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/LoggerState.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/TestForAPIFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/TestForApiFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_for_a_p_i.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyFileDownloader.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/BuildConfigWrap.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentSetup.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/AppSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/LiveDataExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/SmartLiveData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/ViewExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyFileDownloaderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/environment/BuildConfigWrapTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/environment/EnvironmentSetupTest.kt
  Corona-Warn-App/src/test/java/testhelpers/KotestExtensions.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/api/ui/TestForApiFragmentViewModelTest.kt
Labels: 1.5.0, enhancement, maintainers

#1294 Legal Textchange: Delta Interop Screen (EXPOSUREAPP-2919)
  Corona-Warn-App/src/deviceForTesters/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaInteroperabilityFragment.kt
  Corona-Warn-App/src/main/res/layout/include_interoperability.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.5.0, legal, maintainers

#1270 Legal Texts (EXPOSUREAPP-2954 , EXPOSUREAPP-2951, EXPOSUREAPP-2942, EXPOSUREAPP-2938, EXPOSUREAPP-2931, EXPOSUREAPP-2925, EXPOSUREAPP-2924, EXPOSUREAPP-2923, EXPOSUREAPP-2922, EXPOSUREAPP-2920, EXPOSUREAPP-2919, EXPOSUREAPP-2918, EXPOSUREAPP-2917)
  Corona-Warn-App/src/deviceForTesters/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
  Corona-Warn-App/src/main/assets/terms_de.html
  Corona-Warn-App/src/main/assets/terms_en.html
  Corona-Warn-App/src/main/assets/terms_tr.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaInteroperabilityFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_interoperability_configuration.xml
  Corona-Warn-App/src/main/res/layout/include_interoperability.xml
  Corona-Warn-App/src/main/res/layout/include_submission_positive_other_warning.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.5.0, legal, maintainers

#1295 Federation/EUR key-package file support (EXPOSUREAPP-3025)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentSetup.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisInjectionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/environment/EnvironmentSetupTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransactionTest.kt
Labels: 1.5.0, enhancement, maintainers

#1296 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: 1.5.0, maintainers

#1286 Reduce code duplication (EXPOSUREAPP-2844)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/device/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/device/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/TestForAPIFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuAdapter.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuItem.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/risklevel/ui/TestRiskLevelCalculationFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainActivityTestModule.kt
  Corona-Warn-App/src/deviceForTesters/res/drawable/ic_bug.xml
  Corona-Warn-App/src/deviceForTesters/res/drawable/ic_coffee.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_main.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_menu.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_menu_adapter_item.xml
  Corona-Warn-App/src/deviceForTesters/res/menu/menu_main.xml
  Corona-Warn-App/src/deviceForTesters/res/navigation/nav_graph.xml
  Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/lists/BaseAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CWADebug.kt
  Corona-Warn-App/src/main/res/menu/menu_main.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.5.0, enhancement, maintainers

#1298 Translation delivery and default strings (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.5.0, maintainers

#1297 1.5.0 Version bump
  Corona-Warn-App/build.gradle
Labels: 1.5.0, enhancement, maintainers

#1301 Better handling of unexpected supportedCountryData from the server (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/AppConfigProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/applicationconfiguration/ApplicationConfigurationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/interoperability/InteroperabilityRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/Country.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/CountryList.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/res/layout/fragment_interoperability_configuration.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_delta_interoperability.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_tracing.xml
  Corona-Warn-App/src/main/res/layout/include_interop_list_participating_countries_overview.xml
  Corona-Warn-App/src/main/res/layout/include_interoperability.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
  Corona-Warn-App/src/main/res/layout/include_submission_positive_other_warning.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/applicationconfiguration/ApplicationConfigurationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/interoperability/InteroperabilityConfigurationFragmentViewModelTest.kt
Labels: 1.5.0, bug, maintainers

#1307 Update prod_environments.json
  prod_environments.json
Labels: 1.5.0, bug, maintainers

#1299 Add coroutine dispatcher injection to fix tests (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyFileDownloader.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/coroutine/CoroutineModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/coroutine/DefaultDispatcherProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/coroutine/DispatcherProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyFileDownloaderTest.kt
  Corona-Warn-App/src/test/java/testhelpers/TestDispatcherProvider.kt
Labels: bug, maintainers

#1308 German text update: Zufallscode to Zufalls-ID (EXPOSUREAPP-3055)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.5.0, maintainers

#1313 Translation of legal strings to EN/TR (EXPOSUREAPP-2919, EXPOSUREAPP-2931, EXPOSUREAPP-2938, EXPOSUREAPP-2942)
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: 1.5.0, legal, maintainers, ui

#1314 Overlaying text in risk detection view (EXPOSUREAPP-3068)
  Corona-Warn-App/src/main/res/layout/include_interoperability.xml
Labels: 1.5.0, maintainers

#1315 Update data privacy & terms (en) (EXPOSUREAPP-2952 , EXPOSUREAPP-2951)
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/terms_en.html
Labels: maintainers

#1312 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers

#1318 Fix small typos and remove RKI Hotline (EXPOSUREAPP-2633)
  Corona-Warn-App/src/main/assets/terms_de.html
Labels: maintainers

#1316 Update default strings (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#1319 Eula & Data privacy tr (EXPOSUREAPP-2954, EXPOSUREAPP-2951)
  Corona-Warn-App/src/main/assets/privacy_tr.html
  Corona-Warn-App/src/main/assets/terms_en.html
  Corona-Warn-App/src/main/assets/terms_tr.html
Labels: maintainers

#1322 Version bump (DEV)
  Corona-Warn-App/build.gradle
Labels: 1.5.0, maintainers

#1323 Introduce translations for the button to skip the symptoms screen (EXPOSUREAPP-3088)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#1321 Fix code smells (code duplication) (EXPOSUREAPP-3058)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/http/CwaWebException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionTestResultFragment.kt
Labels: maintainers

#1332 Correct Protobuf format (EXPOSUREAPP-3071, EXPOSUREAPP-3049)
  Server-Protocol-Buffer/src/main/proto/applicationConfiguration.proto
Labels: bug, maintainers

#1328 Update privacy (EXPOSUREAPP-2954)
  Corona-Warn-App/src/main/assets/privacy_en.html
Labels: maintainers

#1333 Update privacy_en.html (EXPOSUREAPP-2954)
  Corona-Warn-App/src/main/assets/privacy_en.html
Labels: maintainers

#1335 Update legal_strings.xml (EXPOSUREAPP-2938)
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: maintainers

#1334 Add option to skip Symptoms Screens from Test Result (EXPOSUREAPP-3075)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
Labels: 1.5.0, maintainers

#1336 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers

#1338 Update privacy_tr.html (EXPOSUREAPP-2954)
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers

#1339 Update default translations (EXPOSUREAPP-3090)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#1340 Update legal_strings.xml (EXPOSUREAPP-2938)
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
Labels: maintainers

#1320 Introduce VM injection for home screen and enable screen testing (EXPOSUREAPP-2946, EXPOSUREAPP-2948)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/BaseUITest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestAppComponent.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestApplication.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestApplicationUIRunner.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/viewmodels/MockViewModelModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/TestForApiFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/risklevel/ui/TestRiskLevelCalculationFragmentCWAViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/AppConfigModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/AppConfigStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/DiagnosisKeysModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/legacy/LegacyKeyCacheMigration.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentSetup.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/ENFClientLocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/ENFModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/DeviceStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/SettingsRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/SubmissionModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeMenu.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/TracingExplanationDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/overview/MainOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/share/MainShareFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailsFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailsFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SettingsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/TracingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DialogHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/WatchdogService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/device/DefaultPowerManagement.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AndroidModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AppContext.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/EncryptedPreferencesFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/EncryptionErrorResetTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/FragmentExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/SmartLiveData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/viewmodel/CWAViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/verification/VerificationModule.kt
  Corona-Warn-App/src/main/res/layout/fragment_home.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/main/home/MainFragmentViewModelTest.kt
  Corona-Warn-App/src/testShared/java/testhelpers/BaseTest.kt
  Corona-Warn-App/src/testShared/java/testhelpers/logging/JUnitTree.kt
Labels: enhancement, maintainers

#1343 Text change: 9002 Error Recovery Notice (EXPOSUREAPP-3106)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#1341 Remove text section "Your test result was verified as positive." (EXPOSUREAPP-3075)
  Corona-Warn-App/src/main/res/layout/include_test_result_positive_steps.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#1331 Fix: Pop-up dialog for cancelation of the key upload appears on the wrong screen (EXPOSUREAPP-2915)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomIntroductionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionResultPositiveOtherWarningFragment.kt
Labels: maintainers, ui

#1347 Version bump (DEV)
  Corona-Warn-App/build.gradle
Labels: 1.5.0, maintainers

#1348 Add r8/proguard configuration to keep GSON related classes.
  Corona-Warn-App/proguard-rules.pro
Labels: bug, maintainers

#1330 code smell fixes (EXPOSURAPP-3058)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/server/DownloadInfo.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/GoogleAPIVersion.kt
Labels: maintainers

#1350 1.5.x into 1.6.x
  Corona-Warn-App/build.gradle
  Corona-Warn-App/proguard-rules.pro
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
  Corona-Warn-App/src/main/assets/terms_de.html
  Corona-Warn-App/src/main/assets/terms_en.html
  Corona-Warn-App/src/main/assets/terms_tr.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/server/DownloadInfo.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/http/CwaWebException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomIntroductionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/GoogleAPIVersion.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result.xml
  Corona-Warn-App/src/main/res/layout/include_interoperability.xml
  Corona-Warn-App/src/main/res/layout/include_test_result_positive_steps.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Server-Protocol-Buffer/src/main/proto/applicationConfiguration.proto
  prod_environments.json
Labels: maintainers

#1327 CircleCI pipeline improvement (DEV)
  .circleci/config.yml
  Corona-Warn-App/build.gradle
Labels: enhancement, maintainers

#1357 Moved sonar cloud report to device unit tests (DEV)
  .circleci/config.yml
Labels: maintainers

#1355 Merge 1.5.x into 1.6.x
  .circleci/config.yml
  Corona-Warn-App/build.gradle
Labels: maintainers

#1349 Remove static context access from databinding accessibility formaters (EXPOSUREAPP-2746)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FromatterAccessibilityHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/bindingadapters/AccessibilityBindingAdapters.kt
  Corona-Warn-App/src/main/res/layout/fragment_home.xml
  Corona-Warn-App/src/main/res/layout/fragment_risk_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_qr_code_scan.xml
  Corona-Warn-App/src/main/res/layout/include_button_icon.xml
  Corona-Warn-App/src/main/res/layout/include_dispatcher_card.xml
  Corona-Warn-App/src/main/res/layout/include_information_details.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
  Corona-Warn-App/src/main/res/layout/include_submission_contact.xml
  Corona-Warn-App/src/main/res/layout/include_submission_done.xml
  Corona-Warn-App/src/main/res/layout/include_submission_intro.xml
  Corona-Warn-App/src/main/res/layout/include_submission_positive_other_warning.xml
  Corona-Warn-App/src/main/res/layout/include_tracing_status_card.xml
  Corona-Warn-App/src/main/res/layout/include_tracing_status_card_location.xml
Labels: maintainers

#1353 Fix FAQ link in TR (EXPOSUREAPP-2515)
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers

#1361 Separate link from text (EXPOSUREAPP-3056)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailsFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_risk_details.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#1364 Update legal_strings.xml (EXPOSUREAPP-2012)
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: maintainers

#1351 Fix test readability (DEV)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/DaysSinceOnsetOfSymptomsVectorDeterminatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/TransmissionRiskVectorDeterminatorTest.kt
Labels: maintainers

#1359 Improving Sonarcloud Scans (EXPOSUREAPP-2772)
  .circleci/config.yml
Labels: maintainers

#1366 1.5.x into 1.6.x (DEV)
  .circleci/config.yml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: maintainers

#1367 Version bump (DEV)
  Corona-Warn-App/build.gradle
Labels: maintainers

#1362 Introduce new link key (EXPOSUREAPP-3056)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailsFragment.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#1305 Make it easier for devs to locally test release builds (DEV)
  .gitignore
  Corona-Warn-App/build.gradle
Labels: enhancement, maintainers

#1368 Remove NDK (DEV)
  .circleci/config.yml
  Corona-Warn-App/build.gradle
Labels: maintainers

#1369 Disable Jetifier (DEV)
  Corona-Warn-App/build.gradle
  gradle.properties
Labels: maintainers

#1379 QR Code: Textual enhancement of test result screen (EXPOSUREAPP-3012)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers

#1381 Update terms DE (DEV)
  Corona-Warn-App/src/main/assets/terms_de.html
Labels: maintainers

#1375 Fix behavior of last 3 hours test mode switch (EXPOSUREAPP-3179)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyFileDownloader.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/server/DiagnosisKeyServer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyFileDownloaderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/server/DiagnosisKeyServerTest.kt
Labels: bug, maintainers

#1372 Country list on Risiko-Ermittlung AFTER WLAN ON (EXPOSUREAPP-3152)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/interoperability/InteroperabilityConfigurationFragment.kt
Labels: maintainers

#1326 Information on how to scan QR Code (EXPOSUREAPP-2581)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionQRCodeInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionQRCodeInfoModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionQRCodeInfoFragmentViewModel.kt
  Corona-Warn-App/src/main/res/drawable/ic_illustrations_qr_code_scan_info.xml
  Corona-Warn-App/src/main/res/drawable/ic_illustrations_qr_code_scan_info_dark.xml
  Corona-Warn-App/src/main/res/drawable/ic_qr_icon_info.xml
  Corona-Warn-App/src/main/res/drawable/ic_qr_icon_multiple_tests.xml
  Corona-Warn-App/src/main/res/drawable/ic_qr_icon_personal_result.xml
  Corona-Warn-App/src/main/res/drawable/ic_qr_icon_test_scan.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_qr_code_info.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionQRCodeInfoFragmentViewModelTest.kt
Labels: maintainers

#1382 Version bump
  Corona-Warn-App/build.gradle
Labels: maintainers

#1386 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, maintainers

#1387 Master into 1.4.x (DEV)
  CONTRIBUTING.md
Labels: maintainers

#1388 1.4.x into 1.5.x (DEV)
  CONTRIBUTING.md
Labels: maintainers

#1384 Test menu Random IDs share handled (EXPOSUREAPP-3163)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/TestForAPIFragment.kt
Labels: maintainers

#1389 1.5.x into 1.6.x (DEV)
  CONTRIBUTING.md
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/assets/terms_de.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyFileDownloader.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/server/DiagnosisKeyServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/interoperability/InteroperabilityConfigurationFragment.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyFileDownloaderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/server/DiagnosisKeyServerTest.kt
Labels: maintainers

#1371 Setup new internal release pipeline (DEV)
  .pipeline/Jenkinsfile
Labels: maintainers

#1383 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers

#1391 Update default strings (DEV)
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#1352 Taskcontroller logic (EXPOSUREAPP-2743)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/device/java/de/rki/coronawarnapp/test/DeviceForTestersModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/DeviceForTestersModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/tasks/TaskControllerTestModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/tasks/testtask/TestTask.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/tasks/ui/TestTaskControllerFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/tasks/ui/TestTaskControllerFragmentModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/tasks/ui/TestTaskControllerFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainActivityTestModule.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_task_controller.xml
  Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/MissingTaskFactoryException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/Task.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/TaskCancellationException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/TaskController.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/TaskCoroutineScope.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/TaskFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/TaskInfo.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/TaskRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/TaskState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/TaskTypeKey.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/common/DefaultProgress.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/common/DefaultTaskRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/example/QueueingTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/example/QueueingTaskModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/internal/InternalTaskState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/internal/TaskModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/CachedString.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/LazyString.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/TaskControllerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/TaskStateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/example/SkippingTask.kt
  Corona-Warn-App/src/test/java/testhelpers/coroutines/FlowTest.kt
  Corona-Warn-App/src/test/java/testhelpers/extensions/TimeExtensions.kt
Labels: enhancement, maintainers

#1396 Revert NDK removal (DEV)
  .circleci/config.yml
  Corona-Warn-App/build.gradle
Labels: bug, maintainers

#1400 Update strings.xml (EXPOSUREAPP-2924)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers

#1398 Update terms_en.html (EXPOSUREAPP-3148)
  Corona-Warn-App/src/main/assets/terms_en.html
Labels: maintainers

#1399 Update strings.xml (EXPOSUREAPP-2923)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers

#1402 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers

#1404 Added dark illustration for QR Info screen (EXPOSUREAPP-2581)
  Corona-Warn-App/src/main/res/drawable-night/ic_illustrations_qr_code_scan_info.xml
Labels: maintainers

#1405 Update default strings (DEV)
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#1403 Small button colour change to more closely align with design (EXPOSUREAPP-3089)
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result.xml
Labels: maintainers

#1385 Disabled dates which exceed 21 days in the past (EXPOSUREAPP-3191)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/calendar/CalendarDayViewHolder.kt
Labels: bug, maintainers

#1337 Onboarding flow refactor (EXPOSUREAPP-2995)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaInteroperabilityFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTestFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTestFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTestModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTestViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragmentViewModel.kt
  Corona-Warn-App/src/main/res/layout/fragment_onboarding.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_privacy.xml
Labels: enhancement, maintainers

#1406 Increase transaction timeout (EXPOSUREAPP-3238)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/TimeVariables.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/TimeVariablesTest.kt
Labels: maintainers

#1409 Version bump (DEV)
  gradle.properties
Labels: maintainers

#1408 Update terms_tr.html (EXPOSUREAPP-3148)
  Corona-Warn-App/src/main/assets/terms_tr.html
Labels: maintainers

#1407 TaskController: Support timeout behavior (EXPOSUREAPP-2842)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/tasks/testtask/TestTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/TaskController.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/TaskFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/common/DefaultTaskRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/example/QueueingTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/TaskControllerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/testtasks/SkippingTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/testtasks/timeout/BaseTimeoutTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/testtasks/timeout/TimeoutTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/testtasks/timeout/TimeoutTask2.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/testtasks/timeout/TimeoutTaskArguments.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/testtasks/timeout/TimeoutTaskConfig.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/testtasks/timeout/TimeoutTaskResult.kt
Labels: enhancement, maintainers

#1395 Change "last3HoursMode" to "24 hour mode" and cleanup related code (DEV)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/DebugOptionsState.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/TestForAPIFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/TestForApiFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_for_a_p_i.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyFileDownloader.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/AppSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/TestSettings.kt
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyFileDownloaderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/TestSettingsTest.kt
  Corona-Warn-App/src/test/java/testhelpers/KotestExtensions.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/api/ui/TestForApiFragmentViewModelTest.kt
Labels: enhancement, maintainers

#1417 Update legal_strings.xml (EXPOSUREAPP-2942)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
Labels: maintainers

#1410 Refactor submission flow fragments (EXPOSUREAPP-2746)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SymptomCalendarEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SymptomIntroductionEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionDoneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionIntroFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionQRCodeInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionSymptomCalendarFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionSymptomIntroductionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionContactModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionContactViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionDispatcherModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionDispatcherViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionDoneModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionDoneViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionIntroModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionIntroViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionQRCodeScanModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionQRCodeScanViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionResultPositiveOtherWarningModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionResultPositiveOtherWarningViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionSymptomCalendarModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionSymptomCalendarViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionSymptomIntroductionModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionSymptomIntroductionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionTanModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionTanViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionTestResultModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionTestResultViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
Labels: enhancement, maintainers

#1437 CircleCI signed RC build (EXPOSUREAPP-2773)(DEV)
  .circleci/config.yml
  Corona-Warn-App/build.gradle
Labels: enhancement, maintainers

#1433 Fix automatic data reset on for users affected by encryption issues (EXPOSUREAPP-3313, EXPOSUREAPP-3335)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/errors/RecoveryByResetDialogFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/EncryptionErrorResetTool.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/security/EncryptionResetToolTest.kt
Labels: bug, maintainers

#1439 Increase transaction timeout (EXPOSUREAPP-3238, EXPOSUREAPP-3335) (#1406)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/TimeVariables.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/TimeVariablesTest.kt
Labels: maintainers

#1436 Release 1.6.x housekeeping 🧹 (DEV)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/DaysSinceOnsetOfSymptomsVectorDeterminatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/TransmissionRiskVectorDeterminatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/main/home/MainFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/start/SettingsTracingStateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/tracing/card/TracingCardStateTest.kt
  Corona-Warn-App/src/test/java/testhelpers/coroutines/FlowTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/api/ui/TestForApiFragmentViewModelTest.kt
Labels: maintainers

#1442 Version bump (DEV)
  Corona-Warn-App/build.gradle
Labels: maintainers

#1452 Fix/LocalData - isInteroperabilityShownAtLeastOnce - set(value) to commit=true
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
Labels: bug, community

#1449 Internal signing fix (DEV)
  Corona-Warn-App/build.gradle
Labels: bug, maintainers

#1454 Update strings.xml (EXPOSUREAPP-3384)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers

#1448 [Test] ProtoBuf Update at Wed Oct 21 13:15:13 UTC 2020
  Server-Protocol-Buffer/src/main/proto/external/exposurenotification/diagnosis_key_batch.proto
  Server-Protocol-Buffer/src/main/proto/external/exposurenotification/temporary_exposure_key_export.proto
  Server-Protocol-Buffer/src/main/proto/external/exposurenotification/temporary_exposure_key_signature_list.proto
  Server-Protocol-Buffer/src/main/proto/internal/app_config.proto
  Server-Protocol-Buffer/src/main/proto/internal/app_features.proto
  Server-Protocol-Buffer/src/main/proto/internal/app_version_config.proto
  Server-Protocol-Buffer/src/main/proto/internal/attenuation_duration.proto
  Server-Protocol-Buffer/src/main/proto/internal/risk_level.proto
  Server-Protocol-Buffer/src/main/proto/internal/risk_score_classification.proto
  Server-Protocol-Buffer/src/main/proto/internal/risk_score_parameters.proto
  Server-Protocol-Buffer/src/main/proto/internal/submission_payload.proto
Labels: maintainers

#1461 Streamlined rc naming
  .circleci/config.yml
Labels: enhancement, maintainers

#1462 1.6.0 version bump
  gradle.properties
Labels: maintainers

#1463 Version bump (DEV)
  gradle.properties
Labels: maintainers

#1460 Delta onboarding: legal strings back to normal strings (EXPOSUREAPP-3078)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#1450 Update dependency group for work and test related (EXPOSUREAPP-3289)
  Corona-Warn-App/build.gradle
  build.gradle
Labels: maintainers

#1455 Switch to centralized ProtoBuf format (EXPOSUREAPP-3404)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/AppConfigProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/ApplicationConfigurationExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/Playbook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/DefaultRiskLevelCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/applicationconfiguration/ApplicationConfigurationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/DefaultKeyConverter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ExposureKeyHistoryCalculations.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/KeyConverter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/server/SubmissionApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/server/SubmissionServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RiskLevelTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/update/UpdateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/KeyFileHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ProtoFormatConverterExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/SignatureHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/VerificationKeys.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/ApplicationConfigurationExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskLevelCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/ExposureKeyHistoryCalculationsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/server/SubmissionApiV1Test.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/server/SubmissionServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RiskLevelTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransactionTest.kt
  Server-Protocol-Buffer/src/main/proto/applicationConfiguration.proto
  Server-Protocol-Buffer/src/main/proto/keyExportFormat.proto
  Server-Protocol-Buffer/src/main/proto/qrCode.proto
Labels: maintainers

#1390 Hide app content in app launcher (EXPOSUREAPP-2612)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
Labels: maintainers

#1476 Update strings.xml (EXPOSURREAPP-3384)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers

#1477 Release/1.5.x
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/TimeVariables.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/errors/RecoveryByResetDialogFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/EncryptionErrorResetTool.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/TimeVariablesTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/security/EncryptionResetToolTest.kt
Labels: maintainers

#1478 Include hotline notice (EXPOSUREAPP-3432)
  Corona-Warn-App/src/main/res/layout/include_submission_contact.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#1464 Fix text issues for low risk with 0/1+ encounters (EXPOSUREAPP-3193)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/tracing/details/DefaultRiskDetailPresenter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/tracing/details/TracingDetailsState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/tracing/details/TracingDetailsStateProvider.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/riskdetails/DefaultRiskDetailPresenterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/tracing/details/TracingDetailsStateTest.kt
Labels: bug, maintainers, prio

#1356 Unreliable background priority (EXPOSUREAPP-3094)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsBackgroundPriorityFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_settings_background_priority.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, prio, ui

#1479 Deadman notification text (EXPOSUREAPP-2332)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: enhancement, maintainers, prio

#1472 Update EncryptedPreferencesFactory (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/EncryptedPreferencesFactory.kt
Labels: maintainers

#1484 Legal Textchange: Delta Onboarding (EXPOSUREAPP-3441)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#1481 Cannot delete tests older than 21 days - DE: Tests die älter als 21 Tage sind, können nicht gelöscht werden (EXPOSUREAPP-2398)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/SubmissionCardState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/TestResultCardFetchFailed.kt
  Corona-Warn-App/src/main/res/layout/fragment_home.xml
  Corona-Warn-App/src/main/res/layout/view_submission_status_card_fetch_failed.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/SubmissionCardStateTest.kt
Labels: maintainers, prio, ui

#1473 Monitor ENF calculation more closely for better progress feedback (EXPOSUREAPP-2743)
  Corona-Warn-App/src/main/AndroidManifest.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentSetup.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/UnknownBroadcastException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/ENFClient.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/ENFModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/calculationtracker/Calculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/calculationtracker/CalculationTracker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/calculationtracker/CalculationTrackerStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/calculationtracker/DefaultCalculationTracker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/receiver/ExposureStateUpdateReceiver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/receiver/ReceiverBinder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/TracingRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/tracing/card/TracingCardState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/tracing/card/TracingCardStateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/tracing/common/BaseTracingState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/tracing/details/TracingDetailsState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/tracing/details/TracingDetailsStateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/tracing/settings/SettingsTracingFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/BackgroundModeStatus.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/MapExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/bluetooth/BluetoothProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/flow/FlowExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/flow/HotDataFlow.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/gson/GsonExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/location/LocationProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/BaseGson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/SerializationModule.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/environment/EnvironmentSetupTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/ENFClientTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/modules/calculationtracker/CalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/modules/calculationtracker/CalculationTrackerStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/modules/calculationtracker/DefaultCalculationTrackerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/receiver/ExposureStateUpdateReceiverTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/TaskControllerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/tracing/GeneralTracingStatusTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionCountrySelectViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/tracing/card/TracingCardStateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/tracing/common/BaseTracingStateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/tracing/details/TracingDetailsStateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/bluetooth/BluetoothProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/flow/HotDataFlowTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/location/LocationProviderTest.kt
  Corona-Warn-App/src/test/java/testhelpers/coroutines/FlowTest.kt
  Corona-Warn-App/src/test/java/testhelpers/coroutines/TestExtensions.kt
Labels: bug, enhancement, maintainers, prio

#1474 Switch to centralized ProtoBuf format (EXPOSUREAPP-3404)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/AppConfigProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/ApplicationConfigurationExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/Playbook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/DefaultRiskLevelCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/applicationconfiguration/ApplicationConfigurationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/DefaultKeyConverter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ExposureKeyHistoryCalculations.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/KeyConverter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/server/SubmissionApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/server/SubmissionServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RiskLevelTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/update/UpdateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/KeyFileHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ProtoFormatConverterExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/SignatureHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/VerificationKeys.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/ApplicationConfigurationExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskLevelCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/ExposureKeyHistoryCalculationsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/server/SubmissionApiV1Test.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/server/SubmissionServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RiskLevelTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransactionTest.kt
  Server-Protocol-Buffer/src/main/proto/applicationConfiguration.proto
  Server-Protocol-Buffer/src/main/proto/external/exposurenotification/diagnosis_key_batch.proto
  Server-Protocol-Buffer/src/main/proto/external/exposurenotification/temporary_exposure_key_export.proto
  Server-Protocol-Buffer/src/main/proto/external/exposurenotification/temporary_exposure_key_signature_list.proto
  Server-Protocol-Buffer/src/main/proto/internal/app_config.proto
  Server-Protocol-Buffer/src/main/proto/internal/app_features.proto
  Server-Protocol-Buffer/src/main/proto/internal/app_version_config.proto
  Server-Protocol-Buffer/src/main/proto/internal/attenuation_duration.proto
  Server-Protocol-Buffer/src/main/proto/internal/risk_level.proto
  Server-Protocol-Buffer/src/main/proto/internal/risk_score_classification.proto
  Server-Protocol-Buffer/src/main/proto/internal/risk_score_parameters.proto
  Server-Protocol-Buffer/src/main/proto/internal/submission_payload.proto
  Server-Protocol-Buffer/src/main/proto/keyExportFormat.proto
  Server-Protocol-Buffer/src/main/proto/qrCode.proto
Labels: maintainers

#1490 Update strings.xml (EXPOSUREAPP-3452)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#1418 Homescreen Notifications, even though keys were submitted (EXPOSUREAPP-3181, EXPOSUREAPP-3182)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/SubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RiskLevelTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisTestResultRetrievalPeriodicWorker.kt
Labels: backend, maintainers, prio

#1488 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers, text change

#1491 Update default strings (DEV)
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#1489 Improve logging and data emission (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/calculationtracker/DefaultCalculationTracker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/flow/HotDataFlow.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/flow/HotDataFlowTest.kt
Labels: maintainers

#1492 Grant one more encryption reset attempt for users on v1.6.0 (EXPOSUREAPP-3313)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/EncryptionErrorResetTool.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/security/EncryptionResetToolTest.kt
Labels: bug, maintainers, prio

#1431 Delete country list cache (EXPOSUREAPP-3154)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/AppConfigHttpCache.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/AppConfigModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/AppConfigProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/AppConfigStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/RiskLevelRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/interoperability/InteroperabilityRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/AppConfigApiTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/AppConfigProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/AppConfigStorageTest.kt
Labels: bug, maintainers

#1480 Added logic for showing notification on risk level change (EXPOSUREAPP-2569)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RiskLevelTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: enhancement, maintainers, text change

#1495 1.5.x into 1.6.x
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/errors/RecoveryByResetDialogFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/EncryptionErrorResetTool.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/security/EncryptionResetToolTest.kt
Labels: maintainers

#1494 Version bump (DEV)
  gradle.properties
Labels: maintainers

#1499 Version bump (DEV)
  gradle.properties
Labels: maintainers

#1498 Version bump (DEV)
  gradle.properties
Labels: maintainers

#1500 Version bump (DEV)
  gradle.properties
Labels: maintainers

#1475 Improved crash logging & handling (EXPOSUREAPP-2572)
  .idea/codeStyles/Project.xml
  Corona-Warn-App/build.gradle
  Corona-Warn-App/schemas/de.rki.coronawarnapp.bugreporting.storage.BugDatabase/1.json
  Corona-Warn-App/schemas/de.rki.coronawarnapp.storage.AppDatabase/2.json
  Corona-Warn-App/src/device/java/de/rki/coronawarnapp/bugreporting/BugReportingModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/BugReportingModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/event/BugEvent.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/event/BugEventEntity.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/event/DefaultBugEvent.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/loghistory/RollingLogHistory.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/processor/BugProcessor.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/processor/DefaultBugProcessor.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/reporter/DefaultBugReporter.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/storage/BugDatabase.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/storage/dao/BugDao.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/storage/dao/DefaultBugDao.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/storage/repository/BugRepository.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/storage/repository/DefaultBugRepository.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/DeviceForTestersModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/crash.ui/CrashReportAdapter.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/crash.ui/SettingsCrashReportDetailsFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/crash.ui/SettingsCrashReportFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/crash.ui/SettingsCrashReportFragmentModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/crash.ui/SettingsCrashReportViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_crashreporter_overview.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_settings_crash_report_details.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_menu.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/view_crashreport_list_item.xml
  Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/BugReporter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/loghistory/LogHistoryTree.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ExceptionReporter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/AppDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/database/CommonConverters.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/res/menu/menu_main.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, prio

#1501 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers
