Repository corona-warn-app/cwa-app-android, pull requests merged in 2020-08, with the labels that each got.

#963 Changed background prio dialogs and texts
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RiskLevelTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/TracingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ConnectivityHelper.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RiskLevelTransactionTest.kt
Labels: maintainers

#961 Text changes for the high risk description (EXPOSUREAPP-1994, EXPOSUREAPP-1999)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#969 Translation Delivery
  Corona-Warn-App/src/main/res/values-ar/strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers

#971 Fix: Deleted russian and arabic and updated default strings
  Corona-Warn-App/src/main/res/values-ar/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#972 Re-schedule jobs if they were killed and the app was woken up by the WakeUpService
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
Labels: maintainers

#975 Dev 1.2.0 to Staging
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#977 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers

#978 deleted ru file and updated base string file
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#979 Dev to Staging 1.2.0
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#973 Update ReadMe #395
  README.md
Labels: maintainers

#946 WIP: plausible deniability
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/WebRequestBuilder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/playbook/BackgroundNoise.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/playbook/Playbook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/playbook/PlaybookImpl.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/requests/RegistrationRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/requests/RegistrationTokenRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/requests/TanRequestBody.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/service/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/service/VerificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/diagnosiskey/DiagnosisKeyConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/diagnosiskey/DiagnosisKeyService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/HashHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/SecurityHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundNoiseOneTimeWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundNoisePeriodicWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundWorkBuilder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundWorkHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundWorkScheduler.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/playbook/PlaybookImplTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/service/SubmissionServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/service/VerificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/diagnosiskey/DiagnosisKeyConstantsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/SubmissionConstantsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/SubmissionServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/MockWebServerUtil.kt
  Server-Protocol-Buffer/src/main/proto/keyExportFormat.proto
Labels: do not merge, maintainers

#989 Added support for new TestResult and DeviceUIState based on EXPOSUREAPP-1743
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/SubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DeviceUIState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/TestResult.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: backend, maintainers, ui

#994 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers

#992 Check if ENF is enabled before getting the exposure summary (EXPOSUREAPP-2080)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/ExposureSummaryRepository.kt
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/ExposureSummaryRepositoryTest.kt
Labels: maintainers, on hold

#995 Dev 1.3.0 to RC/1.3.0
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/ExposureSummaryRepository.kt
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/ExposureSummaryRepositoryTest.kt
Labels: maintainers

#996 Append google apiexception statuscode to detailsTitle (EXPOSUREAPP-2081)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorReportReceiver.kt
Labels: maintainers

#999 Dev 1.3.0 to RC/1.3.0
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorReportReceiver.kt
Labels: maintainers

#1004 Show correct text for non increased risk levels on risk details screen (EXPOSUREAPP-2171)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_risk_details.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, on hold

#1005 Translation Delivery
  Corona-Warn-App/src/main/res/values-ar/strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers

#1009 Hotfixes translation updates
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: hotfix-1.2.1, maintainers

#1008 Change wording for 'Mundschutz' (EXPOSUREAPP-2197)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: hotfix-1.2.1, maintainers

#1011 Hotfix version bump to 1.2.1
  Corona-Warn-App/build.gradle
Labels: hotfix-1.2.1, maintainers

#1007 Moved status code to initial error message dialog (EXPOSUREAPP-2081)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorReportReceiver.kt
Labels: maintainers, rc3-1.3.0

#1010 Version code bump for RC3 1.3.0
  Corona-Warn-App/build.gradle
Labels: maintainers, rc3-1.3.0

#1017 Hotfix 1.2.1
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_risk_details.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: hotfix-1.2.1, maintainers

#1022 Plausible Deniability Config Update (EXPOSUREAPP-2214)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/playbook/BackgroundNoise.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/playbook/Playbook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/playbook/PlaybookImpl.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundConstants.kt
Labels: maintainers

#1025 Dev 1.3.0 to RC/1.3.0
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/playbook/BackgroundNoise.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/playbook/Playbook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/playbook/PlaybookImpl.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundConstants.kt
Labels: maintainers

#1012 Update translation for Gesundheitsamt (EXPOSUREAPP-2187)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, release-1.3.0

#1019 Update strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, release-1.3.0

#1028 Feature/onboarding easy language (EXPOSUREAPP-2095)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationAboutFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_information_about.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, release-1.3.0

#1013 Alternative contact possiblity (EXPOSUREAPP-1654)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationLegalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterInformationLegalHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_information_legal.xml
  Corona-Warn-App/src/main/res/layout/include_contact_form.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, release-1.3.0

#1029 Active tracing days count can be negative (EXPOSUREAPP-1844) #828
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/TimeVariables.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/tracing/TracingIntervalRepository.kt
Labels: maintainers, release-1.3.0

#1034 Feature: Added tess relay string
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers

#1035 Feature: Added string to open app daily (EXPOSUREAPP-2005)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#990 Fix the submission with zero keys (EXPOSUREAPP-1742)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/SubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
Labels: maintainers, release-1.3.0

#1038 Update strings.xml 'Zeitpunkt' -> 'Zeitraum'
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers

#1037 Fixes 9002 error caused by test fragment risk reset (related to EXPOSUREAPP-1851)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/deviceForTesters/java/de.rki.coronawarnapp/TestRiskLevelCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/AppDatabase.kt
Labels: maintainers

#1039 Translation Delivery
  Corona-Warn-App/src/main/res/values-ar/strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers

#1040 Fix: Removed ar & ru, update default strings and some auto formatting
  Corona-Warn-App/src/main/res/values-ar/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/playbook/PlaybookImplTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/service/SubmissionServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/service/VerificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/MockWebServerUtil.kt
Labels: maintainers

#1031 Dev 1.3.0 to RC/1.3.0
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/deviceForTesters/java/de.rki.coronawarnapp/TestRiskLevelCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/TimeVariables.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/AppDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/SubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/tracing/TracingIntervalRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationAboutFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationLegalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterInformationLegalHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_information_about.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_legal.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding.xml
  Corona-Warn-App/src/main/res/layout/include_contact_form.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/playbook/PlaybookImplTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/service/SubmissionServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/service/VerificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/MockWebServerUtil.kt
Labels: maintainers

#1059 Text: Fix string for qr code error message (EXPOSUREAPP-2287)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers

#1070 Ship a common codeStyle that matches KLint.
  .editorconfig
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
Labels: enhancement, maintainers

#1060 Automatically enable coroutine debugging in DEBUG and test builds.
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CWADebug.kt
Labels: enhancement, maintainers

#1078 Dev 1.3.0 to RC/1.3.0
  .editorconfig
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CWADebug.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  README.md
Labels: maintainers

#1069 Introduce dagger 2, first risk level unit tests (EXPOSUREAPP-2207)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/deviceForTesters/java/de.rki.coronawarnapp/TestRiskLevelCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/receiver/ReceiverBinder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/DefaultRiskLevelCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/DefaultRiskScoreAnalysis.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskScoreAnalysis.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/ServiceBinder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RiskLevelTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/ActivityBinder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/LauncherActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/AndroidModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AppInjector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/DefaultRiskScoreAnalysisTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskLevelCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RiskLevelTransactionTest.kt
Labels: maintainers, sprint5

#1074 Fix: Replaced brackets with leading # to match website faq structure (EXPOSUREAPP-2261)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorReportReceiver.kt
Labels: maintainers, sprint5

#1076 Storage check with optional allocation (EXPOSUREAPP-2259)
  .idea/codeStyles/Project.xml
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/assets/technical_de.html
  Corona-Warn-App/src/main/assets/technical_en.html
  Corona-Warn-App/src/main/assets/technical_tr.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/DeviceStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ApiLevel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AndroidModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/storage/StatsFsProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/DeviceStorageTest.kt
  Corona-Warn-App/src/test/java/testhelpers/BaseIOTest.kt
  Corona-Warn-App/src/test/java/testhelpers/BaseTest.kt
  Corona-Warn-App/src/test/java/testhelpers/logging/JUnitTree.kt
  build.gradle
Labels: enhancement, maintainers, sprint5

#1048 App usages over 16 years (EXPOSUREAPP-1781)
  Corona-Warn-App/src/main/res/layout/include_16_years.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
  Corona-Warn-App/src/main/res/layout/include_submission_positive_other_warning.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers, sprint5, ui

#1075 Fix: Grammar error in data privacy (EXPOSUREAPP-2251)
  Corona-Warn-App/src/main/assets/privacy_de.html
Labels: fix sprint4, maintainers

#1061 Improve transaction logging
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/ServiceFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RiskLevelTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/Transaction.kt
Labels: enhancement, maintainers

#1057 No Location Services needed for Android 11 (EXPOSUREAPP-2025)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/libs/play-services-nearby-18.0.3-eap.aar
  Corona-Warn-App/libs/play-services-nearby-exposurenotification-1.6.1-eap.aar
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/InternalExposureNotificationClient.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
Labels: maintainers, sprint5

#1073 Include test result retrieval in playbook for initial registration (EXPOSUREAPP-2314)
  Corona-Warn-App/src/deviceForTesters/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/playbook/Playbook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/playbook/PlaybookImpl.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/SubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/playbook/PlaybookImplTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/SubmissionServiceTest.kt
Labels: fix sprint4, maintainers

#1082 Active tracing days no longer negative (EXPOSUREAPP-2366)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/TimeVariables.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/tracing/TracingIntervalRepository.kt
Labels: maintainers

#1083 Feature: Update german & english eula (EXPOSUREAPP-1781)
  Corona-Warn-App/src/main/assets/terms_de.html
  Corona-Warn-App/src/main/assets/terms_en.html
Labels: maintainers, sprint5

#1055 Fix/alternate contact possibility (EXPOSUREAPP-2297, EXPOSUREAPP-2308)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationLegalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationLegalPresentation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/Views.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/device/DefaultSystemInfoProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/device/DeviceModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/device/SystemInfoProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterInformationLegalHelper.kt
  Corona-Warn-App/src/main/res/layout/include_contact_form.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/information/InformationLegalPresentationTest.kt
Labels: fix sprint4, maintainers, sprint5

#1080 Let tests be run for all flavors
  .circleci/config.yml
Labels: maintainers, sprint5

#1088 Fix: Consolidate all number of retrieve diagnosis keys into one (EXPOSUREAPP-2405)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
Labels: maintainers

#1041 Update UTC time to LocalTime (EXPOSUREAPP-1863)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/TracingViewModel.kt
Labels: maintainers, sprint4
