Repository corona-warn-app/cwa-app-android, pull requests merged in 2020-06, with the labels that each got.

#54 Cleanup pull_request_template.md
  .github/pull_request_template.md
Labels: spelling

#67 Correct typos in architecture overview
  docs/architecture-overview.md
Labels: spelling

#71 Fix typo in class documentation
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
Labels: spelling

#99 Fix: Tracing start/stop
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
Labels: maintainers

#98 SQLCipher PW bound to master key of android key store
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/AppDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataRetentionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/SecurityHelper.kt
Labels: backend, maintainers

#38 Shared prefs ktx shorthand
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
Labels: maintainers

#74 Add persistance of timestamp and whether user is allowed to submit keys
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/WebRequestBuilder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/SubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: backend, maintainers

#79 Replace the current exposure status with a positive result card when test result is positive
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/main/res/drawable/ic_risk_details_share.xml
  Corona-Warn-App/src/main/res/layout/fragment_main.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_content.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_fetching.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_positive.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_unregistered.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, ui

#100 Added a loading indicator to the test result fragment
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/TestResultStatus.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result.xml
Labels: maintainers, ui

#102 Submission Contact Fragment & StepView Custom View
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/SimpleStepEntry.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/StepEntry.kt
  Corona-Warn-App/src/main/res/drawable/ic_step_1.xml
  Corona-Warn-App/src/main/res/drawable/ic_step_2.xml
  Corona-Warn-App/src/main/res/drawable/ic_step_background.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_contact.xml
  Corona-Warn-App/src/main/res/layout/include_step_entry_simple_body.xml
  Corona-Warn-App/src/main/res/layout/include_submission_contact.xml
  Corona-Warn-App/src/main/res/layout/view_step_entry.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values/attrs.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, ui

#76 Notifications when risk value has changed between low and high.
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/NotificationConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/NotificationHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RiskLevelTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskLevelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RiskLevelTransactionTest.kt
Labels: maintainers

#105 readable ktlint output
  build.gradle
Labels: maintainers

#96 Circle progress bar
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/CircleProgress.kt
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days_14.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
  Corona-Warn-App/src/main/res/layout/include_risk_card.xml
  Corona-Warn-App/src/main/res/layout/view_circle_progress.xml
  Corona-Warn-App/src/main/res/values/attrs.xml
  Corona-Warn-App/src/main/res/values/colors.xml
Labels: maintainers

#114 TracingStatusHelper unit test
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ExampleInstrumentedTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ExampleUnitTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/TracingStatusHelperTest.kt
Labels: maintainers

#108 Prevent screenshot of the app for all activities
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
Labels: maintainers

#115 Feature: Bluetooth callback
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/SettingsRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SettingsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ConnectivityHelper.kt
Labels: maintainers

#121 Fixed screen orientation to portrait
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
Labels: maintainers

#125 Use local QR code scanning for risk level calculation
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/TestForAPIFragment.kt
Labels: maintainers

#122 QR Code Pattern Adjustment
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/InvalidQRCodeExcpetion.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/SubmissionServiceTest.kt
Labels: maintainers

#123 Result Step: Replace include with custom view
  Corona-Warn-App/src/main/res/layout/include_test_result_invalid_steps.xml
  Corona-Warn-App/src/main/res/layout/include_test_result_negative_steps.xml
  Corona-Warn-App/src/main/res/layout/include_test_result_pending_steps.xml
  Corona-Warn-App/src/main/res/layout/include_test_result_positive_steps.xml
  Corona-Warn-App/src/main/res/layout/include_test_result_step.xml
Labels: maintainers, ui

#128 Gradle Bump to 6.1.1
  .circleci/config.yml
  Corona-Warn-App/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: maintainers

#132 Remove Double Commit in LocalData
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
Labels: maintainers

#103 Feature/submission string changes
  Corona-Warn-App/src/main/res/layout/fragment_submission_done.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#46 Changed text type for TAN input to textPassword (closes #43)
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: ui

#117 okhttp stack and cert pinning setup
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/OkHttp3Stack.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/RequestQueueHolder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/SecurityHelper.kt
Labels: maintainers

#133 QR Code Scanning Dialogs
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DialogHelper.kt
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, ui

#139 Feature: Version information
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterInformationHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_information.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/SubmissionServiceTest.kt
Labels: maintainers

#135 submission test result: extend width of scroll view to full screen
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result.xml
Labels: maintainers, ui

#118 Fix Typo in TTL comment
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/request/ApplicationConfigurationRequest.kt
Labels: maintainers

#140 Added settings reset information, removed legacy resources
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsNotificationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/res/color/card_outdated.xml
  Corona-Warn-App/src/main/res/drawable-anydpi/onboarding_placeholder.xml
  Corona-Warn-App/src/main/res/drawable/ic_main_overview_circle.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days_0.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days_1.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days_10.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days_11.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days_12.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days_13.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days_14.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days_2.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days_3.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days_4.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days_5.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days_6.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days_7.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days_8.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_card_saved_days_9.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_reset_circle.xml
  Corona-Warn-App/src/main/res/layout/fragment_main_overview.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_notifications.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_reset.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
  Corona-Warn-App/src/main/res/layout/include_row.xml
  Corona-Warn-App/src/main/res/layout/include_settings_details_header.xml
  Corona-Warn-App/src/main/res/layout/include_tracing_status_card.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#137 Require tracing for upload
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#146 Set diagnosis key risk level based on day
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ProtoFormatConverterExtensions.kt
Labels: maintainers

#150 Submission thank you card and ui state integration
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/OkHttp3Stack.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/request/ApplicationConfigurationRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/SubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionDoneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/CircleProgress.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ProtoFormatConverterExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/UiStateHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/main/res/drawable/ic_main_overview_circle.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_reset_circle.xml
  Corona-Warn-App/src/main/res/layout/fragment_main.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_reset.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_done.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result.xml
  Corona-Warn-App/src/main/res/layout/include_risk_card.xml
  Corona-Warn-App/src/main/res/layout/include_submission_done.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_content.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_positive.xml
  Corona-Warn-App/src/main/res/layout/include_test_result_card.xml
Labels: backend, maintainers, ui

#155 Exception Dialogs
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/ErrorReportReceiver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/ExceptionReporter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/ReportingConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/Transaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DialogHelper.kt
  Corona-Warn-App/src/main/res/values/strings.xml
  gradle.properties
Labels: maintainers

#162 Tests/util
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/storage/keycache/KeyCacheDaoTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/keycache/KeyCacheRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/CachedKeyFileHolderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/CallHelperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/ConnectivityHelperTest.kt
Labels: enhancement, maintainers

#158 Feature/submission string changes
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#160 QR & TeleTan pattern
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTanViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/TanConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/TanInput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/main/res/values/integers.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/SubmissionServiceTest.kt
Labels: maintainers

#167 Tests/util
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/storage/ExposureSummaryDaoTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/storage/keycache/KeyCacheDaoTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/storage/tracing/TracingIntervalDaoTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/ExposureSummaryRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/tracing/TracingIntervalRepositoryTest.kt
Labels: enhancement, maintainers

#149 Replace Volley with Retrofit
  Corona-Warn-App/build.gradle
  Corona-Warn-App/config/detekt.yml
  Corona-Warn-App/proguard-rules.pro
  Corona-Warn-App/src/main/assets/pins.properties
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/ExceptionReporter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/CertificatePinnerFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/DynamicURLs.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/OfflineCacheInterceptor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/OkHttp3Stack.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/RequestQueueHolder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/RetryInterceptor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/ServiceFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/WebRequestBuilder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/request/ApplicationConfigurationRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/request/KeyFileRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/request/KeySubmissionRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/request/RegistrationTokenRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/request/TanRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/request/TestResultRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/requests/RegistrationTokenRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/requests/ReqistrationRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/requests/TanRequestBody.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/responses/RegistrationTokenResponse.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/responses/TanResponse.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/responses/TestResultResponse.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/service/DistributionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/service/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/service/VerificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/applicationconfiguration/ApplicationConfigurationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/diagnosiskey/DiagnosisKeyConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/diagnosiskey/DiagnosisKeyService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CachedKeyFileHolder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ConnectivityHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/PropertyLoader.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/SecurityHelper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/VerificationServiceTest.kt
Labels: backend, maintainers

#176 Exception handler
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/ErrorReportReceiver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/ExceptionReporter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/handler/GlobalExceptionHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/handler/GlobalExceptionHandlerConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/ActivityErrorReporting.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/LauncherActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingActivity.kt
Labels: maintainers

#182 Null View Bindings when view is destroyed (closes #104)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/TestForAPIFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/TestRiskLevelCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationAboutFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationLegalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationPrivacyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationTechnicalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationTermsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainShareFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTestFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsNotificationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionDoneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionIntroFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionRegisterDeviceFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionSuccessDialogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
Labels: maintainers

#185 Feature/Daily Fetch
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/TestForAPIFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CachedKeyFileHolder.kt
  Corona-Warn-App/src/main/res/layout/fragment_test_for_a_p_i.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/CachedKeyFileHolderTest.kt
Labels: backend

#190 Button Style Update
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/main/res/color/button_primary.xml
  Corona-Warn-App/src/main/res/color/button_stable.xml
  Corona-Warn-App/src/main/res/color/button_stable_grey.xml
  Corona-Warn-App/src/main/res/color/button_text_color.xml
  Corona-Warn-App/src/main/res/color/button_text_color_emphasized.xml
  Corona-Warn-App/src/main/res/drawable/button.xml
  Corona-Warn-App/src/main/res/layout/fragment_risk_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_tan.xml
  Corona-Warn-App/src/main/res/layout/include_risk_card.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers

#141 Error handling for network requests in Submission Flow
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/SubmissionTanInvalidException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/TestAlreadyPairedException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/TestPairingInvalidException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/diagnosiskey/DiagnosisKeyConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/diagnosiskey/DiagnosisKeyService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionRegisterDeviceFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DialogHelper.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskLevelCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/VerificationServiceTest.kt
Labels: backend, maintainers, ui

#194 Feature: Font Styles
  Corona-Warn-App/src/main/res/layout/fragment_test_for_a_p_i.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers

#197 Successfully submitting keys will now set the numberOfSuccessfulSubmissions in LocalData
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransaction.kt
Labels: backend, maintainers

#189 Generate a true DB Secret Key for use in Encryption via AES256
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/SecurityHelper.kt
Labels: backend, maintainers

#184 Removing the registration fragment
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionRegisterDeviceFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/Event.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_register_device.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
Labels: backend, maintainers, ui

#201 update to version 0.8.3
  Corona-Warn-App/build.gradle
Labels: maintainers

#199 Third party notices update
  THIRD-PARTY-NOTICES
Labels: maintainers

#205 Improved test fragments for risk level calculation
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/TestForAPIFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/TestRiskLevelCalculation.kt
  Corona-Warn-App/src/main/res/layout/fragment_test_for_a_p_i.xml
  Corona-Warn-App/src/main/res/layout/fragment_test_risk_level_calculation.xml
  Corona-Warn-App/src/main/res/layout/test_qr_code_view.xml
Labels: maintainers

#193 Background Job Rework
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/SettingsRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SettingsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ConnectivityHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundWorkScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalOneTimeWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalPeriodicWorker.kt
  Corona-Warn-App/src/main/res/layout/include_risk_card.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: backend, maintainers

#208 Feature: IsBackgroundJob Enabled UI
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ConnectivityHelper.kt
Labels: maintainers

#214 Proguard dont minify retrofit data class
  Corona-Warn-App/proguard-rules.pro
Labels: backend, maintainers

#207 Submission Updates
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeAndDateExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_content.xml
  Corona-Warn-App/src/main/res/layout/include_test_result_card.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, ui

#219 Style Adjustments, Risk Card Risk Level Storage
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/RiskLevelRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/TracingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelper.kt
  Corona-Warn-App/src/main/res/drawable/ic_settings_notification_active.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_notification_inactive.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_reset_circle.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_tracing_active.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_tracing_bluetooth.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_tracing_bluetooth_inactive.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_tracing_connection.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_tracing_connection_inactive.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_tracing_inactive.xml
  Corona-Warn-App/src/main/res/layout/fragment_information.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_about.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_contact.xml
  Corona-Warn-App/src/main/res/layout/fragment_main.xml
  Corona-Warn-App/src/main/res/layout/fragment_main_overview.xml
  Corona-Warn-App/src/main/res/layout/fragment_risk_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_reset.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
  Corona-Warn-App/src/main/res/layout/include_header.xml
  Corona-Warn-App/src/main/res/layout/include_information_details.xml
  Corona-Warn-App/src/main/res/layout/include_main_card.xml
  Corona-Warn-App/src/main/res/layout/include_main_overview_glossary.xml
  Corona-Warn-App/src/main/res/layout/include_main_overview_segment.xml
  Corona-Warn-App/src/main/res/layout/include_navigation_row.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
  Corona-Warn-App/src/main/res/layout/include_risk_card.xml
  Corona-Warn-App/src/main/res/layout/include_risk_card_header.xml
  Corona-Warn-App/src/main/res/layout/include_risk_card_row.xml
  Corona-Warn-App/src/main/res/layout/include_risk_details_behavior_row.xml
  Corona-Warn-App/src/main/res/layout/include_row.xml
  Corona-Warn-App/src/main/res/layout/include_setting_row.xml
  Corona-Warn-App/src/main/res/layout/include_settings_switch_row.xml
  Corona-Warn-App/src/main/res/layout/include_tracing_status_card.xml
  Corona-Warn-App/src/main/res/layout/view_circle_progress.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/styles.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RiskLevelTransactionTest.kt
Labels: maintainers

#225 DPP Text & Dialog Updates
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, ui

#220 Using the new http errors introduced in #213
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/SubmissionTanInvalidException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/TestAlreadyPairedException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/TestPairingInvalidException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/WebRequestException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/http/CwaWebException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/diagnosiskey/DiagnosisKeyService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
Labels: backend, maintainers

#218 Correct File Storage to Internal
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/FileStorageHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/keycache/KeyCacheRepository.kt
Labels: maintainers

#229 Static Screens
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_information_legal.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_privacy.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_technical.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_privacy.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, ui

#213 Complex HTTP Errors
  Corona-Warn-App/config/detekt.yml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/SubmissionTanInvalidException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/TestAlreadyPairedException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/TestPairingInvalidException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/WebRequestException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/http/CwaWebException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/HttpErrorParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/ServiceFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/diagnosiskey/DiagnosisKeyService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
Labels: backend, maintainers

#231 Updated Assets
  Corona-Warn-App/src/main/res/drawable-night/ic_illustration_notification_on.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_illustration_privacy.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_illustration_test.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_illustration_together.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_illustration_tracing_on.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_information_illustration_legal.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_information_illustration_technical.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_information_illustration_terms.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_main_about.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_main_illustration_invalid.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_main_illustration_negative.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_main_illustration_overview.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_main_illustration_pending.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_main_illustration_share.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_main_illustration_untested.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_main_overview_1.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_main_overview_2.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_main_overview_3.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_settings_illustration_bluetooth_off.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_settings_illustration_connection_off.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_settings_illustration_notification_off.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_settings_illustration_reset.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_settings_illustration_tracing_off.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_settings_reset_circle.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_submission_illustration_other_warning.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_submission_illustration_qr_code_card.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_submission_illustration_tan_code_card.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_submission_illustration_tan_hotline_card.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_submission_illustration_thanks.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_test_result_illustration_invalid.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_test_result_illustration_negative.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_test_result_illustration_pending.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_test_result_illustration_positive.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_test_result_step_done.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_test_result_step_invalid.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_test_result_step_waiting.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_test_result_step_warning.xml
  Corona-Warn-App/src/main/res/drawable/ic_main_illustration_negative.xml
  Corona-Warn-App/src/main/res/drawable/ic_main_illustration_pending.xml
  Corona-Warn-App/src/main/res/drawable/ic_main_illustration_test.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_details_distance.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_details_home.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_details_stethoscope.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_home.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_share.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_privacy.xml
  Corona-Warn-App/src/main/res/layout/include_information_details_header.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
  Corona-Warn-App/src/main/res/layout/include_submission_done_content.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_positive.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers

#233 Implement passphrase generation for db (closes #173) (#224)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/util/security/DBPasswordTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/TestRiskLevelCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/AppDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataRetentionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/SecurityHelper.kt
Labels: maintainers

#183 Feature/submission image texts
  Corona-Warn-App/src/main/res/layout/fragment_submission_done.xml
  Corona-Warn-App/src/main/res/layout/include_submission_done_card.xml
  Corona-Warn-App/src/main/res/layout/include_submission_done_content.xml
  Corona-Warn-App/src/main/res/layout/include_submission_intro.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#232 Setup Trust Anchors (Public Keys for Signature Verification)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/assets/export-server-public-keys-for-verification.properties
  Corona-Warn-App/src/main/assets/trusted-certs-cwa.bks
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/WebRequestBuilder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/SecurityConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/SecurityHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/VerificationKeys.kt
Labels: maintainers

#243 Translation text for autoupdate affordance dialog
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#244 catch CwaSecurityException for update check
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/update/UpdateChecker.kt
Labels: maintainers

#191 [WIP][Admin] Sonar setup
  .circleci/config.yml
  Corona-Warn-App/build.gradle
  build.gradle
  sonar-project.properties
Labels: maintainers

#254 Feature: Toolbar
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationAboutFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationLegalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationPrivacyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationTechnicalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationTermsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainShareFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsNotificationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionDoneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionIntroFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/res/drawable/ic_close_dark.xml
  Corona-Warn-App/src/main/res/drawable/ic_close_light.xml
  Corona-Warn-App/src/main/res/layout/fragment_information.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_about.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_contact.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_legal.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_privacy.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_technical.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_terms.xml
  Corona-Warn-App/src/main/res/layout/fragment_main.xml
  Corona-Warn-App/src/main/res/layout/fragment_main_overview.xml
  Corona-Warn-App/src/main/res/layout/fragment_main_share.xml
  Corona-Warn-App/src/main/res/layout/fragment_risk_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_notifications.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_reset.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
  Corona-Warn-App/src/main/res/layout/include_header.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
  Corona-Warn-App/src/main/res/layout/include_risk_card.xml
  Corona-Warn-App/src/main/res/layout/include_risk_card_header.xml
  Corona-Warn-App/src/main/res/layout/include_submission_contact.xml
  Corona-Warn-App/src/main/res/layout/include_submission_intro.xml
  Corona-Warn-App/src/main/res/layout/include_submission_positive_other_warning.xml
  Corona-Warn-App/src/main/res/layout/include_submission_test_result.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers

#255 Timestamp for last successful risk level calculation
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/TestRiskLevelCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RiskLevelTransaction.kt
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RiskLevelTransactionTest.kt
Labels: maintainers

#217 Setup Intermediate Pin
  Corona-Warn-App/src/main/assets/pins.properties
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/CwaWebSecurityException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/CertificatePinnerFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/ServiceFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/config/DynamicURLs.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/config/HTTPVariables.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/interceptor/OfflineCacheInterceptor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/interceptor/RetryInterceptor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/interceptor/WebSecurityVerificationInterceptor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/LauncherActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/IndexHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/PropertyLoader.kt
  Corona-Warn-App/src/main/res/xml/network_security_config.xml
Labels: maintainers

#154 Translation Sync To Dev
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/util/security/DBPasswordTest.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#215 Tests/formatter
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterHelperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelperTest.kt
Labels: maintainers

#252 Extend teleTAN to 10 characters + input validation
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTanViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/TanConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/TanInput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TanHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/main/res/drawable/tan_input_digit.xml
  Corona-Warn-App/src/main/res/drawable/tan_input_digit_entered.xml
  Corona-Warn-App/src/main/res/drawable/tan_input_digit_error.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_tan.xml
  Corona-Warn-App/src/main/res/layout/view_tan_input.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/SubmissionTanViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/TanHelperTest.kt
Labels: maintainers

#258 Submission Changes
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/res/layout/include_submission_contact.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#272 UI changes to the qr code scan screen
  Corona-Warn-App/src/main/res/drawable/ic_submission_qr_code_scan_close.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_qr_code_scan.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
Labels: maintainers, ui

#204 Tests/others
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransactionTest.kt
  Corona-Warn-App/src/test/resources/keys.bin
Labels: enhancement, maintainers

#276 Added relative date formatting to risk card via DateUtils
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
Labels: maintainers, ui

#277 Submission Design Review Adjustments
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/main/res/color/card_dark.xml
  Corona-Warn-App/src/main/res/drawable/card_dark.xml
  Corona-Warn-App/src/main/res/drawable/ic_icon_drilldowncard_dark.xml
  Corona-Warn-App/src/main/res/drawable/ic_step_1.xml
  Corona-Warn-App/src/main/res/drawable/ic_step_2.xml
  Corona-Warn-App/src/main/res/drawable/ic_step_background.xml
  Corona-Warn-App/src/main/res/drawable/ic_test_result_illustration_positive_card.xml
  Corona-Warn-App/src/main/res/layout/fragment_main.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result.xml
  Corona-Warn-App/src/main/res/layout/include_dispatcher_card.xml
  Corona-Warn-App/src/main/res/layout/include_submission_contact.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_content.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_done.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_fetching.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_positive.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_unregistered.xml
  Corona-Warn-App/src/main/res/layout/include_submission_test_result.xml
  Corona-Warn-App/src/main/res/layout/include_test_result_card.xml
  Corona-Warn-App/src/main/res/layout/include_test_result_card_positive.xml
  Corona-Warn-App/src/main/res/layout/view_step_entry.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers, ui

#270 Extend teleTAN to 10 characters + input validation (re-submit)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTanViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/TanConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/TanInput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TanHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/main/res/drawable/tan_input_digit.xml
  Corona-Warn-App/src/main/res/drawable/tan_input_digit_entered.xml
  Corona-Warn-App/src/main/res/drawable/tan_input_digit_error.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_tan.xml
  Corona-Warn-App/src/main/res/layout/view_tan_input.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/SubmissionTanViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/TanHelperTest.kt
Labels: maintainers

#284 EN tests
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/TestFragment.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/nearby/InternalExposureNotificationPermissionHelperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/receiver/ExposureStateUpdateReceiverTest.kt
Labels: enhancement, maintainers

#286 Tests/util/formatter
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelperTest.kt
Labels: maintainers

#300 Fix Streaming for KeyFiles
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/service/DistributionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/VerificationKeys.kt
Labels: maintainers

#293 Feature/background work
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/TimeVariables.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/SettingsRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/timer/TimerHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SettingsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/TracingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ConnectivityHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalOneTimeWorker.kt
  Corona-Warn-App/src/main/res/layout/fragment_risk_details.xml
  Corona-Warn-App/src/main/res/layout/include_risk_card.xml
Labels: maintainers

#298 bugfix for version check
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/update/VersionComparator.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/update/VersionComparatorTest.kt
Labels: maintainers

#297 Bullet Point Lists
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/BulletPointList.kt
  Corona-Warn-App/src/main/res/drawable/bullet_point.xml
  Corona-Warn-App/src/main/res/layout/include_submission_done_content.xml
  Corona-Warn-App/src/main/res/layout/include_submission_done_further_info.xml
  Corona-Warn-App/src/main/res/layout/include_submission_intro.xml
  Corona-Warn-App/src/main/res/layout/include_submission_test_result.xml
  Corona-Warn-App/src/main/res/layout/include_submission_test_result_negative_further_info.xml
  Corona-Warn-App/src/main/res/layout/view_bullet_point_entry.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values/attrs.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#302 Submission Translation Tags
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#311 0.8.11
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  gradle.properties
Labels: maintainers

#313 Third party notices patch 1
  THIRD-PARTY-NOTICES
Labels: maintainers

#312 Sync Disable Tracing Behavior
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetFragment.kt
Labels: maintainers

#317 Exception Codes
  Corona-Warn-App/build.gradle
  Corona-Warn-App/config/detekt.yml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/ApplicationConfigurationCorruptException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/ApplicationConfigurationInvalidException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/CwaSecurityException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/CwaWebSecurityException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/DiagnosisKeyServiceException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/ENPermissionException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/FormatterException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/RiskLevelCalculationException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/RollbackException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/TransactionException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/WrongReceiverException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/http/CwaWebException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorCodes.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorReportReceiver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ExceptionReporter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ReportedException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ReportingConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/TracingViewModel.kt
Labels: maintainers

#323 Design Polish & exchanged webViews
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/technical_en.html
  Corona-Warn-App/src/main/assets/terms_en.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationPrivacyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationTechnicalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationTermsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_information_about.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_contact.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_privacy.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_technical.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_terms.xml
  Corona-Warn-App/src/main/res/layout/fragment_main.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_notifications.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_privacy.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_test.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_tracing.xml
  Corona-Warn-App/src/main/res/layout/fragment_risk_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_notifications.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_reset.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
  Corona-Warn-App/src/main/res/layout/include_header.xml
  Corona-Warn-App/src/main/res/layout/include_information_details.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
  Corona-Warn-App/src/main/res/layout/include_risk_card_header.xml
  Corona-Warn-App/src/main/res/values-v28/styles.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#324 Translation in Dev
  Corona-Warn-App/src/main/assets/terms_en.html
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#322 temporarily remove screenshot prevention
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
Labels: maintainers

#326 Data privacy update
  Corona-Warn-App/src/main/assets/privacy_de.html
Labels: maintainers

#333 Offline handling for Risk Level Calculation
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/NoNetworkException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorCodes.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorReportReceiver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ExceptionReporter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ReportedException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ReportingConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/RiskLevelRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RiskLevelTransaction.kt
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RiskLevelTransactionTest.kt
Labels: maintainers

#335 0.8.14
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/terms_de.html
  Corona-Warn-App/src/main/assets/terms_en.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/NoNetworkException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorCodes.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorReportReceiver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ExceptionReporter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ReportedException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ReportingConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/RiskLevelRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RiskLevelTransaction.kt
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RiskLevelTransactionTest.kt
Labels: maintainers

#314 Navigation refactor
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/BaseFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/UIExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationAboutFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationLegalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationPrivacyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationTechnicalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationTermsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainShareFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTestFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionDoneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionIntroFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CallHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/OpenUrlHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ShareHelper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/CallHelperTest.kt
Labels: maintainers

#356 Fix for error dialog described in EXPOSUREAPP-1293
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/TestForAPIFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/InternalExposureNotificationPermissionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransactionTest.kt
Labels: maintainers

#351 Style Changes Submission
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_main.xml
  Corona-Warn-App/src/main/res/layout/include_dispatcher_card.xml
  Corona-Warn-App/src/main/res/layout/include_main_card.xml
  Corona-Warn-App/src/main/res/layout/include_main_faq_card.xml
  Corona-Warn-App/src/main/res/layout/include_submission_contact.xml
  Corona-Warn-App/src/main/res/layout/include_submission_dispatcher.xml
  Corona-Warn-App/src/main/res/layout/include_submission_positive_other_warning.xml
  Corona-Warn-App/src/main/res/layout/include_submission_test_result.xml
  Corona-Warn-App/src/main/res/layout/include_test_result_card.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelperTest.kt
Labels: maintainers, ui

#369 Make Public Keys for Signature Verification Dependant on Environment
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/assets/export-server-public-keys-for-verification.properties
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/SecurityConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/VerificationKeys.kt
  gradle.properties
Labels: maintainers

#370 Minor string change to align dialog text with button (EXPOSUREAPP-1303)
  Corona-Warn-App/src/main/res/values-en/strings.xml
Labels: maintainers

#375 QR Code scan ui changes (EXPOSUREAPP-1402)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/res/drawable/ic_registration_qr_code_scan_torch_off.xml
  Corona-Warn-App/src/main/res/drawable/ic_registration_qr_code_scan_torch_on.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_qr_code_scan_close.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_qr_code_scan.xml
Labels: maintainers, ui

#378 Tan Input Update
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/TanInput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/TanInput.kt
  Corona-Warn-App/src/main/res/drawable/tan_input_digit.xml
  Corona-Warn-App/src/main/res/drawable/tan_input_digit_error.xml
  Corona-Warn-App/src/main/res/layout/include_submission_tan.xml
  Corona-Warn-App/src/main/res/layout/view_tan_input.xml
  Corona-Warn-App/src/main/res/layout/view_tan_input_edittext.xml
  Corona-Warn-App/src/main/res/layout/view_tan_input_group_3.xml
  Corona-Warn-App/src/main/res/layout/view_tan_input_group_4.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers, ui

#383 workers instrumental tests
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalOneTimeWorkerTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalPeriodicWorkerTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/worker/DiagnosisTestResultRetrievalPeriodicWorkerTest.kt
Labels: maintainers

#393 Tests for submission service
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/SubmissionServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/VerificationServiceTest.kt
Labels: backend, maintainers

#384 Small font changes to the test result cards on homescreen
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_content.xml
Labels: backend, maintainers

#390 0.8.17
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalOneTimeWorkerTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalPeriodicWorkerTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/worker/DiagnosisTestResultRetrievalPeriodicWorkerTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/NotEnoughSpaceOnDiskException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorCodes.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/FileStorageHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/TracingRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CachedKeyFileHolder.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_illustration_notification_on.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_illustration_test.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_submission_illustration_other_warning.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_test_result_illustration_positive.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_tracing_inactive.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_tracing_inactive_small.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_legal.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_notifications.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_content.xml
  Corona-Warn-App/src/main/res/values/styles.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/SubmissionServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/VerificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/CachedKeyFileHolderTest.kt
Labels: maintainers

#396 Tests/general
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/ExternalActionHelperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/TimeAndDateExtensionsTest.kt
Labels: maintainers

#401 Translation update
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
Labels: maintainers

#382 update camera request permission flow
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#407 Fix: a18y technical hotline
  Corona-Warn-App/src/main/res/layout/fragment_information_contact.xml
Labels: maintainers

#388 Submission Style Fixes
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/TanInput.kt
  Corona-Warn-App/src/main/res/layout/include_dispatcher_card.xml
  Corona-Warn-App/src/main/res/layout/include_submission_dispatcher.xml
  Corona-Warn-App/src/main/res/layout/view_tan_input_group_4.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers, ui

#410 TAN Input a11y: repeat error messages
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTanViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/TanInput.kt
  Corona-Warn-App/src/main/res/layout/include_submission_tan.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/SubmissionTanViewModelTest.kt
Labels: maintainers

#412 Added exception handler for UnknownHostException's
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/http/CwaWebException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/HttpErrorParser.kt
Labels: backend, maintainers

#409 Fix: Back after test result
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
Labels: maintainers

#413 Fix: a18y
  Corona-Warn-App/src/main/res/layout/fragment_main_overview.xml
  Corona-Warn-App/src/main/res/layout/fragment_risk_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_qr_code_scan.xml
  Corona-Warn-App/src/main/res/layout/include_button_icon.xml
  Corona-Warn-App/src/main/res/layout/include_dispatcher_card.xml
  Corona-Warn-App/src/main/res/layout/include_submission_contact.xml
  Corona-Warn-App/src/main/res/layout/include_submission_done.xml
  Corona-Warn-App/src/main/res/layout/include_submission_intro.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_content.xml
  Corona-Warn-App/src/main/res/layout/include_submission_status_card_unregistered.xml
  Corona-Warn-App/src/main/res/layout/include_test_result_card.xml
  Corona-Warn-App/src/main/res/layout/include_test_result_card_positive.xml
  Corona-Warn-App/src/main/res/layout/view_bullet_point_entry.xml
  Corona-Warn-App/src/main/res/layout/view_circle_progress.xml
  Corona-Warn-App/src/main/res/layout/view_step_entry.xml
Labels: maintainers

#415 Accessibility fixes
  Corona-Warn-App/src/device/java/de.rki.coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragment.kt
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#420 new privacy and terms
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/terms_de.html
  Corona-Warn-App/src/main/assets/terms_en.html
Labels: maintainers

#421 Final Translation Update
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
Labels: maintainers

#427 Fix: Privacy date
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
Labels: maintainers

#431 Fix: Fixed image description
  Corona-Warn-App/src/main/res/layout/include_submission_positive_other_warning.xml
Labels: maintainers

#444 Fix: Text eula privacy
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/terms_de.html
  Corona-Warn-App/src/main/assets/terms_en.html
Labels: maintainers

#588 Disallow scrolling tan entry text view (closes #546)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/UnscrollableEditText.kt
  Corona-Warn-App/src/main/res/layout/view_tan_input_edittext.xml
Labels: maintainers, ui

#462 Add missing intent action for notifications settings (closes #461)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ExternalActionHelper.kt
Labels: ui

#641 Admin/doc updates
  .github/ISSUE_TEMPLATE/01_bugs.md
  .github/ISSUE_TEMPLATE/02_feature_request.md
  .github/ISSUE_TEMPLATE/03_enhancement.md
  .github/ISSUE_TEMPLATE/04_questions.md
  .github/ISSUE_TEMPLATE/05_other.md
  .github/pull_request_template.md
  README.md
Labels: maintainers

#552 Translation
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  translation_v2.json
Labels: maintainers, ui

#646 Fix: Links in alert dialog
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DialogHelper.kt
Labels: do not merge, maintainers

#648 Specific error message for pending Google Play Services and Google Mo…
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorReportReceiver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ExceptionReporter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ReportingConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DialogHelper.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#608 Fix exception message
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/tracing/TracingIntervalRepository.kt
Labels: text issue

#432 Tests/general2
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/CameraPermissionHelperTest.kt
Labels: maintainers

#730 Test/constants
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/exception/reporting/ErrorCodesTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/exception/reporting/ReportingConstantsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/config/HTTPVariablesTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/ResolutionRequestCodeConstantsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/ResolutionRequestCodesTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/notification/NotificationConstantsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskLevelConstantsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskLevelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/TimeVariablesTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/diagnosiskey/DiagnosisKeyConstantsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/SubmissionConstantsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/DatabaseConstantsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/FileStorageConstantsTest.kt
Labels: maintainers

#738 Fix/screen orientation
  Corona-Warn-App/src/main/AndroidManifest.xml
Labels: maintainers, ui

#466 Make entire SettingsRow toggle the setting (closes #455)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsNotificationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
Labels: ui

#716 restore DaysInRetentionPeriod in RiskDetails on resume. fixes #594
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailsFragment.kt
Labels: ui

#564 Added autoLink to layouts (closes issue #633)
  Corona-Warn-App/src/main/res/layout/fragment_information_contact.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_legal.xml
  Corona-Warn-App/src/main/res/layout/include_information_details.xml
Labels: in progress, ui

#760 Fix/free space threshold
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/FileStorageConstants.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/FileStorageConstantsTest.kt
Labels: maintainers
