Repository corona-warn-app/cwa-app-android, pull requests merged in 2020-09, with the labels that each got.

#1093 Prevent UI scopes from canceling transactions (EXPOSUREAPP-2312)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisInjectionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RiskLevelInjectionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RiskLevelTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisInjectionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/Transaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/TransactionCoroutineScope.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AppInjector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RiskLevelTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/TransactionTest.kt
Labels: bug, enhancement, maintainers, sprint5

#1079 Admin: Update notice file
  NOTICE
Labels: maintainers, sprint5

#1094 Voice assist double tap on link fix (EXPOSUREAPP-2288)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationAboutFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragment.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, sprint5

#1097 New Scan Confirmation Texts Change (EXPOSUREAPP-2427)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers

#1096 Remove blanket internet connection status (EXPOSUREAPP-1572)
  .idea/codeStyles/Project.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_main.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/TracingStatusHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_main.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/TracingStatusHelperTest.kt
Labels: maintainers, sprint5

#1098 Single point of resposibility for background activity prioritization (EXPOSUREAPP-2271)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/SettingsRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/timer/TimerHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsBackgroundPriorityFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsNotificationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SettingsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/BackgroundPrioritization.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ConnectivityHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ConnectivityHelperInjection.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DefaultBackgroundPrioritization.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ExternalActionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/PowerManagementHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/UtilModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/device/DefaultPowerManagement.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/device/PowerManagement.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AndroidModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/ExternalActionHelperTest.kt
Labels: maintainers, sprint5

#1077 Translation Delivery
  Corona-Warn-App/src/main/res/values-ar/strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers, sprint5

#1105 Translation Delivery
  Corona-Warn-App/src/main/res/values-ar/strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers, sprint5

#1104 Update strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, sprint5

#1107 Revert "Update UTC time to LocalTime (#1041) (EXPOSUREAPP-1863)"
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/TracingViewModel.kt
Labels: maintainers

#1106 New Strings for Risikobegegnung mit niedrigem Risiko (EXPOSUREAPP-2462)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelperTest.kt
Labels: maintainers, sprint5

#1100 Initial implementation of submission country selection ui (EXPOSUREAPP-2265)
  Corona-Warn-App/src/deviceForTesters/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionCountry.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/adapter/SubmissionCountrySelectionAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionCountrySelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionDoneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionIntroFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionCountrySelectViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionTanViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_austria.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_czech.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_denmark.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_estonia.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_ireland.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_italy.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_latvia.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_netherlands.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_poland.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_spain.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_contact.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_country_selection.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_dispatcher.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_done.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_intro.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_positive_other_warning.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_tan.xml
  Corona-Warn-App/src/main/res/layout/include_submission_country_item.xml
  Corona-Warn-App/src/main/res/layout/include_submission_country_no_selection.xml
  Corona-Warn-App/src/main/res/layout/include_submission_country_selector.xml
  Corona-Warn-App/src/main/res/layout/include_submission_tan.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/SubmissionTanViewModelTest.kt
Labels: maintainers, sprint5, ui

#1086 Test Menu options for Country selection and Measurement (EXPOSUREAPP-2229)
  Corona-Warn-App/src/deviceForTesters/java/de.rki.coronawarnapp/RiskLevelAndKeyRetrievalBenchmark.kt
  Corona-Warn-App/src/deviceForTesters/java/de.rki.coronawarnapp/TestForAPIFragment.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_for_a_p_i.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/WebRequestBuilder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/applicationconfiguration/ApplicationConfigurationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/diagnosiskey/DiagnosisKeyConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CachedKeyFileHolder.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/WebRequestBuilderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/applicationconfiguration/ApplicationConfigurationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/CachedKeyFileHolderTest.kt
  Server-Protocol-Buffer/src/main/proto/applicationConfiguration.proto
Labels: maintainers, sprint5

#1116 Fixed: cannot activate prioritised background activity on some devices (EXPOSUREAPP-2506)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/base/ActivityExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsBackgroundPriorityFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ExternalActionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/device/DefaultPowerManagement.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/device/PowerManagement.kt
Labels: maintainers, sprint5

#1112 Improve Explanation for "Risikobegegnung mit niedrigem Risiko" (EXPOSUREAPP-1971)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/DefaultRiskDetailPresenter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailPresenter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/TracingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_risk_details.xml
  Corona-Warn-App/src/main/res/layout/include_risk_details_low_risk_encounter.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/riskdetails/DefaultRiskDetailPresenterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelperTest.kt
Labels: maintainers, sprint6

#1108 Remove Cache Clearing to reduce CDN load on failing devices (EXPOSUREAPP-2405)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/WebRequestBuilder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/keycache/KeyCacheDao.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/keycache/KeyCacheRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CachedKeyFileHolder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/GoogleQuotaCalculator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/QuotaCalculator.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/CachedKeyFileHolderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/GoogleQuotaCalculatorTest.kt
Labels: maintainers

#1125 Feature: Update low risk string (EXPOSUREAPP-1971)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: hotfix-1.3.1, maintainers, sprint6

#1126 Translation Delivery
  Corona-Warn-App/src/main/res/values-ar/strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: hotfix-1.3.1, maintainers

#1128 Fix: Strings - removed ar & ru and updated default strings
  Corona-Warn-App/src/main/res/values-ar/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: hotfix-1.3.1, maintainers

#1133 Hotfix: Removed ar & ru and updated defaults
  Corona-Warn-App/src/main/res/values-ar/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: hotfix-1.3.1, maintainers

#1120 Update strings.xml App-Nutzung ab 16 Jahren (EXPOSUREAPP-2559)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.4.0, maintainers, sprint6

#945 Removed 'Button' announcement on risk card (EXPOSUREAPP-1542)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/res/layout/include_risk_card.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelperTest.kt
Labels: 1.4.0, maintainers

#1138 Double Timeout Variables for HTTP Requests and Triple the Timeout for the Transaction to ensure less timeouts are received with bad networking (EXPOSUREAPP-2190)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/config/HTTPVariables.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/TimeVariables.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/config/HTTPVariablesTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/TimeVariablesTest.kt
Labels: 1.4.0, maintainers

#1143 Fix: Line break on Imprint in german (EXPOSUREAPP-1530)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.4.0, maintainers

#1144 Fixed klint issues
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/CachedKeyFileHolderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/GoogleQuotaCalculatorTest.kt
Labels: maintainers, sprint6

#1140 Implementation of tests for the interoperability countries selection screen (EXPOSUREAPP-2439)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionCountrySelectViewModelTest.kt
Labels: 1.5.0, maintainers, ui

#1146 Remove unavailable test fragment from release navgraph and fix pkg/path
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/TestForAPIFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/TestRiskLevelCalculationFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/deviceForTesters/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
Labels: bug, maintainers

#1118 Changes PR template, removed checkboxes and added new points
  .github/pull_request_template.md
Labels: maintainers, sprint6

#1152 Update CODEOWNERS
  CODEOWNERS
Labels: maintainers

#1150 Version Checker with Branching for Checks on provideDiagnosisKeys below v16 of ENF (EXPOSUREAPP-2213)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/InternalExposureNotificationClient.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisInjectionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/GoogleAPIVersion.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/GoogleAPIVersionTest.kt
Labels: 1.4.0, maintainers

#1127 QR Code stricter validation (EXPOSUREAPP-2570)
  Corona-Warn-App/config/detekt.yml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/QRScanResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/ScanResultTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/SubmissionConstantsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/SubmissionServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModelTest.kt
Labels: 1.4.0, maintainers

#1158 Dev -> interop
  .github/pull_request_template.md
  CODEOWNERS
  Corona-Warn-App/config/detekt.yml
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/RiskLevelAndKeyRetrievalBenchmark.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/TestForAPIFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/TestRiskLevelCalculationFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/deviceForTesters/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/assets/terms_de.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/config/HTTPVariables.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/InternalExposureNotificationClient.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/TimeVariables.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/QRScanResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisInjectionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/base/ActivityExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/DefaultRiskDetailPresenter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailPresenter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsBackgroundPriorityFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/TracingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ExternalActionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/GoogleAPIVersion.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/GoogleQuotaCalculator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/QuotaCalculator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/device/DefaultPowerManagement.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/device/PowerManagement.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_risk_details.xml
  Corona-Warn-App/src/main/res/layout/include_risk_card.xml
  Corona-Warn-App/src/main/res/layout/include_risk_details_low_risk_encounter.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-ar/strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/config/HTTPVariablesTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/TimeVariablesTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/ScanResultTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/SubmissionConstantsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/SubmissionServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/riskdetails/DefaultRiskDetailPresenterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/GoogleAPIVersionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/GoogleQuotaCalculatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelperTest.kt
Labels: maintainers

#1142 Submission: Warning if user cancels submission (EXPOSUREAPP-2509)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.4.0, maintainers

#1159 Improve function name to better reflect its result.
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/GoogleAPIVersion.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/GoogleAPIVersionTest.kt
Labels: maintainers

#928 Add delegated property to automatically handle Fragment view unbinding (closes #927)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/device/java/de.rki.coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/TestForAPIFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/TestRiskLevelCalculationFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/UIExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationAboutFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationLegalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationPrivacyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationTechnicalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationTermsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainShareFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTestFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsBackgroundPriorityFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsNotificationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionDoneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionIntroFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
Labels: community

#1067 Allow expandable long text in notification (related to #1066)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/NotificationHelper.kt
Labels: bug, community

#919 #918 Fix Hard coded by Http Status code judgment. (EXPOSUREAPP-1929)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/HttpErrorParser.kt
Labels: community

#1165 Reverted replaced wording (EXPOSUREAPP-2638) (#1153)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelperTest.kt
Labels: 1.4.0, maintainers

#1168 Adjustment of Google Service description (EXPOSUREAPP-2012)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.4.0, maintainers

#1131 Fixed Message for bad TAN (EXPOSUREAPP-2552)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, sprint5

#1135 SubmissionQRCodeScanFragment - fix for not equal Error Dialogs(EXPOSUREAPP-1829)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionQRCodeScanFragment.kt
Labels: maintainers, sprint5, text issue

#1167 Remove phone number in terms_de.html (#2633)
  Corona-Warn-App/src/main/assets/terms_de.html
Labels: 1.4.0, maintainers

#1137 Improve Explanation for usage of location services (EXPOSUREAPP-2384)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationLegalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/LocationTracingStatusCardBodyTextView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/Views.kt
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
  Corona-Warn-App/src/main/res/layout/include_tracing_status_card_location.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.4.0, maintainers

#1171 Invalid TAN shows QR-Code error message (EXPOSUREAPP-2552)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.4.0, maintainers

#1172 Fixed quotes
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.4.0, maintainers

#1174 TAN subtext adjustment - layout & text (EXPOSUREAPP-2549)
  Corona-Warn-App/src/main/res/layout/include_submission_tan.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.4.0, maintainers, text issue

#1176 File Logger Introduction for Test Builds (EXPOSUREAPP-2640)
  Corona-Warn-App/src/deviceForTesters/java/de.rki.coronawarnapp/TestForAPIFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de.rki.coronawarnapp/TestRiskLevelCalculation.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_for_a_p_i.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/GoogleQuotaCalculator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/debug/FileLogger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/debug/FileLoggerTree.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/GoogleQuotaCalculatorTest.kt
Labels: hotfix-1.3.1, maintainers

#1175 Align dataprivacy text with button and fixed wrong wording (EXPOSUREAPP-2567)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.4.0, maintainers

#1170 Provide onset of symptoms before upload (EXPOSUREAPP-1605)
  .idea/codeStyles/Project.xml
  Corona-Warn-App/build.gradle
  Corona-Warn-App/config/detekt.yml
  Corona-Warn-App/src/device/java/de.rki.coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/TestForAPIFragment.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_for_a_p_i.xml
  Corona-Warn-App/src/deviceForTesters/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/service/submission/SubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/DefaultKeyConverter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ExposureKeyHistoryCalculations.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/KeyConverter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/Symptoms.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/TransmissionRiskVector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/TransmissionRiskVectorDeterminator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/SingleLiveEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/calendar/CalendarAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/calendar/CalendarCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/calendar/CalendarDayViewHolder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/calendar/CalendarView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/calendar/CalendarWeekDayView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomCalendarFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomIntroductionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SymptomCalendarEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SymptomIntroductionEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ProtoFormatConverterExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/main/res/color/calendar_header.xml
  Corona-Warn-App/src/main/res/drawable/calendar_header_background.xml
  Corona-Warn-App/src/main/res/drawable/calendar_header_background_focus_off.xml
  Corona-Warn-App/src/main/res/drawable/calendar_header_background_focus_on.xml
  Corona-Warn-App/src/main/res/drawable/calendar_layout_background.xml
  Corona-Warn-App/src/main/res/drawable/calendar_layout_background_focus_off.xml
  Corona-Warn-App/src/main/res/drawable/calendar_layout_background_focus_on.xml
  Corona-Warn-App/src/main/res/drawable/calendar_selected_day_back.xml
  Corona-Warn-App/src/main/res/drawable/calendar_today_back.xml
  Corona-Warn-App/src/main/res/layout/fragment_calendar.xml
  Corona-Warn-App/src/main/res/layout/fragment_calendar_day.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_symptom_calendar.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_symptom_intro.xml
  Corona-Warn-App/src/main/res/layout/include_submission_symptom_length_selection.xml
  Corona-Warn-App/src/main/res/layout/include_submission_target_selection.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/ScanResultTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/submission/SubmissionServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/ExposureKeyHistoryCalculationsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/TransmissionRiskVectorDeterminatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/SubmitDiagnosisKeysTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/calendar/CalendarCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/GoogleAPIVersionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/ProtoFormatConverterExtensionsTest.kt
Labels: 1.4.0, maintainers

#1177 1.3.1 into 1.4.0
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/TestForAPIFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/TestRiskLevelCalculationFragment.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_for_a_p_i.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/GoogleQuotaCalculator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/debug/FileLogger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/debug/FileLoggerTree.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/GoogleQuotaCalculatorTest.kt
Labels: 1.4.0, maintainers

#1151 Introduce ViewModel Injection
  .idea/codeStyles/Project.xml
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/device/java/de/rki/coronawarnapp/ui/main/MainActivityTestModule.kt
  Corona-Warn-App/src/device/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/TestRiskLevelCalculationFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/TestForAPIFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/TestForApiFragmentModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/TestForApiFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/risklevel/ui/TestRiskLevelCalculationFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/risklevel/ui/TestRiskLevelCalculationFragmentCWAViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/risklevel/ui/TestRiskLevelCalculationFragmentModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainActivityTestModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/deviceForTesters/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/assets/technical_de.html
  Corona-Warn-App/src/main/assets/technical_en.html
  Corona-Warn-App/src/main/assets/technical_tr.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/NearbyModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/timer/TimerHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/ActivityBinder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/LauncherActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AppInjector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AssistedInjectModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AutoInject.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/LiveDataExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/SingleLiveEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/viewmodel/CWAViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/viewmodel/CWAViewModelExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/viewmodel/CWAViewModelFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/viewmodel/CWAViewModelFactoryProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/viewmodel/CWAViewModelKey.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/viewmodel/SavedStateCWAViewModelFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/viewmodel/SimpleCWAViewModelFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/viewmodel/ViewModelLazyKeyed.kt
  Corona-Warn-App/src/test/java/testhelpers/extensions/CoroutineTestExtension.kt
  Corona-Warn-App/src/test/java/testhelpers/extensions/InstantExecutorExtension.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/risklevel/ui/TestRiskLevelCalculationFragmentCWAViewModelTest.kt
Labels: 1.5.0, enhancement, maintainers

#1161 Reduce boilerplate code for fragment view setup
  .idea/codeStyles/Project.xml
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/device/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/TestForAPIFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/risklevel/ui/TestRiskLevelCalculationFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/UIExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationAboutFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationLegalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationPrivacyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationTechnicalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationTermsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainShareFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTestFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsBackgroundPriorityFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsNotificationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionDoneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionIntroFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionResultPositiveOtherWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/ViewBindingExtensions.kt
  build.gradle
Labels: 1.5.0, maintainers

#1178 Translation Delivery
  Corona-Warn-App/src/main/res/values-ar/strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: 1.4.0, maintainers

#1179 Remover ar & ru and update default strings
  Corona-Warn-App/src/main/res/values-ar/strings.xml
  Corona-Warn-App/src/main/res/values-ru/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.4.0, maintainers

#1181 Improve keyfile checksum handling
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyFileDownloader.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/server/DiagnosisKeyServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/server/DownloadInfo.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyFileDownloaderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/server/DownloadInfoTest.kt
Labels: 1.5.0, maintainers

#1180 Improve interop storage check
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/CountryData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyFileDownloader.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/DeviceStorage.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/CountryDataTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyFileDownloaderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/DeviceStorageTest.kt
Labels: 1.5.0, maintainers

#1182 Fix databinding lifecycle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/ViewBindingExtensions.kt
Labels: 1.5.0, bug, maintainers

#1195 Improve transaction and workmanager related
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundWorkHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalOneTimeWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalPeriodicWorker.kt
Labels: enhancement, maintainers

#1196 Remove QuotaCalculator from hotfix 1.3.1
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/GoogleQuotaCalculator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/QuotaCalculator.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/GoogleQuotaCalculatorTest.kt
Labels: bug, hotfix-1.3.1, maintainers

#1203 Replace Handy with Smartphone (EXPOSUREAPP-2777)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.4.0, maintainers

#1201 QuotaCalculator v2
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/TestForAPIFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/TestRiskLevelCalculationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/ENFClient.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/ENFClientLocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/ENFModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/InternalExposureNotificationClient.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/diagnosiskeyprovider/DefaultDiagnosisKeyProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/diagnosiskeyprovider/DiagnosisKeyProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/diagnosiskeyprovider/SubmissionQuota.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisInjectionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/GoogleQuotaCalculator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/QuotaCalculator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeStamper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundWorkHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalOneTimeWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalPeriodicWorker.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/ENFClientTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/modules/diagnosiskeyprovider/DefaultDiagnosisKeyProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/modules/diagnosiskeyprovider/SubmissionQuotaTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/GoogleQuotaCalculatorTest.kt
Labels: 1.4.0, enhancement, maintainers

#1190 Improve low storage error message (EXPOSUREAPP-2745)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/InsufficientStorageException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/FormattedError.kt
Labels: 1.5.0, enhancement, maintainers

#1206 Fix: Update data privacy (de & en) and user consent (de) (EXPOSUREAPP-2778)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.4.0, maintainers

#1209 Replace "Mobiltelefon/Handy/Endgerät" by "Smartphone" in terms_de (EXPOSUREAPP-2777)
  Corona-Warn-App/src/main/assets/terms_de.html
Labels: 1.4.0, maintainers

#1212 Add SabineLoss as additional UA Code Owner
  CODEOWNERS
Labels: 1.4.0, maintainers

#1211 Fix: Update data privacy (tr) (EXPOSUREAPP-2778)
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: 1.4.0, maintainers

#1216 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: 1.4.0, maintainers

#1205 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: 1.5.0, maintainers

#1219 Feature: Update default strings
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.4.0, maintainers

#1194 Texts for interoperability user consent (EXPOSUREAPP-2750)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.5.0, maintainers

#1198 Turkish FAQ link fixed (EXPOSUREAPP-2759)
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: 1.5.0, maintainers

#1225 Merge hotfix 1.3.1 to master
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/deviceForTesters/java/de.rki.coronawarnapp/TestForAPIFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de.rki.coronawarnapp/TestRiskLevelCalculation.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_for_a_p_i.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/WebRequestBuilder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/keycache/KeyCacheDao.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/keycache/KeyCacheRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/DefaultRiskDetailPresenter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailPresenter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/TracingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CachedKeyFileHolder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/debug/FileLogger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/debug/FileLoggerTree.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundWorkHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalOneTimeWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalPeriodicWorker.kt
  Corona-Warn-App/src/main/res/layout/fragment_risk_details.xml
  Corona-Warn-App/src/main/res/layout/include_risk_details_low_risk_encounter.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/riskdetails/DefaultRiskDetailPresenterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelperTest.kt
Labels: hotfix-1.3.1, maintainers

#1197 Text changes for existing user consent (EXPOSUREAPP-2751)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.5.0, maintainers

#1220 Simplify threading to prevent flaky tests
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyFileDownloaderTest.kt
Labels: maintainers

#1229 Fix: Update legal texts for symptom request (EXPOSUREAPP-2851)
  Corona-Warn-App/src/main/res/layout/fragment_submission_symptom_intro.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.4.0, maintainers

#1227 Make transaction timeout settable per transaction. Increase Risk Leve…
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RiskLevelTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/Transaction.kt
Labels: 1.5.0, enhancement, maintainers

#1231 Remove RKI-Hotline from terms of use (tr, en) (EXPOSUREAPP-2633)
  Corona-Warn-App/src/main/assets/terms_en.html
  Corona-Warn-App/src/main/assets/terms_tr.html
Labels: 1.4.0, bug, maintainers

#1242 Replace "Mobiltelefon/Handy/Endgerät" by "Smartphone" (EXPOSUREAPP-2777)
  Corona-Warn-App/src/main/assets/privacy_en.html
Labels: 1.4.0, maintainers

#1191 Activity “Risiko-Ermittlung” switch off does not announce “Gestoppt” directly after action (EXPOSUREAPP-1798)
  Corona-Warn-App/src/main/res/layout/include_settings_switch_row.xml
Labels: 1.5.0, accessibility, maintainers

#1236 Fix Grammar error in "Datenschutzverordung" (EXPOSUREAPP-2251)
  Corona-Warn-App/src/main/assets/privacy_de.html
Labels: 1.4.0, maintainers

#1193 TAN Hotline no. not clickable (EXPOSUREAPP-2551)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionContactFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_contact.xml
  Corona-Warn-App/src/main/res/layout/include_submission_contact.xml
Labels: 1.5.0, maintainers

#1243 Encounter with low risk missing link in risk details (EXPOSUREAPP-2883)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_risk_details.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.4.0, maintainers

#1232 Interoperability: List of Countries can not be loaded for 1.5.x in new onboarding / interop (EXPOSUREAPP-2744)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/interoperability/InteroperabilityRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/interoperability/InteroperabilityConfigurationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/interoperability/InteroperabilityConfigurationFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaInteroperabilityFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragmentViewModel.kt
  Corona-Warn-App/src/main/res/drawable/ic_interop_no_network.xml
  Corona-Warn-App/src/main/res/layout/fragment_interoperability_configuration.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_delta_interoperability.xml
  Corona-Warn-App/src/main/res/layout/include_interop_list_participating_countries_overview.xml
  Corona-Warn-App/src/main/res/layout/include_interop_no_countries_infoview.xml
  Corona-Warn-App/src/main/res/layout/include_interop_riskdetails_no_countries_infoview.xml
  Corona-Warn-App/src/main/res/layout/include_interoperability.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.5.0, enhancement, maintainers

#1224 Interoperability: New Note on Data Processing (EXPOSUREAPP-2742)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.5.0, enhancement, maintainers

#1245 Update privacy_tr.html - device to smartphone (EXPOSUREAPP-2777)
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: 1.4.0, maintainers

#1235 Wrap EncryptedSharedPreferences initialization in a retry mechanism (EXPOSUREAPP-1851)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/RetryMechanism.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/EncryptedPreferencesFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/SecurityHelper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/RetryMechanismTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/security/EncryptedPreferencesFactoryTest.kt
Labels: 1.4.0, bug, maintainers

#1247 Update gitignore
  .gitignore
Labels: 1.4.0, maintainers

#1248 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: 1.4.0, maintainers

#1252 1.4.0 version code bump
  Corona-Warn-App/build.gradle
Labels: 1.4.0, maintainers

#1254 Texts for error recovery notice (EXPOSUREAPP-1851)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.4.0, bug, maintainers

#1234 Embed country list for submission of keys screen (EXPOSUREAPP-2738)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/SubmissionViewModel.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_positive_other_warning.xml
  Corona-Warn-App/src/main/res/layout/include_submission_positive_other_warning.xml
  Corona-Warn-App/src/main/res/layout/view_country_list_entry.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/CountryDataTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyFileDownloaderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/server/DiagnosisKeyApiTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/server/DiagnosisKeyServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/service/applicationconfiguration/ApplicationConfigurationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransactionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/HashExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/database/CommonConvertersTest.kt
  Corona-Warn-App/src/test/java/testhelpers/extensions/InstantExecutorExtension.kt
Labels: 1.5.0, enhancement, maintainers

#1251 Update default strings (EXPOSUREAPP-2865)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.4.0, maintainers

#1244 Tess Relay for technical hotline (EXPOSUREAPP-2690)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.5.0, maintainers

#1253 Textual Enhancement in Context of "Gesundheitsamt" (EXPOSUREAPP-2692)
  Corona-Warn-App/src/main/res/layout/include_submission_done_content.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.5.0, maintainers, ui

#1249 Force specific log tags in a few instances
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/TracingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/VerificationKeys.kt
Labels: 1.5.0, enhancement, maintainers

#1255 Enhanced tests for interop / countrylist (Exposureapp-2733, EXPOSUREAPP-2744)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/interoperability/InteroperabilityConfigurationFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/testhelpers/extensions/LiveDataTestExtension.kt
Labels: 1.5.0, maintainers

#1257 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: 1.4.0, maintainers

#1258 Update default strings
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: 1.4.0, maintainers

#1256 Perform data reset for users already affected by the encryption issues (EXPOSUREAPP-1851/EXPOSUREAPP-2958)
  Corona-Warn-App/config/detekt.yml
  Corona-Warn-App/src/device/java/de.rki.coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/errors/ExceptionExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/errors/RecoveryByResetDialogFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/EncryptionErrorResetTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/SecurityHelper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/errors/ExceptionExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/security/EncryptionResetToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/security/SecurityHelperTest.kt
  Corona-Warn-App/src/test/java/testhelpers/preferences/MockSharedPreferences.kt
  Corona-Warn-App/src/test/java/testhelpers/preferences/MockSharedPreferencesTest.kt
Labels: 1.4.0, bug, maintainers

#1259 Version code bump
  Corona-Warn-App/build.gradle
Labels: 1.4.0, maintainers

#1262 Unify interoperability titles and fix small typo
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.5.0, maintainers

#1221 Fix various code smells and refactor our Application class
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/api/ui/TestForAPIFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CWADebug.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/WatchdogService.kt
Labels: maintainers

#1260 Pull latest 1.4.x into 1.5.x
  Corona-Warn-App/build.gradle
  Corona-Warn-App/config/detekt.yml
  Corona-Warn-App/src/device/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainFragment.kt
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
  Corona-Warn-App/src/main/assets/terms_en.html
  Corona-Warn-App/src/main/assets/terms_tr.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/RetryMechanism.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/errors/ExceptionExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/errors/RecoveryByResetDialogFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterRiskHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/EncryptedPreferencesFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/EncryptionErrorResetTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/SecurityHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_risk_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_symptom_intro.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/RetryMechanismTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/errors/ExceptionExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/security/EncryptedPreferencesFactoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/security/EncryptionResetToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/security/SecurityHelperTest.kt
  Corona-Warn-App/src/test/java/testhelpers/preferences/MockSharedPreferences.kt
  Corona-Warn-App/src/test/java/testhelpers/preferences/MockSharedPreferencesTest.kt
Labels: 1.5.0, maintainers

#1264 Improve German wording on interoperability onboarding screen (EXPOSUREAPP-2971)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: 1.5.0, maintainers
