Repository corona-warn-app/cwa-app-android, pull requests merged in 2021-10, with the labels that each got.

#4144 Root Detection & User Information (EXPOSUREAPP-9069)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/launcher/LauncherActivityTest.kt
  Corona-Warn-App/src/main/assets/technical.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/rootdetection/RootDetectionCheck.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/rootdetection/RootDetectionDialogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/rootdetection/RootDetectionModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/rootdetection/RootDetectionCheckTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/rootdetection/RootDetectionModuleTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/launcher/LauncherActivityViewModelTest.kt
Labels: maintainers

#4159 FAB colour (EXPOSUREAPP-9671)
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
Labels: ui, maintainers

#4160 Text change
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#4150 Create notifications settings screen on/off states (EXPOSUREAPP-9616)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/notifications/NotificationSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/notifications/NotificationSettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/notifications/NotificationSettingsFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/notifications/NotificationSettingsState.kt
  Corona-Warn-App/src/main/res/layout/fragment_settings_notifications.xml
  Corona-Warn-App/src/main/res/layout/include_navigation_row.xml
  Corona-Warn-App/src/main/res/layout/notifications_delta_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/values-de/notifications_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/notifications_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/notification/NotificationSettingsFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/notification/NotificationSettingsStateTest.kt
Labels: maintainers, text change

#4166 Fix Toolbar is not visible in UQS screen (DEV)
  Corona-Warn-App/src/main/res/layout/fragment_qrcode_scanner.xml
Labels: bug, maintainers

#4162 Translation Delivery
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#4167 UQS styling issues (EXPOSUREAPP-9755)
  Corona-Warn-App/src/main/res/layout/fragment_qrcode_scanner.xml
Labels: bug, maintainers

#4169 Notification manager compat only (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/notification/DigitalCovidCertificateNotifications.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/GeneralNotifications.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/common/PresenceTracingNotifications.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/notifications/NotificationSettingsFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AndroidModule.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/pcr/notification/PCRTestResultAvailableNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/notification/RATestResultAvailableNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationTest.kt
Labels: enhancement, maintainers

#4164 Adapt Vaccination Color + Bring Back EU Stars (EXPOSUREAPP-9076)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
Labels: bug, ui, maintainers

#4163 Link App notifications settings + screenshots (EXPOSUREAPP-9618, 9617)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaNotificationsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/settings/notifications/NotificationSettingsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/common/TestResultAvailableNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/notification/PCRTestResultAvailableNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/notification/RATTestResultAvailableNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/notification/DigitalCovidCertificateNotifications.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/main/CWASettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/GeneralNotifications.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/common/PresenceTracingNotifications.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/notifications/NotificationSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/notifications/NotificationSettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/notifications/NotificationSettingsFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsNotificationState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AndroidModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/encryptionmigration/EncryptedPreferencesMigration.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/pcr/notification/PCRTestResultAvailableNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/notification/RATestResultAvailableNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/notification/NotificationSettingsFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/notification/NotificationsSettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/start/SettingsFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/start/SettingsNotificationStateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/encryptionmigration/EncryptedPreferencesMigrationTest.kt
Labels: maintainers

#4173 UQS Certificate Scan - "Neu" ist missing on Vacc und Rec Certificates (EXPOSUREAPP-9756)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonCertificatesData.kt
Labels: bug, maintainers

#4171 Uqs error handling / dialog clenaup (EXPOSUREAPP-9777)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
Labels: bug, maintainers

#4180 Fix crash due to mismatch of time types (EXPOSUREAPP-9880)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
Labels: bug, maintainers, prio

#4152 Auto checkout fix (EXPOSUREAPP-8700)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/qrcode/DefaultAutoCheckoutLength.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/locations/DefaultAutoCheckoutLengthTest.kt
Labels: bug, maintainers

#4186 Update overflow menu to have new icons and new recycle bin item (EXPOSUREAPP-9836)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_menu_info.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_menu_overview.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_menu_settings.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_menu_trash.xml
  Corona-Warn-App/src/main/res/drawable/ic_menu_info.xml
  Corona-Warn-App/src/main/res/drawable/ic_menu_overview.xml
  Corona-Warn-App/src/main/res/drawable/ic_menu_settings.xml
  Corona-Warn-App/src/main/res/drawable/ic_menu_trash.xml
  Corona-Warn-App/src/main/res/menu/menu_main.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: ui, maintainers, text change

#4201 Text change
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#4187 RecycleBin - Return recycled certs (EXPOSUREAPP-9845, EXPOSUREAPP-9857)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/repository/CertificateRepoContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/BaseTestCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPerson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/common/Recyclable.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPersonTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/common/RecyclableTest.kt
Labels: maintainers

#4210 RecycleBin - additonal testcases for recycled filtering (EXPOSUREAPP-9703)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
Labels: maintainers

#4212 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#4208 Recycle certificate confirm dialog (EXPOSUREAPP-9841)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/recycler_bin_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
Labels: ui, maintainers, text change

#4193 Global 7 day infections and hospitalisation incidents (EXPOSUREAPP-9833)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/StatsItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/StatisticsParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsCardAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/IncidenceAndHospitalizationCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/SevenDayHospitalizationCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterStatistics.kt
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_incidence_layout.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/StatisticsDataTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/source/StatisticsParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterStatisticsHelperTest.kt
Labels: ui, maintainers, text change

#4224 Fix new release back navigation (EXPOSUREAPP-9971, 10005)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/release/NewReleaseInfoViewModelTest.kt
Labels: bug, maintainers, prio

#4227 Update event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
Labels: text change

#4230 RecycleBin - Screenshot (EXPOSUREAPP-9859)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
Labels: maintainers

#4242 Adaption of text
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4247 Bump to next Version 2.13.0.1
  gradle.properties
Labels: maintainers

#4252 Info adjustments for recycleview (EXPOSUREAPP-10122)
  Corona-Warn-App/src/main/res/values-de/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values/recycler_bin_strings.xml
Labels: maintainers, text change
