Repository corona-warn-app/cwa-app-android, pull requests merged in 2021-09, with the labels that each got.

#3991 Update logic to show / hide notification badges (EXPOSUREAPP-9192)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/StoredRecoveryCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/BaseTestCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/GenericTestCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/PCRCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/RACertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckSchedulerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckWorkerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonCertificatesData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
Labels: maintainers

#3999 Booster notification api service (EXPOSUREAPP-9197)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterRulesRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/server/BoosterRulesApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/server/BoosterRulesServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationCache.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/Mappings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/common/exception/DccValidationException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRuleApi.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRuleConverter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/server/DccValidationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/ValidationResultItemCreator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterRulesRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRuleConverterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/server/DccValidationServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
Labels: maintainers

#4005 Wrong vaccination ranking (EXPOSUREAPP-9261)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
Labels: bug, maintainers, prio

#4001 Apply booster rules (EXPOSUREAPP-9201)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/DigitalCovidCertificateModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/DccBoosterRulesValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DigitalSignatureCertificateModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationCertificateModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/execution/VaccinationUpdateScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/execution/task/VaccinationUpdateTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/execution/worker/VaccinationUpdateWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/execution/worker/VaccinationUpdateWorkerRequestBuilder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicEngineWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/Mappings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/worker/WorkerBinder.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/CoronaWarnApplicationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/DccBoosterRulesValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/execution/VaccinationUpdateSchedulerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/execution/task/VaccinationUpdateTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/execution/worker/VaccinationUpdateWorkerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicEngineWrapperTest.kt
Labels: maintainers

#3998 Vaccination Info Card Update (EXPOSUREAPP-9203)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationInfoCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPerson.kt
  Corona-Warn-App/src/main/res/drawable/ic_booster_badge.xml
  Corona-Warn-App/src/main/res/layout/vaccination_info_card.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: ui, maintainers, text change

#3987 Inconsistent formatting of dates (EXPOSUREAPP-9127)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/CommonSubmissionStates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/CwaUserCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeAndDateExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileDataCreateFragmentViewModelTest.kt
Labels: bug, maintainers

#4009 UA Bugfix(EXPOSUREAPP-9243)
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
Labels: text change

#4006 Certificate poster fragment (EXPOSUREAPP-9188, EXPOSUREAPP-9189, EXPOSUREAPP-9190)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/DigitalCovidCertificateUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/CertificateExportException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/CertificatePdfExportInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/poster/CertificatePosterFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/poster/CertificatePosterModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/poster/CertificatePosterViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ContextExtensions.kt
  Corona-Warn-App/src/main/res/layout/certificate_poster_fragment.xml
  Corona-Warn-App/src/main/res/layout/fragment_recovery_certificate_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_test_certificate_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
  Corona-Warn-App/src/main/res/menu/menu_certificate_poster.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: ui, maintainers

#4024 Bump kotlin gradle version(DEV)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/Timber.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/retention/ContactDiaryCleanTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotification.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/NotificationReceiver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/organizer/submission/OrganizerSubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/organizer/submission/server/OrganizerSubmissionServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/receiver/ExposureStateUpdateReceiver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelTask.kt
  Corona-Warn-App/src/test/java/testhelpers/BaseTest.kt
  Corona-Warn-App/src/testShared/java/testhelpers/BaseTestInstrumentation.kt
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, maintainers, author merge

#4023 Cleanup (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/coil/CoilExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
Labels: maintainers

#4016 Notification badges on cards and details (EXPOSUREAPP-9195)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/drawable/circle_certificate_notification_badge.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
  Corona-Warn-App/src/main/res/layout/recovery_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/test_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/vaccination_certificate_card.xml
Labels: ui, maintainers

#4022 Update cert logic (EXPOSUREAPP-9120)
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-51-9ec94ba/dgc-certlogic-android-light-1.0.0-51-9ec94ba-sources.jar
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-51-9ec94ba/dgc-certlogic-android-light-1.0.0-51-9ec94ba-sources.jar.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-51-9ec94ba/dgc-certlogic-android-light-1.0.0-51-9ec94ba-sources.jar.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-51-9ec94ba/dgc-certlogic-android-light-1.0.0-51-9ec94ba-sources.jar.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-51-9ec94ba/dgc-certlogic-android-light-1.0.0-51-9ec94ba-sources.jar.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-51-9ec94ba/dgc-certlogic-android-light-1.0.0-51-9ec94ba.aar
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-51-9ec94ba/dgc-certlogic-android-light-1.0.0-51-9ec94ba.aar.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-51-9ec94ba/dgc-certlogic-android-light-1.0.0-51-9ec94ba.aar.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-51-9ec94ba/dgc-certlogic-android-light-1.0.0-51-9ec94ba.aar.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-51-9ec94ba/dgc-certlogic-android-light-1.0.0-51-9ec94ba.aar.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-51-9ec94ba/dgc-certlogic-android-light-1.0.0-51-9ec94ba.pom.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-51-9ec94ba/dgc-certlogic-android-light-1.0.0-51-9ec94ba.pom.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-51-9ec94ba/dgc-certlogic-android-light-1.0.0-51-9ec94ba.pom.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-51-9ec94ba/dgc-certlogic-android-light-1.0.0-51-9ec94ba.pom.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-59-4094e31/dgc-certlogic-android-light-1.0.0-59-4094e31-sources.jar
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-59-4094e31/dgc-certlogic-android-light-1.0.0-59-4094e31-sources.jar.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-59-4094e31/dgc-certlogic-android-light-1.0.0-59-4094e31-sources.jar.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-59-4094e31/dgc-certlogic-android-light-1.0.0-59-4094e31-sources.jar.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-59-4094e31/dgc-certlogic-android-light-1.0.0-59-4094e31-sources.jar.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-59-4094e31/dgc-certlogic-android-light-1.0.0-59-4094e31.aar
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-59-4094e31/dgc-certlogic-android-light-1.0.0-59-4094e31.aar.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-59-4094e31/dgc-certlogic-android-light-1.0.0-59-4094e31.aar.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-59-4094e31/dgc-certlogic-android-light-1.0.0-59-4094e31.aar.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-59-4094e31/dgc-certlogic-android-light-1.0.0-59-4094e31.aar.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-59-4094e31/dgc-certlogic-android-light-1.0.0-59-4094e31.pom
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-59-4094e31/dgc-certlogic-android-light-1.0.0-59-4094e31.pom.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-59-4094e31/dgc-certlogic-android-light-1.0.0-59-4094e31.pom.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-59-4094e31/dgc-certlogic-android-light-1.0.0-59-4094e31.pom.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-59-4094e31/dgc-certlogic-android-light-1.0.0-59-4094e31.pom.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml.sha512
Labels: maintainers

#4010 Unit tests / Test menu entry improvement (EXPOSUREAPP-9193)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/booster/ui/BoosterTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/booster/ui/BoosterTestViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_booster.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationService.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/DccBoosterRulesValidatorTest.kt
Labels: maintainers

#4025 Improve certificate validity notifications testability (DEV)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dsc/ui/DscTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dsc/ui/DscTestViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_dsc.xml
Labels: enhancement, maintainers

#4012 Update PersonDetails Screenshots (EXPOSUREAPP-9275)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestExtensions.kt
Labels: maintainers

#4033 Unify badge colour (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/BottomNavigationViewExtensions.kt
  Corona-Warn-App/src/main/res/drawable/circle_certificate_notification_badge.xml
  Corona-Warn-App/src/main/res/drawable/ic_booster_badge.xml
  Corona-Warn-App/src/main/res/values/colors.xml
Labels: enhancement, maintainers

#4034 UA Bugfix(EXPOSUREAPP-9310)
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
Labels: text change

#4008 PDF Generator (EXPOSUREAPP-9191)
  Corona-Warn-App/src/main/assets/recovery_certificate_template.pdf
  Corona-Warn-App/src/main/assets/test_certificate_template.pdf
  Corona-Warn-App/src/main/assets/vaccination_certificate_template.pdf
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/DigitalCovidCertificateModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificateUI.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/repository/CertificateRepoContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/CertificateDrawHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/ExportCertificateModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/PdfGenerator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/PdfTemplateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/RecoveryCertificateDrawHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/TestCertificateDrawHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/TextArea.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/Utils.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/VaccinationCertificateDrawHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/poster/CertificatePosterFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/poster/CertificatePosterViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/PersonDetailsQrCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/res/font/opensans.ttf
  Corona-Warn-App/src/main/res/layout/certificate_poster_fragment.xml
  Corona-Warn-App/src/main/res/menu/menu_certificate_poster.xml
  Corona-Warn-App/src/main/res/xml/provider_paths.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/pdf/core/PdfTemplateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/pdf/core/UtilsTest.kt
Labels: maintainers

#4031 Test cert card status (EXPOSUREAPP-8718)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: ui, maintainers, text change

#4029 Show badge count and badge text under certificate QR (EXPOSUREAPP-9194)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/drawable/circle_badge_count.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers, text change

#4032 Adapt privacy notice for Release 2.10 (EXPOSUREAPP-9169)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers

#4037 Adjust Info Screen to announce new Release-Features for 2.10 (EXPOSUREAPP-9172)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#4035 Formatting issue on active check-in (EXPOSUREAPP-9313)
  Corona-Warn-App/src/main/res/layout/trace_location_attendee_checkins_item_active.xml
Labels: bug, maintainers

#4027 White Screen after Entering a Reused or Expired TAN (EXPOSUREAPP-9043)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/SubmissionTanFragment.kt
Labels: bug, maintainers

#4026 Fix wrong screenshot name (EXPOSUREAPP-9302)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/eventregistration/organizer/TraceLocationsFragmentTest.kt
Labels: bug, maintainers

#4039 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/green_certificate_strings.xml
Labels: maintainers

#4028 Fix behaviour after certificate scan (EXPOSUREAPP-9221)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/scan/DccQrCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/scan/DccQrCodeScanViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: bug, maintainers

#4040 Update screenshots on overview screen (EXPOSUREAPP-9278)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
Labels: maintainers

#4041 Fix: Person details screenshots (EXPOSUREAPP-9319)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
Labels: bug, maintainers

#4036 Regression in date of birth formatting (EXPOSUREAPP-9297)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/CwaUserCard.kt
Labels: bug, maintainers, author merge

#4043 Fix screenshots 2.10 (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
Labels: bug, maintainers

#4045 Bump to next Version 2.10.0.1
  gradle.properties
Labels: maintainers

#4047 Implement new Scan screen design in Dark/Light modes (EXPOSUREAPP-9328)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/scan/DccQrCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/scan/ScanCheckInQrCodeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/qrcode/QrViewfinderView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/scan/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/res/drawable/ic_image.xml
  Corona-Warn-App/src/main/res/layout/fragment_scan_qr_code.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_qr_code_scan.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/attrs.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#4049 Negative PCR-Test: Line between symbols wrongly connected (EXPOSUREAPP-9378)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
Labels: bug, maintainers

#4055 UA Bugfix(EXPOSUREAPP-9382)
  Corona-Warn-App/src/main/res/values-de/green_certificate_strings.xml
Labels: text change

#4050 Contact Journal AllOver-10Minute Change (EXPOSUREAPP-9236)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/contactdiary/storage/ContactDiaryDatabaseTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/DiaryData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/ContactDiaryPersonEncounter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/internal/converters/ContactDiaryRoomConverters.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/location/ContactDiaryLocationListFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/person/DiaryPersonViewHolder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/exporter/ContactDiaryExporter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewViewModel.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_person_list_item.xml
  Corona-Warn-App/src/main/res/values-bg/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-pl/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-ro/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-tr/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings_export.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/storage/internal/converters/ContactDiaryRoomConvertersTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/ui/exporter/ContactDiaryExporterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/util/ContactDiaryData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/util/ContactDiaryExportStringsMock.kt
Labels: maintainers, text change, author merge

#4059 Harmonization of Einstellungen Usages
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4063 Adjustment of Release Note
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: text change

#4064 Fix url link replacement (EXPOSUREAPP-9385)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TextViewUrlExtensions.kt
Labels: bug, maintainers

#4054 UQS error handling (EXPOSUREAPP-9326)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/exception/InvalidHealthCertificateException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/handler/CoronaTestQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/scanner/UnsupportedQrCodeException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/TestRegistrationStateProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ExternalActionHelper.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/ExternalActionHelperTest.kt
Labels: maintainers, text change

#4062 Expose corrected json payload (EXPOSUREAPP-9435)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccV1Parser.kt
Labels: bug, maintainers, prio

#4068 Add arrow in persons card (EXPOSUREAPP-9429)
  Corona-Warn-App/src/main/res/layout/person_overview_item.xml
Labels: bug, maintainers

#4069 Harmonization of Einstellungen Usages
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4065 Check duplicate test on scanning (EXPOSUREAPP-9441)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
Labels: maintainers, author merge

#4067 Bug: Registration Token visible in error report
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/BugReportingSharedModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/CoronaTestCertificateCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/DebugLogger.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/CensorInjectionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/CoronaTestCertificateCensorTest.kt
Labels: bug, maintainers

#4073 Fix/9452 Correct RKI spelling in recovery certificate screenshot (COMMUNITY)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
Labels: mirrored-to-jira, community

#4072 Incorrect booster vaccination screenshots (EXPOSUREAPP-9398)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
Labels: bug, maintainers

#4060 Add import file to submission on behalf(EXPOSUREAPP-9331)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/res/layout/fragment_qrcode_scanner.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#4057 Certificate display switches to expired-view (if expired) after opening the certificate view (EXPOSUREAPP-8837)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
Labels: maintainers, prio, author merge

#4061 UQS update submission flow screen order (EXPOSUREAPP-9332)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionQrCodeScanFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/scan/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/scan/SubmissionQRCodeScanViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionDispatcherViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionNavigationEvents.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_consent.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/qrcode/scan/SubmissionQRCodeScanViewModelTest.kt
Labels: maintainers, author merge

#4058 Update FAQ Position (EXPOSUREAPP-9031)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/failed/DccValidationFailedViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/open/DccValidationOpenViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/passed/DccValidationPassedViewModel.kt
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: maintainers, text change

#4077 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#4076 Revert certificates priority changes (EXPOSUREAPP-9277)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
Labels: bug, maintainers, prio

#4079 Bump to next Version 2.10.0.2
  gradle.properties
Labels: maintainers

#4081 Wire test consent screen (EXPOSUREAPP-9324)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/qrcode/CoronaTestQRCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/qrcode/PcrQrCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/qrcode/RapidAntigenQrCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionNavigationEvents.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/CoronaTestRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/qrcode/CoronaTestQRCodeTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RAProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/SubmissionRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/TestRegistrationStateProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentViewModelTest.kt
Labels: maintainers

#4080 Implement error dialog of importing files (EXPOSUREAPP-9335)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/QrCodeFileParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/provider/QRCodeBitmapProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/scanner/ImportDocumentException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/scanner/UnsupportedQrCodeException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#4082 Update Playstore Screenshots (EXPOSUREAPP-9470)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestExtensions.kt
Labels: maintainers

#4085 Registration Token visible in error report (EXPOSUREAPP-9383)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/BugReportingSharedModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/contactdiary/OrganizerRegistrationTokenCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/OrganizerPlaybook.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/contactdiary/OrganizerRegistrationTokenCensorTest.kt
Labels: bug, maintainers, prio

#4084 No Notification to Warn Others after Positive PCR (EXPOSUREAPP-9122)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/main/CWASettings.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotificationServiceTest.kt
Labels: bug, maintainers, prio

#4091 Bump to next Version 2.10.1.0
  gradle.properties
Labels: maintainers

#4089 Adjust Tests navigation (EXPOSUREAPP-9325)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestDccNavEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentFragment.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateViewModelTest.kt
Labels: maintainers

#4093 Bump to next Version 2.10.1.1
  gradle.properties
Labels: maintainers

#4083 UQS badges (EXPOSUREAPP-9327)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/CoronaTestRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/CoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/CoronaTestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRCoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRTestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RACoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RATestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/StoredRecoveryCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/BaseTestCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/GenericTestCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/RetrievedTestCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/ui/onboarding/CovidCertificateOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/storage/CoronaTestStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
Labels: maintainers

#4092 Follow-up: Fix missing blog link (EXPOSUREAPP-9385)
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: bug, maintainers, prio

#4086 Update external qr scan flow (EXPOSUREAPP-9463)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/DeepLinkDirections.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentFragment.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
Labels: maintainers

#4078 Add visual certificate indicator (EXPOSUREAPP-9200)
  Corona-Warn-App/src/main/res/layout/recovery_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/test_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/vaccination_certificate_card.xml
Labels: ui, maintainers, text change

#4097 2.10 into 2.11 (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/BugReportingSharedModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/contactdiary/OrganizerRegistrationTokenCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/CoronaTestCertificateCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/DebugLogger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccV1Parser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/decoder/DccCoseDecoder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/main/CWASettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/OrganizerPlaybook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TextViewUrlExtensions.kt
  Corona-Warn-App/src/main/res/layout/person_overview_item.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/CensorInjectionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/CoronaTestCertificateCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/contactdiary/OrganizerRegistrationTokenCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/KidExtractionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/TestData.java
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/qrcode/TestCertificateQRCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationQrCodeTestData.java
Labels: maintainers, author merge

#4095 Adapt privacy notice for Release 2.11 (EXPOSUREAPP-9304)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers

#4090 Add CovPass Info Fragment (EXPOSUREAPP-9474)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/covpass/CovPassInfoFragment.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_cov_pass_info.xml
  Corona-Warn-App/src/main/res/drawable/ic_cov_pass_info.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_privacy_card.xml
  Corona-Warn-App/src/main/res/layout/fragment_cov_pass_info.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: ui, text change

#4096 Adjust Info Screen to announce new Release-Features for 2.11 (EXPOSUREAPP-9305)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#4099 Polishing / Testing UQS (EXPOSUREAPP-9433)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/coronatest/ui/CoronaTestTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/coronatest/ui/CoronaTestTestFragmentModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/coronatest/ui/CoronaTestTestFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainActivityTestModule.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_coronatest.xml
  Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/qrcode/CoronaTestQRCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/qrcode/CoronaTestQrCodeValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/qrcode/PcrQrCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/qrcode/RapidAntigenQrCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/qrcode/DccQrCodeValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/scanner/QrCodeValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/DeepLinkDirections.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentViewModel.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/CoronaTestRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/qrcode/CoronaTestQRCodeTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/qrcode/CoronaTestQrCodeValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RAProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/qrcode/DccQrCodeValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/scanner/QrCodeValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/SubmissionRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/TestRegistrationStateProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentViewModelTest.kt
Labels: maintainers

#4105 Create CovPassInfoFragment Screenshot (EXPOSUREAPP-9481)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/covpass/CovPassInfoFragmentTest.kt
Labels: maintainers

#4104 QR Certificate - details adjustments (EXPSUREAPP-9479)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/res/layout/person_details_fragment.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: maintainers

#4103 UA Text Adjustment(EXPOSUREAPP-9502)
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
Labels: text change

#4046 App Update (EXPOSUREAPP-8905)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/launcher/LauncherActivityTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/update/InAppUpdate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/update/InAppUpdateModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/update/UpdateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/update/VersionComparator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/launcher/LauncherActivityViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/update/UpdateCheckerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/update/VersionComparatorTest.kt
Labels: maintainers

#4102 Adjust recommended actions for risk details screens (EXPOSUREAPP-9222)
  Corona-Warn-App/src/main/res/drawable/ic_thermometer.xml
  Corona-Warn-App/src/main/res/drawable/ic_vaccination_arm.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_item_behavior_increased_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_item_behavior_normal_view.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#4110 Fix space for Next button on PDF export info screen (COMMUNITY)
  Corona-Warn-App/src/main/res/layout/certificate_pdf_export_info_fragment.xml
Labels: community

#4108 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-bg/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#4109 Register DCC after info screen confirmation (EXPOSUREAPP-9562)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/vaccination/CovidCertificateOnboardingFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/ui/onboarding/CovidCertificateOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/ui/onboarding/CovidCertificateOnboardingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrcodeSharedViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/CheckInsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/confirm/ConfirmCheckInFragment.kt
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
Labels: maintainers

#4111 Translation delivery
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-bg/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#4087 Certificates - CovPass Information Adjustments (EXPOSUREAPP-9430)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/covpass/CovPassInfoFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/covpass/CovPassInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/PersonDetailsQrCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_cov_pass_info.xml
  Corona-Warn-App/src/main/res/drawable/ic_cov_pass_info.xml
  Corona-Warn-App/src/main/res/drawable/ic_person_overview_item_right_arrow.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_privacy_card.xml
  Corona-Warn-App/src/main/res/layout/fragment_cov_pass_info.xml
  Corona-Warn-App/src/main/res/layout/fragment_recovery_certificate_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
  Corona-Warn-App/src/main/res/layout/person_details_fragment.xml
  Corona-Warn-App/src/main/res/layout/person_overview_item.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: maintainers, author merge

#4107 Improve QR code importing capabilities and prevent OOM crash
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/QrCodeFileParser.kt
Labels: bug, maintainers

#4115 Bump to next Version 2.11.0.1
  gradle.properties
Labels: maintainers

#4118 Open scanner instead of Consent (EXPOSUREAPP-9633)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/ProfileQrCodeNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragmentViewModel.kt
  Corona-Warn-App/src/main/res/layout/rat_profile_qr_code_fragment.xml
Labels: bug, maintainers, prio

#4119 Bump to next Version 2.11.0.2
  gradle.properties
Labels: maintainers

#4123 Latest issued Vaccination DCC 2/2 does not have highest priority (EXPOSUREAPP-8756)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
Labels: bug, maintainers, prio

#4120 New Bottom Bar design (EXPOSUREAPP-9605)
  .reuse/dep5
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/onboarding/ContactDiaryOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/CameraPermissionCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/ui/onboarding/CovidCertificateOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/UIExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/CheckInEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/CheckInsAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/CheckInsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/CheckInsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/items/CameraPermissionVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/onboarding/CheckInOnboardingFragment.kt
  Corona-Warn-App/src/main/res/animator/fab_hide.xml
  Corona-Warn-App/src/main/res/animator/fab_show.xml
  Corona-Warn-App/src/main/res/drawable/ic_certificates.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_certificates.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_certificates_active.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_certificates_inactive.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_checkin.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_checkins_active.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_checkins_inactive.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_diary.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_diary_active.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_diary_inactive.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_home.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_qrcode.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_status.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_status_active.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_status_inactive.xml
  Corona-Warn-App/src/main/res/layout/activity_main.xml
  Corona-Warn-App/src/main/res/layout/camera_permission_item.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_fragment.xml
  Corona-Warn-App/src/main/res/layout/fragment_qrcode_scanner.xml
  Corona-Warn-App/src/main/res/layout/home_fragment_layout.xml
  Corona-Warn-App/src/main/res/layout/person_overview_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_attendee_checkins_fragment.xml
  Corona-Warn-App/src/main/res/menu/menu_bottom_nav.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/integers.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/CheckInsViewModelTest.kt
Labels: ui, maintainers, text change

#4126 UA Bug(EXPOSUREAPP-9657)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
Labels: prio, text change

#4125 Overlapping infobox (EXPOSUREAPP-9628)
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
Labels: bug, maintainers, prio

#4124 No Notification to Warn Others after app restart (EXPOSUREAPP-9122)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotification.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/GeneralNotifications.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/NotificationConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/NotificationReceiver.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotificationServiceTest.kt
Labels: bug, maintainers, prio

#4127 Update Placeholder Texts (EXPOSUREAPP-9614)
  Corona-Warn-App/src/main/res/layout/person_overview_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_attendee_checkins_fragment.xml
  Corona-Warn-App/src/main/res/values-bg/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-pl/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-ro/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-tr/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
Labels: maintainers, text change

#4129 Camera permission dialog (EXPOSUREAPP-9612)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/DeepLinkDirections.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/MainActivityEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ExternalActionHelper.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
Labels: ui, maintainers, text change

#4128 Delete certificate pdf after exporting (EXPOSUREAPP-9556)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/poster/CertificatePosterViewModel.kt
Labels: bug, maintainers, prio

#4131 UA Bugfix(EXPOSUREAPP-9681)
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#4132 Add new env (EXPOSUREAPP-9686)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentSetup.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/environment/EnvironmentSetupTest.kt
Labels: maintainers

#4133 Wrong link in certificate infos (EXPOSUREAPP-9668)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/covpass/CovPassInfoFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_cov_pass_info.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers, prio

#4130 Update Details Screen (EXPOSUREAPP-8755)
  Corona-Warn-App/src/main/res/layout/fragment_recovery_certificate_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_test_certificate_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
Labels: bug, maintainers

#4136 Fix re-arranging issue of Vax certs that have the same vaccinationOn (EXPOSUREAPP-8756)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
Labels: bug, maintainers, prio, author merge

#4139 [INTERNAL] Translation delivery: commit by LX Lab
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#4140 Bump to next Version 2.11.0.3
  gradle.properties
Labels: maintainers

#4142 Text Changes
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#4143 Add content description to add qr code button (EXPOSUREAPP-9694)
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_trace_locations_list_fragment.xml
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
Labels: bug, maintainers, text change

#4141 Update Notification Text for Invalid / Expired Certificates (EXPOSUREAPP-9620)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotification.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#4147 Text change(EXPOSUREAPP-9681)
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#4145 Add plurals for last vaccination text (EXPOSUREAPP-9659)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationInfoCard.kt
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: bug, maintainers, text change

#4135 Adjust Info Screen to announce new Release-Features for 2.12 (EXPOSUREAPP-9499)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#4121 Adapt Darkmode Colors (EXPOSUREAPP-9566, 9561)
  Corona-Warn-App/src/main/res/color/button_contact_diary_person.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_old_checkin.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_selected.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_day_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: bug, maintainers

#4137 Notifications delta onboarding (EXPOSUREAPP-9615)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/deltaonboarding/ui/DeltaOnboardingFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/deltaonboarding/ui/DeltaOnboardingFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainActivityTestModule.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_deltaonboarding.xml
  Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/main/CWASettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaAnalyticsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaNotificationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaNotificationsModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaNotificationsNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaNotificationsViewModel.kt
  Corona-Warn-App/src/main/res/layout/notifications_delta_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph_onboarding.xml
  Corona-Warn-App/src/main/res/values-de/notifications_strings.xml
  Corona-Warn-App/src/main/res/values/notifications_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/release/NewReleaseInfoViewModelTest.kt
Labels: ui, maintainers, text change

#4151 Improve CheckIn scanning using slow connection (EXPOSUREAPP-9732)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/qrcode/CheckInQrCodeExtractor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/qrcode/CheckInQrCodeExtractorTest.kt
Labels: bug, maintainers, prio

#4153 Avoid multiple scanner openings (EXPOSUREAPP-9671)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
Labels: maintainers

#4157 Bump to next Version 2.11.1.0
  gradle.properties
Labels: maintainers
