Repository corona-warn-app/cwa-app-android, pull requests merged in 2021-01, with the labels that each got.

#2020 Re-add gradle docs (DEV)
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: maintainers

#2007 Announce Overview and Onboarding screens - accessibility (EXPOSUREAPP-4454-4455)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/onboarding/ContactDiaryOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewMenu.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_day_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_locations_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_persons_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_onboarding_row.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_privacy_card.xml
  Corona-Warn-App/src/main/res/layout/include_contact_diary_header.xml
  Corona-Warn-App/src/main/res/layout/include_contact_diary_overview_header.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: accessibility, maintainers

#2019 Better handling of issues caused by time traveling (RiskResults) (DEV)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/schemas/de.rki.coronawarnapp.risk.storage.internal.RiskResultDatabase/2.json
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/risk/storage/RiskResultDatabaseMigrationTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/risk/storage/RiskResultDatabaseTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/internal/RiskResultDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/internal/migrations/RiskResultDatabaseMigration1To2.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/internal/riskresults/PersistedRiskLevelResultDao.kt
  Corona-Warn-App/src/testShared/java/testhelpers/IsAUnitTest.kt
Labels: maintainers

#2018 Better handling of issues caused by time traveling (DownloadTask) (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/ExposureDetectionConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/ExposureDetectionConfigMapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTaskTest.kt
Labels: maintainers

#2017 Fix sorting of persons and places to be case insensitive for names (EXPOSUREAPP-4488)(closes #2012)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/ContactDiaryLocation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/ContactDiaryLocationVisit.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/ContactDiaryPerson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/ContactDiaryPersonEncounter.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/util/ContactDiaryExtensionsTest.kt
Labels: community, mirrored-to-jira

#2024 Reset the initial registration date on test removal correctly (EXPOSUREAPP-4484) (closes #2005)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/CwaSecurityException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/SubmissionRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/SubmissionRepositoryTest.kt
Labels: bug, community, mirrored-to-jira

#1994 Announce type for location and person - accessibility (EXPOSUREAPP-4459-4458-4456)
  Corona-Warn-App/config/detekt.yml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/ContactDiaryDayFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/location/ContactDiaryLocationListAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/location/ContactDiaryLocationListFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/location/ContactDiaryLocationListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/person/ContactDiaryPersonListAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/person/ContactDiaryPersonListFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/person/ContactDiaryPersonListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditLocationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditPersonsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewMenu.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/util/ContactDiaryExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/util/SelectableItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/LazyString.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_day_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_locations_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_persons_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_location_list_item.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_person_list_item.xml
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
Labels: accessibility, maintainers, text change

#2028 Add fastlane Gemfile (DEV)
  Gemfile
  Gemfile.lock
Labels: enhancement, maintainers

#2015 Create Instrumentation tests & screenshots for the Onboarding flow (EXPOSUREAPP-4478)
  .gitignore
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaInteroperabilityFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTestFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/Screenshot.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/SystemUIDemoModeHelper.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/SystemUIDemoModeRule.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestExtensions.kt
  Corona-Warn-App/src/debug/AndroidManifest.xml
  Corona-Warn-App/src/main/res/layout/include_interoperability.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph_onboarding.xml
  Corona-Warn-App/src/testShared/java/testhelpers/TestDispatcherProvider.kt
  Server-Protocol-Buffer/build.gradle
  fastlane/Screengrabfile
Labels: enhancement, maintainers

#2033 Fix typo in settings background state function (COMMUNITY)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsBackgroundState.kt
  Corona-Warn-App/src/main/res/layout/fragment_settings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/start/SettingsBackgroundStateTest.kt
Labels: community

#2023 Removed Kotlin Android Extensions plugin (EXPOSUREAPP-4495)(closes #2022)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/config/detekt.yml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/entity/ContactDiaryLocationEntity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/entity/ContactDiaryPersonEntity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/Symptoms.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/TanInput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/SimpleStepEntry.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/StepEntry.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/TestResultSectionView.kt
Labels: community, mirrored-to-jira

#2032 Fix typo - UA review (EXPOSUREAPP-4499)
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
Labels: maintainers, text change

#2026 Use ContextCompat when accessing color resources (EXPOSUREAPP-4419) (#1924)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/states/TracingState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/behavior/BehaviorNormalRiskBox.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/statusbar/TracingHeaderState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsBackgroundState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsNotificationState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsTracingState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/invalid/SubmissionTestResultInvalidFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ContextExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DialogHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/tracing/ui/statusbar/TracingHeaderStateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/start/SettingsBackgroundStateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/start/SettingsNotificationStateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/start/SettingsTracingStateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterHelperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelperTest.kt
Labels: community, mirrored-to-jira

#2039 Fix crash when displaying test result (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/TestResultSectionView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
Labels: maintainers

#2034 Deletes wrong Romanian translation (EXPOSUREAPP-4310)
  Corona-Warn-App/src/main/res/values-ro/strings.xml
Labels: maintainers, text change

#2029 Add debug log feature for non-tester builds (EXPOSUREAPP-4451)
  Corona-Warn-App/src/deviceForTesters/AndroidManifest.xml
  Corona-Warn-App/src/deviceForTesters/res/xml/provider_paths.xml
  Corona-Warn-App/src/main/AndroidManifest.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/BugReportingSharedModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/BugCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/RegistrationTokenCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/DebugLogTree.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/DebugLogger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/DebugLoggerBase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/DebugLoggerScope.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/LogLine.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/DebugLogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/DebugLogFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/DebugLogViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CWADebug.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/compression/Zipper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/sharing/FileSharing.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/threads/NamedThreadFactory.kt
  Corona-Warn-App/src/main/res/layout/bugreporting_debuglog_fragment.xml
  Corona-Warn-App/src/main/res/layout/fragment_information.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/xml/provider_paths.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/RegistrationTokenCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/debuglog/DebugLoggerTest.kt
Labels: enhancement, maintainers, text change

#2041 Small build.gradle adjustment (EXPOSUREAPP-4517)
  Corona-Warn-App/build.gradle
Labels: community

#2047 Adjust LongMethod LINT check (DEV)
  Corona-Warn-App/config/detekt.yml
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/risklevel/ui/TestRiskLevelCalculationFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/tasks/ui/TestTaskControllerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorReportReceiver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
Labels: maintainers

#2031 No illustration description for image on Background Priority settings screen (EXPOSUREAPP-4097)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/backgroundpriority/BackgroundPriorityState.kt
  Corona-Warn-App/src/main/res/layout/fragment_settings_background_priority.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers, text change

#2056 Change R8 version to fix pipeline issues (DEV)
  build.gradle
Labels: maintainers

#2040 Use close button on warn others screen (EXPOSUREAPP-4257)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_no_consent_positive_other_warning.xml
Labels: maintainers

#2045 Adjust debuglog sensitive data warning (DEV)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#2006 Contact Journal Day date is not announced (EXPOSUREAPP-4457)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/ContactDiaryDayFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/ContactDiaryDayViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/ContactDiaryOverviewAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/util/ContactDiaryExtensions.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_day_fragment.xml
Labels: accessibility, maintainers

#2057 Revert PR 2034 - Accept is correct in RO (EXPOSUREAPP-4310)
  Corona-Warn-App/src/main/res/values-ro/strings.xml
Labels: maintainers, text change

#2048 Fix missing timestamp on TracingFailed card (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/states/TracingState.kt
Labels: bug, maintainers

#2043 Skeletons for showing statistics in the home screen feed (EXPOSUREAPP-3674)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/StatsItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/StatisticsProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsCardAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsCardPaddingDecorator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/IncidenceCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/InfectionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/KeySubmissionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/StatisticsCardItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_basecard_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_incidence_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_infections_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_keysubmissions_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_scrollcontainer.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
Labels: enhancement, maintainers

#2053 Transnational country list names not changing when language is changed (EXPOSUREAPP-4416)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/Country.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/CountryListView.kt
Labels: maintainers, ui

#2044 Fix Pending result when positive test result has been registered (EXPOSUREAPP-4309)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/TestResultAvailableNotification.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/task/SubmissionTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/task/SubmissionTaskTest.kt
Labels: bug, maintainers

#2051 Contact Journal - cleanUp and code smells (EXPOSUREAPP-4503)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/DefaultContactDiaryLocation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/DefaultContactDiaryPerson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/ContactDiaryDayFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/location/ContactDiaryLocationListAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/person/ContactDiaryPersonListAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditLocationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditLocationsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditPersonsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditPersonsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/adapter/LocationEditAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/adapter/PersonEditAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewMenu.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/ContactDiaryOverviewAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/ContactDiaryOverviewNestedAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/sheets/location/ContactDiaryLocationBottomSheetDialogViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/sheets/person/ContactDiaryPersonBottomSheetDialogViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/util/AbstractAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/util/ContactDiaryExtensions.kt
Labels: maintainers

#2054 Log uncaught exceptions (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CWADebug.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/debug/UncaughtExceptionLogger.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/debug/UncaughtExceptionLoggerTest.kt
Labels: enhancement, maintainers

#2058 Adjust ripple area on dispatcher screen (EXPOSUREAPP-4518)
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_appconfig.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_contact_diary.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_debugoptions.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_deviceinfo.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_keydownload.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_risk_level_calculation.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_submission.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_task_controller.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/view_crashreport_list_item.xml
  Corona-Warn-App/src/main/res/drawable/grey_card_ripple.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_privacy_card.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_dispatcher.xml
  Corona-Warn-App/src/main/res/layout/include_16_years.xml
  Corona-Warn-App/src/main/res/layout/include_dispatcher_card.xml
  Corona-Warn-App/src/main/res/layout/include_privacy_card.xml
  Corona-Warn-App/src/main/res/layout/include_privacy_card_no_consent.xml
  Corona-Warn-App/src/main/res/layout/include_submission_consent_body.xml
  Corona-Warn-App/src/main/res/layout/include_submission_country_no_selection.xml
  Corona-Warn-App/src/main/res/layout/include_submission_country_selector.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers

#2050 Remove legacy FileLogger in favor of new DebugLogger (DEV)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_debugoptions.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/DebugLogger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CWADebug.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/debug/FileLogger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/debug/FileLoggerTree.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/debug/LoggerState.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/debuglog/DebugLoggerTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModelTest.kt
Labels: maintainers, prio

#2059 CleanUp - Remove static app context access (EXPOSUREAPP-4506)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/TestResultSectionView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterInformationLegalHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSettingsHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_settings.xml
  Corona-Warn-App/src/main/res/layout/include_contact_form.xml
  Corona-Warn-App/src/main/res/layout/include_divider.xml
  Corona-Warn-App/src/main/res/layout/include_main_overview_row.xml
  Corona-Warn-App/src/main/res/layout/include_setting_row.xml
  Corona-Warn-App/src/main/res/layout/include_submission_country_item.xml
  Corona-Warn-App/src/main/res/layout/include_submission_country_no_selection.xml
  Corona-Warn-App/src/main/res/layout/include_submission_country_selector.xml
  Corona-Warn-App/src/main/res/layout/include_test_result_card.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterHelperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelperTest.kt
Labels: maintainers

#2064 Fix some Kotlin warnings(DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/DebugLogger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/LogLine.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/location/ContactDiaryLocationListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/person/ContactDiaryPersonListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditLocationsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditPersonsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/sheets/location/ContactDiaryLocationBottomSheetDialogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/sheets/location/ContactDiaryLocationBottomSheetDialogViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/sheets/person/ContactDiaryPersonBottomSheetDialogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/sheets/person/ContactDiaryPersonBottomSheetDialogViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/homecards/TracingProgressCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsFragmentViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/start/SettingsFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterHelperTest.kt
Labels: enhancement, maintainers, prio

#2072 Fix typo in german and english strings for finland country name (EXPOSUREAPP-4565) (closes #2069)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: community, mirrored-to-jira, text change

#2073 Minor DE text changes (DEV)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#2063 Pump versions - Android API 30 (EXPOSUREAPP-4562)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorReportReceiver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/settings/TracingSettingsState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/notifications/NotificationSettingsState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsBackgroundState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsNotificationState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsTracingState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/TanInput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/LocationTracingStatusCardBodyTextView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/TestResultSectionView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ConnectivityHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ContextExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataBindingAdapters.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_notifications.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_test.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_tracing.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_positive_no_consent.xml
  Corona-Warn-App/src/main/res/layout/include_dispatcher_card.xml
  Corona-Warn-App/src/main/res/layout/include_main_overview_row.xml
  Corona-Warn-App/src/main/res/layout/include_setting_row.xml
  Corona-Warn-App/src/main/res/layout/include_submission_behaviour_row.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_disabled_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_failed_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_increased_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_low_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_progress_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_fragment_layout.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_item_behavior_increased_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_item_behavior_row_view.xml
  Corona-Warn-App/src/main/res/layout/view_circle_progress.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/tracing/ui/settings/TracingSettingsStateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/notification/NotificationSettingsStateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/start/SettingsBackgroundStateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/start/SettingsNotificationStateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/start/SettingsTracingStateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataBindingAdaptersTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterHelperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelperTest.kt
  build.gradle
Labels: enhancement, maintainers, prio

#2075 Fixed card elevation (EXPOSUREAPP-4519)
  Corona-Warn-App/src/main/res/layout/home_card_container_layout.xml
Labels: bug, maintainers

#2083 Add missing word (DEV)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#2082 Update privacy_de.html (EXPOSUREAPP-3141)
  Corona-Warn-App/src/main/assets/privacy_de.html
Labels: maintainers, text change

#2078 Contact Journal clickable cards
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/ContactDiaryOverviewAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/ContactDiaryOverviewNestedAdapter.kt
Labels: bug, maintainers

#2087 API downgrade to 29
  Corona-Warn-App/build.gradle
Labels: hot topic 🔥, maintainers

#2084 Update terms_de.html (EXPOSUREAPP-3146)
  Corona-Warn-App/src/main/assets/terms_de.html
Labels: maintainers, text change

#2088 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers, text change

#2089 Bump Version and fix Timber aar dependency (DEV)
  Corona-Warn-App/build.gradle
  gradle.properties
Labels: maintainers

#2090 Update default translations (DEV)
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2077 Switching from CLA to DCO and Migrating to the Reuse Tool (EXPOSUREAPP-3046)
  .reuse/dep5
  CONTRIBUTING.md
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/util/security/DBPasswordTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/legacy/KeyCacheLegacyDao.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/legacy/KeyCacheLegacyEntity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/tracing/TracingIntervalDao.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/tracing/TracingIntervalEntity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/tracing/TracingIntervalRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/SingleLiveEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ZipHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/database/CommonConverters.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/SecurityHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/adapter/RuntimeTypeAdapterFactory.java
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/SingleLiveEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/viewmodel/ViewModelLazyKeyed.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/database/CommonConvertersTest.kt
  LICENSE
  LICENSES/Apache-2.0.txt
  NOTICE
  README.md
  THIRD-PARTY-NOTICES
  gradlew
  gradlew.bat
Labels: maintainers

#2052 Create automated app screenshots - Risk calculation screen(EXPOSUREAPP-2996)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/TracingData.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/TracingDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
Labels: enhancement, maintainers, prio

#2042 Set up and configure fastlane to take screenshots - Home Screen(EXPOSUREAPP-2950)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeData.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaInteroperabilityFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTestFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/RecyclerViewScrollAction.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestApplication.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataBindingAdapters.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_homescreen_card_include.xml
  Corona-Warn-App/src/main/res/layout/home_submission_status_card_error.xml
  Corona-Warn-App/src/main/res/layout/home_submission_status_card_invalid.xml
  Corona-Warn-App/src/main/res/layout/home_submission_status_card_negative.xml
  Corona-Warn-App/src/main/res/layout/home_submission_status_card_pending.xml
  Corona-Warn-App/src/main/res/layout/home_submission_status_card_unregistered.xml
  Corona-Warn-App/src/main/res/layout/include_submission_behaviour_row.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_disabled_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_failed_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_increased_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_low_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_progress_view.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataBindingAdaptersTest.kt
  screenshot.sh
Labels: enhancement, maintainers, prio

#2068 Contact Journal - Fast double click leads to double entry in contact journal (EXPOSUREAPP-4561)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/location/ContactDiaryLocationListAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/person/ContactDiaryPersonListAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/recyclerview/ThrottledClickListener.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/ViewExtensions.kt
Labels: maintainers, ui

#2094 Add snapping scroll behavior to the statistic cards (EXPOSUREAPP-4520)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
Labels: maintainers

#2095 Fix missing submission consent when using TANs (EXPOSUREAPP-4588)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/SubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentViewModel.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_positive_other_warning.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentViewModelTest.kt
Labels: bug, maintainers

#2096 Add placeholders for statistic UIs.
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/TrendArrowView.kt
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers

#2097 Update table with links to other repositories
  README.md
Labels: community

#2100 Version Bump to 1.11.0 - RC 3 (DEV)
  gradle.properties
Labels: maintainers

#2101 Screen: 7-day Incidence (EXPOSUREAPP-4512)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2076 Update strings.xml (EXPOSUREAPP-4578)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#2103 Layout for Risk History (EXPOSUREAPP-4577)
  Corona-Warn-App/src/main/res/drawable/ic_high_risk_alert.xml
  Corona-Warn-App/src/main/res/drawable/ic_low_risk_alert.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_nested_list_item_risk.xml
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
Labels: maintainers, text change, ui

#2080 Create automated app screenshots - Submission flow QR-Code/TAN (EXPOSUREAPP-2997)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionContactFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionDispatcherFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomCalendarFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomIntroFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultAvailableFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultConsentGivenFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNegativeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNoConsentGivenFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionYourConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestExtensions.kt
Labels: enhancement, maintainers, prio

#2074 Show pending card when offline/ request fails (EXPOSUREAPP-4507)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/SubmissionStateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/LiveDataExtensions.kt
Labels: maintainers

#2107 Statistics explanation screen texts (EXPOSUREAPP-4509)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2106 New release info screen strings (EXPOSUREAPP-4591)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  translation_v2.json
Labels: maintainers, text change

#2110 Screen: Confirmed New Infections - string update (EXPOSUREAPP-4510)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2112 Fix foreground state emissions (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/WatchdogService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/device/ForegroundState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AndroidModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ProcessLifecycle.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/device/ForegroundStateTest.kt
Labels: bug, maintainers

#2113 Statistics explanation screen text (EXPOSUREAPP-4509)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: enhancement, text change

#2114 Add styles (EXPOSUREAPP-4621) and strings (EXPOSUREAPP-4513)
  Corona-Warn-App/src/main/res/drawable-night/ic_info.xml
  Corona-Warn-App/src/main/res/drawable/ic_info.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_reproduction_layout.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers, text change

#2121 Capitalise security error messages (EXPOSUREAPP-4655) (closes #2120)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/CwaSecurityException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/CwaWebSecurityException.kt
Labels: community, mirrored-to-jira

#2116 Create NumberFormatter for Statistics Values (EXPOSUREAPP-4652)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2098 Contact Journal screenshots(EXPOSUREAPP-4559)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryDayFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryEditLocationsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryEditPersonsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryInformationPrivacyFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryOnboardingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/DiaryData.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/TracingDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/SystemUIDemoModeRule.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestAndroidModule.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestAppComponent.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestExtensions.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/ViewActions.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_list_item.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_locations_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_persons_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_location_list_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_location_list_item.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_list_item.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_person_list_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_person_list_item.xml
  Corona-Warn-App/src/main/res/layout/include_information_details.xml
  Corona-Warn-App/src/main/res/navigation/contact_diary_nav_graph.xml
Labels: maintainers

#2122 Remove recommendation to create labels in new issues (COMMUNITY)
  CONTRIBUTING.md
Labels: community

#2126 Stats explanation screen text update (EXPOSUREAPP-4509)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: enhancement, text change

#2125 Samsung S6: freshly installed app does not open (EXPOSUREAPP-4647)
  Corona-Warn-App/build.gradle
Labels: author merge, bug, maintainers, prio

#2127 Version bump to 1.11.0 - RC4 (Dev)
  gradle.properties
Labels: maintainers

#2115 Load statistics data from server (EXPOSUREAPP-4514)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/internal/ApplicationConfigurationInvalidException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/StatisticsModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/StatsItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/InvalidStatisticsSignatureException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/StatisticsApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/StatisticsCache.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/StatisticsParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/StatisticsProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/StatisticsServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsCardAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/SevenDayRValueCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/StatisticsCardItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/InvalidSignatureException.kt
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_sevendayrvalue_layout.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/StatisticsDataTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/StatisticsModuleTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/source/StatisticsAPIV1Test.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/source/StatisticsCacheTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/source/StatisticsParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/source/StatisticsProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/source/StatisticsServerTest.kt
  Corona-Warn-App/src/test/java/testhelpers/coroutines/TestExtensions.kt
Labels: enhancement, maintainers, prio

#2118 Create NumberFormatter for Statistics Values (EXPOSUREAPP-4652)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/util/StatisticsNumberValueFormatter.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/util/StatisticsNumberValueFormatterTest.kt
Labels: maintainers, prio

#2105 Abort test result available notification scheduling when viewed (EXPOSUREAPP-4516)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultConsentGivenFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNegativeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNoConsentGivenFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/worker/DiagnosisTestResultRetrievalPeriodicWorkerTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/CwaSecurityException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/NotificationConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/NotificationReceiver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/ShareTestResultNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/TestResultAvailableNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/SubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/task/SubmissionTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/invalid/SubmissionTestResultInvalidFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/invalid/SubmissionTestResultInvalidViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultConsentGivenViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultNoConsentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundWorkScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisTestResultRetrievalPeriodicWorker.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/notification/TestResultAvailableNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/SubmissionRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/task/SubmissionTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/testresult/SubmissionTestResultConsentGivenViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/worker/WorkerBinderTest.kt
Labels: maintainers

#2132 Add TrendArrowView (EXPOSUREAPP-4621)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/TrendArrowView.kt
  Corona-Warn-App/src/main/res/drawable/bg_statistics_trend_negative.xml
  Corona-Warn-App/src/main/res/drawable/bg_statistics_trend_neutral.xml
  Corona-Warn-App/src/main/res/drawable/bg_statistics_trend_positive.xml
  Corona-Warn-App/src/main/res/drawable/ic_trend_stable.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_incidence_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_keysubmissions_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_reproduction_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_sevendayrvalue_layout.xml
  Corona-Warn-App/src/main/res/layout/statistics_trend_view.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#2123 Date formatter for statistics (EXPOSUREAPP-4654)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterStatistics.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/formatter/FormatterStatisticsHelperTest.kt
Labels: maintainers, prio, text change

#2129 Contact Journal Location/Person not announced (EXPOSUREAPP-4459)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/ContactDiaryOverviewNestedAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/ListItem.kt
Labels: accessibility, maintainers

#2135 Bump to next Version 1.11.0.5 (DEV)
  gradle.properties
Labels: maintainers

#2109 Contact diary date formatting (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/util/CWADateTimeFormatPatternFactory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/util/ContactDiaryExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/util/CWADateTimeFormatPatternFactoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/util/ContactDiaryDateFormatterExtensionTest.kt
Labels: bug, maintainers

#2138 Statistics 7-Day-R-Value (EXPOSUREAPP-4513)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsCardPaddingDecorator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/SevenDayRValueCard.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_7_day_r_value.xml
  Corona-Warn-App/src/main/res/drawable/circle_ripple.xml
  Corona-Warn-App/src/main/res/drawable/ic_7_day_r_value.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_basecard_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_sevendayrvalue_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_scrollcontainer.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers, prio

#2145 Make talkback speak out decimal values appropriately (EXPOSUREAPP-4665)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/util/AccessibilityHelper.kt
Labels: maintainers, prio

#2147 Contact Journal Location/Person not announced (EXPOSUREAPP-4459)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/ContactDiaryOverviewNestedAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/ListItem.kt
Labels: accessibility, maintainers

#2150 Increase button touch size to 48x48 (EXPOSUREAPP-3674)
  Corona-Warn-App/src/main/res/drawable/circle_ripple.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_location_bottom_sheet_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_person_bottom_sheet_fragment.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_sevendayrvalue_layout.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers, prio

#2149 Fix parsing of StatisticsData (EXPOSUREAPP-3674)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/StatisticsParser.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/source/StatisticsParserTest.kt
Labels: bug, maintainers, prio

#2108 Screen: Confirmed New Infections (EXPOSUREAPP-4510)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/InfectionsCard.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_main_illustration_infection.xml
  Corona-Warn-App/src/main/res/drawable/ic_main_illustration_infection.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_infections_layout.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
Labels: maintainers, prio

#2146 Contact Journal Day date is not announced (EXPOSUREAPP-4457)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/ContactDiaryDayViewModel.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_day_fragment.xml
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
Labels: accessibility, maintainers, prio, text change

#2144 New release info screen - UI (EXPOSUREAP-4591)
  Corona-Warn-App/src/main/res/drawable/ic_new_release_info.xml
  Corona-Warn-App/src/main/res/layout/new_release_info_screen_fragment.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers

#2156 Move statistics cards (EXPOSUREAPP-4666)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
Labels: maintainers

#2153 Screen 7-day Incidence (EXPOSUREAPP-4512)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/IncidenceCard.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_statistics_incidence.xml
  Corona-Warn-App/src/main/res/drawable/ic_statistics_incidence.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_incidence_layout.xml
Labels: maintainers, prio

#2151 Screen: Warned Persons (EXPOSUREAPP-4511)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/InfectionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/KeySubmissionsCard.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_main_illustration_warnende_personen.xml
  Corona-Warn-App/src/main/res/drawable/ic_main_illustration_warnende_personen.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_infections_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_keysubmissions_layout.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, prio, text change

#2152 Contact Journal Edit Screen Title not accounced (EXPOSUREAPP-4456)
  Corona-Warn-App/src/main/AndroidManifest.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: accessibility, maintainers, prio

#2148 Privacy update for exposure history (EXPOSUREAPP-4590)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers, text change

#2157 Fixing typos in test names (COMMUNITY)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/ENFClientTest.kt
Labels: community

#2163 Fix 7-day-value and adjust layout (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/SevenDayRValueCard.kt
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_basecard_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_incidence_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_sevendayrvalue_layout.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
Labels: maintainers

#2158 Prioritized Background Title not announced (EXPOSUREAPP-4097)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/backgroundpriority/SettingsBackgroundPriorityFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_settings_background_priority.xml
Labels: accessibility, maintainers, prio

#2164 Improve 7-Day-R-Value layout resilience (DEV)
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_sevendayrvalue_layout.xml
Labels: maintainers, prio

#2165 Statistics layout polish seven day incidence (DEV)
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_incidence_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_sevendayrvalue_layout.xml
Labels: maintainers

#2167 Polishing statistics (EXPOSUREAPP-4693)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/SevenDayRValueCard.kt
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_infections_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_keysubmissions_layout.xml
Labels: maintainers, prio

#2159 Statistics explanation screen (EXPOSUREAPP-4509)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/StatisticsExplanationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/SpannableStringBuilder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/Views.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_illustration_statistics_explanation.xml
  Corona-Warn-App/src/main/res/drawable/ic_illustration_statistics_explanation.xml
  Corona-Warn-App/src/main/res/layout/fragment_statistics_explanation.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: enhancement, maintainers, prio, text change

#2162 Updated imprint (EXPOSUREAPP-4669)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#2139 Fix calendar calculation tests for non-English locales (COMMUNITY/DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/calendar/CalendarCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/calendar/CalendarView.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/calendar/CalendarCalculationTest.kt
Labels: community, maintainers

#2160 CircleCI config overhaul, instrumentation tests & screenshot automation (EXPOSUREAPP-4480,DEV)
  .circleci/config.yml
  .circleci/install-android-sdk.sh
  .gitignore
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/DiaryData.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/util/security/DBPasswordTest.kt
Labels: author merge, maintainers

#2170 Fix ui tests (Dev)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
Labels: maintainers

#2173 Enhance translation comment for FAQ (EXPOSUREAPP-3674)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2161 Error message after positive test result (EXPOSUREAPP-4515)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/TanPairingException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/HttpModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/DefaultPlaybook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/playbook/DefaultPlaybookTest.kt
Labels: bug, maintainers

#2168 Wrong Item is used for Active Tracing Duration on High Risk Details (EXPOSUREAPP-4694)
  Corona-Warn-App/src/main/res/layout/tracing_content_increased_view.xml
Labels: maintainers, ui

#2174 Improve CircleCI instrumentation test performance (DEV)
  .circleci/config.yml
Labels: maintainers

#2176 Country prefix +49 for hotline is misleading(EXPOSUREAPP-4677)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers, text change

#2175 Fix flickering of statistics cards when returning from statistics information screen (EXPOSUREAPP-4704)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCardItemTest.kt
Labels: bug, maintainers

#2128 Notification to open app from time to time comes back every few minutes (EXPOSUREAPP-4623)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationScheduler.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/deadman/DeadmanNotificationSchedulerTest.kt
Labels: backend, bug, maintainers

#2172 UA enhancements (EXPOSUREAPP-4578)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#2186 Evergreen instrumentation tests (Dev)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionContactFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionDispatcherFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultConsentGivenFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalPeriodicWorkerTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/worker/DiagnosisTestResultRetrievalPeriodicWorkerTest.kt
Labels: enhancement, maintainers

#2185 Fix invisible tracing settings screen if the last calculation failed (EXPOSUREAPP-4717)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/settings/SettingsTracingFragmentViewModel.kt
Labels: bug, maintainers, prio

#2183 Small LocalData cleanup (DEV, EXPOSUREAPP-2126)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers

#2179 Responsive statistics cards (EXPOSUREAPP-4700)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsCardPaddingDecorator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsLayoutManager.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/IncidenceCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/InfectionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/KeySubmissionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/SevenDayRValueCard.kt
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_basecard_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_incidence_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_infections_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_keysubmissions_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_sevendayrvalue_layout.xml
Labels: alternative approaches, maintainers, prio

#2142 Contact Journal Risk Extension - Risk details contact overview logic & peristance (EXPOSUREAPP-4577)
  Corona-Warn-App/schemas/de.rki.coronawarnapp.risk.storage.internal.RiskResultDatabase/3.json
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/risk/storage/RiskResultDatabaseMigrationTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/risk/storage/RiskResultDatabaseTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/retention/ContactDiaryCleanTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/retention/ContactDiaryRetentionCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/ContactDiaryOverviewAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/ContactDiaryOverviewNestedAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/ListItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/DefaultRiskLevels.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/result/AggregatedRiskPerDateResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/result/AggregatedRiskResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/BaseRiskLevelStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/RiskLevelStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/internal/RiskResultDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/internal/migrations/RiskResultDatabaseMigration2To3.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/internal/riskresults/PersistedAggregatedRiskPerDateResult.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_list_item.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_nested_list_item_risk.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/retention/ContactDiaryCleanTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/retention/ContactDiaryDataRetentionCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/result/AggregatedRiskPerDateResultTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/storage/BaseRiskLevelStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/storage/RiskStorageTestData.kt
Labels: maintainers

#2188 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-en/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: author merge, maintainers, text change

#2155 Info screen of the contact journal adapted with the additional texts (EXPOSUREAPP-4582)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/ContactDiaryActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/ContactDiaryPreferences.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/ContactDiarySettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/onboarding/ContactDiaryOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/ui/ContactDiarySettingsTest.kt
Labels: maintainers, text change

#2191 Update default strings (DEV)
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2194 Bump to next Version 1.11.0.6
  gradle.properties
Labels: maintainers

#2193 Adjust circleCI config to run screenshots on release candidates (DEV)
  .circleci/config.yml
Labels: maintainers

#2187 Low Risk without Exposures contains FAQ Link (EXPOSUREAPP-4599)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/riskdetails/DetailsLowRiskBox.kt
  Corona-Warn-App/src/main/res/layout/tracing_details_item_riskdetails_low_view.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers

#2200 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers, text change

#2197 Error 2001 - App does not work anymore (EXPOSUREAPP-2009)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/CwaWebSecurityException.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2190 Refactor DispatcherProvider to improve testing coroutine timing (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryDayFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryEditLocationsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryEditPersonsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaInteroperabilityFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomCalendarFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomIntroFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultAvailableFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultConsentGivenFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNegativeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionYourConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/TracingDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/coroutine/DispatcherProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/AppConfigProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/sources/local/LocalAppConfigSourceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/sources/remote/RemoteAppConfigSourceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditLocationsViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditPersonsViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/DayPackageSyncToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/HourPackageSyncToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/modules/detectiontracker/DefaultExposureDetectionTrackerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/receiver/ExposureStateUpdateReceiverTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/source/StatisticsProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/interoperability/InteroperabilityConfigurationFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/launcher/LauncherActivityViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/notification/NotificationSettingsFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/start/SettingsFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/tan/SubmissionTanViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/testavailable/SubmissionTestResultAvailableViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/testresult/SubmissionTestResultConsentGivenViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/yourconsent/SubmissionYourConsentViewModelTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModelTest.kt
  Corona-Warn-App/src/testShared/java/testhelpers/TestDispatcherProvider.kt
Labels: maintainers

#2201 Update default strings (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2184 Optimize Accessibility for Retrieve Test Result Screen (EXPOSUREAPP-4460)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_dispatcher.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: accessibility, maintainers, text change

#2177 Improved popup text for state "non internet" (EXPOSUREAPP-4569)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/scan/SubmissionQRCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingFragment.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#2199 Diary screenshots with Risk Warning (EXPOSUREAPP-4585)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/DiaryData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/ContactDiaryPreferences.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/ContactDiarySettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/ui/ContactDiarySettingsTest.kt
Labels: maintainers

#2203 Additional statistics testcase (DEV)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/source/StatisticsProviderTest.kt
Labels: maintainers

#2178 Buttons on Symptom-Screens scroll with the screen (EXPOSUREAPP-4595)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomIntroFragmentTest.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_symptom_calendar.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_symptom_intro.xml
Labels: maintainers, ui

#2205 Updated release info strings
  Corona-Warn-App/src/main/res/layout/new_release_info_screen_fragment.xml
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
Labels: maintainers, text change

#2204 Test result no notification intended fix (EXPOSUREAPP-4625)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/TestResultAvailableNotificationService.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/notification/TestResultAvailableNotificationServiceTest.kt
Labels: bug, maintainers

#2212 7 day incidence decimal place issue (EXPOSUREAPP-4750)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/util/StatisticsNumberValueFormatter.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/util/StatisticsNumberValueFormatterTest.kt
Labels: bug, maintainers

#2214 Bump to next Version 1.11.0.7
  gradle.properties
Labels: maintainers

#2207 Clean UI tests (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryDayFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryEditLocationsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryEditPersonsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryOnboardingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaInteroperabilityFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTestFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionContactFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionDispatcherFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionQrCodeScanFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomCalendarFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomIntroFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultAvailableFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultConsentGivenFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNegativeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNoConsentGivenFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionYourConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/TracingDetailsFragmentTest.kt
Labels: maintainers

#2202 Inconsistent ( X icon ) navigation behaviour (EXPOSUREAPP-4256)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentFragment.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
Labels: maintainers

#2217 Fix text issues (DEV)
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#2218 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers, text change

#2219 Translation Delivery and default strings (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2216 7 day r value decimal place issue (EXPOSUREAPP-4751)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/util/StatisticsNumberValueFormatter.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/util/StatisticsNumberValueFormatterTest.kt
Labels: bug, maintainers, prio

#2209 Update worker dependecies to last (EXPSOUREAPP-4765)
  Corona-Warn-App/build.gradle
Labels: maintainers

#2215 Run instrumentation tests on Firebase Test Lab (Dev)
  .circleci/config.yml
Labels: enhancement, maintainers

#2220 Bump to next Version 1.11.0.8
  gradle.properties
Labels: maintainers

#2211 Exposure logging switch not working when screen reader is active (EXPOSUREAPP-2758)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/settings/SettingsTracingFragment.kt
Labels: bug, maintainers, prio

#2180 New release info screen logic (EXPOSUREAPP-4591)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/main/CWASettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/release/NewReleaseInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/release/NewReleaseInfoFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/release/NewReleaseInfoFragmentNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/release/NewReleaseInfoFragmentViewModel.kt
  Corona-Warn-App/src/main/res/layout/fragment_information.xml
  Corona-Warn-App/src/main/res/layout/new_release_info_screen_fragment.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
Labels: maintainers, prio, text change

#2210 Wrong navigation in "Symptom-Erfassung" (EXPOSUREAPP-4703)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionViewModelTest.kt
Labels: maintainers

#2206 Update automatic screenshot behaviour for statistics (EXPOSUREAPP-4622)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/statistics/StatisticsCardsTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/statistics/StatisticsExplanationFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
Labels: maintainers
