Repository corona-warn-app/cwa-app-android, pull requests merged in 2021-12, with the labels that each got.

#4461 TicketValidation - missing error and url logging (EXPSOUREAPP-10660)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingInvalidQrCodeException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/DccTicketingRequestService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/submission/DccTicketingSubmissionHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/dialog/DccTicketingDialogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/dialog/DccTicketingDialogType.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/DccTicketingRequestServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/submission/DccTicketingSubmissionHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
Labels: maintainers

#4447 JWT censor for access token (EXPOSUREAPP-10747)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/BugReportingSharedModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/dcc/DccQrCodeCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/dccticketing/DccTicketingJwtCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccQrCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/AccessTokenRequestProcessor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/dcc/DccQrCodeCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/dccticketing/DccTicketingJwtCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccQrCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/qrcode/TestCertificateQRCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationGroupingTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/processor/AccessTokenRequestProcessorTest.kt
Labels: maintainers

#4460 Adapt privacy notice for Release 2.15 (EXPOSUREAPP-10171)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers, author merge

#4462 Ticketvalidation: Validation Result update (EXPOSUREAPP-10196)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/ValidationResultItemCreator.kt
  Corona-Warn-App/src/main/res/values-de/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_ticketing_strings.xml
Labels: maintainers, text change

#4455 DCC Consent 2 screen screenshots (EXPOSUREAPP-10489)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
Labels: maintainers, author merge

#4463 Bump to next Version 2.15.0.1
  gradle.properties
Labels: maintainers

#4466 Fix capitalization mistake for vaccination time (EXPOSUREAPP-9781)
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#4467 Add bouncycastle to proguard (EXPOSUREAPP-10880)
  Corona-Warn-App/proguard-rules.pro
Labels: bug, maintainers, prio

#4470 Bump to next Version 2.15.0.2
  gradle.properties
Labels: maintainers

#4471 Android Infoscreen Typo
  Corona-Warn-App/src/main/res/values-de/dcc_ticketing_strings.xml
Labels: text change

#4476 [UI] Screenshots consent I (EXPOSUREAPP-10489)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/ViewActions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrcodeSharedViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneViewModelTest.kt
Labels: ui, maintainers

#4479 Ticket Validation - missing navigation (EXPOSUREAPP-10919)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoViewModel.kt
  Corona-Warn-App/src/main/res/navigation/dcc_ticketing_nav_graph.xml
Labels: maintainers

#4449 Request allow list (EXPOSUREAPP-10570)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/DccTicketing.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/DccTicketingCoreModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/DccTicketingAllowListEntry.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/DccTicketingAllowListRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/api/DccTicketingAllowListApi1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/api/DccTicketingAllowListServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/data/DccTicketingAllowListContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/data/DccTicketingServiceProviderAllowListEntry.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/data/DccTicketingValidationServiceAllowListEntry.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/filtering/DccJwkFilteringResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/filtering/DccTicketingJwkFilter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/internal/DccTicketingAllowListException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/internal/DccTicketingAllowListParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/repo/DccTicketingAllowListRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/repo/storage/DccTicketingAllowListStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/server/DccTicketingAllowListApi1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/server/DccTicketingAllowListServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingTransactionContext.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
Labels: maintainers

#4478 Filter jwk against allowlist (EXPOSUREAPP-10572)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/filtering/DccTicketingJwkFilter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/check/DccTicketingServerCertificateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/DccTicketingRequestService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationDecoratorRequestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationServiceRequestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneProcessor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/allowlist/filtering/DccTicketingJwkFilterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/DccTicketingRequestServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationDecoratorRequestProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationServiceRequestProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneProcessorTest.kt
Labels: maintainers

#4488 Fix FAQ EN link (EXPOSUREAPP-10927)
  Corona-Warn-App/src/main/res/values-bg/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-pl/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-ro/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-tr/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_ticketing_strings.xml
Labels: bug, maintainers

#4484 Trigger value set download (EXPOSUREAPP-10903)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/valueset/ValueSetsRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/valueset/ValueSetsRepositoryTest.kt
Labels: bug, maintainers

#4477 Remove outdated paragraph (EXPOSUREAPP-10931)
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_passed_hint_item.xml
  Corona-Warn-App/src/main/res/layout/validation_start_fragment_notes.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: bug, ui, text change

#4486 Check service provider (EXPOSUREAPP-10865)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dccticketing/DccTicketingTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dccticketing/DccTicketingTestViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_dcc_ticketing.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/repo/DccTicketingAllowListRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
Labels: maintainers

#4485 G events person details (EXPOSUREAPP-10889)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/ConfirmedStatusCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonColorShade.kt
  Corona-Warn-App/src/main/res/layout/confirmed_status_card.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: ui, maintainers, text change

#4489 Increase JVM args memory (DEV)
  gradle.properties
Labels: enhancement, maintainers

#4497 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#4475 Recommended actions text changes (EXPOSUREAPP-10696)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/TracingDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/home/HomeRulesFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/hygiene/HygieneRulesFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/behavior/BehaviorIncreasedRiskBox.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/behavior/BehaviorInfoRow.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_illustration_hygiene_rules.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_illustration_stay_at_home.xml
  Corona-Warn-App/src/main/res/drawable/ic_illustration_hygiene_rules.xml
  Corona-Warn-App/src/main/res/drawable/ic_illustration_stay_at_home.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_details_health_department.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_details_home_office.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_details_meetings.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_details_no_lugage.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_details_public_transport.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_details_shopping.xml
  Corona-Warn-App/src/main/res/layout/fragment_tracing_details_home.xml
  Corona-Warn-App/src/main/res/layout/fragment_tracing_details_hygiene.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_find_details_in_journal.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_item_behavior_increased_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_item_behavior_normal_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_item_behavior_row_view.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  translation_v2.json
Labels: maintainers, text change

#4494 Check server certificate against allowlist (EXPOSUREAPP-10571)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/repo/DccTicketingAllowListRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/check/DccTicketingServerCertificateCheckException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/check/DccTicketingServerCertificateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/server/DccTicketingServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/server/DccTicketingServerParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/DccTicketingRequestService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/AccessTokenRequestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ResultTokenRequestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationDecoratorRequestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationServiceRequestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/submission/DccTicketingSubmissionHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/DccTicketingValidationResultFragment.kt
  Corona-Warn-App/src/main/res/navigation/dcc_ticketing_nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/server/DccTicketingServerParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/DccTicketingRequestServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ResultTokenRequestProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationDecoratorRequestProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationServiceRequestProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/submission/DccTicketingSubmissionHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneViewModelTest.kt
Labels: maintainers, prio

#4499 Validation service min app version check (EXPOSUREAPP-10956)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/CWAConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CWAConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/dialog/DccTicketingDialogType.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ExternalActionHelper.kt
  Corona-Warn-App/src/main/res/values-de/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_ticketing_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeHandlerTest.kt
Labels: maintainers

#4438 Fix lists displaying old data, due to payload race-condition, if redraw is delayed (COMMUNITY)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/CwaUserCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/PersonDetailsQrCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationInfoCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/CovidTestCertificatePendingCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/RuleHeaderVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/TechnicalValidationFailedVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/ValidationFaqVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/ValidationInputVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/ValidationOverallResultVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/ValidationPassedHintVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/businessrule/BusinessRuleVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/CoronaTestCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/AddCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/AppliedVaccinationRatesCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/IncidenceAndHospitalizationCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/InfectionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/KeySubmissionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/LocalIncidenceAndHospitalizationCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/OccupiedIntensiveCareCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/PersonsVaccinatedCompletelyCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/PersonsVaccinatedOnceCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/SevenDayRValueCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/StatisticsCardItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/PcrTestErrorCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/PcrTestInvalidCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/PcrTestNegativeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/PcrTestPendingCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/PcrTestPositiveCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/PcrTestReadyCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/PcrTestSubmissionDoneCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/RapidTestErrorCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/RapidTestInvalidCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/RapidTestNegativeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/RapidTestOutdatedCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/RapidTestPendingCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/RapidTestPositiveCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/RapidTestReadyCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/RapidTestSubmissionDoneCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/TestUnregisteredCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/items/CreateTraceLocationCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/items/FAQCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/items/IncompatibleCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/consent/HeaderCheckInsVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/consent/SelectableCheckInVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/items/ActiveCheckInVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/items/PastCheckInVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/lists/diffutil/HasPayloadDiffer.kt
Labels: bug, community

#4493 Determine admission state (EXPOSUREAPP-10887)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
Labels: maintainers

#4492 Fix: missing cancelation popup on screen "Zertifikat auswählen" (EXPOSUREAPP-10914)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionViewModel.kt
Labels: bug, maintainers

#4503 Dcc person max config parameters (EXPOSUREAPP-10971)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/CWAConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CWAConfigMapper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/CWAConfigMapperTest.kt
Labels: maintainers

#4505 Max person checker (EXPOREAPP-10613)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccMaxPersonChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
Labels: maintainers

#4508 Checker unit test (EXPOSUREAPP-10613)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccMaxPersonCheckerTest.kt
Labels: maintainers

#4501 Bump to next Version 2.15.1.0
  gradle.properties
Labels: maintainers

#4509 Correct typos in CODEOWNERS comment (COMMUNITY)
  CODEOWNERS
Labels: community

#4507 Adjust logic to consider maximum allowance (EXPOSUREAPP-10973)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
Labels: maintainers

#4495 Fix: Outdated RATs should be removed directly
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
Labels: bug, maintainers

#4511 Add config params (EXPOSUREAPP-10613)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccMaxPersonChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccMaxPersonCheckerTest.kt
Labels: maintainers

#4512 Update covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#4514 Eliminate negative values (EXPOSUREAPP-10613)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CWAConfigMapper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/CWAConfigMapperTest.kt
Labels: maintainers

#4510 Update covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#4513 Restrict number persons warning dialog (EXPOSUREAPP-10970)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: ui, maintainers, text change

#4506 Fix: TAN in PCR-replacement scenario (EXPOSUREAPP-10964)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningViewModel.kt
Labels: bug, maintainers, prio

#4502 Restrict number of persons (EXPOSUREAPP-10613)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/CWAConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CWAConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccMaxPersonChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/CWAConfigMapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccMaxPersonCheckerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
Labels: maintainers

#4517 Update strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4516 Update risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-de/risk_details_strings.xml
Labels: text change

#4504 Update dcc priorities (EXPOSUREAPP-10890)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
Labels: maintainers

#4519 Wrong color shade dcc tile ticket validation (EXPOSUREAPP-10941)
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_vaccination_card.xml
Labels: bug, maintainers

#4518 Ticket validation font style fix (EXPOSUREAPP-10895)
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_consent_one.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_consent_two.xml
Labels: bug, maintainers

#4520 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-pl/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-ro/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-tr/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#4521 Fix: Log statement (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/filtering/DccTicketingJwkFilter.kt
Labels: bug, maintainers

#4522 Allowlist - various tests (EXPOSUREAPP-10933)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/internal/DccTicketingAllowListParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/repo/DccTicketingAllowListRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/repo/storage/DccTicketingAllowListStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/check/DccTicketingServerCertificateChecker.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/allowlist/internal/DccTicketingAllowListParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/allowlist/repo/DccTicketingAllowListRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/allowlist/repo/storage/DccTicketingAllowListStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/check/DccTicketingServerCertificateCheckerTest.kt
Labels: maintainers

#4523 Bump to next Version 2.15.1.1
  gradle.properties
Labels: maintainers

#4498 Update text (EXPOSUREAPP-10460)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/testresults/negative/RATResultNegativeFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_antigen_test_result_negative.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_negative.xml
  Corona-Warn-App/src/main/res/layout/view_bullet_point_entry.xml
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: ui, maintainers, text change

#4532 Hide info button (EXPOSUREAPP-10946)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerFragment.kt
Labels: bug, maintainers

#4530 Fix: Ticketvalidation - missing cancelation popup on screen (EXPOSUREAPP-10914)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionViewModel.kt
Labels: bug, maintainers, prio

#4533 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-pl/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#4537 Bump to next Version 2.15.1.2
  gradle.properties
Labels: maintainers

#4538 Fix: Wrong text (/EXPOSUREAPP-10988)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers

#4542 Update certificate selection title (EXPOSUREAPP-10913)
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_certificate_selection.xml
Labels: bug, maintainers, prio, text change

#4541 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, prio

#4487 Remove references to `EncryptedSharedPreferences` architecture overview (COMMUNITY)
  docs/architecture-overview.md
Labels: documentation, community

#4491 Check in for G events person overview UI changes (EXPOSUREAPP-10888)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNegativeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/color/certificate_selector_button_stroke.xml
  Corona-Warn-App/src/main/res/color/certificate_selector_button_text_color.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_info.xml
  Corona-Warn-App/src/main/res/drawable/grey_card_ripple.xml
  Corona-Warn-App/src/main/res/drawable/ic_certificate_background_border.xml
  Corona-Warn-App/src/main/res/drawable/ic_info.xml
  Corona-Warn-App/src/main/res/layout/cwa_user_card_item.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_overview_qr_card.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
  Corona-Warn-App/src/main/res/layout/person_overview_item.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: maintainers

#4543 Fix: TAN error message (EXPOSUREAPP-10958)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/TestRegistrationStateProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningFragment.kt
Labels: bug, maintainers

#4540 Increase max length to 255 for check ins (EXPOSUREAPP-10535)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/handler/CheckInQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/create/TraceLocationCreateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/create/TraceLocationCreateViewModel.kt
  Corona-Warn-App/src/main/res/layout/trace_location_create_fragment.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/qrcode/InvalidQRCodeProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/qrcode/ValidQRCodeProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/presencetracing/organizer/create/TraceLocationCreateViewModelTest.kt
Labels: maintainers

#4549 Fix EN link (EXPOSUREAPP-10927)
  Corona-Warn-App/src/main/res/values-bg/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-pl/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-ro/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-tr/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_ticketing_strings.xml
Labels: bug, maintainers

#4553 FIX: Correct legal texts for dcc ticketing validation consent II screen (EXPOSUREAPP-11049)
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: bug, maintainers, prio, text change

#4555 Fix: Unify allow list error message (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/internal/DccTicketingAllowListException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeHandler.kt
Labels: bug, maintainers, prio

#4558 Bump to next Version 2.15.1.3
  gradle.properties
Labels: maintainers

#4556 Change rule names
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#4557 Sync info buttons style (DEV)
  Corona-Warn-App/src/main/res/layout/tracing_details_item_behavior_row_view.xml
Labels: maintainers

#4554 Dcc tile color (EXPOSUREAPP-10941)
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_recovery_card.xml
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_test_card.xml
Labels: bug, maintainers

#4562 Update dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-de/dcc_ticketing_strings.xml
Labels: maintainers, text change

#4559 Updated text style for covpass info text (EXPXOSUREAPP-11060)
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
Labels: bug, maintainers

#4561 Adjust Info Screen to announce new Release-Features for 2.16 (EXPOSUREAPP-10768)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#4547 Fix: DCC ticketing error dialog (EXPOSUREAPP-10962)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoFragment.kt
Labels: bug, maintainers

#4550 Advanced root warning (EXPOSUREAPP-10698)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/launcher/LauncherActivityTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/main/CWASettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/rootdetection/RootDetectionCheck.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/rootdetection/RootDetectionModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/rootdetection/core/RootDetectionCheck.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/rootdetection/ui/RootDetectionDialogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/rootdetection/ui/RootDetectionDialogViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/rootdetection/ui/RootDetectionUiModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherActivityViewModel.kt
  Corona-Warn-App/src/main/res/layout/root_detection_dialog_checkbox_view.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/rootdetection/RootDetectionCheckTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/launcher/LauncherActivityViewModelTest.kt
Labels: maintainers, author merge

#4563 Bump to next Version 2.16.0.1
  gradle.properties
Labels: maintainers

#4565 Update strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4546 Fix wrong statistics text (EXPOSUREAPP-10213)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers, text change

#4564 Fix duplicate certificate list item (EXPOSUREAPP-11052)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionHelperUiTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionHelperFunctions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionHelperTest.kt
Labels: bug, maintainers

#4566 Update risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-de/risk_details_strings.xml
Labels: text change

#4567 Update strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4570 FIX: Recycle Bin - Certificates - name issue (EXPOSUREAPP-10430)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/VaccinationCertificateCard.kt
Labels: bug, maintainers

#4569 FIX: Going back from "Print Version" to "Display print version" does not work (EXPOSUREAPP-11001)
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
Labels: bug, maintainers, UX

#4568 Remove paragraph from data privacy (EXPOSUREAPP-10995)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: bug, maintainers

#4574 Ticketvalidation screens sometimes empty (EXPOSUREAPP-11054)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/shared/DccTicketingSharedViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/ui/shared/DccTicketingSharedViewModelTest.kt
Labels: bug, maintainers

#4571 Wrong vacc icon when eligible for booster (EXPOSUREAPP-10479)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
Labels: bug, maintainers

#4544 FIX: DCC parent color shade (EXPOSUREAPP-9950)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonColorShade.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_bookmark.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_bookmark_blue.xml
  Corona-Warn-App/src/main/res/drawable/ic_bookmark_blue.xml
  Corona-Warn-App/src/main/res/drawable/ic_bookmark_blue_1.xml
  Corona-Warn-App/src/main/res/drawable/ic_bookmark_blue_2.xml
  Corona-Warn-App/src/main/res/drawable/ic_bookmark_blue_3.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: bug, ui, maintainers

#4575 Update strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4577 Advanced root detection - test (EXPOSUREAPP-11051)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/rootdetection/core/RootDetectionCheckTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/rootdetection/ui/RootDetectionDialogViewModelTest.kt
Labels: maintainers

#4578 Refactoring of links (EXPOSUREAPP-10927)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationInfoCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/cards/DccTicketingNoValidCertificateFaqCard.kt
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-de/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/links.xml
  Corona-Warn-App/src/main/res/values-de/notifications_strings.xml
  Corona-Warn-App/src/main/res/values-de/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/links.xml
  Corona-Warn-App/src/main/res/values/notifications_strings.xml
  Corona-Warn-App/src/main/res/values/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values/vaccination_strings.xml
Labels: enhancement, maintainers, text change

#4560 Fix: Duplicate `ci` (EXPOSUREAPP-11050)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/repository/TestCertificateContainerId.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/qrcode/RecoveryCertificateQRCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/qrcode/TestCertificateQRCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/qrcode/VaccinationCertificateQRCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/TestCertificateTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainerTest.kt
Labels: bug, maintainers

#4581 Open live App Google play for Test APK (EXPOSUREAPP-11042)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ExternalActionHelper.kt
Labels: bug, maintainers

#4580 Fix : Person overview colours (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonColorShade.kt
Labels: bug, maintainers

#4579 Add default locale to `getValidQrCode` (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificateUI.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/PersonDetailsQrCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
Labels: enhancement, maintainers

#4573 Update risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-de/risk_details_strings.xml
Labels: text change, rapid-test

#4583 Remove superflous paragraph from recommended action (EXPOSUREAPP-11073)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers, text change

#4592 Bump to next Version 2.16.0.2
  gradle.properties
Labels: maintainers

#4591 Update map of Europe (EXPOSUREAPP-11071)
  Corona-Warn-App/src/main/res/drawable-night/ic_map_of_europe.xml
  Corona-Warn-App/src/main/res/drawable/ic_map_of_europe.xml
Labels: bug, maintainers

#4595 Fix: RecyclerBinOverviewFragmentTest (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinOverviewFragmentTest.kt
Labels: maintainers

#4594 Fix redeemed state (EXPOSUREAPP-10035)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/CoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/CoronaTestExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRCoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRTestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/execution/PCRResultScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RACoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/execution/RAResultScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/SubmissionRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/CoronaTestExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRCoronaTestTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/pcr/execution/PCRResultSchedulerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RACoronaTestTest.kt
Labels: bug, maintainers

#4584 Fix : save state the right way (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/shared/DccTicketingSharedViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/ui/shared/DccTicketingSharedViewModelTest.kt
Labels: maintainers

#4599 Redundant cancel button in QR scanner dialog (EXPOSUREAPP-10963)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerFragment.kt
Labels: bug, maintainers

#4589 Increase tap area of infobuttons (EXPOSUREAPP-11080)
  Corona-Warn-App/src/main/res/layout/fragment_qrcode_scanner.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_overview_qr_card.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: bug, maintainers

#4593 FIx: Pop Up in Contact Journal (EXPOSUREAPP-11079)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/dao/BaseDao.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/dao/ContactDiaryLocationVisitDao.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/dao/ContactDiaryPersonEncounterDao.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/repo/DefaultContactDiaryRepository.kt
Labels: bug, maintainers

#4603 Bump to next Version 2.16.0.3
  gradle.properties
Labels: maintainers

#4601 Fix: Recycled Tests date labels (EXPOSUREAPP-10627)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/CoronaTestCard.kt
  Corona-Warn-App/src/main/res/values-de/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values/recycler_bin_strings.xml
Labels: bug, maintainers, text change

#4600 Privacy (EXPOSUREAPP-10995)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: bug, maintainers

#4605 FIX: NoSuchElementException in PersonDetailsViewModel (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPerson.kt
Labels: bug, maintainers

#4604 Display Unique Vaccination Certificate/Assertion Identifier (UVCI) (EXPOSUREAPP-11108)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNegativeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/CoronaTestCertificateCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/DccBoosterRulesValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/qrcode/DccQrCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/repository/CertificateContainerId.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/repository/CertificateRepoContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/repository/RecoveryCertificateContainerId.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/repository/TestCertificateContainerId.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/repository/VaccinationCertificateContainerId.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotification.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/CertificateDrawHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/qrcode/RecoveryCertificateQRCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/qrcode/TestCertificateQRCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/ui/onboarding/CovidCertificateOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/qrcode/VaccinationCertificateQRCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/AffectedFieldsMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrcodeSharedViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/testresults/negative/RATResultNegativeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/DccBoosterRulesValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonCertificatesData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPersonTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/scanner/QrCodeValidatorTest.kt
Labels: bug, maintainers, prio

#4608 Test certificate refresh error dialog (EXPOSUREAPP-10327)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/exception/TestCertificateException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateProcessor.kt
  Corona-Warn-App/src/main/res/values-de/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/green_certificate_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateProcessorTest.kt
Labels: maintainers

#4597 Fix risk change notification (EXPOSUREAPP-10749)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/changedetection/CombinedRiskLevelChangeDetector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/BaseRiskLevelStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/RiskLevelStorage.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/changedetection/CombinedRiskLevelChangeDetectorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/changedetection/EwRiskLevelChangeDetectorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/storage/BaseRiskLevelStorageTest.kt
Labels: bug, maintainers

#4607 Hide tooltip (EXPOSUREAPP-10623 - EXPOSUREAPP-10493)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/UIExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
Labels: bug, maintainers

#4609 Refactor to camerax / boofCV, POC (EXPOSUREAPP-11089)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/parser/QrCodeCameraImageParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerPreviewView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/qrcode/QrViewfinderView.kt
  Corona-Warn-App/src/main/res/layout/fragment_qrcode_scanner.xml
  Corona-Warn-App/src/main/res/layout/qr_code_scanner_preview_view.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
Labels: maintainers

#4618 Last encounter in ew day risk (EXPOSUREAPP-10666)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/BaseRiskLevelStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/states/TracingState.kt
  Corona-Warn-App/src/main/res/layout/tracing_content_increased_view.xml
Labels: maintainers

#4615 Remove embedded zxing (EXPOSUREAPP-11117)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/AndroidManifest.xml
  Corona-Warn-App/src/main/assets/technical.html
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentViewModelTest.kt
  docs/architecture-overview.md
Labels: enhancement, maintainers

#4617 Fix legal text (EXPOSUREAPP-11109)
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
Labels: bug, maintainers, text change

#4619 Upgrade sonar (DEV)
  .circleci/config.yml
Labels: enhancement, maintainers

#4616 Autofocus (EXPOSUREAPP-11115)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerPreviewView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/BuildVersionWrap.kt
Labels: enhancement, maintainers

#4623 Bump to next Version 2.16.0.4
  gradle.properties
Labels: maintainers

#4621 Unit test parser (EXPOSUREAPP-11090)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/parser/QrCodeCameraImageParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerViewModel.kt
  Corona-Warn-App/src/test/dcc-test-data/vc-bf014fb1b3-maria-bondi.png
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/parser/QrCodeCameraImageParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
Labels: maintainers

#4612 Store RATProfile with Jetpack Datastore (EXPOSUREAPP-10912)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionDispatcherFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/RatProfileCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/CoronaTestModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/antigen/profile/RATProfileSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/antigen/profile/RATProfileSettingsDataStore.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/antigen/profile/RatProfileDataStore.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/antigen/profile/RatProfileModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/onboarding/RATProfileOnboardingFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionDispatcherViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/CensorInjectionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/submission/RatProfileCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/antigen/profile/RATProfileSettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileDataCreateFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
  Corona-Warn-App/src/testShared/java/testhelpers/preferences/FakeDataStore.kt
Labels: bug, maintainers

#4625 Automatic hyphens (DEV)
  Corona-Warn-App/src/main/res/layout/fragment_confirm_check_in.xml
  Corona-Warn-App/src/main/res/layout/fragment_edit_check_in.xml
  Corona-Warn-App/src/main/res/layout/trace_location_attendee_checkins_item_active.xml
  Corona-Warn-App/src/main/res/layout/trace_location_attendee_checkins_item_past.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_qr_code_detail_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_trace_locations_item.xml
Labels: bug, maintainers

#4627 Remove error dialog detials (EXPOSUREAPP-10328)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/ui/ErrorDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerExtensions.kt
Labels: bug, maintainers

#4629 Issuer country in DE or EN in print version (EXPOSUREAPP-9863)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/repository/CertificateRepoContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/RecoveryCertificateDrawHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/TestCertificateDrawHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/Utils.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/VaccinationCertificateDrawHelper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/pdf/core/UtilsKtTest.kt
Labels: bug, maintainers

#4624 Increase screen brightness 🔆 🔅 (EXPOSUREAPP-8224)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/qrcode/fullscreen/QrCodeFullScreenFragment.kt
Labels: enhancement, maintainers

#4631 Bump to next Version 2.16.0.5
  gradle.properties
Labels: maintainers
