Repository corona-warn-app/cwa-app-android, pull requests merged in 2021-05, with the labels that each got.

#3044 Type in 'Neue Funktionen' DE - Fehlerprotokoll
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#3030 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-en/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers

#3027 Fix flaky unit test (DEV)
  .reuse/dep5
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/SmartLiveData.kt
  Corona-Warn-App/src/test/java/testhelpers/extensions/LiveDataTestUtil.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModelTest.kt
Labels: maintainers

#3055 Typos in event registration (closes #2888) (COMMUNITY)
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
Labels: community, mirrored-to-jira

#3052 Default strings update (DEV)
  Corona-Warn-App/src/main/res/layout/fragment_information_technical.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#3046 Align error message to the one from the iOS repo (closes #2949) (COMMUNITY)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: community, text change

#2955 Support Android 5 (COMMUNITY)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/contactdiary/ui/ContactDiaryTestFragment.kt
  Corona-Warn-App/src/main/AndroidManifest.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/ui/ErrorDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/location/DiaryLocationViewHolder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/behavior/BehaviorInfoRow.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/calendar/CalendarWeekDayView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeMenu.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsBackgroundState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/TanInput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ConnectivityHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DialogHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/device/PowerManagement.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/network/NetworkStateProvider.kt
  Corona-Warn-App/src/main/res/drawable-v23/tan_input_digit.xml
  Corona-Warn-App/src/main/res/drawable-v23/tan_input_digit_error.xml
  Corona-Warn-App/src/main/res/drawable/splash_screen.xml
  Corona-Warn-App/src/main/res/drawable/tan_input_digit.xml
  Corona-Warn-App/src/main/res/drawable/tan_input_digit_error.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings.xml
  Corona-Warn-App/src/main/res/layout/home_fragment_layout.xml
  Corona-Warn-App/src/main/res/values/styles.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskLevelTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/network/NetworkStateProviderTest.kt
Labels: community, mirrored-to-jira

#3025 Fix being able to change optional data donation entries if sharing is disabled (EXPOSUREAPP-5489)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/analytics/SettingsPrivacyPreservingAnalyticsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/analytics/SettingsPrivacyPreservingAnalyticsState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/views/MoreInformationView.kt
  Corona-Warn-App/src/main/res/layout/fragment_settings_privacy_preserving_analytics.xml
  Corona-Warn-App/src/main/res/layout/view_more_information.xml
  Corona-Warn-App/src/main/res/values/attrs.xml
Labels: bug, maintainers

#3026 Refactor Contact Diary Work Scheduler (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/retention/ContactDiaryWorkScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/retention/ContactDiaryWorkSchedulerTest.kt
Labels: maintainers

#3064 Remove internet requirement for EW risk calculation (EXPOSUREAPP-6948)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskLevelTaskTest.kt
Labels: maintainers

#3065 Rapid Test - QR-Code from Schnelltestprofile cannot be scanned by PoC if fields contain Umlauts (EXPOSUREAPP-7016)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/qrcode/QrCodeGenerator.kt
Labels: backend, bug, maintainers

#3019 Settings toggle (eg. tracing) (EXPOSUREAPP-6871)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/settings/SettingsTracingFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/analytics/SettingsPrivacyPreservingAnalyticsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/notifications/NotificationSettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/yourconsent/SubmissionYourConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/MoreInformationView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/SwitchRowView.kt
  Corona-Warn-App/src/main/res/layout/bugreporting_debuglog_fragment.xml
  Corona-Warn-App/src/main/res/layout/bugreporting_debuglog_upload_fragment.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_notifications.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_privacy_preserving_analytics.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_your_consent.xml
  Corona-Warn-App/src/main/res/layout/fragment_trace_location_onboarding.xml
  Corona-Warn-App/src/main/res/layout/include_settings_switch_row.xml
  Corona-Warn-App/src/main/res/layout/rat_profile_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/switch_row.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_qr_code_info_fragment.xml
  Corona-Warn-App/src/main/res/values/attrs.xml
Labels: bug, maintainers

#3068 Fix line break in error report screen (EXPOSUREAPP-7002)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers

#3069 Update strings.xml (DEV)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#3067 Test not found exception (EXPOSUREAPP-6870)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotification.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/GeneralNotifications.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/SubmissionTanViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentViewModel.kt
Labels: bug, maintainers

#3066 Fix potential crash on network check (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/network/NetworkStateProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/network/NetworkStateProviderTest.kt
Labels: bug, maintainers

#3070 Rethrow exception to trigger unsuccessful SyncResult (EXPOSUREAPP-6857)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/HourPackageSyncTool.kt
Labels: bug, maintainers

#3050 No auto-submission in CheckIn-Selection-Screen (EXPOSUREAPP-6689)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/consent/CheckInsConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/consent/CheckInsConsentViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/consent/CheckInsConsentViewModelTest.kt
Labels: bug, maintainers

#3077 Bump to next Version 2.2.0.5
  gradle.properties
Labels: maintainers

#3072 No risk in journal - special switch (EXPOSUREAPP-7039)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/checkout/ContactJournalCheckInEntryCreator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/common/CheckInExtension.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/checkout/ContactJournalCheckInEntryCreatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/common/CheckInExtensionTest.kt
Labels: maintainers

#2947 Fix overlapping views in tracing settings fragment (COMMUNITY)
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
Labels: community, mirrored-to-jira

#3061 Home Screen - Registration card (EXPOSUREAPP-6724)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/homecards/CreateVaccinationHomeCard.kt
  Corona-Warn-App/src/main/res/drawable/ic_card_impfzertifikat_registrieren.xml
  Corona-Warn-App/src/main/res/layout/home_vaccination_registration_card.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#3081 Close button disappearing (EXPOSUREAPP-5548, EXPOSUREAPP-6652)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsFragment.kt
Labels: bug, maintainers, ui

#3079 Default updates (DEV)
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#3083 Fix rat wrong birthdate format (EXPOSUREAPP-7069)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/testresults/negative/RATResultNegativeFragment.kt
Labels: bug, maintainers

#3080 Data privacy update (EXPOSUREAPP-6536)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers

#3074 Corona test error handling (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/notification/PCRTestResultAvailableNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/notification/RATTestResultAvailableNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/SubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/resultavailable/SubmissionTestResultAvailableViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/invalid/SubmissionTestResultInvalidFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultNoConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/yourconsent/SubmissionYourConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/yourconsent/SubmissionYourConsentViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/testresult/pending/SubmissionTestResultPendingViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/testavailable/SubmissionTestResultAvailableViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/yourconsent/SubmissionYourConsentViewModelTest.kt
Labels: bug, maintainers

#3085 Adjust test availability constant (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/server/VerificationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RapidAntigenProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundConstants.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/server/VerificationServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RapidAntigenProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/worker/BackgroundConstantsTest.kt
Labels: bug, maintainers

#3058 Vaccination Repository Part 1 (EXPOSUREAPP-6729)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/SerializationModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/adapter/ByteStringBase64Adapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/ProofCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinatedPerson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinatedPersonIdentifier.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinationCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinationException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationCertificateCOSEParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationCertificateQRCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationCertificateV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/ValueSetsRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/errors/VaccinatedPersonNotFoundException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/errors/VaccinationCertificateNotFoundException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/errors/VaccinationDateOfBirthMissmatchException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/errors/VaccinationNameMissmatchException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/PersonData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/ProofContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/ProofCertificateCOSEParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/ProofCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/ProofCertificateException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/ProofCertificateResponse.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/ProofCertificateServerData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/ProofCertificateV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/VaccinationProofServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/VaccinationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/VaccinationValueSet.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/VaccinationTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/storage/ProofContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationStorageTest.kt
Labels: maintainers

#3084 AGP -> 4.2.0
  build.gradle
Labels: enhancement, maintainers

#3090 Update code style (DEV)
  .idea/codeStyles/Project.xml
Labels: enhancement, maintainers

#3094 Re-add strings that got lost during merge.
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#3047 Navigation enhancements (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationAboutFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationLegalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationTechnicalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationTermsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/interoperability/InteroperabilityConfigurationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeMenu.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/overview/MainOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/share/MainShareFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/backgroundpriority/SettingsBackgroundPriorityFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/notifications/NotificationSettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/yourconsent/SubmissionYourConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ExternalActionHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/errors/RecoveryByResetDialogFactory.kt
  Corona-Warn-App/src/main/res/layout/home_fragment_layout.xml
  Corona-Warn-App/src/main/res/menu/menu_main.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/ExternalActionHelperTest.kt
Labels: enhancement, maintainers

#3063 Change Zufall-IDs to Zufalls-IDs (closes #3062) (COMMUNITY)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: community, mirrored-to-jira

#3096 All material (DEV)
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_crashreporter_overview.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_keydownload.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_menu.xml
  Corona-Warn-App/src/main/res/layout/analytics_ppa_userinfo_input_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_comment_info_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_day_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_locations_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_persons_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_homescreen_card_include.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_location_list_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_person_list_fragment.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_delta_ppa.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_ppa.xml
  Corona-Warn-App/src/main/res/layout/fragment_ppa_more_info.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_privacy_preserving_analytics.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
  Corona-Warn-App/src/main/res/layout/fragment_statistics_explanation.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_deletion_warning.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_done.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_no_consent_positive_other_warning.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_positive_keys_shared.xml
  Corona-Warn-App/src/main/res/layout/fragment_test_home_test_cards_layout.xml
  Corona-Warn-App/src/main/res/layout/home_create_trace_location_card.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_incidence_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_infections_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_keysubmissions_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_sevendayrvalue_layout.xml
  Corona-Warn-App/src/main/res/layout/home_submission_pcr_status_card_error.xml
  Corona-Warn-App/src/main/res/layout/home_submission_pcr_status_card_invalid.xml
  Corona-Warn-App/src/main/res/layout/home_submission_pcr_status_card_negative.xml
  Corona-Warn-App/src/main/res/layout/home_submission_pcr_status_card_pending.xml
  Corona-Warn-App/src/main/res/layout/home_submission_pcr_status_card_positive_not_shared.xml
  Corona-Warn-App/src/main/res/layout/home_submission_pcr_status_card_positive_shared.xml
  Corona-Warn-App/src/main/res/layout/home_submission_pcr_status_card_ready.xml
  Corona-Warn-App/src/main/res/layout/home_submission_rapid_status_card_error.xml
  Corona-Warn-App/src/main/res/layout/home_submission_rapid_status_card_invalid.xml
  Corona-Warn-App/src/main/res/layout/home_submission_rapid_status_card_negative.xml
  Corona-Warn-App/src/main/res/layout/home_submission_rapid_status_card_outdated.xml
  Corona-Warn-App/src/main/res/layout/home_submission_rapid_status_card_pending.xml
  Corona-Warn-App/src/main/res/layout/home_submission_rapid_status_card_positive_not_shared.xml
  Corona-Warn-App/src/main/res/layout/home_submission_rapid_status_card_positive_shared.xml
  Corona-Warn-App/src/main/res/layout/home_submission_rapid_status_card_ready.xml
  Corona-Warn-App/src/main/res/layout/home_submission_status_card_unregistered.xml
  Corona-Warn-App/src/main/res/layout/include_submission_behaviour_row.xml
  Corona-Warn-App/src/main/res/layout/new_release_info_screen_fragment.xml
  Corona-Warn-App/src/main/res/layout/survey_consent_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_trace_locations_list_fragment.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_disabled_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_failed_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_increased_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_low_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_progress_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_access_survey_card.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_fragment_layout.xml
Labels: enhancement, maintainers

#3095 Device agnostic PDF size (EXPOSUREAPP-6696)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/poster/QrCodePosterFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/poster/QrCodePosterViewModel.kt
Labels: bug, maintainers

#3048 Vaccination details screenshots (EXPOSUREAPP-6738)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/ScreenShotter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/vaccination_strings.xml
Labels: maintainers

#3102 Fix codeowner setting for strings due to team name change (DEV)
  CODEOWNERS
Labels: maintainers

#3103 Removed bold Description in Event Creation (DEV)
  Corona-Warn-App/src/main/res/layout/trace_location_create_fragment.xml
Labels: maintainers

#3105 Data privacy update (EXPOSUREAPP-7074)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers

#3078 Adapt System UI colour in light and dark themes (EXPOSUREAPP-6991)
  Corona-Warn-App/src/main/res/values-night/bools.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/bools.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: enhancement, maintainers, ui

#3104 Text on "Fehlerberichte senden" mentions Apple instead of Google (EXPOSUREAPP-7102)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: maintainers

#3106 Update legal_strings.xml UA Bug fix (EXPOSUREAPP-7099)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
Labels: text change

#3088 Switched texts in trace location organizer onboarding screen (DEV)
  Corona-Warn-App/src/main/res/layout/trace_location_privacy_card.xml
Labels: maintainers

#3108 Typo in german (EXPOSUREAPP-7122)
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
Labels: maintainers

#3111 Version bump 2.2.1.0 (DEV)
  gradle.properties
Labels: maintainers

#3098 Fix app info cut on screen bottom (EXPOSUREAPP-7040)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_information.xml
Labels: bug, maintainers

#3112 Remove build tools (DEV)
  Corona-Warn-App/build.gradle
Labels: enhancement, maintainers

#3113 Update strings.xml (EXPOSUREAPP-7104)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#3114 UA Bugfix (EXPOSUREAPP-6891)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#3100 Improve network availability checks (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/TracingRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/interoperability/InteroperabilityRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/interoperability/InteroperabilityConfigurationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/interoperability/InteroperabilityConfigurationFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ConnectivityHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/device/PowerManagement.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/network/NetworkStateProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/interoperability/InteroperabilityConfigurationFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/ConnectivityHelperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/device/PowerManagementTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/network/NetworkStateProviderTest.kt
Labels: maintainers

#3097 Update strings.xml (EXPOSUREAPP-6753)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#3117 Remove development section (DEV)
  README.md
Labels: maintainers

#3118 Wrong german faq (EXPOSUREAPP-7100)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers

#3053 Updated Pending Result Screen (EXPOSUREAPP-6897)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingFragment.kt
  Corona-Warn-App/src/main/res/drawable/ic_hourglass.xml
  Corona-Warn-App/src/main/res/drawable/ic_result_pending_contact_diary.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_pending.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change, ui

#3115 Fix duplicate test removal error case handling (EXPOSUREAPP-7124)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/TransactionException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/QrCodeRegistrationStateProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/SubmissionTanViewModel.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRCoronaTestTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RACoronaTestTest.kt
Labels: bug, maintainers, prio

#3099 Vaccination Server - Retrofit interfaces & Module (EXPOSUREAPP-6854, EXPOSUREAPP-6856, EXPOSUREAPP-7129)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/EnvironmentState.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_debugoptions.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentSetup.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/vaccination/VaccinationCertificateCDNUrl.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/vaccination/VaccinationCertificateProofServerUrl.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/vaccination/VaccinationCertificateUrlModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinatedPerson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinationModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/ValueSetsRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/ProofContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/VaccinationServerModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/ProofCertificateCOSEParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/ProofCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/ProofCertificateException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/ProofCertificateResponse.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/ProofCertificateServerData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/VaccinationProofApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/VaccinationProofApiV2.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/VaccinationProofHttpClient.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/VaccinationProofModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/VaccinationProofServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/valueset/VaccinationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/valueset/VaccinationValueSet.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/valueset/VaccinationValueSetApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/valueset/VaccinationValueSetHttpClient.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/valueset/VaccinationValueSetModule.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/environment/EnvironmentSetupTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/VaccinationTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModelTest.kt
  prod_environments.json
Labels: maintainers

#3087 Adapt censoring (EXPOSUREAPP-7080)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/CoronaTestCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/PcrQrCodeCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/RatQrCodeCensor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/CoronaTestCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/PcrQrCodeCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/RatQrCodeCensorTest.kt
Labels: backend, maintainers

#3126 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers, text change

#3125 UA bugfix - Alignment with iOS (EXPOSUREAPP-7103)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#3128 Update default strings (DEV)
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#3121 fix typos: Ok and Check-In (closes #3120) (COMMUNITY)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: community, mirrored-to-jira, text change

#3123 Material Alert (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/upload/DebugLogUploadFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/upload/LogUploadBlockingDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/ui/ErrorDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentBlockingProgressDialogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/popups/DeviceTimeIncorrectDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/CheckInsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/TraceLocationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionBlockingDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionCancelDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/invalid/SubmissionTestResultInvalidFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultConsentGivenFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultKeysSharedFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultNoConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DialogHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/errors/RecoveryByResetDialogFactory.kt
Labels: enhancement, maintainers

#3138 Remove dummy storage data (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationStorage.kt
Labels: enhancement, maintainers

#3140 Fix flaky "onTestOpened" PPA unit-test (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNoConsentGivenFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultNoConsentViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultNoConsentViewModelTest.kt
Labels: bug, maintainers

#3127 Fix flags (EXPOSUREAPP-4209)
  Corona-Warn-App/src/main/res/drawable/ic_country_be.xml
  Corona-Warn-App/src/main/res/drawable/ic_country_de.xml
Labels: bug, maintainers

#3135 Polishing (EXPOSUREAPP-6913)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/details/VaccinationDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/VaccinationListFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
  Corona-Warn-App/src/main/res/navigation/vaccination_nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/vaccination_strings.xml
Labels: maintainers, prio

#3133 Fix typos en: Check-In (closes #3132) (COMMUNITY)
  Corona-Warn-App/src/main/res/values-en/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: community, text change

#3136 Expand line in data sharing onboarding information layout (EXPOSUREAPP-7202) closes #3131
  Corona-Warn-App/src/main/res/layout/fragment_ppa_more_info.xml
Labels: UX, community, mirrored-to-jira

#3145 Delete empty ConfirmCheckInViewModelTest (DEV)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/presencetracing/checkin/ConfirmCheckInViewModelTest.kt
Labels: enhancement, maintainers

#3146 Change default environment to WRU (EXPOSUREAPP-7213)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/environment/BuildConfigWrapTest.kt
Labels: maintainers

#3150 Refactor and reduce code complexity (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/scan/SubmissionQRCodeScanFragment.kt
Labels: maintainers

#3148 Remove code smell in DefaultTracingStatus (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/tracing/DefaultTracingStatus.kt
Labels: maintainers

#3149 Remove duplicate date formatting code (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/details/QrCodeDetailFragment.kt
Labels: maintainers

#3151 Reduce code smell debt within RiskLevelChange detektor (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelChangeDetector.kt
Labels: maintainers

#3092 Vaccination legal text consent screen (EXPOSUREAPP-6725)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/deltaonboarding/ui/DeltaOnboardingFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/deltaonboarding/ui/DeltaonboardingFragment.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_deltaonboarding.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinationPreferences.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinationSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/VaccinationUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/consent/VaccinationConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/consent/VaccinationConsentFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/consent/VaccinationConsentNavigationEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/consent/VaccinationConsentViewModel.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_vaccination_consent.xml
  Corona-Warn-App/src/main/res/drawable/ic_vaccination_consent.xml
  Corona-Warn-App/src/main/res/layout/vaccination_consent_fragment.xml
  Corona-Warn-App/src/main/res/layout/vaccination_consent_privacy_card.xml
  Corona-Warn-App/src/main/res/layout/vaccination_home_registration_card.xml
  Corona-Warn-App/src/main/res/navigation/vaccination_nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/main/res/values/vaccination_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
Labels: maintainers, text change

#3130 Kotlin 1.5.0 (DEV)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/ContactDiaryLocation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/ContactDiaryLocationVisit.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/ContactDiaryPerson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/ContactDiaryPersonEncounter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/exporter/ContactDiaryExporter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/ui/input/AnalyticsUserInputViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/server/LocationCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorReportReceiver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/ENFClient.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/calculation/PresenceTracingRiskCalculator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/DefaultRiskLevels.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/interoperability/InteroperabilityRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/behavior/BehaviorInfoRow.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/Tan.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/TanInput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/HashExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/ConfigParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/submission/RatProfileCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/registeredtest/TestResultDonorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/CheckInRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/receiver/ExposureStateUpdateReceiverTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/storage/BaseRiskLevelStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/calendar/CalendarCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/flow/HotDataFlowTest.kt
  Corona-Warn-App/src/test/java/testhelpers/KotestExtensions.kt
  Corona-Warn-App/src/testDevice/java/de/rki/coronawarnapp/nearby/modules/exposurewindow/ExposureWindowProviderTest.kt
  build.gradle
Labels: enhancement, maintainers

#3110 Qr Code partially scrolled (EXPOSUREAPP-6541)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/antigen/profile/VCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/ProfileQrCodeNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/details/QrCodeDetailFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/details/QrCodeDetailNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/details/QrCodeDetailViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/qrcode/fullscreen/QrCodeFullScreenFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/qrcode/fullscreen/QrCodeFullScreenFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/qrcode/fullscreen/QrCodeFullScreenViewModel.kt
  Corona-Warn-App/src/main/res/layout/activity_main.xml
  Corona-Warn-App/src/main/res/layout/fragment_qr_code_full_screen.xml
  Corona-Warn-App/src/main/res/layout/rat_profile_qr_code_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_qr_code_detail_fragment.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values-v27/styles.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/styles.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
Labels: enhancement, maintainers, ui

#3144 ProofCertificate wiring, Vaccination Repository Episode 3 (EXPOSUREAPP-6888, EXPOSUREAPP-6729)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/compression/InvalidInputException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/compression/ZLIBCompression.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinatedPersonIdentifier.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/certificate/CoseCertificateHeader.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/certificate/HealthCertificateCOSEDecoder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/certificate/HealthCertificateHeader.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/certificate/HealthCertificateHeaderParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/certificate/InvalidHealthCertificateException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/certificate/RawCOSEObject.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/certificate/VaccinationDGCV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/certificate/VaccinationDGCV1Parser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/HealthCertificateCOSEDecoder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationCertificateCOSEParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationCertificateHeader.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationCertificateQRCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationCertificateV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationCertificateV1Parser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationQRCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationQRCodeValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/ContainerPostProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/ProofContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/ProofCertificateCOSEParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/ProofCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/ProofCertificateException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/ProofCertificateResponse.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/ProofCertificateServerData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/VaccinationProofApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/VaccinationProofApiV2.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/VaccinationProofModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/VaccinationProofServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/decoder/InvalidInputException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/decoder/ZLIBDecompressor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/compression/ZLIBCompressionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/RawCOSEObjectTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/VaccinationTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/VaccinationTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationQRCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationQrCodeTestData.java
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationStorageTest.kt
  prod_environments.json
Labels: maintainers, prio

#3154 Reset vaccinations on data reset (EXPOSUREAPP-6869)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
Labels: maintainers

#3157 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers, text change

#3153 Wire up full 'Register Vaccination' Flow (EXPOSUREAPP-7108, EXPOSUREAPP-6732)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/vaccination/ui/VaccinationTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_vaccination.xml
  Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinatedPersonIdentifier.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/VaccinationListFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/VaccinationListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/scan/VaccinationQrCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/scan/VaccinationQrCodeScanViewModel.kt
  Corona-Warn-App/src/main/res/navigation/vaccination_nav_graph.xml
Labels: maintainers, prio

#3156 change "bei der Teststelle" to "an der Teststelle" (closes #3155) (COMMUNITY)
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
Labels: community, text change

#3160 Extend data vaccination structures (EXPOSUREAPP-7247)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinatedPerson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinatedPersonIdentifier.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinationCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/VaccinationListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/VaccinationMockData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListVaccinationCardItemVH.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/VaccinatedPersonIdentifierTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/VaccinatedPersonTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/VaccinationTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationContainerTest.kt
Labels: maintainers, prio

#3165 Remove proof certificate code (EXPOSUREAPP-7248)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/EnvironmentState.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_debugoptions.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentSetup.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/vaccination/VaccinationCertificateProofServerUrl.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/vaccination/VaccinationCertificateUrlModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/ProofCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinatedPerson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/execution/VaccinationUpdateScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/ContainerPostProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/ProofContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinatedPersonData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/VaccinationServerModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/ProofCertificateCOSEParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/ProofCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/ProofCertificateResponse.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/VaccinationProofApiV2.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/VaccinationProofHttpClient.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/VaccinationProofModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/proof/VaccinationProofServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/VaccinationMockData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/environment/EnvironmentSetupTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/VaccinationTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/execution/VaccinationUpdateSchedulerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/storage/ProofContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationStorageTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModelTest.kt
Labels: maintainers, prio

#3174 Qr code decoding (EXPOSUREAPP-7254)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/compression/ZLIBCompression.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/encoding/Base45Extensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinationCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/certificate/HealthCertificateCOSEDecoder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/certificate/RawCOSEObject.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/certificate/VaccinationDGCV1Parser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/common/RawCOSEObject.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationCertificateCOSEParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationCertificateQRCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationQRCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/ContainerPostProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationStorage.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/compression/ZLIBCompressionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/encoding/Base45ExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/RawCOSEObjectTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/VaccinationTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationStorageTest.kt
Labels: maintainers, prio

#3137 Test result not updated when clicking on "Test anzeigen" (EXPOSUREAPP-7136)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingViewModel.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/testresult/pending/SubmissionTestResultPendingViewModelTest.kt
Labels: author merge, bug, maintainers

#3159 Update default strings (DEV)
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#3101 Separate links for different types of incompatibility warnings (COMMUNITY)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: community, mirrored-to-jira

#3177 UA Text Change: Capitalize Adjectives (DEV)
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
Labels: maintainers, text change

#3179 Fix typos in TraceWarningPackageSyncTool module (COMMUNITY)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/warning/download/TraceWarningPackageSyncTool.kt
Labels: community

#3168 Fix duration text overflow in check ins screen. (EXPOSUREAPP-7199)
  Corona-Warn-App/src/main/res/layout/trace_location_attendee_checkins_item_active.xml
Labels: bug, maintainers

#3171 Vaccination details (EXPOSUREAPP-7242)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
  Corona-Warn-App/src/deviceForTesters/res/drawable/test_qr_code.png
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/details/QrCodeDetailFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/details/VaccinationDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListCertificateCardItemVH.kt
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_qr_code_detail_fragment.xml
  Corona-Warn-App/src/main/res/layout/vaccination_list_certificate_card.xml
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
  Corona-Warn-App/src/main/res/values/vaccination_strings.xml
  build.gradle
Labels: enhancement, maintainers, text change

#3178 Use hashed identifier in deep link (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/VaccinationListFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/VaccinationListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/scan/VaccinationQrCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/scan/VaccinationQrCodeScanViewModel.kt
  Corona-Warn-App/src/main/res/navigation/vaccination_nav_graph.xml
Labels: maintainers

#3161 Add (missing) arrow icon to create RAT profile card (closes #3162)
  Corona-Warn-App/src/main/res/layout/submission_create_rat_profile_card.xml
Labels: community, mirrored-to-jira

#3188 UA Text Change
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#3141 Vaccination server - ValueSet, Responses,.. (EXPOSUREAPP-6855)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/ValueSetsRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/ValueSetsStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/valueset/DefaultVaccinationValueSet.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/valueset/VaccinationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/valueset/VaccinationValueSet.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/valueset/VaccinationValueSetModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/valueset/ValueSet.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/valueset/internal/VaccinationValueSetMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/valueset/internal/ValueSetInvalidSignatureException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/VaccinationListViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/ValueSetsRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationContainerTest.kt
Labels: maintainers

#3190 Duration Picker ViewBinding (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/durationpicker/DurationPicker.kt
Labels: enhancement, maintainers

#3195 UA Text Change Isolationszeit
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#3193 Hide spinner on scan screen by default (DEV)
  Corona-Warn-App/src/main/res/layout/fragment_scan_qr_code.xml
Labels: bug, maintainers

#3187 Protocol Buffer update for release 2.4.x at Mon May 17 11:33:00 UTC 2021
  Server-Protocol-Buffer/src/main/proto/internal/ppdd/ppa_data.proto
Labels: maintainers

#3196 Fixing strings (EXPOSUREAPP-7117, EXPOSUREAPP-5443)
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#3184 Update vaccination consent screen (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/consent/VaccinationConsentFragment.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_shield_illustration.xml
  Corona-Warn-App/src/main/res/drawable/ic_shield_illustration.xml
  Corona-Warn-App/src/main/res/layout/vaccination_consent_fragment.xml
  Corona-Warn-App/src/main/res/layout/vaccination_consent_privacy_card.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: maintainers, text change

#3189 Fix country code mapping (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinationCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/VaccinationQrCodeTestData.java
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/VaccinationTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationQRCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationContainerTest.kt
Labels: maintainers

#3198 UA Text Change 'bei jeder teilnehmenden Teststelle.'
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
Labels: maintainers, text change

#3197 Improve VaccinationRepo tests and edge-case handling (EXPOSUREAPP-6729)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinatedPersonIdentifier.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/errors/VaccinationDateOfBirthMissmatchException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/errors/VaccinationNameMissmatchException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinatedPersonData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListVaccinationCardItemVH.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/VaccinatedPersonIdentifierTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/VaccinationTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/VaccinationTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationQRCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationStorageTest.kt
Labels: bug, maintainers, prio

#3200 Incognito mode for all edit text fields (EXPOSUREAPP-6596)
  Corona-Warn-App/src/main/res/layout/contact_diary_add_location_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_add_person_fragment.xml
  Corona-Warn-App/src/main/res/layout/rat_profile_create_fragment.xml
Labels: maintainers

#3176 Update test registration screen to new design. (EXPOSUREAPP-7229)
  Corona-Warn-App/src/main/res/drawable-night/ic_register_test_illustration.xml
  Corona-Warn-App/src/main/res/drawable/ic_register_test_illustration.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_dispatcher.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers

#3199 Vaccination Home Cards (EXPOSUREAPP-7231)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/homecard/CompleteVaccinationHomeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/homecard/ImmuneVaccinationHomeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/homecard/VaccinationHomeCard.kt
  Corona-Warn-App/src/main/res/drawable/vaccination_card_icon_complete.xml
  Corona-Warn-App/src/main/res/drawable/vaccination_card_icon_immune.xml
  Corona-Warn-App/src/main/res/layout/vaccination_home_card.xml
  Corona-Warn-App/src/main/res/layout/vaccination_home_immune_card.xml
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/vaccination_strings.xml
Labels: enhancement, maintainers, prio, text change

#3206 Data privacy update (EXPOSUREAPP-6804)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers

#3185 Adjust vaccination list screen (EXPOSUREAPP-7238)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeAndDateExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/VaccinatedPerson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/VaccinationListFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/VaccinationListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/VaccinationListAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListCertificateCardItemVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListImmunityInformationCardItemVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListIncompleteTopCardItemVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListQrCodeCardItemVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListVaccinationCardItemVH.kt
  Corona-Warn-App/src/main/res/drawable/ic_vaccination_incomplete_final.xml
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_list.xml
  Corona-Warn-App/src/main/res/layout/vaccination_list_immunity_card.xml
  Corona-Warn-App/src/main/res/layout/vaccination_list_incomplete_top_card.xml
  Corona-Warn-App/src/main/res/layout/vaccination_list_qrcode_card.xml
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/vaccination_strings.xml
Labels: maintainers, prio, text change

#3173 Vaccination Certificate - Censor Logs (EXPOSUREAPP-7097)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/BugReportingSharedModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/vaccination/CertificateQrCodeCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/qrcode/CoronaTestQRCodeValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationQRCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/qrcode/VaccinationQRCodeValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/VaccinationStorage.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/vaccination/CertificateQrCodeCensorTest.kt
Labels: backend, maintainers

#3210 Exclude resources from shrinking (DEV)
  Corona-Warn-App/proguard-rules.pro
Labels: bug, maintainers

#3208 Screenshots test (DEV)
  Corona-Warn-App/src/debug/res/drawable/test_qr_code.png
Labels: bug, maintainers

#3202 FIx: Use local timestamp for error report filename
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/internal/LogSnapshotter.kt
Labels: community

#3211 Add explanation to proguard rule that fixes R8 bugfix (DEV)
  Corona-Warn-App/proguard-rules.pro
Labels: maintainers

#3201 Circle Ci clean up (DEV)
  .circleci/config.yml
  .circleci/install-android-sdk.sh
Labels: enhancement, maintainers

#3194 Vaccination registration screenshots (EXPOSUREAPP-6741)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/vaccination/VaccinationConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
Labels: maintainers

#3204 Fix Datenabruf dialog not dismissed when completing submission (EXPOSUREAPP-7105)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionFragment.kt
Labels: bug, maintainers

#3207 Release strings for 2.3 (EXPOSUREAPP-6806)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
Labels: maintainers, text change

#3215 Automated Screenshots: Homescreen Vaccination Status (EXPOSUREAPP-6740)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeData.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/ViewActions.kt
Labels: maintainers

#3218 UA Bugfix Privacy Policy (EXPOSUREAPP-7274)
  Corona-Warn-App/src/main/assets/privacy_de.html
Labels: text change

#3192 Strings for Invalid RAT Test Result not correct (EXPOSUREAPP-6899)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/invalid/SubmissionTestResultInvalidFragment.kt
  Corona-Warn-App/src/main/res/drawable/ic_test_result_step_deletion.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_invalid.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#3209 Deletion of vaccination certificates (EXPOSUREAPP-7111)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/VaccinationListFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/VaccinationListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListImmunityInformationCardItemVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListNameCardItemVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListQrCodeCardItemVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListVaccinationCardItemVH.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_arrow_right_grey.xml
  Corona-Warn-App/src/main/res/drawable/ic_arrow_right_grey.xml
  Corona-Warn-App/src/main/res/layout/vaccination_list_vaccination_card.xml
  Corona-Warn-App/src/main/res/menu/menu_vaccination_item.xml
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
  Corona-Warn-App/src/main/res/values/vaccination_strings.xml
Labels: maintainers, text change

#3224 Update RAT illustration (EXPOSUREAPP-7336)
  Corona-Warn-App/src/main/res/drawable/ic_rat_profile_create_card_illustration.xml
Labels: maintainers

#3220 RAT Test timestamp (EXPOSUREAPP-6895)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RapidAntigenCoronaTestExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/TestResultSectionView.kt
Labels: bug, maintainers

#3226 Bump to next Version 2.3.0.1
  gradle.properties
Labels: maintainers

#3212 Improved Vaccination ServerCom / CleanUP (EXPOSUREAPP-6849)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/EnvironmentState.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_debugoptions.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentSetup.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/vaccination/VaccinationCertificateCDNUrl.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/vaccination/VaccinationCertificateUrlModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/ValueSetsRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/storage/ValueSetsStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/valueset/VaccinationValueSet.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/valueset/VaccinationValueSetModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/VaccinationListViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/environment/EnvironmentSetupTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/ValueSetsRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/repository/storage/ValueSetsStorageTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModelTest.kt
  prod_environments.json
Labels: maintainers

#3225 Vaccination List Screenshots (EXPOSUREAPP-6739)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/vaccination/ui/list/VaccinationListFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_list.xml
Labels: maintainers

#3221 UA Bugfix Privacy Policy (EXPOSUREAPP-7274)
  Corona-Warn-App/src/main/assets/privacy_en.html
Labels: maintainers, text change

#3229 Navigation after QR scan broken (EXPOSUREAPP-7288)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/scan/SubmissionQRCodeScanFragment.kt
Labels: bug, maintainers, prio

#3233 Remove fitsSystemWindows from fragments (EXPOSUREAPP-7366,EXPOSUREAPP-7368)
  Corona-Warn-App/src/main/res/layout/contact_diary_add_location_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_add_person_fragment.xml
  Corona-Warn-App/src/main/res/layout/fragment_confirm_check_in.xml
  Corona-Warn-App/src/main/res/layout/fragment_edit_check_in.xml
Labels: bug, maintainers, prio

#3222 Align progress indicator on list and details screen (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListQrCodeCardItemVH.kt
  Corona-Warn-App/src/main/res/layout/vaccination_list_qrcode_card.xml
Labels: maintainers

#3219 Align Margins on Register Test Screen (EXPOSUREAPP-7348)
  Corona-Warn-App/src/main/res/layout/fragment_submission_dispatcher.xml
  Corona-Warn-App/src/main/res/layout/include_dispatcher_card.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers

#3236 UA Adjustment to IOS Text (EXPOSUREAPP-7372)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#3231 Vaccination Server Test (EXPOSUREAPP-6890)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/server/valueset/VaccinationServer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/server/valueset/VaccinationServerTest.kt
  Corona-Warn-App/src/test/resources/vaccination/valueset_default.zip
  Corona-Warn-App/src/test/resources/vaccination/valueset_invalid.zip
Labels: maintainers

#3223 Reverse swipe-responsibility (opt-out -> opt-in) (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/CheckInsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/items/ActiveCheckInVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/items/CameraPermissionVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/items/PastCheckInVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/TraceLocationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/items/TraceLocationVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/list/SwipeConsumer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/list/SwipeExtension.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/list/Swipeable.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/VaccinationListFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListImmunityInformationCardItemVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListNameCardItemVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListQrCodeCardItemVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/list/adapter/viewholder/VaccinationListVaccinationCardItemVH.kt
Labels: maintainers

#3239 Bump to next Version 2.3.0.3
  gradle.properties
Labels: maintainers

#3227 Coroutines 1.5.0 (👨‍💻)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/coronatest/ui/CoronaTestTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/coronatest/ui/CoronaTestTestFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/tasks/testtask/TestTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/retention/ContactDiaryCleanTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/execution/PresenceTracingWarningTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/execution/PresenceTracingWarningTaskProgress.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/task/SubmissionTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/TaskController.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/common/DefaultProgress.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/execution/VaccinationUpdateScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/execution/task/VaccinationUpdateTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/CoronaWarnApplicationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/risk/execution/PresenceTracingWarningTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/TaskControllerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/testtasks/alerterror/AlertErrorTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/testtasks/precondition/PreconditionTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/testtasks/queue/QueueingTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/testtasks/silenterror/SilentErrorTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/testtasks/timeout/BaseTimeoutTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/execution/task/VaccinationUpdateTaskTest.kt
Labels: enhancement, maintainers

#3240 Version Bump (DEV)
  gradle.properties
Labels: maintainers

#3242 Bump to next Version 2.4.0.1
  gradle.properties
Labels: maintainers

#3243 Add missing "Uhr" indicator to check in duration (EXPOSUREAPP-6440)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/items/PastCheckInVH.kt
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
Labels: maintainers, text change

#3244 Fix headings in vaccination onboarding screen (EXPOSUREAPP-7361)
  Corona-Warn-App/src/main/res/layout/vaccination_consent_fragment.xml
Labels: maintainers, ui

#3230 Fix debug log censoring collisions (EXPOSUREAPP-7196)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/BugCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/contactdiary/DiaryEncounterCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/contactdiary/DiaryLocationCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/contactdiary/DiaryPersonCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/contactdiary/DiaryVisitCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/presencetracing/CheckInsCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/presencetracing/TraceLocationCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/CoronaTestCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/PcrQrCodeCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/RACoronaTestCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/RatProfileCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/RatQrCodeCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/vaccination/CertificateQrCodeCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/DebugLogger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/LogLine.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/internal/DebugLogStorageCheck.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/internal/DebugLoggerScope.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/internal/LogWriter.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/BugCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/CheckInsCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/CoronaTestCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/DiaryEncounterCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/DiaryLocationCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/DiaryPersonCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/DiaryVisitCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/PcrQrCodeCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/RACoronaTestCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/RatQrCodeCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/TraceLocationCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/submission/RatProfileCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/vaccination/CertificateQrCodeCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/debuglog/DebugLoggerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/debuglog/LogLineTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/debuglog/internal/DebugLogStorageCheckTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/debuglog/internal/LogSnapshotterTest.kt
Labels: bug, maintainers

#3246 Numbers missing in numbered list table of contents (EXPOSUREAPP-7360)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers

#3248 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-bg/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-bg/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-en/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-en/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-en/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-en/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-pl/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-ro/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-tr/vaccination_strings.xml
Labels: maintainers

#3247 Added missing Dark Mode Icons (EXPOSUREAPP-7399)
  Corona-Warn-App/src/main/res/drawable-night/ic_hourglass.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_test_result_step_deletion.xml
Labels: maintainers, ui

#3249 Default strings (DEV)
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/values/vaccination_strings.xml
Labels: maintainers

#3245 Reduce config check timeout for the update checker (EXPOSUREAPP-6101)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/update/UpdateChecker.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/update/UpdateCheckerTest.kt
Labels: maintainers

#3251 Added missing de-strings (DEV)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change
