Repository corona-warn-app/cwa-app-android, pull requests merged in 2021-07, with the labels that each got.

#3548 Add card (EXPOSUREAPP-7445)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/StatsItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsCardAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/AddCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/AppliedVaccinationRatesCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/IncidenceCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/InfectionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/KeySubmissionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/PersonsVaccinatedCompletelyCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/PersonsVaccinatedOnceCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/SevenDayRValueCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/StatisticsCardItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/lists/modular/mods/SavedStateMod.kt
  Corona-Warn-App/src/main/res/drawable/ic_blue_plus.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_add_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_dashed_layout.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCardItemTest.kt
Labels: maintainers, text change

#3595 Swap json logic deps (DEV)
  Corona-Warn-App/build.gradle
Labels: maintainers

#3594 fix order of the certificates (EXPOSUREAPP-8154)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProviderTest.kt
Labels: bug, maintainers

#3592 Implementation to retrieve countries supported by dcc validation (EXPOSUREAPP-8051)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/DigitalCovidCertificateModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/exception/CovidCertificateException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/common/exception/DccValidationException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/DccCountry.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/DccCountryLocalCache.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/DccCountryRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/server/DccCountryApi.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/server/DccCountryServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRuleRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/server/DccValidationRulesServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/DccCountryLocalCacheTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/DccCountryRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/DccCountryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/server/DccCountryApiTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/server/DccCountryServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
Labels: maintainers

#3578 UA Bugfix (EXPOSUREAPP-8120)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#3570 Selection screens (EXPOSUREAPP-7465)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/stateselection/FederalStateAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/stateselection/FederalStateSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/stateselection/FederalStateSelectionModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/stateselection/FederalStateSelectionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/stateselection/ListItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/res/layout/federal_state_input_adapter_item.xml
  Corona-Warn-App/src/main/res/layout/federal_state_selection_fragment.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
Labels: maintainers

#3599 Journal-PCR test results are listed in wrong date entry (EXPOSUREAPP-8211)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewViewModel.kt
Labels: bug, maintainers, prio

#3597 Filter emojis in RAT profile fields (EXPOSUREAPP-8108)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/view/EmojiFilterTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/EmojiFilter.kt
Labels: bug, maintainers, prio

#3606 Inserting non-breaking spaces(EXPOSUREAPP-8120)
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
Labels: maintainers, text change

#3607 Inserting non-breaking spaces (EXPOSUREAPP-8120)
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: maintainers, text change

#3608 Inserting non-breaking spaces(EXPOSUREAPP-8120)
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
Labels: maintainers, text change

#3609 Inserting non-breaking spaces(EXPOSUREAPP-8120)
  Corona-Warn-App/src/main/res/values-de/green_certificate_strings.xml
Labels: maintainers, text change

#3610 Inserting non-breaking spaces(EXPOSUREAPP-8120)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
Labels: maintainers, text change

#3611 Inserting non-breaking spaces(EXPOSUREAPP-8120)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#3612 Updating FAQ Link (EXPOSUREAPP-8226)
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
Labels: maintainers, text change

#3615 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-bg/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-pl/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-ro/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-tr/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/values/vaccination_strings.xml
Labels: maintainers

#3613 Fix wrong certificate issuer value being displayed (EXPOSUREAPP-8214,EXPOSUREAPP-8163)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/TestCertificateContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonCertificatesData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainerTest.kt
Labels: bug, maintainers, prio

#3617 CertificateS error message (EXPOSUREAPP-8226)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/exception/InvalidVaccinationCertificateException.kt
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
Labels: bug, maintainers, text change

#3621 Bump to next Version 2.5.0.4
  gradle.properties
Labels: maintainers

#3604 Fix a few code smells to reduce sonar debt (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/exception/InvalidVaccinationCertificateException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/qrcode/TraceLocationVerifier.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingViewModel.kt
Labels: maintainers

#3618 Missing person overview screenshots (EXPOSUREAPP-8231)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/debug/res/drawable/test_qr_code.png
Labels: bug, maintainers, prio

#3565 Validation Rules Info Screen (EXPOSUREAPP-8057)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/datetimeinfo/DateTimeInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/datetimeinfo/ValidationTimeInfoFragment.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_car.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_flight.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_map_of_europe.xml
  Corona-Warn-App/src/main/res/drawable/ic_car.xml
  Corona-Warn-App/src/main/res/drawable/ic_flight.xml
  Corona-Warn-App/src/main/res/drawable/ic_map_of_europe.xml
  Corona-Warn-App/src/main/res/layout/validation_time_info_fragment.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers, text change, ui

#3622 Update certificates Tab icon (EXPOSUREAPP-8228)
  Corona-Warn-App/src/main/res/drawable/ic_certificates.xml
Labels: bug, maintainers

#3620 Add missing `ptRiskLevelAtTestRegistration` to analytics (EXPOSUREAPP-8166)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsTestResultDonor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsPCRTestResultDonorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsRATestResultDonorTest.kt
Labels: bug, maintainers, prio

#3624 Gradle Kotlin bump (DEV)
  Corona-Warn-App/build.gradle
  build.gradle
  gradle.properties
Labels: enhancement, maintainers

#3601 Use dgc-certlogic-android "light" dependency (EXPOSUREAPP-8209)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/libs/engine-debug-bc467afcd8375ff5f579f9cac5bcfba74b55fcd7.aar
  Corona-Warn-App/libs/engine-release-bc467afcd8375ff5f579f9cac5bcfba74b55fcd7.aar
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/validation/business/BusinessValidator.kt
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-17-0bb8bac/dgc-certlogic-android-light-1.0.0-17-0bb8bac-sources.jar
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-17-0bb8bac/dgc-certlogic-android-light-1.0.0-17-0bb8bac-sources.jar.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-17-0bb8bac/dgc-certlogic-android-light-1.0.0-17-0bb8bac-sources.jar.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-17-0bb8bac/dgc-certlogic-android-light-1.0.0-17-0bb8bac-sources.jar.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-17-0bb8bac/dgc-certlogic-android-light-1.0.0-17-0bb8bac-sources.jar.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-17-0bb8bac/dgc-certlogic-android-light-1.0.0-17-0bb8bac.aar
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-17-0bb8bac/dgc-certlogic-android-light-1.0.0-17-0bb8bac.aar.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-17-0bb8bac/dgc-certlogic-android-light-1.0.0-17-0bb8bac.aar.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-17-0bb8bac/dgc-certlogic-android-light-1.0.0-17-0bb8bac.aar.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-17-0bb8bac/dgc-certlogic-android-light-1.0.0-17-0bb8bac.aar.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-17-0bb8bac/dgc-certlogic-android-light-1.0.0-17-0bb8bac.pom
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-17-0bb8bac/dgc-certlogic-android-light-1.0.0-17-0bb8bac.pom.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-17-0bb8bac/dgc-certlogic-android-light-1.0.0-17-0bb8bac.pom.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-17-0bb8bac/dgc-certlogic-android-light-1.0.0-17-0bb8bac.pom.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-17-0bb8bac/dgc-certlogic-android-light-1.0.0-17-0bb8bac.pom.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml.sha512
Labels: author merge, maintainers

#3630 Shortening the Text for Statistics Card (DEV)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#3623 Delete obsolete strings in de (DEV)
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-de/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
Labels: maintainers

#3632 Fix card position (EXPOSUREAPP-7431)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
Labels: bug, maintainers

#3628 General error message handling for invalid certificates (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccQrCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccV1Parser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/exception/InvalidHealthCertificateException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/exception/InvalidVaccinationCertificateException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/qrcode/DccQrCodeValidator.kt
  Corona-Warn-App/src/main/res/values-bg/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-pl/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-ro/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-tr/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/vaccination_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/qrcode/TestCertificateQRCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/qrcode/DccQrCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/qrcode/DccQrCodeValidatorTest.kt
Labels: maintainers, prio

#3633 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-pl/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-ro/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-tr/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/vaccination_strings.xml
Labels: maintainers

#3636 Certificate Switch - show username, adjust text (EXPOSUREAPP-8253)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/CwaUserCard.kt
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers, text change

#3637 Only one shot required strings (EXPOSUREAPP-8264)
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers, text change

#3603 Unite validation repos and server (EXPOSUREAPP-7618)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationCache.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/DccCountryApi.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/DccCountryRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRuleApi.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRuleRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/server/DccValidationRulesServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/server/DccValidationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/validation/business/BusinessValidator.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/DccCountryLocalCacheTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/server/DccCountryApiTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/server/DccCountryServerTest.kt
Labels: maintainers, prio

#3640 Adjustment of text to the button(EXPOSUREAPP-5455)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
Labels: text change

#3639 Fix dcc exceptions (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccV1Parser.kt
Labels: bug, maintainers

#3644 New text for tile
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
Labels: text change

#3634 Add JsonSchema based validation to DCC data extraction (EXPOSUREAPP-8257)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/assets/jsonschema-dcc-06fe7ed.json
  Corona-Warn-App/src/main/assets/technical.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccJsonSchema.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccJsonSchemaValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccQrCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccV1Parser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AndroidModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/validation/JsonSchemaSource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/validation/JsonSchemaValidator.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/dcc/DccQrCodeCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/CoronaTestTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccJsonSchemaTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccJsonSchemaValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/qrcode/TestCertificateDccParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/qrcode/TestCertificateQRCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPersonTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/qrcode/DccQrCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/qrcode/DccQrCodeValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/serialization/validation/JsonSchemaValidatorTest.kt
Labels: maintainers

#3643 Bump to next Version 2.5.1.0
  gradle.properties
Labels: maintainers

#3641 UA Bugfix(EXPOSUREAPP-8252)
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: text change

#3642 One dose info (EXPOSUREAPP-8264)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
Labels: maintainers, prio

#3631 Remove sqlcipher (DEV)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/proguard-rules.pro
  Corona-Warn-App/src/main/assets/technical.html
  docs/architecture-overview.md
Labels: enhancement, maintainers

#3647 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-bg/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-tr/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/values/vaccination_strings.xml
Labels: maintainers

#3649 Fix typo
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: bug, maintainers, text change

#3616 Validation start screen (EXPOSUREAPP-8030)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/DebugLogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/DigitalCovidCertificateUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CertificateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/TravelNoticeView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/DccCountry.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/DccCountryAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartNavEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/StatisticsExplanationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/behavior/BehaviorInfoRow.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/LocationTracingStatusCardBodyTextView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TextViewUrlExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/Views.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_map_of_europe.xml
  Corona-Warn-App/src/main/res/drawable/ic_map_of_europe.xml
  Corona-Warn-App/src/main/res/layout/dcc_country_list_item.xml
  Corona-Warn-App/src/main/res/layout/fragment_test_certificate_details.xml
  Corona-Warn-App/src/main/res/layout/validation_start_fragment.xml
  Corona-Warn-App/src/main/res/layout/validation_time_info_fragment.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonCertificatesData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/DccCountryTest.kt
Labels: maintainers, prio, text change, ui

#3650 Generate test certificate rsa key-pair only once (EXPOSUREAPP-8162)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/exception/InvalidTestCertificateException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/exception/TestCertificateServerException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/server/TestCertificateServer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
Labels: author merge, bug, maintainers, prio

#3652 Only strings (EXPOSUREAPP-8162)
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers, text change

#3654 Bump to next Version 2.5.1.1
  gradle.properties
Labels: maintainers

#3655 Certificate Onboarding icon (EXPOSUREAPP-7825)
  Corona-Warn-App/src/main/res/drawable-night/ic_phone_illustration.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_shield_illustration.xml
  Corona-Warn-App/src/main/res/drawable/ic_phone_illustration.xml
  Corona-Warn-App/src/main/res/drawable/ic_shield_illustration.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_onboarding_fragment.xml
Labels: bug, maintainers, prio

#3659 Tile "Test registrieren" headline + button text wrong (EXPOSUREAPP-8291)
  Corona-Warn-App/src/main/res/layout/home_submission_status_card_unregistered.xml
Labels: maintainers, prio

#3651 Profile screenshots (EXPOSUREAPP-7653)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/onboarding/RATProfileOnboardingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
Labels: maintainers

#3656 Additional edgecase handling for failed public key registration (EXPOSUREAPP-8162)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/exception/ErrorMessage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/exception/TestCertificateException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/execution/TestCertificateRetrievalScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/server/TestCertificateServer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/server/TestCertificateServerTest.kt
Labels: author merge, bug, maintainers, prio

#3660 Create 4 bullet points in "Hinweis" section of validation rules (EXPOSUREAPP-8293)
  Corona-Warn-App/src/main/res/layout/validation_start_fragment.xml
  Corona-Warn-App/src/main/res/layout/validation_start_fragment_notes.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: bug, maintainers, text change, ui

#3664 Add text for clarity
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: text change

#3600 Business rule validation (EXPOSUREAPP-8054)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/BusinessValidation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/BusinessValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicEngineWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/Mappings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/EvaluatedDccRule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/validation/business/AcceptanceProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/validation/business/BusinessValidation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/validation/business/BusinessValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/validation/business/EvaluatedDccRule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/validation/business/InvalidationProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/validation/technical/TechnicalValidation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/validation/technical/TechnicalValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicEngineWrapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/MappingsTest.kt
Labels: maintainers

#3663 Value set wrapper (EXPOSUREAPP-8258)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/BusinessValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicEngineWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/Mappings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/ValueSetWrapper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicEngineWrapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/ValueSetWrapperTest.kt
Labels: author merge, maintainers

#3646 Validation Result Common List Items (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRuleTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/ValidationResultAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/BaseValidationResultVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/BusinessRuleFailedVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/BusinessRuleOpenVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/RuleHeaderVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/TechnicalValidationFailedVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/ValidationFaqVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/ValidationInputVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/ValidationOverallResultVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/ValidationPassedHintVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/ValidationResultItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/lists/decorations/RecylerViewPaddingDecorator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/BaseJackson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/SerializationModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/validation/JsonSchemaValidator.kt
  Corona-Warn-App/src/main/res/drawable/card_with_outline.xml
  Corona-Warn-App/src/main/res/drawable/ic_grey_question_mark.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_faq_item.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_header_item.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_input_item.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_passed_hint_item.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_rule_container.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_rule_failed_item.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_rule_header_item.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_rule_open_item.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_technical_failed_item.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccJsonSchemaValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/qrcode/TestCertificateDccParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/qrcode/TestCertificateQRCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/serialization/validation/JsonSchemaValidatorTest.kt
Labels: maintainers

#3665 Certificates FAB (DEV)
  Corona-Warn-App/src/main/res/drawable/ic_add.xml
  Corona-Warn-App/src/main/res/layout/person_overview_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_trace_locations_list_fragment.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: enhancement, maintainers, text change

#3668 Support different loading button styles (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/PersonDetailsQrCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/ProgressLoadingButton.kt
  Corona-Warn-App/src/main/res/layout/person_details_qr_card_item.xml
  Corona-Warn-App/src/main/res/layout/view_progress_loading_button.xml
  Corona-Warn-App/src/main/res/values/attrs.xml
Labels: maintainers

#3666 Kid extraction (EXPOSUREAPP-8053)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccQrCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/decoder/DccCoseDecoder.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/dcc/DccQrCodeCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccQrCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/KidExtractionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationQrCodeTestData.java
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationTestData.kt
Labels: maintainers

#3671 New release strings (EXPOSUREAPP-7621)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
Labels: maintainers, text change

#3672 Data privacy update (EXPOSUREAPP-8068)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers, text change

#3662 Dcc Validation Failed Screen (EXPOSUREAPP-8062)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/DigitalCovidCertificateUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/DccValidationResultModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/CovidCertificateValidationResultFragmentsBindingExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/BusinessRuleFailedVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/BusinessRuleOpenVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/failed/DccValidationFailedFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/failed/DccValidationFailedViewModel.kt
  Corona-Warn-App/src/main/res/drawable-night/covid_certificate_validation_failed_header.xml
  Corona-Warn-App/src/main/res/drawable/covid_certificate_validation_failed_header.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_fragments.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: enhancement, maintainers

#3673 Compact when statement (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterStatistics.kt
Labels: enhancement, maintainers

#3675 Removing Periods in the Titles
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#3588 Add Start Validation Button to Existing Screens (EXPOSUREAPP-8047)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/PersonDetailsQrCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/DccCountry.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/ProgressLoadingButton.kt
  Corona-Warn-App/src/main/res/layout/fragment_recovery_certificate_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_test_certificate_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
  Corona-Warn-App/src/main/res/layout/person_details_qr_card_item.xml
  Corona-Warn-App/src/main/res/layout/validation_start_fragment.xml
  Corona-Warn-App/src/main/res/layout/view_progress_loading_button.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/attrs.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: maintainers, text change, ui

#3679 Fix Image Margins (DEV)
  Corona-Warn-App/src/main/res/layout/contact_diary_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/fragment_interoperability_configuration.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_privacy_preserving_analytics.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_no_consent_positive_other_warning.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_result_ready.xml
  Corona-Warn-App/src/main/res/layout/include_interoperability.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
  Corona-Warn-App/src/main/res/layout/include_submission_done.xml
  Corona-Warn-App/src/main/res/layout/survey_consent_fragment.xml
Labels: maintainers, ui

#3674 Merge if statements (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/common/CheckInExtension.kt
Labels: enhancement, maintainers

#3667 Validation state (EXPOSUREAPP-8053)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidation.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicTestData.kt
Labels: maintainers

#3678 Validation Result Common passed (EXPOSUREAPP-8031)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/DccValidationResultModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/CovidCertificateValidationResultFragmentsBindingExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/RuleHeaderVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/passed/DccValidationPassedFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/passed/DccValidationPassedNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/passed/DccValidationPassedViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartFragment.kt
  Corona-Warn-App/src/main/res/drawable-night/covid_certificate_validation_passed_header.xml
  Corona-Warn-App/src/main/res/drawable/covid_certificate_validation_passed_header.xml
  Corona-Warn-App/src/main/res/drawable/ic_valid_cert_new_night.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_passed_fragment.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_input_item.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers, ui

#3681 Remove unused link properties (EXPOSUREAPP-8335)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/network/NetworkStateProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/network/NetworkStateProviderTest.kt
Labels: maintainers

#3686 Dcc Validation Open Screen (EXPOSUREAPP-8061)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/DccValidationResultModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/CovidCertificateValidationResultFragmentsBindingExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/RuleHeaderVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/open/DccValidationOpenFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/open/DccValidationOpenViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/passed/DccValidationPassedViewModel.kt
  Corona-Warn-App/src/main/res/drawable-night/covid_certificate_validation_open_header.xml
  Corona-Warn-App/src/main/res/drawable/covid_certificate_validation_open_header.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_rule_header_item.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers, text change

#3693 Bump to next Version 2.6.0.1
  gradle.properties
Labels: maintainers

#3669 Pick highest version of rule (DEV)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRuleParcelTest.kt
  Corona-Warn-App/src/main/assets/technical.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/Mappings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRule.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicEngineWrapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/MappingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRuleTest.kt
Labels: maintainers

#3658 Validation repo (EXPOSUREAPP-7618)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRuleParcelTest.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/datadonation/analytics/storage/DefaultLastAnalyticsSubmissionLogger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/server/CoronaTestResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationCache.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/BusinessValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/Mappings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRuleApi.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/server/DccValidationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/encryption/rsa/RSAKey.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/SerializationModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/adapter/DurationAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/adapter/InstantAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/adapter/JsonNodeAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/adapter/LocalDateAdapter.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/MappingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/country/DccCountryLocalCacheTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/server/DccValidationServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/serialization/adapter/JsonNodeAdapterTest.kt
Labels: maintainers

#3690 Wrong birthdate format (EXPOSUREAPP-8283)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/CwaUserCard.kt
Labels: bug, maintainers

#3691 Fix link in EN (EXPOSUREAPP-8269)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/StatisticsExplanationFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_statistics_explanation.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers, text change

#3701 Hotline icons in dark mode (EXPOSUREAPP-8281)
  Corona-Warn-App/src/main/res/drawable/ic_international_phone.xml
  Corona-Warn-App/src/main/res/drawable/ic_phone.xml
Labels: bug, maintainers

#3703 Fix illustrations (EXPOSUREAPP-8309)
  Corona-Warn-App/src/main/res/drawable-night/ic_deletion_warning.xml
  Corona-Warn-App/src/main/res/drawable/ic_deletion_warning.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_deletion_warning.xml
Labels: bug, maintainers

#3702 Delete button style (EXPOSUREAPP-8308)
  Corona-Warn-App/src/main/res/layout/home_submission_pcr_status_card_positive_not_shared.xml
  Corona-Warn-App/src/main/res/layout/home_submission_rapid_status_card_positive_not_shared.xml
Labels: bug, maintainers

#3696 DCC-UI - No Connectivity View (EXPOSUREAPP-8251)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartNavEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartViewModel.kt
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers, prio, text change

#3699 Test certificate details headline (EXPOSUREAPP-8288)
  Corona-Warn-App/src/main/res/layout/fragment_test_certificate_details.xml
Labels: bug, maintainers

#3676 Provide `Random` via injection and use `SecureRandom` for padding (DEV)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/server/VerificationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNet.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/locations/TraceLocationCreator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/server/SubmissionServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/PaddingTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/RandomFast.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/RandomStrong.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/SecurityModule.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/server/VerificationServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNetTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/locations/TraceLocationCreatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/server/SubmissionServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/CWADebugTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/PaddingToolTest.kt
Labels: maintainers

#3708 Select latest country selection (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartViewModel.kt
Labels: bug, maintainers, prio

#3689 Statistics cards issues (EXPOSUREAPP-8259)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/util/StatisticsNumberValueFormatter.kt
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_applied_vaccination_rates_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_incidence_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_infections_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_keysubmissions_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_sevendayrvalue_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_vaccinated_completely_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_vaccinated_once_layout.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/util/StatisticsNumberValueFormatterTest.kt
Labels: bug, maintainers

#3706 Improve statistics card redraw behavior (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/AddCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/AppliedVaccinationRatesCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/IncidenceCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/InfectionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/KeySubmissionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/PersonsVaccinatedCompletelyCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/PersonsVaccinatedOnceCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/SevenDayRValueCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/StatisticsCardItem.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCardItemTest.kt
Labels: maintainers

#3711 Fix pickers style (DEV)
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers

#3712 Handle non existing person (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
Labels: bug, maintainers

#3705 Update build.gradle quickBuild task (DEV)
  build.gradle
Labels: maintainers

#3710 Sort countries (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartViewModel.kt
Labels: maintainers, prio

#3707 Add missing `clipToPadding` in App Information screen (COMMUNITY)
  Corona-Warn-App/src/main/res/layout/fragment_information.xml
Labels: community

#3680 Improve `stableId` for person details list (EXPOSUREAPP-8325)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/repository/CertificateContainerId.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/repository/RecoveryCertificateContainerId.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/repository/TestCertificateContainerId.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/repository/VaccinationCertificateContainerId.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/CertificateItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationInfoCard.kt
Labels: bug, maintainers, prio

#3713 Statistics screenshots + layout fix (EXPOSUREAPP-7448)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/statistics/Statistics.kt
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_add_layout.xml
Labels: maintainers, ui

#3716 Bump to next Version 2.6.0.2
  gradle.properties
Labels: maintainers

#3717 Bump to next Version 2.6.0.3
  gradle.properties
Labels: maintainers

#3700 Rat redeemed state handling (EXPOSUREAPP-7517)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/server/CoronaTestResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRCoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRTestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RACoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RATestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/SubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/CoronaTestRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRCoronaTestTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RACoronaTestTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RAProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsPCRTestResultDonorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsTestResultCollectorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/SubmissionRepositoryTest.kt
Labels: bug, maintainers

#3720 UA Bugfix
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#3721 Protocol Buffer update for release 2.7.x at Thu Jul 15 08:34:40 UTC 2021
  Server-Protocol-Buffer/src/main/proto/internal/dgc/dsc_list.proto
  Server-Protocol-Buffer/src/main/proto/internal/v2/dgc_parameters.proto
Labels: maintainers

#3718 Fix screenshots tests (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/CertificateItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
Labels: maintainers

#3687 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-bg/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-bg/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-bg/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-pl/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-pl/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-ro/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-ro/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-tr/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-tr/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/values/vaccination_strings.xml
Labels: maintainers

#3697 Connect Validation Result List Items (EXPOSUREAPP-8329)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/Mappings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/ValidationResultAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/ValidationResultItemCreator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/AffectedFieldsMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/BusinessRuleFailedVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/BusinessRuleOpenVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/RuleHeaderVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/TechnicalValidationFailedVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/ValidationInputVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/ValidationOverallResultVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/businessrule/BusinessRuleVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/businessrule/EvaluatedFieldAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/failed/DccValidationFailedFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/failed/DccValidationFailedViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/open/DccValidationOpenFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/open/DccValidationOpenViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/passed/DccValidationPassedViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartNavEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeAndDateExtensions.kt
  Corona-Warn-App/src/main/res/drawable/bg_rule_card.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_rule_item.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_rule_item_evaluated_field_item.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_rule_open_item.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_attribute_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers, prio, text change, ui

#3723 Add more logging to dcc parsing error handling (EXPOSUREAPP-8402)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccQrCodeExtractor.kt
Labels: bug, maintainers

#3724 Businessrule version on result view (EXPOSUREAPP-8398)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/ValidationResultItemCreator.kt
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_rule_item.xml
Labels: maintainers, prio

#3726 UA Text Change(EXPOSUREAPP-8403)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#3728 UA Bugfix (DEV)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#3729 Fix padding on person details fragment (COMMUNITY)
  Corona-Warn-App/src/main/res/layout/person_details_fragment.xml
Labels: community

#3730 Bump to next Version 2.6.0.4
  gradle.properties
Labels: maintainers

#3731 Json Schema proguard (EXPOSUREAPP-8402)
  Corona-Warn-App/proguard-rules.pro
Labels: maintainers

#3732 Bump to next Version 2.6.0.5
  gradle.properties
Labels: maintainers

#3734 Fix: 'Reset App' does not reset custom incidence locations (EXPOSUREAPP-8439)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/local/source/LocalStatisticsProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/local/storage/LocalStatisticsConfigStorage.kt
Labels: bug, maintainers

#3735 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#3733 Update statistics explanation (EXPOSUREAPP-8423)
  Corona-Warn-App/src/main/res/layout/fragment_statistics_explanation.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers, text change

#3736 UA Bugfix(EXPOSUREAPP-8453)
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#3737 Fix heading switched - local statistics(EXPOSUREAPP-8410)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/stateselection/FederalStateSelectionFragment.kt
Labels: maintainers, prio

#3741 Bump to next Version 2.6.0.6
  gradle.properties
Labels: maintainers

#3727 Protocol Buffer update for release 2.7.x at Thu Jul 15 12:52:59 UTC 2021
  Server-Protocol-Buffer/src/main/proto/internal/dgc/dsc_list.proto
Labels: maintainers

#3738 DSC skeleton wiring & classes for 2.7.x
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/DigitalCovidCertificateModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/DigitalCovidCertificateUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/notification/DigitalCovidCertificateNotifications.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DccStateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DigitalSignatureCertificateModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscDataParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscSignatureValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/execution/DccStateCheckScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/execution/DccStateCheckWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/server/DscServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/storage/DefaultDscSource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/storage/LocalDscStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/ui/DigitalSignatureCertificateUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/ui/notification/DscCheckNotification.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPerson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/NotificationConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/worker/WorkerBinder.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/CoronaWarnApplicationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonCertificatesData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPersonTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/worker/WorkerBinderTest.kt
Labels: maintainers, prio

#3743 Value map combined (EXPOSUREAPP-8458)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicEngineWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/ValueSetWrapper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/ValueSetWrapperTest.kt
Labels: maintainers

#3744 UA Bug fix (DEV)
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
Labels: maintainers, text change

#3739 Add Expiration Date Info Box to Detail Screens (EXPOSUREAPP-8371)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_recovery_certificate_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_test_certificate_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
  Corona-Warn-App/src/main/res/layout/include_expiration_notice_card.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers, text change, ui

#3740 Align centering of empty list placeholders (DEV)
  Corona-Warn-App/src/main/res/layout/trace_location_attendee_checkins_fragment.xml
Labels: maintainers

#3746 Title Change(EXPOSUREAPP-8422)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
Labels: text change

#3745 Fix :Rule counter on success screen considers both AR and IR instead if just AR (EXPOSUREAPP-8459)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/passed/DccValidationPassedViewModel.kt
Labels: bug, maintainers

#3748 Bump to next Version 2.6.0.7
  gradle.properties
Labels: maintainers

#3715 Validation date time refactoring (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/BusinessValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicEngineWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/Mappings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/ValidationResultItemCreator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeAndDateExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicEngineWrapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/MappingsTest.kt
Labels: maintainers, prio

#3753 Add info for clarity (DEV)
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: maintainers, text change

#3749 Business rules View correction (EXPOSUREAPP-8460)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/ValidationResultItemCreator.kt
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_rule_item.xml
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers

#3751 Better `HotData` queue handling on fast operations (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/flow/HotDataFlow.kt
Labels: maintainers

#3750 Increase ValueSet storage resilience (DEV,EXPOSUREAPP-8113)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/valueset/ValueSetsRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/valueset/valuesets/ValueSetsStorage.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/ValueSetsStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/valueset/ValueSetsRepositoryTest.kt
Labels: maintainers

#3759 Update TUR legal strings
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
Labels: text change

#3757 Bump to next Version 2.6.0.8
  gradle.properties
Labels: maintainers

#3755 Convert validation clock to utc (EXPOSUREAPP-8470)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/BusinessValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicEngineWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/Mappings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRule.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/TestData.java
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/qrcode/TestCertificateQRCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicEngineWrapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/MappingsTest.kt
Labels: maintainers, prio

#3765 UA Bug Fix(EXPOSUREAPP-8518)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#3742 Increase certificate storage resilience (EXPOSUREAPP-8113, EXPOSUREAPP-8117)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorage.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorageTest.kt
Labels: maintainers

#3756 Wrong result on rule validation screen for expired certs (EXPOSUREAPP-8468)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/ValidationResultItemCreator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/TechnicalValidationFailedVH.kt
Labels: maintainers

#3766 Bump to next Version 2.6.0.9
  gradle.properties
Labels: maintainers

#3758 Update EN legal strings (EXPOSUREAPP-7574)
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: maintainers, text change

#3763 Swap text sections in statistics info screen (EXPOSUREAPP-8519)
  Corona-Warn-App/src/main/res/layout/fragment_statistics_explanation.xml
Labels: maintainers

#3768 Keep CertLogic explicitly. (EXPOSUREAPP-8531)
  Corona-Warn-App/proguard-rules.pro
Labels: bug, maintainers, prio

#3752 PersonCertificates data generation improvements (DEV,EXPOSUREAPP-8113)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/valueset/ValueSetsRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepositoryTest.kt
Labels: maintainers

#3770 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#3769 Bump to next Version 2.6.0.10
  gradle.properties
Labels: maintainers

#3774 Bump to next Version 2.6.1.0
  gradle.properties
Labels: maintainers

#3760 QRCode Generation Performance Improvements (DEV,EXPOSUREAPP-8113)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/ScreenshotCertificateTestData.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/eventregistration/organizer/QrCodeDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FakeImageLoader.kt
  Corona-Warn-App/src/debug/res/drawable/test_qr_code.png
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/presencetracing/ui/poster/QrCodePosterTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/presencetracing/ui/poster/QrCodePosterTestViewModel.kt
  Corona-Warn-App/src/main/assets/technical.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/PersonDetailsQrCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/qrcode/QrCodeGenerator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/details/QrCodeDetailFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/details/QrCodeDetailViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/poster/QrCodePosterFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/poster/QrCodePosterViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/qrcode/fullscreen/QrCodeFullScreenFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/qrcode/fullscreen/QrCodeFullScreenViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/coil/CoilExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/coil/CoilModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/qrcode/QrCodeOptions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/qrcode/coil/BitMatrixDecoder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/qrcode/coil/CoilQrCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/qrcode/coil/QrCodeBitMatrixFetcher.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/CoronaWarnApplicationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/presencetracing/organizer/poster/QrCodePosterViewModelTest.kt
  Server-Protocol-Buffer/build.gradle
Labels: maintainers

#3754 "Gesamtes Bundesland" is not visible (EXPOSUREAPP-8437)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/statistics/Statistics.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/StatsItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/local/source/LocalStatisticsParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/local/source/LocalStatisticsProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/local/source/LocalStatisticsRetrievalScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/local/storage/LocalStatisticsConfigStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/local/storage/SelectedDistrict.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/local/storage/SelectedLocations.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/local/storage/SelectedStatisticsLocation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/LocalIncidenceCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/StatisticsCardItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/stateselection/FederalStateSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/stateselection/FederalStateSelectionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers, prio

#3781 Harmonize "Zertifikats" usage (DEV)
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: maintainers, text change

#3776 Expiration check (EXPOSUREAPP-8368)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/CovidCertificateConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CovidCertificateConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DccStateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeAndDateExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/signature/core/DccStateCheckerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/TimeAndDateExtensionsTest.kt
Labels: maintainers

#3782 Fix Wrong affected failed rules (EXPOSUREAPP-8522)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/AffectedFieldsMapper.kt
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_attribute_strings.xml
Labels: maintainers, prio

#3761 Retrieve DSCs from server (EXPOSUREAPP-8362)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/DigitalCovidCertificateModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/common/exception/DscValidationException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/server/DscApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/server/DscServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/server/DscServerModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentSetup.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/signature/core/server/DscServerTest.kt
Labels: maintainers

#3786 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers
