Repository corona-warn-app/cwa-app-android, pull requests merged in 2021-11, with the labels that each got.

#4299 Reset PPA on restore (EXPOSUREAPP-10204)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/coronatest/RecycledCoronaTestsProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/coronatest/RecycledCoronaTestsProviderTest.kt
Labels: maintainers

#4305 Bugfix: Universal Scanner Button moves to the center of the screen (EXPOSUREAPP-10250)
  Corona-Warn-App/src/main/res/layout/activity_main.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_tan.xml
Labels: bug, maintainers, prio

#4277 PPA extension with exposure windows (EXPOSUREAPP-10054)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/common/ExposureWindowModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposurewindows/AnalyticsExposureWindowModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposurewindows/AnalyticsExposureWindowRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsExposureWindowsSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsTestResultCollector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsTestResultDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsTestResultSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsPCRTestResultDonorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsRATestResultDonorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsTestResultCollectorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsTestResultSettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskLevelTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
Labels: maintainers

#4296 Fix: Default check out duration (EXPOSUREAPP-9551)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/qrcode/DefaultAutoCheckoutLength.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/confirm/ConfirmCheckInViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/locations/DefaultAutoCheckoutLengthTest.kt
Labels: bug, maintainers

#4306 Fix exposure risk donor (EXPOSUREAPP-10192)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposureriskmetadata/ExposureRiskMetadataDonor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/ExposureRiskMetadataDonorTest.kt
Labels: bug, maintainers

#4307 RecycleBin (Tests) - recycle / restore tests (EXPOSUREAPP-10118, EXPOSUREAPP-10113)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/CoronaTestRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRCoronaTestTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RACoronaTestTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RAProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/coronatest/RecycledCoronaTestsProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
Labels: maintainers

#4311 Recycle Bin(tests) - automatic cleanup (EXPOSUREAPP-10120)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/cleanup/RecycleBinCleanUpScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/cleanup/RecycleBinCleanUpService.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/cleanup/RecycleBinCleanUpSchedulerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/cleanup/RecycleBinCleanUpServiceTest.kt
Labels: maintainers

#4308 New features (EXPOSUREAPP-10056)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoFragment.kt
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
Labels: maintainers, text change

#4312 Fix profile deletion (EXPOSUREAPP-9905)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/antigen/profile/RATProfileSettings.kt
Labels: bug, maintainers

#4313 Adjust Test restoring navigation (EXPOSUREAPP-10274)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/coronatest/request/RestoreRecycledTestRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningViewModel.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/ui/RecyclerBinOverviewViewModelTest.kt
Labels: maintainers

#4318 Protocol Buffer update for release 2.13.x at Wed Nov 3 09:26:38 UTC 2021
  Server-Protocol-Buffer/src/main/proto/internal/v2/dgc_parameters.proto
Labels: maintainers

#4310 Kathrin luecke patch 1 (EXPOSUREAPP-10246)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4319 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
Labels: maintainers, text change

#4292 Move test to recycle bin dialog (EXPOSUREAPP-10105)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNegativeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/CoronaTestRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/common/TestResultAvailableNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/dialog/RecycleBinDialogType.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/SubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/testresults/negative/RATResultNegativeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/testresults/negative/RATResultNegativeViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/DuplicateWarningEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/invalid/SubmissionTestResultInvalidFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/invalid/SubmissionTestResultInvalidViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultKeysSharedFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultKeysSharedViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultNoConsentFragment.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/pcr/notification/PCRTestResultAvailableNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/notification/RATestResultAvailableNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/ui/RecyclerBinOverviewViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/testresult/pending/SubmissionTestResultPendingViewModelTest.kt
Labels: maintainers

#4317 Text overlapping and redundant parentheses (EXPOSUREAPP-10244)
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_infections_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_keysubmissions_layout.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-v28/styles.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
Labels: bug, maintainers

#4304 Bugfix: App Crash after vacc. deletion (EXPOSUREAPP-10153)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/CwaUserCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
Labels: bug, maintainers

#4326 Adding the word "Ihre"
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#4324 Update recycler_bin_strings.xml (EXPOSUREAPP-10407)
  Corona-Warn-App/src/main/res/values-de/recycler_bin_strings.xml
Labels: prio, text change

#4325 Adjustment of "Neue Funktionen 2.14"
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: text change

#4320 Bump to next Version 2.13.2.0
  gradle.properties
Labels: maintainers

#4330 Revert "Update recycler_bin_strings.xml (EXPOSUREAPP-10407)"
  Corona-Warn-App/src/main/res/values-de/recycler_bin_strings.xml
Labels: maintainers, text change

#4329 Improve Person regrouping (EXPOSUREAPP-10154)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinatedPersonData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorage.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationGroupingTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorageTest.kt
Labels: bug, maintainers, author merge

#4337 Protocol Buffer update for release 2.13.x at Wed Nov 3 09:26:38 UTC 2021
  Server-Protocol-Buffer/src/main/proto/internal/v2/dgc_parameters.proto
Labels: maintainers

#4336 Update mapping of app config (EXPOSUREAPP-10446)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/CovidCertificateConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CovidCertificateConfigMapper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/CovidCertificateConfigMapperTest.kt
Labels: maintainers

#4345 Fix relation between administrative units belonging to federal state Thuringia (EXPOSUREAPP-10406)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/LocalIncidenceAndHospitalizationCard.kt
Labels: bug, maintainers

#4348 Revert "Kathrin luecke patch 1 (EXPOSUREAPP-10246)"
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4350 Dcc Ticketing skeleton (EXPOSUREAPP-10490)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dccticketing/DccTicketingTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dccticketing/DccTicketingTestModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dccticketing/DccTicketingTestViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainActivityTestModule.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_dcc_ticketing.xml
  Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/scanner/QrCodeValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/info/UqsInfoFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_consent_one.xml
  Corona-Warn-App/src/main/res/layout/fragment_uqs_info.xml
  Corona-Warn-App/src/main/res/navigation/dcc_ticketing_nav_graph.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
  translation_v2.json
Labels: maintainers

#4342 Bump to next Version 2.13.3.0
  gradle.properties
Labels: maintainers

#4341 Mitigate base45 security vulnerability (EXPOSUREAPP-10454)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/encoding/Base45Decoder.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccQrCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/qrcode/TestCertificateQRCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationQrCodeTestData.java
Labels: maintainers, prio

#4344 Remove white space that brakes cert logic (EXPOSUREAPP-10455)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/ValueSetWrapper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/ValueSetWrapperTest.kt
Labels: bug, maintainers

#4351 Disable exporting of Blocked Certs(EXPOSUREAPP-10449)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/PersonDetailsQrCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/res/color/text_button_color.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
Labels: maintainers

#4360 Replace entfernen by löschen (Text Change)
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
Labels: maintainers, text change

#4358 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#4359 Replace entfernen by löschen (Text Change)
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
Labels: maintainers, text change

#4357 Replace entfernen by löschen (Text Change)
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
Labels: maintainers, text change

#4343 Most relevant DCC, update vaccination priority (EXPOSUREAPP-9443)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPerson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationCertificate.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: maintainers, do not merge

#4352 Invalidate fake certificates: UI update (EXPOSUREAPP-10400)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
Labels: ui, maintainers

#4347 Blocked certs notifications (EXPOSUREAPP-10448)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/StoredRecoveryCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/BaseTestCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/GenericTestCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/PCRCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/RACertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonCertificatesData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorageTest.kt
Labels: maintainers

#4340 Update certificate validation logic (EXPOSUREAPP-10447)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificateUI.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/exception/InvalidHealthCertificateException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/PersonDetailsQrCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/StoredRecoveryCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/BaseTestCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/GenericTestCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/PCRCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/RACertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/ui/onboarding/CovidCertificateOnboardingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/BlocklistValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/color/text_button_color.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonCertificatesData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/BlocklistValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
Labels: maintainers

#4362 Bump to next Version 2.13.3.1
  gradle.properties
Labels: maintainers

#4355 Json and extractor (EXPOSUREAPP-10477)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingInvalidQrCodeException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeExtractor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeExtractorTest.kt
Labels: maintainers

#4322 [Feature] Invalidate Fake Certificates (EXPOSUREAPP-10238)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/CovidCertificateConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CovidCertificateConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificateUI.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/exception/InvalidHealthCertificateException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/PersonDetailsQrCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/StoredRecoveryCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/BaseTestCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/GenericTestCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/PCRCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/RACertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/ui/onboarding/CovidCertificateOnboardingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/BlocklistValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/color/text_button_color.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/CovidCertificateConfigMapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonCertificatesData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/BlocklistValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
Labels: maintainers, text change, author merge

#4367 Bump to next Version 2.13.3.2
  gradle.properties
Labels: maintainers

#4366 Fix: Recycled TAN after 30 days (EXPOSUREAPP-10495)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/CoronaTestRepository.kt
Labels: bug, maintainers

#4365 Fix: 2.13 screenshots (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
Labels: bug, maintainers

#4370 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers, text change

#4368 Lenient mode for decoder (EXPOSUREAPP-10507)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccQrCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/encoding/Base45Decoder.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccQrCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/qrcode/TestCertificateQRCodeExtractorTest.kt
Labels: bug, maintainers

#4361 Restore recycled tests without consent - fix (EXPOSUREAPP-10441)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
Labels: bug, maintainers

#4363 Update recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-de/recycler_bin_strings.xml
Labels: maintainers, text change

#4364 Replace entfernen by löschen
  Corona-Warn-App/src/main/res/values-de/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
Labels: maintainers, text change

#4372 Revert "Replace Alle entfernen-Alle endgültig löschen (EXPOSUREAPP-10108)"
  Corona-Warn-App/src/main/res/values-de/recycler_bin_strings.xml
Labels: text change

#4373 EC Key pair generation (EXPOSUREAPP-10487)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/encryption/ec/EcKeyGenerator.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/encryption/ec/EcKeyGeneratorTest.kt
Labels: maintainers

#4377 TicketValidation: update data structures (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccJWK.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingService.kt
Labels: maintainers

#4376 [Test menu] Generates keys (EXPOSUREAPP-10487)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dccticketing/DccTicketingTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dccticketing/DccTicketingTestViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_dcc_ticketing.xml
Labels: enhancement, maintainers

#4378 Test replacement screeen recycle bin text fix (EXPOSUREAPP-10539)
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
Labels: text change

#4369 Added info box check for series completing vaccines over 14 days (EXPOSUREAPP-10538)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPerson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPersonTest.kt
Labels: bug, maintainers

#4384 Gson library update (EXPOSUREAPP-10561)
  Corona-Warn-App/build.gradle
Labels: maintainers

#4385 Bump to next Version 2.14.0.1
  gradle.properties
Labels: maintainers

#4374 Init transaction (EXPOSUREAPP-10484)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingAccessToken.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingResultItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingResultToken.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingTransactionContext.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingValidationCondition.kt
Labels: maintainers

#4354 Fix: DCC parent color shade (EXPOSUREAPP-9950)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonColorShade.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_bookmark.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_bookmark_blue.xml
  Corona-Warn-App/src/main/res/drawable/ic_bookmark_blue.xml
  Corona-Warn-App/src/main/res/drawable/ic_bookmark_blue_1.xml
  Corona-Warn-App/src/main/res/drawable/ic_bookmark_blue_2.xml
  Corona-Warn-App/src/main/res/drawable/ic_bookmark_blue_3.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: bug, ui, maintainers

#4394 Bump to next Version 2.14.1.0
  gradle.properties
Labels: maintainers

#4395 [Text] Adjust text "Find Testing Center"
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4392 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#4401 Revert "Fix: DCC parent color shade (EXPOSUREAPP-9950)"
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonColorShade.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_bookmark.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_bookmark_blue.xml
  Corona-Warn-App/src/main/res/drawable/ic_bookmark_blue.xml
  Corona-Warn-App/src/main/res/drawable/ic_bookmark_blue_1.xml
  Corona-Warn-App/src/main/res/drawable/ic_bookmark_blue_2.xml
  Corona-Warn-App/src/main/res/drawable/ic_bookmark_blue_3.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: maintainers

#4390 Text adaptation of iOS with Android
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4398 DCC Ticketing Consent I (EXPOSUREAPP-10471)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dccticketing/DccTicketingTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_dcc_ticketing.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/DccTicketingFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityModule.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_dcc_ticketing_consent_illustration.xml
  Corona-Warn-App/src/main/res/drawable/ic_dcc_ticketing_consent_illustration.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_consent_one.xml
  Corona-Warn-App/src/main/res/values-de/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: ui, maintainers, text change

#4391 UQS design changes and info screen (EXPOSUREAPP-10470)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/info/UqsInfoFragment.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_qr_code_info.xml
  Corona-Warn-App/src/main/res/drawable/ic_location_simple.xml
  Corona-Warn-App/src/main/res/drawable/ic_qr_code_info.xml
  Corona-Warn-App/src/main/res/drawable/ic_star.xml
  Corona-Warn-App/src/main/res/layout/fragment_qrcode_scanner.xml
  Corona-Warn-App/src/main/res/layout/fragment_uqs_info.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers, text change

#4397 SafetyNetExcetion leads to retry (EXPOSREAPP-10284)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/server/auth/LogUploadAuthorizer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/Analytics.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNet.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/SafetyNetException.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/AnalyticsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNetTest.kt
Labels: maintainers

#4404 Update privacy files (EXPOSUREAPP-10579)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers

#4396 Unit test certlogic French rule (DEV)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicEngineWrapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicTestData.kt
Labels: maintainers

#4389 Logic - Identity document of Validation Service(EXPOSUREAPP-10486)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/DccTicketingModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/DccTicketingCoreModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/check/DccTicketingServerCertificateCheckException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/check/DccTicketingServerCertificateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/server/DccTicketingApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/server/DccTicketingServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/server/DccTicketingServerException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/DccTicketingRequestService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/AccessTokenRequestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/FindJwkSetHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationDecoratorRequestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationServiceRequestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccJWK.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingServiceIdentityDocument.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingVerificationMethod.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/DccTicketingUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/res/values-de/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_ticketing_strings.xml
Labels: maintainers, prio

#4383 Cancel booster indication (EXPOSUREAPP-10232)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterCheckScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/DccBoosterRulesValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/covidcertificate/RecycledCertificatesProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/covidcertificate/RecycledCertificatesProviderTest.kt
Labels: maintainers

#4393 Request Service Identity Document of Validation Decorator (EXPOSUREAPP-10194)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingAccessToken.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingResultToken.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingTransactionContext.kt
  Corona-Warn-App/src/main/res/values/dcc_ticketing_strings.xml
Labels: maintainers

#4408 Techspec adjustments - Verify JWKS (EXPOSUREAPP-10194)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/DccTicketingRequestServiceHelpers.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationDecoratorRequestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationServiceRequestProcessor.kt
Labels: maintainers

#4406 [Logic] decorator service fixes(DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/filtering/DccTicketingJwkFilter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/server/DccTicketingServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/DccTicketingRequestService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/DccTicketingRequestServiceHelpers.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationDecoratorRequestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
Labels: maintainers

#4414 Improved ticket validation gson handling (EXPOSUREAPP-10194)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/DccTicketingCoreModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/server/DccTicketingServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/DccTicketingRequestService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/DccTicketingRequestServiceHelpers.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationDecoratorRequestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationServiceRequestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/GsonExtensions.kt
Labels: maintainers

#4413 Screenshot for QR code info fragment (EXPOSUREAPP-10645)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/qrcode/ui/QrCodeInfoFragmentTest.kt
Labels: maintainers

#4411 Fix privacy formatting (Dev)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers

#4412 Statistics Turkish formatting issue (EXPOSUREAPP-10330)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/OccupiedIntensiveCareCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/PersonsVaccinatedCompletelyCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/PersonsVaccinatedOnceCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/util/StatisticsNumberValueFormatter.kt
Labels: bug, maintainers

#4416 Bump to next Version 2.14.1.1
  gradle.properties
Labels: maintainers

#4399 Request Access Token (EXPOSUREAPP-10488)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccJWKExt.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingAccessTokenValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/JwtTokenConverter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/JwtTokenParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/server/AccessTokenRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/server/DccTicketingApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/server/DccTicketingServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/DccTicketingRequestService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/AccessTokenRequestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccJWK.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/common/JwtTokenValidatorKtTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/dccticketing/core/common/JwtTokenConverterTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccJWKKtTest.kt
Labels: maintainers

#4421 Dcc Ticketing skeleton part II (EXPOSUREAPP-10651)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/certificateselection/DccTicketingCertificateFilter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/DccTicketingSubmissionService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingAccessToken.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/failed/DccTicketingValidationFailedFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/open/DccTicketingValidationOpenFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/success/DccTicketingValidationSuccessFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_certificate_selection.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_consent_two.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_validation_failed.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_validation_open.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_validation_success.xml
  Corona-Warn-App/src/main/res/navigation/dcc_ticketing_nav_graph.xml
Labels: maintainers

#4425 Repeat flaky tests (DEV)
  .circleci/config.yml
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragmentTest.kt
Labels: maintainers

#4418 Avoid spaces and hyphens in pdf export filename (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/poster/CertificatePosterViewModel.kt
Labels: maintainers

#4424 DCC Ticketing: navigation to Consent I
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/dialog/DccTicketingDialogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/dialog/DccTicketingDialogHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/dialog/DccTicketingDialogType.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrcodeSharedViewModel.kt
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_consent_one.xml
  Corona-Warn-App/src/main/res/navigation/dcc_ticketing_nav_graph.xml
Labels: ui, maintainers

#4426 Verifying the Signature of a JWT with a Public Key and JSON Web Token library (EXPOSUREAPP-10647)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/assets/technical.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/SecurityProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccJWKVerification.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingJwtException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/server/DccTicketingServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/AccessTokenRequestProcessor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/common/DccJWKVerificationTest.kt
Labels: maintainers

#4429 Update strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4420 Request result token (EXPOSUREAPP-10626)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccJWKVerification.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/JwtTokenConverter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/server/DccTicketingApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/server/DccTicketingServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/server/ResultTokenRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ResultTokenRequestProcessor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/qrcode/DccTicketingQrCodeHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/server/ResultTokenRequestTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ResultTokenRequestProcessorTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/dccticketing/core/common/JwtTokenConverterTest.kt
Labels: maintainers

#4432 Certificate selection filtering (EXPOSUREAPP-10654)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccV1Extensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/certificateselection/DccTicketingCertificateFilter.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/dcc/DccQrCodeCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/certificateselection/DccTicketingCertificateFilterTest.kt
Labels: maintainers

#4433 [Logic] Request Access Token: Certificate Pinning (EXPOSUREAPP-10706)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccJWKVerification.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingAccessTokenValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingJwtException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/JwtTokenConverter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/JwtTokenParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/server/DccTicketingServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/AccessTokenRequestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ResultTokenRequestProcessor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/common/DccJWKVerificationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/common/JwtTokenParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/common/JwtTokenValidatorKtTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/processor/AccessTokenRequestProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ResultTokenRequestProcessorTest.kt
Labels: maintainers

#4427 Fix statistics cards accessibility announcements (EXPOSUREAPP-10650)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/AppliedVaccinationRatesCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/IncidenceAndHospitalizationCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/InfectionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/KeySubmissionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/LocalIncidenceAndHospitalizationCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/OccupiedIntensiveCareCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/PersonsVaccinatedCompletelyCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/PersonsVaccinatedOnceCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/SevenDayRValueCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterStatistics.kt
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_local_incidence_and_hospitalization_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_vaccinated_once_layout.xml
Labels: bug, maintainers

#4440 Update dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-de/dcc_ticketing_strings.xml
Labels: text change

#4430 Loading Event - Consent I (EXPOSUREAPP-10649)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingResultItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingResultToken.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingTransactionContext.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingValidationCondition.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/dialog/DccTicketingDialogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/dialog/DccTicketingDialogType.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/shared/DccTicketingSharedViewModel.kt
  Corona-Warn-App/src/main/res/navigation/dcc_ticketing_nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/ui/shared/DccTicketingSharedViewModelTest.kt
Labels: maintainers

#4441 Update strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4428 Encrypt and sign DCC (EXPOSUREAPP-10658)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/cryptography/AesCryptography.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/decoder/DccCoseDecoder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/security/DccTicketingCryptography.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/security/DccTicketingSecurityTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/cryptography/CheckInCryptography.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/encryption/aes/AesCryptography.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/encryption/rsa/RSACryptography.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/Sha256Signature.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/qrcode/TestCertificateQRCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/security/DccTicketingCryptographyTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/CheckInsTransformerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/OrganizerCheckInsTransformerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/cryptography/CheckInCryptographyTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/risk/calculation/CheckInWarningMatcherTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/risk/calculation/CheckInWarningMatcherTest2.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/risk/calculation/FindMatchesTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/encryption/AesCryptographyTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/encryption/rsa/RSACryptographyTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/security/Sha256SignatureTest.kt
Labels: maintainers

#4444 Protocol Buffer update for release 2.15.x at Mon Nov 29 09:52:10 UTC 2021
  Server-Protocol-Buffer/src/main/proto/internal/dgc/validation_service_allowlist.proto
Labels: maintainers

#4439 Ticket validation certificates selection screen (EXPOSUREAPP-10483)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestExtensions.kt
  Corona-Warn-App/src/debug/java/de/rki/coronawarnapp/ui/main/FakeEmptyActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/DccTicketingFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/certificateselection/DccTicketingCertificateFilter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/certificateselection/DccTicketingCertificatesFilterType.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionHelperFunctions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/cards/DccTicketingNoValidCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/cards/DccTicketingNoValidCertificateFaqCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/cards/DccTicketingNoValidCertificateHeaderCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/cards/DccTicketingRecoveryCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/cards/DccTicketingTestCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/cards/DccTicketingVaccinationCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/cards/DccTicketingValidCertificateHeaderCard.kt
  Corona-Warn-App/src/main/res/drawable/ic_warning_triangle.xml
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_no_valid_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_no_valid_certificate_faq_card.xml
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_no_valid_certificate_header_card.xml
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_recovery_card.xml
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_test_card.xml
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_vaccination_card.xml
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_valid_certificate_header_card.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_certificate_selection.xml
  Corona-Warn-App/src/main/res/navigation/dcc_ticketing_nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_ticketing_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/certificateselection/DccTicketingCertificateFilterTest.kt
Labels: maintainers, prio, text change

#4451 DCC Ticketing: Consent Two Screen (EXPOSUREAPP-10482)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CertificateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/DccTicketingFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/JwtTokenParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ResultTokenRequestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/cards/DccTicketingRecoveryCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/cards/DccTicketingTestCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/cards/DccTicketingVaccinationCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoViewModel.kt
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_recovery_card.xml
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_test_card.xml
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_vaccination_card.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_consent_two.xml
  Corona-Warn-App/src/main/res/navigation/dcc_ticketing_nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/common/JwtTokenParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/processor/AccessTokenRequestProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ResultTokenRequestProcessorTest.kt
Labels: ui, maintainers, text change

#4448 Ticket Validation logic tests (EXPOSUREAPP-10629, 10646)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/DccTicketingRequestService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/DccTicketingRequestServiceHelpers.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationServiceRequestProcessor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/DccTicketingRequestServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/processor/DccTicketingRequestServiceHelpersTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationDecoratorRequestProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/service/processor/ValidationServiceRequestProcessorTest.kt
Labels: maintainers

#4446 Update the allow dialog text / Loading spinner of UQS (EXPOSUREAPP-10773)
  Corona-Warn-App/src/main/res/layout/fragment_qrcode_scanner.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/dcc_ticketing_strings.xml
Labels: maintainers, text change

#4452 Provide allow list provider (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/allowlist/DccTicketingAllowListEntry.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingTransactionContext.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoViewModel.kt
Labels: maintainers

#4450 Ticketvalidation: UX Show Validation Result (EXPOSUREAPP-10196)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/success/DccTicketingTransactionContextData.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/success/DccTicketingValidationResultFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/DccTicketingModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/DccTicketingUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingResultItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/transaction/DccTicketingResultToken.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/DccTicketingUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/DccTicketingFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/DccTicketingValidationNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/DccTicketingValidationResultFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/DccTicketingValidationResultFragmentsBindingExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/DccTicketingValidationResultViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/ValidationResultAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/ValidationResultItemCreator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/failed/DccTicketingValidationFailedFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/items/BaseValidationResultVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/items/DescriptionVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/items/ResultRuleVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/items/TestingInfoVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/items/ValidationFaqVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/items/ValidationResultItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/open/DccTicketingValidationOpenFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/validationresult/success/DccTicketingValidationSuccessFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityModule.kt
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_validation_result_description_item.xml
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_validation_result_faq_item.xml
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_validation_result_rule_item.xml
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_validation_result_testing_info_item.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_validation_failed.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_validation_open.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_validation_result.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_validation_success.xml
  Corona-Warn-App/src/main/res/navigation/dcc_ticketing_nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/dcc_ticketing_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_ticketing_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/common/JwtTokenParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/submission/DccTicketingSubmissionHandlerTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/dccticketing/core/common/JwtTokenConverterTest.kt
Labels: maintainers, prio, text change

#4457 New release text change (EXPOSUREAPP-10166)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#4458 Remove leftover (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/service/DccTicketingSubmissionService.kt
Labels: maintainers
