Repository corona-warn-app/cwa-app-android, pull requests merged in 2021-08, with the labels that each got.

#3851 Fix installation date plural strings (EXPOSUREAPP-7278)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/periodlogged/PeriodLoggedBox.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers

#3846 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#3852 RAT negative deletion popup - wrong button color (EXPOSUREAPP-8306)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/testresults/negative/RATResultNegativeFragment.kt
Labels: bug, maintainers

#3835 Improve scrolling behavior in validation result screen (COMMUNITY)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/failed/DccValidationFailedFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/open/DccValidationOpenFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/passed/DccValidationPassedFragment.kt
  Corona-Warn-App/src/main/res/drawable-night/covid_certificate_validation_failed_header.xml
  Corona-Warn-App/src/main/res/drawable-night/covid_certificate_validation_gradient.xml
  Corona-Warn-App/src/main/res/drawable-night/covid_certificate_validation_open_header.xml
  Corona-Warn-App/src/main/res/drawable-night/covid_certificate_validation_passed_header.xml
  Corona-Warn-App/src/main/res/drawable/covid_certificate_validation_failed_header.xml
  Corona-Warn-App/src/main/res/drawable/covid_certificate_validation_gradient.xml
  Corona-Warn-App/src/main/res/drawable/covid_certificate_validation_open_header.xml
  Corona-Warn-App/src/main/res/drawable/covid_certificate_validation_passed_header.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_fragments.xml
Labels: community

#3848 Upgrade Kotlin/ AGP versions (DEV)
  Corona-Warn-App/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  lint.xml
Labels: enhancement, maintainers

#3855 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#3854 Adjust Info Screen to announce new Release-Features for 2.7 (EXPOSUREAPP-8333)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#3856 Fix Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#3843 TabBar badge for certificate state changes (EXPOSUREAPP-8377)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/repository/CertificateRepoContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/StoredRecoveryCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonCertificatesData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPersonTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
Labels: enhancement, maintainers, prio

#3857 Update privacy policy texts (EXPOSUREAPP-8334)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers, text change

#3858 Add missing word to homescreen risk card (EXPOSUREAPP-7482)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers, text change

#3859 Version Bump to 2.8.0.0
  gradle.properties
Labels: maintainers

#3860 Protocol Buffer update for release 2.8.x at Mon Aug 2 13:06:32 UTC 2021
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscDataParser.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscSignatureValidatorTest.kt
  Server-Protocol-Buffer/src/main/proto/internal/dgc/dsc_list.proto
  Server-Protocol-Buffer/src/main/proto/internal/pt/check_in.proto
  Server-Protocol-Buffer/src/main/proto/internal/pt/trace_warning.proto
  Server-Protocol-Buffer/src/main/proto/internal/submission_payload.proto
Labels: maintainers

#3862 Fix screenshot test (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
Labels: maintainers

#3864 Incomplete error message at the input field (EXPOSUREAPP-8787)
  Corona-Warn-App/src/main/res/layout/validation_start_fragment.xml
Labels: bug, maintainers

#3866 Skeletion PR - App Config (EXPOSUREAPP-8804)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/CWAConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CWAConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/CheckInsTransformer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/cryptography/CheckInCryptography.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/CWAConfigMapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/cryptography/CheckInCryptographyTest.kt
Labels: maintainers

#3867 Release-Feature announcement for 2.8 (EXPOSUREAPP-8712)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#3865 Protocol Buffer update for release 2.8.x at Tue Aug 3 08:26:54 UTC 2021
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscDataParser.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscSignatureValidatorTest.kt
  Server-Protocol-Buffer/src/main/proto/internal/dgc/dsc_list.proto
Labels: maintainers

#3869 Show HC_DSC_NO_MATCH error message (EXPOSUREAPP-8812)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/scan/DccQrCodeScanViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscSignatureValidator.kt
Labels: bug, maintainers, prio

#3872 Revert gradle version (DEV)
  Corona-Warn-App/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: maintainers

#3870 Add unit tests for both RSA and ECDSA (DEV)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscSignatureValidatorTest.kt
Labels: enhancement, maintainers

#3874 Update json schema (EXPOSUREAPP-8833)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/assets/jsonschema-dcc-ebb6720.json
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccJsonSchema.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccJsonSchemaTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccJsonSchemaValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/serialization/validation/JsonSchemaValidatorTest.kt
Labels: bug, maintainers, prio

#3868 ICAO name for certificates (EXPOSUREAPP-8686)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_recovery_certificate_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_test_certificate_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_attribute_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonCertificatesData.kt
Labels: maintainers, text change, ui

#3876 Bump to next Version 2.7.0.2 (DEV)
  gradle.properties
Labels: maintainers

#3877 Update Screenshot test (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
Labels: maintainers

#3880 UA Bugfix(EXPOSUREAPP-8552)
  Corona-Warn-App/src/main/assets/privacy_en.html
Labels: text change

#3879 UA Bugfix(EXPOSUREAPP-8552)
  Corona-Warn-App/src/main/assets/privacy_de.html
Labels: text change

#3882 Fix issue with text placeholders (EXPOSUREAPP-8870)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/periodlogged/PeriodLoggedBox.kt
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, prio, text change

#3885 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#3886 Fix CWA crashes and cannot be restarted after the attempt to receive a faked-vaccination certificate (EXPOSUREAPP-8876)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/scan/DccQrCodeScanViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
Labels: bug, maintainers, prio

#3884 AES encyption decryption (EXPOSUREAPP-8788, EXPOSUREAPP-8789)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/cryptography/AesCryptography.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/decoder/DccCoseDecoder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/cryptography/CheckInCryptography.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/cryptography/AesCryptographyTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/cryptography/CheckInCryptographyTest.kt
Labels: maintainers, prio

#3889 Fix: correct dcc state check worker (EXPOSUREAPP-8849)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckScheduler.kt
Labels: bug, maintainers

#3888 "Aktuell verwendetes Zertifikat" unnecessary line break (EXPOSUREAPP-8871)
  Corona-Warn-App/src/main/res/layout/recovery_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/test_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/vaccination_certificate_card.xml
Labels: bug, maintainers

#3871 Adjust Checkin submission (EXPOSUREAPP-8792)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/DefaultPlaybook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/Playbook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/CheckInsTransformer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/server/SubmissionServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/task/SubmissionTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/playbook/DefaultPlaybookTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/CheckInsTransformerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/server/SubmissionServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/task/SubmissionTaskTest.kt
Labels: maintainers

#3837 Spike: Import QR Code via Image (EXPOSUREAPP-8358)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/qrcode/ui/QrCodeTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/qrcode/ui/QrCodeTestFragmentModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/qrcode/ui/QrCodeTestFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainActivityTestModule.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_qrcode.xml
  Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/scan/DccQrCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/QRCodeFileParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/QrCodeFileParserModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/provider/QRCodeBitmapProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/provider/image/BaseImageUriResolver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/provider/image/ImageUriResolver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/provider/image/NewImageUriResolver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/provider/pdf/PdfUriResolver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
Labels: maintainers, do not merge

#3883 Download / Save Protected CheckIns (EXPOSUREAPP-8794)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/cryptography/CheckInCryptography.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/calculation/CheckInWarningMatcher.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/execution/PresenceTracingWarningTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/warning/PresenceTracingWarningModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/warning/WarningPackageId.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/warning/download/TraceWarningPackageDownloader.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/warning/download/TraceWarningPackageSyncTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/warning/download/server/DiscoveryResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/warning/download/server/TraceWarningApi.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/warning/download/server/TraceWarningEncryptedApiV2.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/warning/download/server/TraceWarningServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/warning/download/server/TraceWarningUnencryptedApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/warning/storage/TraceWarningPackage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/warning/storage/TraceWarningPackageContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/server/SubmissionServer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/cryptography/CheckInCryptographyTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/risk/calculation/CheckInWarningMatcherTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/risk/calculation/CheckInWarningMatcherTest2.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/risk/calculation/FindMatchesTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/risk/calculation/TraceTimeIntervalWarningValidityTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/risk/execution/PresenceTracingWarningTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/warning/download/server/TraceWarningServerTest.kt
Labels: maintainers, prio

#3897 Update default dsc list (DEV)
  Corona-Warn-App/src/main/assets/default_dsc_list.bin
  Corona-Warn-App/src/main/assets/default_dsc_list.sha256
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/signature/core/storage/DefaultDscSourceTest.kt
Labels: maintainers

#3898 Version Bump to 2.7.0.3 (DEV)
  gradle.properties
Labels: maintainers

#3899 Bump to next Version 2.7.0.4
  gradle.properties
Labels: maintainers

#3900 2.7 into 2.8 (DEV)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/qrcode/ui/QrCodeTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/qrcode/ui/QrCodeTestFragmentModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/qrcode/ui/QrCodeTestFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainActivityTestModule.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_qrcode.xml
  Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/main/assets/default_dsc_list.bin
  Corona-Warn-App/src/main/assets/default_dsc_list.sha256
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/scan/DccQrCodeScanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/scan/DccQrCodeScanViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/QRCodeFileParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/QrCodeFileParserModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/provider/QRCodeBitmapProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/provider/image/BaseImageUriResolver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/provider/image/ImageUriResolver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/provider/image/NewImageUriResolver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/provider/pdf/PdfUriResolver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/periodlogged/PeriodLoggedBox.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/signature/core/storage/DefaultDscSourceTest.kt
  gradle.properties
Labels: maintainers

#3901 Improve logs for 8113 (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
Labels: maintainers

#3891 Negative PCR-Test + Certificate: Symbol missing and wrong text (EXPOSUREAPP-8816)
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_negative.xml
Labels: bug, maintainers

#3904 Text Change (EXPOSUREAPP-8915)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#3906 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
Labels: maintainers, text change

#3902 Certificate expired adjustments (EXPOSUREAPP-8837)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
Labels: maintainers, prio

#3907 Version Bump to 2.7.1.0 (DEV)
  gradle.properties
Labels: maintainers

#3903 Navigation to test certificate from test result (EXPOSUREAPP-8688)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNegativeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/testresults/negative/RATResultNegativeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/testresults/negative/RATResultNegativeNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/testresults/negative/RATResultNegativeViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeViewModel.kt
  Corona-Warn-App/src/main/res/drawable/card_with_outline_ripple.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_antigen_test_result_negative.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_negative.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
Labels: ui, maintainers, prio

#3893 Certificates schema validation EU exceptions (EXPOSUREAPP-8687)
  Corona-Warn-App/src/main/assets/jsonschema-dcc-ebb6720.json
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccV1Parser.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/TestData.java
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/qrcode/TestCertificateQRCodeExtractorTest.kt
Labels: maintainers, prio

#3909 Fix version 2.8.0.0 (DEV)
  gradle.properties
Labels: maintainers

#3910 Follow-up: Installation date "today" not correct (EXPOSUREAPP-7482)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers, text change

#3912 Fix instrumentation test (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: bug, prio

#3911 Merge 2.7 into 2.8 (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: maintainers, author merge

#3913 Fix dev menu crash (DEV)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dsc/ui/DscTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dsc/ui/DscTestViewModel.kt
Labels: bug, maintainers, prio

#3918 UA Bugfix(EXPOSUREAPP-8977)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#3917 Warn info screen (EXPOSUREAPP-8947)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/TraceLocationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/TraceLocationWarnInfoFragment.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_bureaucracy_illustration.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_trace_location_warn_info_illustration.xml
  Corona-Warn-App/src/main/res/drawable/ic_bureaucracy_illustration.xml
  Corona-Warn-App/src/main/res/drawable/ic_trace_location_warn_info_illustration.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_warn_info_fragment.xml
  Corona-Warn-App/src/main/res/menu/menu_trace_location_organizer_list.xml
  Corona-Warn-App/src/main/res/navigation/trace_location_organizer_nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
Labels: ui, maintainers, text change

#3919 Wrong FAQ link for duplicate vaccination certificate (EXPOSUREAPP-8929)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/scan/DccQrCodeScanFragment.kt
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: bug, maintainers, text change

#3923 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#3920 Test result: wrong header title (EXPOSUREAPP-8823)
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_invalid.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_negative.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_pending.xml
Labels: bug, maintainers

#3929 Protocol Buffer update for release 2.9.x at Mon Aug 16 16:57:35 UTC 2021
  Server-Protocol-Buffer/src/main/proto/internal/submission_payload.proto
Labels: maintainers

#3931 Onbehalf Warning - Api Interface (EXPOSUREAPP-8955)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/PresenceTracingModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/organizer/submission/OrganizerSubmissionModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/organizer/submission/server/OrganizerSubmissionApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/server/SubmissionApiV1.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/organizer/submission/server/OrganizerSubmissionApiV1Test.kt
Labels: maintainers

#3930 UI -List of events: In Vertretung warnen (EXPOSUREAPP-8948)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/PresenceTracingUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/TraceLocationWarnInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/list/TraceLocationSelectionAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/list/TraceLocationSelectionEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/list/TraceLocationSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/list/TraceLocationSelectionFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/list/TraceLocationSelectionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/list/items/TraceLocationItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/list/items/TraceLocationSubHeaderItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/list/items/TraceLocationSubHeaderVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/list/items/TraceLocationVH.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_illustration_no_events.xml
  Corona-Warn-App/src/main/res/drawable/ic_illustration_no_events.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_trace_locations_warn_item.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_trace_locations_warn_list_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_trace_locations_warn_subheader.xml
  Corona-Warn-App/src/main/res/navigation/trace_location_organizer_nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
Labels: maintainers

#3933 V2.8.0.1
  gradle.properties
Labels: maintainers

#3934 Bump to next Version 2.8.0.2
  gradle.properties
Labels: maintainers

#3936 Follow-up: Installation date "today" not correct (EXPOSUREAPP-7482)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers

#3935 Automatically refresh certificates after DSC list update (EXPOSUREAPP-8886)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepositoryTest.kt
Labels: bug, maintainers, prio

#3921 Implement submission (EXPOSUREAPP-8954)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/OrganizerPlaybook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/CheckInsTransformer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/OrganizerCheckInsTransformer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/organizer/submission/OrganizerSubmissionException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/organizer/submission/OrganizerSubmissionPayload.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/organizer/submission/OrganizerSubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/organizer/submission/server/OrganizerSubmissionServer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/OrganizerCheckInsTransformerTest.kt
Labels: maintainers

#3937 Risk calculation with result CALCULATION_FAILED (EXPOSUREAPP-9020)
  Corona-Warn-App/proguard-rules.pro
Labels: bug, maintainers, prio

#3938 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, prio

#3928 First vaccination dose shows up as complete for recovered people (EXPOSUREAPP-8896)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPerson.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPersonTest.kt
Labels: maintainers

#3940 Add blog link in statistics info screen (EXPOSUREAPP-8978)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/StatisticsExplanationFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_statistics_explanation.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, prio

#3946 UA Bugfix(EXPOSUREAPP-9023)
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#3944 Remember Scroll Position (EXPOSUREAPP-8799)
  Corona-Warn-App/src/main/res/layout/validation_start_fragment.xml
Labels: ui, maintainers

#3939 Duration selection screen (EXPOSUREAPP-8949)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/PresenceTracingUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/duration/TraceLocationWarnDurationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/duration/TraceLocationWarnDurationFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/duration/TraceLocationWarnDurationViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/list/TraceLocationSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeAndDateExtensions.kt
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_warn_duration_fragment.xml
  Corona-Warn-App/src/main/res/navigation/trace_location_organizer_nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
Labels: ui, maintainers, text change

#3941 Bump to next Version 2.8.0.3
  gradle.properties
Labels: maintainers

#3952 OnBehalfWarning - Error Handling (EXPOSUREAPP-8956)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/OrganizerPlaybook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/organizer/submission/OrganizerSubmissionException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/organizer/submission/server/OrganizerSubmissionApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/organizer/submission/server/OrganizerSubmissionServer.kt
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/organizer/submission/server/OrganizerSubmissionApiV1Test.kt
Labels: maintainers

#3951 Consistent toolbar + adjust info screen Navigation (EXPOSUREAPP-8958) Part 1
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_trace_locations_list_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_trace_locations_warn_list_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_warn_duration_fragment.xml
  Corona-Warn-App/src/main/res/navigation/trace_location_organizer_nav_graph.xml
Labels: enhancement, maintainers

#3953 Update Event Registration Onboarding Screen (EXPOSUREAPP-9087)
  Corona-Warn-App/src/main/res/drawable-night/ic_two_people_icon.xml
  Corona-Warn-App/src/main/res/drawable/ic_two_people_icon.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_qr_code_info_fragment.xml
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
Labels: ui, maintainers, text change

#3955 OnBehalfWarning - Thank You Screen (EXPOSUREAPP-8950)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/PresenceTracingUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/thanks/TraceLocationOrganizerThanksFragment.kt
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_thanks_fragment.xml
  Corona-Warn-App/src/main/res/navigation/trace_location_organizer_nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
Labels: maintainers, text change

#3950 Bump to next Version 2.8.0.4
  gradle.properties
Labels: maintainers

#3945 Submission - tests (EXPOSUREAPP-9046)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/presencetracing/ui/PresenceTracingTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/presencetracing/ui/PresenceTracingTestViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_presence_tracing.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/OrganizerPlaybook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/organizer/submission/OrganizerSubmissionPayload.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/organizer/submission/OrganizerSubmissionRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/playbook/OrganizerPlaybookTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/organizer/submission/OrganizerSubmissionPayloadTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/organizer/submission/OrganizerSubmissionRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/organizer/submission/server/OrganizerSubmissionServerTest.kt
Labels: maintainers

#3954 Create screenshot for different certificate types (EXPOSUREAPP-8943)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
Labels: maintainers

#3956 Add QR code scanner fragment (EXPOSUREAPP-8952)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/PresenceTracingUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/list/TraceLocationSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/res/navigation/trace_location_attendee_nav_graph.xml
  Corona-Warn-App/src/main/res/navigation/trace_location_organizer_nav_graph.xml
Labels: maintainers

#3947 Update Layout in Validation Result Screen (EXPOSUREAPP-8802)
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_passed_fragment.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_faq_item.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_fragments.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_header_item.xml
Labels: ui, maintainers

#3959 Adding Text(EXPOSUREAPP-8928)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#3960 OnBehalfWarning - test improvements (DEV)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/organizer/submission/server/OrganizerSubmissionServerTest.kt
Labels: maintainers

#3958 Small UI Refactoring (DEV)
  Corona-Warn-App/src/main/res/layout/bugreporting_debuglog_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_locations_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_persons_fragment.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_delta_ppa.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_tracing.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_reset.xml
Labels: ui, maintainers

#3961 Remove duplicate text (EXPOSUREAPP-8816)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#3965 Adjust Info Screen to announce new Release-Features for 2.9 (EXPOSUREAPP-8902)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#3966 Host warning tan (EXPOSUREAPP-8953)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/PresenceTracingUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/TraceLocationWarnDuration.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/duration/TraceLocationWarnDurationEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/duration/TraceLocationWarnDurationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/duration/TraceLocationWarnDurationViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/tan/TraceLocationWarnTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/tan/TraceLocationWarnTanModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/tan/TraceLocationWarnTanViewModel.kt
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_warn_tan_fragment.xml
  Corona-Warn-App/src/main/res/navigation/trace_location_organizer_nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
Labels: ui, maintainers, text change

#3967 Update Test Menu (DEV)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dsc/ui/DscTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dsc/ui/DscTestViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_dsc.xml
Labels: maintainers

#3971 Implement and test navigation (EXPOSUREAPP-8958) Part 2
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/thanks/TraceLocationOrganizerThanksFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/tan/TraceLocationWarnTanFragment.kt
  Corona-Warn-App/src/main/res/navigation/trace_location_organizer_nav_graph.xml
Labels: maintainers

#3969 Translation Delivery
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#3970 Clear RATProfileSettings correctly including onboarding status (#3964)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/antigen/profile/RATProfileSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
Labels: community

#3973 Booster vaccination UI (EXPOSUREAPP-9041)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationCertificate.kt
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers, text change

#3974 Screenshots (EXPOSUREAPP-8960)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/eventregistration/organizer/QrCodeDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/eventregistration/organizer/TraceLocationCreateFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/eventregistration/organizer/TraceLocationData.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/eventregistration/organizer/TraceLocationsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/presencetracing/organizer/thanks/TraceLocationOrganizerThanksFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/TraceLocationWarnInfoFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/duration/TraceLocationWarnDurationFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/list/TraceLocationSelectionFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/tan/TraceLocationWarnTanFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
Labels: maintainers

#3978 Adapt privacy notice for Release 2.9 (EXPOSUREAPP-8901)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers

#3979 UA Bugfix Neue Funktionen 2.9
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: text change

#3980 Add fake header (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/organizer/submission/server/OrganizerSubmissionApiV1.kt
Labels: bug, maintainers

#3981 Don't show infobox for incomplete vaccination if Booster vaccination certificate is available (EXPOSUREAPP-9176)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPerson.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPersonTest.kt
Labels: maintainers

#3993 Change date of birth entry from calendar to input view (EXPOSUREAPP-9128) (COMMUNITY)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateFragment.kt
Labels: bug, mirrored-to-jira, community

#3977 Proposal: Perform update check against `currentConfig`
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/update/UpdateChecker.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/update/UpdateCheckerTest.kt
Labels: enhancement, community

#3997 Correct to "Mustermann, Max" in certificate screenshots (EXPOSUREAPP-9233) (COMMUNITY)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
Labels: bug, community

#3995 Add missing line in negative PCR test fragment (EXPOSUREAPP-8816)
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_negative.xml
Labels: bug, maintainers

#3996 Fix Dcc censoring (EXPOSUREAPP-9075)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/dcc/DccQrCodeCensor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/dcc/DccQrCodeCensorTest.kt
Labels: bug

#3989 PDF export dialog and info screen (EXPOSUREAPP-9187)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/CertificateExportErrorDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/CertificateExportHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/CertificatePdfExportInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_pdf_icon.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_pdf_info_illustration.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_pdf_lock.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_pdf_phone.xml
  Corona-Warn-App/src/main/res/drawable/ic_pdf_icon.xml
  Corona-Warn-App/src/main/res/drawable/ic_pdf_info_illustration.xml
  Corona-Warn-App/src/main/res/drawable/ic_pdf_lock.xml
  Corona-Warn-App/src/main/res/drawable/ic_pdf_phone.xml
  Corona-Warn-App/src/main/res/layout/certificate_pdf_export_info_fragment.xml
  Corona-Warn-App/src/main/res/menu/menu_covid_certificate_detail.xml
  Corona-Warn-App/src/main/res/menu/menu_recovery_certificate_details.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/green_certificate_strings.xml
Labels: ui, maintainers, text change

#4002 Remove term "Auffrischimpfung" from booster certificate (EXPOSUREAPP-9244)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPerson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationCertificate.kt
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPersonTest.kt
Labels: maintainers, prio

#4003 Updated priority rules (EXPOSUREAPP-9244)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: maintainers, prio

#4004 Bump to next Version 2.9.0.2
  gradle.properties
Labels: maintainers
