Repository corona-warn-app/cwa-app-android, pull requests merged in 2021-02, with the labels that each got.

#2228 New release info screen navigation change (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/release/NewReleaseInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/release/NewReleaseInfoFragmentNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/release/NewReleaseInfoFragmentViewModel.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
Labels: enhancement, maintainers

#2245 Fix statistics FAQ link (EXPOSUREAPP-4900)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers, prio, text change

#2246 Contact export says "14 days" instead of "15 days" (EXPOSUREAPP-4911)
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
Labels: maintainers, prio, text change

#2254 Update ppa main to include new protos and stuff from 1.13.x
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/release/NewReleaseInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/release/NewReleaseInfoFragmentNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/release/NewReleaseInfoFragmentViewModel.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Server-Protocol-Buffer/src/main/proto/internal/ppdd/ppa_data.proto
  Server-Protocol-Buffer/src/main/proto/internal/ppdd/ppa_data_request_android.proto
  Server-Protocol-Buffer/src/main/proto/internal/ppdd/ppa_data_request_ios.proto
  Server-Protocol-Buffer/src/main/proto/internal/v2/app_config_android.proto
  Server-Protocol-Buffer/src/main/proto/internal/v2/app_config_ios.proto
  Server-Protocol-Buffer/src/main/proto/internal/v2/ppdd_ppa_parameters.proto
Labels: maintainers

#2251 Change escaping of percentage sign (DEV)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#2250 FAQ link with advice how to behave when getting tested (EXPOSUREAPP-4640)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/behavior/BehaviorInfoRow.kt
  Corona-Warn-App/src/main/res/drawable/ic_faq_information.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_item_behavior_increased_view.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change, ui

#2233 Update new release info (EXPOSUREAPP-4731)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/release/NewReleaseInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/release/NewReleaseInfoFragmentNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/release/NewReleaseInfoFragmentViewModel.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_new_release_info.xml
  Corona-Warn-App/src/main/res/drawable/ic_new_release_info.xml
  Corona-Warn-App/src/main/res/layout/new_release_info_item.xml
  Corona-Warn-App/src/main/res/layout/new_release_info_screen_fragment.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/release/NewReleaseInfoViewModelTest.kt
Labels: maintainers, text change

#2231 Risk tracing stopped correct info (EXPOSUREAPP-4414)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProviderTest.kt
Labels: bug, maintainers, prio

#2236 Adjust high risk card (EXPOSUREAPP-4835)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/states/TracingState.kt
  Corona-Warn-App/src/main/res/layout/tracing_content_increased_view.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/tracing/states/IncreasedRiskTest.kt
Labels: maintainers, text change

#2263 Change escaping of percentage sign (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/StatisticsExplanationFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_statistics_explanation.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, prio, text change

#2230 End of life behaviour UI (EXPOSUREAPP-4641)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/SubmissionState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/SubmissionStateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/items/ReenableRiskCard.kt
  Corona-Warn-App/src/main/res/layout/home_reenable_risk_card_layout.xml
  Corona-Warn-App/src/main/res/layout/include_submission_done_content.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/tracing/ui/homecards/SubmissionStateProviderTest.kt
Labels: author merge, maintainers

#2262 Pull firebase results anyways (Dev)
  .circleci/config.yml
Labels: maintainers, prio

#2238 Adjust low risk card (EXPOSUREAPP-4836)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeData.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/TracingData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/states/TracingState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/states/TracingStateProvider.kt
  Corona-Warn-App/src/main/res/layout/tracing_content_low_view.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2257 Delta-Onboarding interoperability info not shown (EXPOSUREAPP-4910)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
Labels: bug, maintainers, prio

#2249 Fix class cast exception on pending tests (EXPOSUREAPP-4909)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/NetworkRequestWrapper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/testresult/pending/SubmissionTestResultPendingViewModelTest.kt
Labels: bug, maintainers, prio

#2267 Fix scrolling issue in InformationFragment (EXPOSUREAPP-4939)
  Corona-Warn-App/src/main/res/layout/fragment_information.xml
Labels: bug, maintainers

#2256 Accessibility: Statistics Blocks Enhancements (EXPOSUREAPP-4845)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/IncidenceCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/InfectionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/KeySubmissionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/SevenDayRValueCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/util/AccessibilityHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/StringBuilderExtension.kt
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_incidence_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_infections_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_keysubmissions_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_sevendayrvalue_layout.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: accessibility, maintainers, text change

#2270 PPA UserInput Selection Screens (EXPOSUREAPP-4752)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/playground/ui/PlaygroundFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/playground/ui/PlaygroundModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/playground/ui/PlaygroundViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainActivityTestModule.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_playground.xml
  Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/main/assets/ppdd-ppa-administrative-unit-set.json
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/AnalyticsSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/common/Districts.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/common/PpaDataExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/ui/AnalyticsUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/ui/input/AnalyticsUserInputFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/ui/input/AnalyticsUserInputViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/ui/input/UserInfoItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/ui/input/UserInfoItemAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityModule.kt
  Corona-Warn-App/src/main/res/color/radiobutton_accented.xml
  Corona-Warn-App/src/main/res/layout/analytics_ppa_userinfo_input_adapter_item.xml
  Corona-Warn-App/src/main/res/layout/analytics_ppa_userinfo_input_fragment.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/common/DistrictsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/common/PpaDataExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/ui/AnalyticsSettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/ui/input/AnalyticsUserInputViewModelTest.kt
Labels: maintainers

#2235 Add Tab bar (EXPOSUREAPP-4639)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryDayFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryOnboardingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/statistics/StatisticsCardsTest.kt
  Corona-Warn-App/src/main/AndroidManifest.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ContactDiaryRootModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/ContactDiaryActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/ContactDiarySettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/onboarding/ContactDiaryOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/ActivityBinder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/UIExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/items/DiaryCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/FragmentExtensions.kt
  Corona-Warn-App/src/main/res/color/nav_item_color.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_diary.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_home.xml
  Corona-Warn-App/src/main/res/layout/activity_main.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_activity.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_fragment.xml
  Corona-Warn-App/src/main/res/menu/menu_bottom_nav.xml
  Corona-Warn-App/src/main/res/navigation/contact_diary_nav_graph.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
Labels: author merge, maintainers, text change

#2276 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers, text change

#2277 Update default strings (DEV)
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2278 Bump to next Version 1.12.0.5 (DEV)
  gradle.properties
Labels: maintainers

#2271 Survey Event UI Base (EXPOSUREAPP-4807, 4808 )
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/DataDonationModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/SurveyModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/Surveys.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/survey/UserSurveyBox.kt
  Corona-Warn-App/src/main/res/drawable/ic_illustration_datenspende.xml
  Corona-Warn-App/src/main/res/drawable/ic_tracing_survey_icon.xml
  Corona-Warn-App/src/main/res/layout/survey_consent_fragment.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_access_survey_card.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#2247 Adjust Screenshots tests to reflect latest UI changes(EXPOSUREAPP-4878)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryDayFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryEditLocationsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryEditPersonsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryInformationPrivacyFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryOnboardingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/MainActivityTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaInteroperabilityFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTestFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/statistics/Statistics.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/statistics/StatisticsCardsTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionDispatcherFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomCalendarFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomIntroFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/TracingDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/ScreenShotter.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestAppComponent.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestExtensions.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/ViewActions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityModule.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/tracing/states/IncreasedRiskTest.kt
  Gemfile.lock
Labels: author merge, maintainers

#2287 Endpoint URL for data donation (DEV)
  prod_environments.json
Labels: maintainers

#2232 Repository for One Time Passwords(EXPOSUREAPP-4857)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/OneTimePassword.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/storage/OTPRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/SurveySettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/OneTimePasswordTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/storage/OTPRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/survey/SurveySettingsTest.kt
Labels: maintainers, prio

#2288 Merge release/1.12.x into release/1.13.x (DEV)
  .circleci/config.yml
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/MainActivityTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/StatisticsExplanationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/IncidenceCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/InfectionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/KeySubmissionsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/SevenDayRValueCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/util/AccessibilityHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/NetworkRequestWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/StringBuilderExtension.kt
  Corona-Warn-App/src/main/res/layout/fragment_statistics_explanation.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_incidence_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_infections_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_keysubmissions_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_sevendayrvalue_layout.xml
  Corona-Warn-App/src/main/res/values-bg/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-en/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/testresult/pending/SubmissionTestResultPendingViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProviderTest.kt
Labels: author merge, maintainers

#2242 SafetyNet Implementation (EXPOSUREAPP-4754)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragmentModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainActivityTestModule.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_datadonation.xml
  Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/ConfigData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/internal/AppConfigSource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/internal/ConfigDataContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/AttestationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNet.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/SafetyNetClientWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/SafetyNetException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/main/CWASettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AndroidModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/gplay/GoogleApiVersion.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/SecurityHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/SecurityModule.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/internal/AppConfigSourceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/safetynet/AttestationContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNetTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/safetynet/SafetyNetClientWrapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/CWASettingsTest.kt
  Corona-Warn-App/src/test/java/testhelpers/gms/MockGMSTask.kt
Labels: enhancement, maintainers, prio

#2283 Nicer error messages if a value is missing in an *_environments.json (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentSetup.kt
Labels: maintainers

#2285 Fix contact journal text (EXPOSUREAPP-4982)
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
Labels: maintainers, text change

#2289 Accessibility: Image not announces in Submission Consent Screen (EXPOSUREAPP-4098)
  Corona-Warn-App/src/main/res/layout/fragment_submission_consent.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: accessibility, maintainers, text change

#2255 Collect Exposure Risk Metadata (EXPOSUREAPP-4921)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/AnalyticsModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/AnalyticsSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/DonorModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposureriskmetadata/ExposureRiskMetadataDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposurewindows/NewExposureWindowsDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/KeySubmissionStateDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/registeredtest/RegisteredTestDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/risklevelhistory/RiskLevelHistoryChangesDonor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/ui/AnalyticsSettingsTest.kt
Labels: backend, maintainers

#2294 Accessibility: Text in Symptoms not in explore by touch sequence (EXPOSUREAPP-4102)
  Corona-Warn-App/src/main/res/layout/fragment_submission_symptom_intro.xml
Labels: accessibility, maintainers

#2293 Update FAQ Link - exclude dot (EXPOSUREAPP-4900)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#2298 Clean up environment types (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentSetup.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/environment/EnvironmentSetupTest.kt
Labels: maintainers

#2264 Scrolling issues with back navigation from Statistics Info screen to Homescreen (EXPOSUREAPP-4771)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/StatisticsExplanationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/SubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/behavior/BehaviorInfoRow.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/lists/modular/ModularAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/lists/modular/mods/SavedStateMod.kt
  Corona-Warn-App/src/main/res/drawable/ic_faq_information.xml
  Corona-Warn-App/src/main/res/drawable/ic_illustration_datenspende.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_diary.xml
  Corona-Warn-App/src/main/res/drawable/ic_nav_home.xml
  Corona-Warn-App/src/main/res/drawable/ic_tracing_survey_icon.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/SubmissionRepositoryTest.kt
Labels: maintainers

#2290 Adjust automated screenshots - add low risk card without encounters (EXPOSUREAPP-4837)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/MainActivityTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeData.kt
Labels: maintainers

#2286 Fix autoLink being too aggressive on some devices (closes #2275) (EXPOSUREAPP-4992)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/Views.kt
  Corona-Warn-App/src/main/res/layout/fragment_information_contact.xml
  Corona-Warn-App/src/main/res/layout/fragment_information_legal.xml
  Corona-Warn-App/src/main/res/layout/include_information_details.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
Labels: community, mirrored-to-jira

#2281 Accessibility: Contact Journal Edit Screens not announced (EXPOSUREAPP-4456)
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_locations_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_persons_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_onboarding_fragment.xml
Labels: accessibility, maintainers

#2269 PPA User Input Strings Only (EXPOSUREAPP-4752)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2296 Appconfig survey handling (EXPOSUREAPP-4847)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/SurveyConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/SurveyConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/Surveys.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/SurveyConfigMapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProviderTest.kt
Labels: maintainers

#2308 Fix SafetyNet nonce comparison (DEV)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_datadonation.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNet.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/SafetyNetClientWrapper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/safetynet/SafetyNetClientWrapperTest.kt
Labels: bug, maintainers

#2300 Implement Donor for User Metadata (EXPOSUREAPP-4823)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/DonorModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposureriskmetadata/ExposureRiskMetadataDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposurewindows/NewExposureWindowsDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/KeySubmissionStateDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/registeredtest/RegisteredTestDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/usermetadata/UserMetadataDonor.kt
Labels: backend, enhancement, maintainers, prio

#2303 Remove redundant district prefixes (EXPOSUREAPP-4815)
  Corona-Warn-App/src/main/assets/ppdd-ppa-administrative-unit-set.json
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/common/DistrictsTest.kt
Labels: enhancement, maintainers

#2309 Missing sentence in description of contact journal (EXPOSUREAPP-4941)
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
Labels: maintainers, text change

#2305 Change statistics overview header to 'bundesweite' Statistiken (EXPOSUREAPP-4975)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers, text change

#2306 Show normal behavior box when tracing disabled (EXPOSUREAPP-4768)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProvider.kt
  Corona-Warn-App/src/main/res/layout/tracing_details_fragment_layout.xml
Labels: bug, maintainers

#2253 End-of-Life behaviour (EXPOSUREAPP-4641)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/MainActivityTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeData.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/BackgroundNoise.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/DefaultPlaybook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/Playbook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/LocalData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/SubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/server/SubmissionServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/task/SubmissionTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/SubmissionState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/ui/homecards/SubmissionStateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/items/ReenableRiskCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/BackgroundWorkScheduler.kt
  Corona-Warn-App/src/main/res/layout/home_reenable_risk_card_layout.xml
  Corona-Warn-App/src/main/res/layout/include_submission_done_content.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/playbook/DefaultPlaybookTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskLevelTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/storage/SubmissionRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/server/SubmissionServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/task/SubmissionTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/tracing/ui/homecards/SubmissionStateProviderTest.kt
Labels: enhancement, maintainers, prio, text change

#2297 Fix exposure logging progress circle inconsistencies. (EXPOSUREAPP-1835)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/TracingData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/states/TracingState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/periodlogged/PeriodLoggedBox.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/settings/SettingsTracingFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/CircleProgress.kt
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
  Corona-Warn-App/src/main/res/layout/include_risk_details_period_logged_progress.xml
  Corona-Warn-App/src/main/res/layout/include_setting_tracing_period_logged.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_increased_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_low_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_item_periodlogged_view.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers

#2260 Fix: First and last item of statistic cards was not reachable on some devices (EXPOSUREAPP-4945) (closes #2259)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ContextExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/ContextExtensionsTests.kt
Labels: community, mirrored-to-jira

#2299 PPA onboarding screen (EXPOSUREAPP-4815)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingAnalyticsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/ui/PpaMoreInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingAnalyticsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingAnalyticsModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingAnalyticsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaAnalyticsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaAnalyticsModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsViewModel.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_illustration_ppa.xml
  Corona-Warn-App/src/main/res/drawable/ic_illustration_ppa.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_delta_ppa.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_ppa.xml
  Corona-Warn-App/src/main/res/layout/fragment_ppa_more_info.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_fragment_layout.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph_onboarding.xml
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: do not merge, enhancement, maintainers, prio, text change

#2312 Survey Consent Details Screen (EXPOSUREAPP-5055)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentDetailFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentViewModel.kt
  Corona-Warn-App/src/main/res/layout/survey_consent_detail_fragment.xml
  Corona-Warn-App/src/main/res/layout/survey_consent_fragment.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, prio, text change

#2319 Privacy-Preserving Analytics: Strings (EXPOSUREAPP-4752)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, prio, text change

#2318 Change Risiko-Ermittlung to -Überprüfung in dialog (DEV)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#2316 Adjust device time test setting (DEV)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/appconfig/ui/AppConfigTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/appconfig/ui/AppConfigTestFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_appconfig.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CWAConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/sources/remote/AppConfigServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/sources/remote/RemoteAppConfigSource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/TestSettings.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/CWAConfigMapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/sources/remote/AppConfigServerTest.kt
Labels: author merge, maintainers, prio

#2279 Submission process swapped dialogs (EXPOSUREAPP-4899)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/resultavailable/SubmissionTestResultAvailableFragment.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers, text change

#2321 Bump to next Version 1.13.0.2 (DEV)
  gradle.properties
Labels: maintainers

#2310 Survey - Error state handling, progress logic, ui, etc. (EXPOSUREAPP-4848, 4854)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/SurveyException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/Surveys.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentBlockingProgressDialogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentViewModel.kt
  Corona-Warn-App/src/main/res/layout/survey_consent_blocking_progress_dialog.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, prio, text change

#2315 Privacy Preserving Analytics Settings (EXPOSUREAPP-4816)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingFragmentsModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/analytics/SettingsPrivacyPreservingAnalyticsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/analytics/SettingsPrivacyPreservingAnalyticsFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/analytics/SettingsPrivacyPreservingAnalyticsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsPrivacyPreservingAnalyticsState.kt
  Corona-Warn-App/src/main/res/drawable/ic_settings_privacy_preserving_analytics_disabled.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_privacy_preserving_analytics_enabled.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_privacy_preserving_analytics.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: enhancement, maintainers, ui

#2320 Adapt 'fake correct device time' feature (DEV)
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_appconfig.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/sources/remote/AppConfigServer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/sources/remote/AppConfigServerTest.kt
Labels: maintainers

#2317 Fix coroutine scope canceling log spam (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/device/BackgroundModeStatus.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/flow/HotDataFlow.kt
Labels: maintainers

#2304 Change text style (EXPOSUREAPP-4489)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/settings/SettingsTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/interoperability/InteroperabilityConfigurationFragment.kt
  Corona-Warn-App/src/main/res/color/row.xml
  Corona-Warn-App/src/main/res/drawable/row.xml
  Corona-Warn-App/src/main/res/layout/fragment_interoperability_configuration.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
  Corona-Warn-App/src/main/res/layout/include_header.xml
  Corona-Warn-App/src/main/res/layout/include_information_details.xml
  Corona-Warn-App/src/main/res/layout/include_interoperability.xml
  Corona-Warn-App/src/main/res/layout/include_settings_switch_row.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: bug, maintainers

#2314 Ignore latest risk calculation status when it is turned off (EXPOSUREAPP-4414)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProvider.kt
Labels: bug, maintainers

#2327 Contact journal extension skeletons (EXPOSUREAPP-5105)
  Corona-Warn-App/schemas/de.rki.coronawarnapp.contactdiary.storage.ContactDiaryDatabase/2.json
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/ContactDiaryLocation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/ContactDiaryLocationVisit.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/ContactDiaryPerson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/ContactDiaryPersonEncounter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/DefaultContactDiaryLocation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/DefaultContactDiaryLocationVisit.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/DefaultContactDiaryPerson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/DefaultContactDiaryPersonEncounter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/ContactDiaryDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/entity/ContactDiaryLocationEntity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/entity/ContactDiaryPersonEntity.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditLocationsViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditPersonsViewModelTest.kt
Labels: enhancement, maintainers

#2329 Moving legal strings to strings (DEV)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2322 Privacy-Preserving Analytics Settings Polishing (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/analytics/SettingsPrivacyPreservingAnalyticsFragment.kt
  Corona-Warn-App/src/main/res/drawable/ic_settings_privacy_preserving_analytics_disabled.xml
  Corona-Warn-App/src/main/res/drawable/ic_settings_privacy_preserving_analytics_enabled.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_privacy_preserving_analytics.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
Labels: maintainers, ui

#2324 Persist result from otp authorization server (EXPOSUREAPP-4637)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/OTPAuthorizationResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/storage/OTPRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/SurveySettings.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/storage/OTPRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/survey/SurveySettingsTest.kt
Labels: maintainers, prio

#2307 Provide survey URL (EXPOSUREAPP-4858)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/SurveyUrlProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/Surveys.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/survey/SurveyUrlProviderTest.kt
Labels: enhancement, maintainers, prio

#2333 Change onboarding age ranges (DEV)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, prio, text change

#2332 Data privacy update (EXPOSUREAPP-4756)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: enhancement, maintainers, text change

#2331 Make whole high risk survey card clickable (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/survey/UserSurveyBox.kt
Labels: maintainers

#2313 Show easy language link for German only (EXPOSUREAPP-4986)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragmentViewModel.kt
  Corona-Warn-App/src/main/res/layout/fragment_onboarding.xml
  Corona-Warn-App/src/main/res/layout/include_onboarding.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/onboarding/EasyLanguageLinkTest.kt
Labels: bug, maintainers

#2326 Missing tracing duration on low risk detail screen (EXPOSUREAPP-5092)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/states/TracingState.kt
  Corona-Warn-App/src/main/res/layout/tracing_content_low_view.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/tracing/states/LowRiskTest.kt
Labels: bug, maintainers

#2334 Missing EU Flag (EXPOSUREAPP-4208)
  Corona-Warn-App/src/main/res/drawable-night/ic_submission_illustration_other_warning.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_illustration_other_warning.xml
Labels: bug, maintainers, ui

#2339 Adjust text style in survey UI (DEV)
  Corona-Warn-App/src/main/res/layout/survey_consent_detail_fragment.xml
  Corona-Warn-App/src/main/res/layout/survey_consent_fragment.xml
Labels: bug, maintainers

#2337 Typo: donate to share (EXPOSUREAPP-4756)
  Corona-Warn-App/src/main/assets/privacy_en.html
Labels: maintainers, text change

#2340 Update legal survey strings (DEV)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: maintainers, text change

#2342 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-en/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers, text change

#2311 Survey OTP Authorization Backend Integration (EXPOSUREAPP-4809)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/SurveyModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/server/SurveyApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/server/SurveyServer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/survey/server/SurveyApiV1Test.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/survey/server/SurveyServerTest.kt
Labels: author merge, enhancement, maintainers, prio

#2341 Survey debug menu (EXPOSUREAPP-4855)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_datadonation.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/SafetyNetException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/SurveyException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentViewModel.kt
Labels: maintainers

#2280 Submit Analytics Data (EXPOSUREAPP-4823)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingAnalyticsFragmentTest.kt
  Corona-Warn-App/src/device/java/de/rki/coronawarnapp/datadonation/analytics/storage/DefaultLastAnalyticsSubmissionLogger.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/datadonation/analytics/storage/DefaultLastAnalyticsSubmissionLogger.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_datadonation.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/AnalyticsConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/AnalyticsConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/DataDonationModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/Analytics.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/AnalyticsException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/AnalyticsModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/DonorModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposureriskmetadata/ExposureRiskMetadataDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposurewindows/NewExposureWindowsDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/KeySubmissionStateDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/registeredtest/RegisteredTestDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/usermetadata/UserMetadataDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/server/DataDonationAnalyticsApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/server/DataDonationAnalyticsServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/storage/AnalyticsSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/storage/LastAnalyticsSubmission.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/storage/LastAnalyticsSubmissionLogger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/ui/input/AnalyticsUserInputViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/worker/DataDonationAnalyticsPeriodicWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/worker/DataDonationAnalyticsScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/worker/DataDonationAnalyticsTimeCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/worker/DataDonationAnalyticsWorkBuilder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingAnalyticsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/analytics/SettingsPrivacyPreservingAnalyticsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/worker/WorkerBinder.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/AnalyticsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/ExposureRiskMetadataDonorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/server/DataDonationAnalyticsApiV1Test.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/server/DataDonationAnalyticsServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/ui/AnalyticsSettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/ui/input/AnalyticsUserInputViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/survey/SurveyUrlProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/worker/WorkerBinderTest.kt
Labels: enhancement, maintainers, prio

#2343 Update default strings (DEV)
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2330 Integrate Analytics UI with the analytics backend (EXPOSUREAPP-4823)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/Analytics.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/analytics/SettingsPrivacyPreservingAnalyticsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/analytics/SettingsPrivacyPreservingAnalyticsState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/analytics/SettingsPrivacyPreservingAnalyticsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/start/SettingsFragmentViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/settings/start/SettingsFragmentViewModelTest.kt
Labels: prio, ui

#2349 SafetyNet Error Message (DEV)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#2352 PPA Settings - Change default switch state (DEV)
  Corona-Warn-App/src/main/res/layout/fragment_settings_privacy_preserving_analytics.xml
Labels: maintainers, ui

#2350 Legal text update for ppa
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: maintainers, text change

#2351 Privacy-Preserving Analytics String Update (DEV)
  Corona-Warn-App/src/main/res/layout/fragment_ppa_more_info.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change, ui

#2354 Fix invisible close icon in survey consent detail view (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentDetailFragment.kt
  Corona-Warn-App/src/main/res/layout/survey_consent_detail_fragment.xml
Labels: bug, maintainers, prio

#2335 Contact journal extension database changes (EXPOSUREAPP-5112)
  Corona-Warn-App/schemas/de.rki.coronawarnapp.contactdiary.storage.ContactDiaryDatabase/2.json
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/contactdiary/storage/ContactDiaryDatabaseMigrationTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/contactdiary/storage/ContactDiaryDatabaseTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/ContactDiaryDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/entity/ContactDiaryLocationEntity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/entity/ContactDiaryLocationVisitEntity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/entity/ContactDiaryLocationVisitWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/entity/ContactDiaryPersonEncounterEntity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/entity/ContactDiaryPersonEncounterWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/entity/ContactDiaryPersonEntity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/internal/converters/ContactDiaryRoomConverters.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/internal/migrations/ContactDiaryDatabaseMigration1To2.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/repo/ContactDiaryRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/repo/DefaultContactDiaryRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/storage/internal/converters/ContactDiaryRoomConvertersTest.kt
Labels: enhancement, maintainers

#2325 New consent Google API (EXPOSUREAPP-4635)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/libs/play-services-nearby-exposurenotification-1.7.2-eap.aar
  Corona-Warn-App/libs/play-services-nearby-exposurenotification-18.0.3.aar
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionConsentFragmentTest.kt
  Corona-Warn-App/src/main/AndroidManifest.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/tekhistory/DefaultTEKHistoryProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/tekhistory/TEKHistoryProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/version/DefaultENFVersion.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/version/ENFVersion.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/sharing/ExposureSharingService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/data/tekhistory/TEKHistoryUpdater.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionNavigationEvents.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/survey/SurveyUrlProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/modules/tekhistory/DefaultTEKHistoryProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/modules/version/DefaultENFVersionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/data/tekhistory/TEKHistoryUpdaterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentViewModelTest.kt
  Corona-Warn-App/src/test/java/testhelpers/gms/MockGMSTask.kt
Labels: enhancement, maintainers, prio

#2355 Don't close survey consent screen on errors (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentFragment.kt
Labels: bug, maintainers, prio

#2353 Discard OTP when high risk card disappears (EXPOSUREAPP-5144)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/Surveys.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelChangeDetector.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskLevelChangeDetectorTest.kt
Labels: maintainers, prio

#2348 Strings for contact diary encounter/visit button groups and extensions (EXPOSUREAPP-5108)
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
Labels: maintainers, text change

#2347 Rki Survey (EXPOSUREAPP-4637)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/SurveyException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/Surveys.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/survey/server/SurveyApiV1Test.kt
Labels: maintainers, prio

#2359 Bump to next Version 1.13.0.3
  gradle.properties
Labels: maintainers

#2361 Adjust nonce calculation and corresponding tests.
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNet.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/HashExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNetTest.kt
Labels: bug, maintainers, prio

#2365 Additional nonce test-case (DEV)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNetTest.kt
Labels: maintainers

#2364 Use protobuf container as request param (EXPOSUREAPP-4637)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/OneTimePassword.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/server/SurveyServer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/OneTimePasswordTest.kt
Labels: maintainers, prio

#2366 Fix PPA Submission Endpoint Return Type (EXPOSUREAPP-FREESTYLE)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/server/DataDonationAnalyticsApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/server/DataDonationAnalyticsServer.kt
Labels: backend, maintainers

#2367 Fix screenshots tests in 1.13 release (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/ScreenshotUnderTest.kt
Labels: enhancement, maintainers

#2370 Bump to next Version 1.13.0.4
  gradle.properties
Labels: maintainers

#2376 Bump to next Version 1.13.0.5 (DEV)
  gradle.properties
Labels: maintainers

#2380 PPA onboarding update (EXPOSUREAPP-5164)
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_delta_ppa.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_ppa.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_privacy_preserving_analytics.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2374 Minor corrections to formatting in legal texts (DEV)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: text change

#2381 Update strings.xml (DEV)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#2383 Bump to next Version 1.13.0.6
  gradle.properties
Labels: maintainers

#2357 Contact journal comment info screen (EXPOSUREAPP-5109)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/contactdiary/ui/ContactDiaryCommentInfoTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/ContactDiaryCommentInfoFragment.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_comment_info_fragment.xml
  Corona-Warn-App/src/main/res/navigation/contact_diary_nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
Labels: maintainers, text change

#2389 "Ihr Einverständnis" in Settings not translated (EXPOSUREAPP-5200)
  Corona-Warn-App/src/main/res/layout/fragment_settings_privacy_preserving_analytics.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, prio, text change

#2371 Your Risk Status Announcements (EXPOSUREAPP-5135)
  Corona-Warn-App/src/main/res/layout/tracing_details_item_behavior_increased_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_item_behavior_normal_view.xml
Labels: accessibility, maintainers

#2378 Contact Journal Day Announcement (EXPOSUREAPP-5133)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/ContactDiaryOverviewAdapter.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_list_item.xml
Labels: accessibility, maintainers

#2388 PPA User Metadata not deleted on In-App Reset (EXPOSUREAPP-5203)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/storage/AnalyticsSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
Labels: backend, maintainers, prio

#2390 PPA Exposure Risk Metadata mostRecentDateAtRiskLevel not correct (EXPOSUREAPP-5202)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposureriskmetadata/ExposureRiskMetadataDonor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/ExposureRiskMetadataDonorTest.kt
Labels: backend, maintainers, prio

#2386 Added changes from lawyers (Feb 16) to legal strings (DEV)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
Labels: text change

#2385 chore: update ppdd parameters of default app config
  Corona-Warn-App/src/main/assets/default_app_config_android.bin
  Corona-Warn-App/src/main/assets/default_app_config_android.sha256
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/sources/fallback/DefaultAppConfigSanityCheck.kt
Labels: maintainers

#2393 Adjust PPDD error dialog messages (EXPOSUREAPP-5201)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/SafetyNetException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/SurveyException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/HasHumanReadableError.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers, text change

#2362 Contact journal day screen: New attributes (EXPOSUREAPP-5108)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/contactdiary/storage/ContactDiaryDatabaseTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryDayFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/DiaryData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/ContactDiaryLocationVisit.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/DefaultContactDiaryLocationVisit.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/model/DefaultContactDiaryPersonEncounter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/entity/ContactDiaryLocationVisitEntity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/entity/ContactDiaryPersonEncounterEntity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/internal/converters/ContactDiaryRoomConverters.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/common/DiaryCircumstancesTextView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/common/DiaryTabViewHolderExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/common/ExpandingDiaryListItemView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/common/SelectableDiaryItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/location/ContactDiaryLocationListAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/location/ContactDiaryLocationListFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/location/ContactDiaryLocationListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/location/DiaryLocationListItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/location/DiaryLocationViewHolder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/person/ContactDiaryPersonListAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/person/ContactDiaryPersonListFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/person/ContactDiaryPersonListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/person/DiaryPersonListItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/person/DiaryPersonViewHolder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/util/AbstractAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/util/SelectableItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/StringExtensions.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_location_list_item.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_person_list_item.xml
  Corona-Warn-App/src/main/res/layout/view_diary_circumstances_textview.xml
  Corona-Warn-App/src/main/res/layout/view_expanding_diary_listitem.xml
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: enhancement, maintainers

#2394 Bump to next Version 1.13.0.7
  gradle.properties
Labels: maintainers

#2395 Fix text on bottom of new release info screen (DEV)
  Corona-Warn-App/src/main/res/layout/new_release_info_screen_fragment.xml
Labels: bug, maintainers

#2377 Feature/4741 contact journal bottom sheet extension
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/ContactDiaryUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/ContactDiaryDayFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/ContactDiaryDayNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/ContactDiaryDayViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditLocationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditLocationsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditPersonsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditPersonsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/location/ContactDiaryAddLocationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/location/ContactDiaryAddLocationFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/location/ContactDiaryAddLocationViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/person/ContactDiaryAddPersonFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/person/ContactDiaryAddPersonModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/person/ContactDiaryAddPersonViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/sheets/location/ContactDiaryLocationBottomSheetDialogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/sheets/person/ContactDiaryPersonBottomSheetDialogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/util/ContactDiaryExtensions.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_add_location_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_add_person_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_location_bottom_sheet_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_person_bottom_sheet_fragment.xml
  Corona-Warn-App/src/main/res/navigation/contact_diary_nav_graph.xml
  Corona-Warn-App/src/main/res/values-bg/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-en/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-pl/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-ro/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-tr/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/styles.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditLocationsViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditPersonsViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/util/ContactDiaryExtensionsTest.kt
Labels: maintainers

#2392 Reduce timeout to 5 sec (EXPOSUREAPP-5196)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/tekhistory/DefaultTEKHistoryProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/resultavailable/SubmissionTestResultAvailableFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/resultavailable/SubmissionTestResultAvailableViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/modules/tekhistory/DefaultTEKHistoryProviderTest.kt
Labels: bug, do not merge, maintainers

#2404 App survey crash (Exposureapp-5229)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentViewModel.kt
Labels: maintainers

#2400 PPA - Enhance dev menu (EXPOSUREAPP-5215)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_appconfig.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_datadonation.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/Analytics.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNet.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/TestSettings.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNetTest.kt
Labels: backend, maintainers, prio

#2402 Additional nonce test case for ppa data.
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNetTest.kt
Labels: maintainers

#2403 Bump to next Version 1.13.0.8
  gradle.properties
Labels: maintainers

#2401 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers, text change

#2405 Privacy update (EXPOSUREAPP-5181)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers, text change

#2391 Contact Journal Day Screen Accessibility (EXPOSUREAPP-5134)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/ContactDiaryDayFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/ContactDiaryDayTab.kt
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
Labels: accessibility, maintainers

#2406 Update default strings (DEV)
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2407 Log http error bodies (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/HttpErrorParser.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/HttpErrorParserTest.kt
Labels: maintainers, prio

#2410 Don't additionally base64 encode the nonce (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNet.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/SafetyNetClientWrapper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNetTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/safetynet/SafetyNetClientWrapperTest.kt
Labels: maintainers, prio

#2411 Bump to next Version 1.13.0.9
  gradle.properties
Labels: maintainers

#2409 Changes to legal strings in EN (DEV)
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: maintainers, text change

#2412 Fix legal strings Turkish (DEV)
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
Labels: maintainers, text change

#2413 Improve analytics error handling (DEV)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/reporter/DefaultBugReporter.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/crash.ui/CrashReportAdapter.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/view_crashreport_list_item.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/BugReporter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/Analytics.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/BugReporterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/AnalyticsTest.kt
Labels: maintainers, prio

#2373 PPA: Collect Client Metadata (EXPOSUREAPP-5147)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/AnalyticsModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/clientmetadata/ClientMetadataDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/BuildConfigWrap.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/clientmetadata/ClientMetadataDonorTest.kt
Labels: backend, maintainers

#2415 Format `mostRecentDateAtRiskLevel` in seconds, not milliseconds (EXPOSUREAPP-5239)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposureriskmetadata/ExposureRiskMetadataDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeAndDateExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/ExposureRiskMetadataDonorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/TimeAndDateExtensionsTest.kt
Labels: maintainers, prio

#2417 Show data donation server URL in test fragment for server environments (DEV)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/EnvironmentState.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_debugoptions.xml
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModelTest.kt
Labels: maintainers, prio

#2416 Fix endless uploading progress (EXPOSUREAPP-5237)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarViewModel.kt
Labels: bug, maintainers, prio

#2420 Bump to next Version 1.13.0.10
  gradle.properties
Labels: maintainers

#2422 Slider of Exposure Logging (EXPOSUREAPP-5222)
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
Labels: bug, maintainers, prio

#2399 Add styles for diary circumstances text field (EXPOSUREAPP-5161)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/common/DiaryCircumstancesTextView.kt
  Corona-Warn-App/src/main/res/layout/view_diary_circumstances_textview.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers

#2398 Onboarding refactoring (EXPOSUREAPP-4659)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/MainActivityTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaInteroperabilityFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingLoadingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingLoadingModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingLoadingViewModel.kt
  Corona-Warn-App/src/main/res/layout/onboaring_loading_layout.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph_onboarding.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/launcher/LauncherActivityViewModelTest.kt
Labels: author merge, maintainers

#2396 Default app config cleanup (DEV)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/assets/default_app_config.bin
  Corona-Warn-App/src/main/assets/default_app_config.sha256
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/sources/fallback/DefaultAppConfigSanityCheck.kt
Labels: maintainers

#2427 Translation Delivery (DEV)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-en/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
Labels: maintainers, text change

#2428 Update default strings (DEV)
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#2429 Use last OTP auth result to check month on client side (EXPOSUREAPP-5246)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/OTPAuthorizationResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/SurveySettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/Surveys.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/storage/OTPRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/survey/SurveySettingsTest.kt
Labels: maintainers, prio

#2433 Skip consent screen on subsequent survey participations (EXPOSUREAPP-5278)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/TracingDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/Surveys.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsNavigationEvents.kt
Labels: maintainers

#2432 Optimized otp auth result entity (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/OTPAuthorizationResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/Surveys.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/storage/OTPRepositoryTest.kt
Labels: maintainers

#2431 Add network connected constraint to DataDonationAnalyticsWorker (EXPOSUREAPP-5286)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/worker/DataDonationAnalyticsWorkBuilder.kt
Labels: backend, maintainers, prio

#2435 Exposure Checks are continued in End-of-Life State (EXPOSUREAPP-5298)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTaskTest.kt
Labels: bug, maintainers
