Repository corona-warn-app/cwa-app-android, pull requests merged in 2022-11, with the labels that each got.

#5674 Fix: Delete All locations in journal (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditLocationsFragment.kt
Labels: bug, maintainers

#5672 Tapped notification because of increased risk does not open the Status Tab EXPOSUREAPP-14231
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/changedetection/CombinedRiskLevelChangeDetector.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/changedetection/CombinedRiskLevelChangeDetectorTest.kt
Labels: bug, maintainers

#5675 Adapt family test delete dialog (EXPOSUREAPP-13864)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/FamilyTestListFragment.kt
Labels: bug, maintainers

#5673 Add missing action arrows in submission flow (EXPOSUREAPP-12854)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/consent/SurveyConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/yourconsent/SubmissionYourConsentFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_family_test_consent.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_consent.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_no_consent_positive_other_warning.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_your_consent.xml
  Corona-Warn-App/src/main/res/layout/survey_consent_fragment.xml
  Corona-Warn-App/src/main/res/layout/view_consent_status.xml
Labels: bug, maintainers

#5680 Bump to next Version 2.29.0.1
  gradle.properties
Labels: maintainers

#5682 Local prerequisites (EXPOSUREAPP-14185)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/SrsLocalChecker.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/SrsLocalCheckerTest.kt
Labels: maintainers

#5678 Srs settings (EXPOSUREAPP-14186)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/SrsSubmissionModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/storage/SrsSubmissionSettings.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/storage/SrsSubmissionSettingsTest.kt
Labels: maintainers

#5681 Self Report Submission config param (EXPOSUREAPP-14187)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/AppConfigModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/SelfReportSubmissionConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/ConfigMapping.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/ConfigParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/DefaultConfigMapping.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/SelfReportSubmissionConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/SrsLocalChecker.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/ConfigParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/SrsLocalCheckerTest.kt
Labels: maintainers

#5685 Dialog refactoring - popup missing (EXPOSUREAPP-14288)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateFragment.kt
Labels: bug, maintainers

#5688 Update libs (EXPOSUREAPP-14043)
  Corona-Warn-App/build.gradle
Labels: maintainers

#5686 Srs submission consent screen (EXPOSUREAPP-14176)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/SrsSubmissionUiModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionFragmentViewModel.kt
  Corona-Warn-App/src/main/res/drawable/ic_srs_clock.xml
  Corona-Warn-App/src/main/res/drawable/ic_srs_not_official.xml
  Corona-Warn-App/src/main/res/drawable/ic_srs_virus.xml
  Corona-Warn-App/src/main/res/layout/fragment_srs_submission_consent.xml
  Corona-Warn-App/src/main/res/layout/include_srs_privacy_card.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/navigation/srs_nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/main/res/values/srs_submission_strings.xml
Labels: maintainers

#5687 SRS Server Api (EXPOSUREAPP-14188, 14189)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_submission.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/AppConfigProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/AttestationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/CheckInRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/AndroidIdProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/SrsSubmissionModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/error/SrsSubmissionException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/model/SrsAuthorizationRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/model/SrsAuthorizationResponse.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/model/SrsDeviceAttestationRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/model/SrsOtp.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/model/SrsSubmissionPayload.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/model/SrsSubmissionType.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/playbook/SrsPlaybook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/repository/TypeMapping.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/server/SrsAuthorizationApi.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/server/SrsAuthorizationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/server/SrsSubmissionApi.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/server/SrsSubmissionServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/storage/SrsSubmissionSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/SubmissionModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/task/SubmissionTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/AppConfigProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/AndroidIdProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/playbook/SrsPlaybookTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/repository/TypeMappingTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/server/SrsAuthorizationServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/server/SrsSubmissionServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/storage/SrsSubmissionSettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/task/SubmissionTaskTest.kt
Labels: maintainers

#5692 Remove tan tiles from dispatcher screen (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionDispatcherFragmentTest.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_dispatcher.xml
Labels: maintainers

#5694 Suggestion (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeListData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionItemAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterSubmissionHelper.kt
  Corona-Warn-App/src/main/res/color/srs_type_bg_color.xml
  Corona-Warn-App/src/main/res/color/srs_type_text_color.xml
  Corona-Warn-App/src/main/res/layout/fragment_srs_type_selection.xml
  Corona-Warn-App/src/main/res/layout/srs_type_selection_adapter_item.xml
  Corona-Warn-App/src/main/res/values-de/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values/srs_submission_strings.xml
Labels: maintainers

#5691 Srs test type selection fragment (EXPOSUREAPP-14177)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionItemAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionNavigationEvents.kt
  Corona-Warn-App/src/main/res/color/srs_type_bg_color.xml
  Corona-Warn-App/src/main/res/color/srs_type_text_color.xml
  Corona-Warn-App/src/main/res/layout/fragment_srs_type_selection.xml
  Corona-Warn-App/src/main/res/layout/srs_type_selection_adapter_item.xml
  Corona-Warn-App/src/main/res/navigation/srs_nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values/srs_submission_strings.xml
Labels: maintainers, text change

#5696 Remove pending Test TAN note (EXPOSUREAPP-14305)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#5695 Dev menu (EXPOSUREAPP-14182)
  Corona-Warn-App/src/device/java/de/rki/coronawarnapp/srs/core/storage/DefaultSrsDevSettings.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/srs/core/storage/DefaultSrsDevSettings.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_submission.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/internal/ConfigDataContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/sources/fallback/DefaultAppConfigSource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/sources/local/LocalAppConfigSource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/sources/remote/RemoteAppConfigSource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/SrsDevSettingsModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/SrsLocalChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/SrsSubmissionModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/server/SrsAuthorizationApi.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/server/SrsAuthorizationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/storage/SrsDevSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/storage/SrsSubmissionSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragment.kt
  Corona-Warn-App/src/main/res/navigation/srs_nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/sources/fallback/DefaultAppConfigSourceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/sources/local/LocalAppConfigSourceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/sources/remote/RemoteAppConfigSourceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/SrsLocalCheckerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/server/SrsAuthorizationServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/storage/SrsSubmissionSettingsTest.kt
  Corona-Warn-App/src/testDevice/java/de/rki/coronawarnapp/srs/core/storage/DefaultSrsDevSettingsTest.kt
Labels: maintainers

#5693 Submissions in journal (EXPOSUREAPP-14181)
  Corona-Warn-App/schemas/de.rki.coronawarnapp.contactdiary.storage.ContactDiaryDatabase/5.json
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/contactdiary/storage/ContactDiaryDatabaseMigrationTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/contactdiary/storage/ContactDiaryDatabaseTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/ContactDiaryOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/contactdiary/DiaryData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/retention/ContactDiaryCleanTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/retention/ContactDiaryRetentionCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/ContactDiaryDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/dao/ContactDiarySubmissionDao.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/entity/ContactDiarySubmissionEntity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/repo/ContactDiaryRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/storage/repo/DefaultContactDiaryRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/day/DayOverviewItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/day/DayOverviewVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/day/submission/SubmissionItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/SubmissionReporter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/task/SubmissionTask.kt
  Corona-Warn-App/src/main/res/drawable/ic_submission.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_day_list_item_submission.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_list_item.xml
  Corona-Warn-App/src/main/res/values-de/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values/srs_submission_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/retention/ContactDiaryCleanTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/retention/ContactDiaryDataRetentionCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/SubmissionReporterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/task/SubmissionTaskTest.kt
Labels: maintainers, text change

#5701 SRS errors (EXPOSUREAPP-14175)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/SrsLocalChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/error/SrsSubmissionException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/server/SrsAuthorizationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/res/values-de/links.xml
  Corona-Warn-App/src/main/res/values-de/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values/links.xml
  Corona-Warn-App/src/main/res/values/srs_submission_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/server/SrsAuthorizationServerTest.kt
Labels: maintainers, text change

#5703 Move Android ID to payload (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/server/SrsAuthorizationServer.kt
Labels: maintainers

#5700 Update thank you screen (EXPOSUREAPP-14180)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/submissiondone/SubmissionDoneFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/main/res/drawable/ic_diary_white.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_done.xml
  Corona-Warn-App/src/main/res/layout/include_submission_done_content.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#5699 SRS Symptoms flow (EXPOSUREAPP-14179)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/SrsSubmissionUiModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/checkins/SrsCheckinsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/checkins/SrsCheckinsFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/checkins/SrsCheckinsFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/checkins/SrsCheckinsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/dialogs/SrsSubmissionCancelDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/SrsSymptomsCalendarFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/SrsSymptomsCalendarModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/SrsSymptomsCalendarNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/SrsSymptomsCalendarViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/SrsSymptomsIntroductionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/SrsSymptomsIntroductionModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/SrsSymptomsIntroductionNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/SrsSymptomsIntroductionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionFragment.kt
  Corona-Warn-App/src/main/res/navigation/srs_nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values/srs_submission_strings.xml
Labels: maintainers, text change

#5704 Srs Flow Tweaking (EXPOSUREAPP-14184)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/error/SrsSubmissionException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/SrsSubmissionUiModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/checkins/SrsCheckinsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/checkins/SrsCheckinsFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/checkins/SrsCheckinsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/done/SrsSubmissionDoneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/SrsSymptomsCalendarNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/SrsSymptomsIntroductionNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionFragment.kt
  Corona-Warn-App/src/main/res/navigation/srs_nav_graph.xml
Labels: maintainers

#5705 Fix certificates cards background (DEV)
  Corona-Warn-App/src/main/res/drawable/dispatcher_card_background.xml
  Corona-Warn-App/src/main/res/drawable/grey_card_ripple.xml
  Corona-Warn-App/src/main/res/layout/dispatcher_card_layout.xml
Labels: bug, maintainers

#5706 Change card background (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/DispatcherCardView.kt
Labels: bug, maintainers

#5709 Fix: Close dialog look and feel (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/dialogs/SrsSubmissionCancelDialog.kt
  Corona-Warn-App/src/main/res/values-de/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values/srs_submission_strings.xml
Labels: maintainers, text change

#5711 Unit tests consent screen (EXPOSUREAPP-14323)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragmentViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragmentViewModelTest.kt
Labels: maintainers

#5712 Update since onboarding error code (Dev)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/SrsLocalChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/error/SrsSubmissionException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/server/SrsAuthorizationServer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/SrsLocalCheckerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/server/SrsAuthorizationServerTest.kt
Labels: enhancement, maintainers

#5708 Add otp censor (EXPOSUREAPP-14190)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/BugReportingSharedModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/OtpCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/OtpCensorTest.kt
Labels: maintainers

#5713 Typeselection test (EXPOSUREAPP-14325)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionFragmentViewModelTest.kt
Labels: maintainers

#5710 Srs progress loading button (EXPOSUREAPP-14322)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_symptom_calendar.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_symptom_intro.xml
Labels: maintainers

#5715 Check ins screen test (EXPOSUREAPP-14324)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/ui/chekins/SrsCheckinsViewModelTest.kt
Labels: maintainers

#5716 Adjust release info (EXPOSUREAPP-14155)
  Corona-Warn-App/src/main/res/drawable/ic_new_release_info_3_0.xml
  Corona-Warn-App/src/main/res/layout/new_release_info_screen_fragment.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-uk/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
Labels: maintainers, text change

#5714 Srs plausible deniability (EXPOSUREAPP-14314)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/AnalyticsConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/PlausibleDeniabilityParametersContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/SelfReportSubmissionConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/AnalyticsConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/SelfReportSubmissionConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/Analytics.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/model/SrsAuthorizationFakeRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/playbook/SrsPlaybook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/server/SrsAuthorizationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/server/SrsSubmissionServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/PaddingTool.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/AnalyticsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/server/SrsAuthorizationServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/PaddingToolTest.kt
Labels: maintainers

#5718 Bump to next Version 3.0.0.2
  gradle.properties
Labels: maintainers

#5719 Fix: Screenshots (EXPOSUREAPP-14344)
  .github/workflows/screenshots.yml
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionDispatcherFragmentTest.kt
Labels: maintainers

#5720 Symptoms screens tests (EXPOSUREAPP-14326)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/ui/chekins/SrsCheckinsFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/ui/symptoms/calnedar/SrsSymptomsCalendarViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/ui/symptoms/introduction/SrsSymptomsIntroductionViewModelTest.kt
Labels: maintainers

#5721 Remove space below illustration (EXPOSUREAPP-14320)
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_available.xml
Labels: bug, maintainers

#5722 Use UTC in date conversion (EXPOSUREAPP-14230)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/edit/EditCheckInFragment.kt
Labels: bug, maintainers

#5726 Hide notification badge on certificate detail view (EXPOSUREAPP-14335)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
Labels: maintainers

#5727 Navigation from consent screen to survey consent detials fragment (EXPOSUREAPP-14349)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_srs_submission_consent.xml
  Corona-Warn-App/src/main/res/layout/include_srs_privacy_card.xml
  Corona-Warn-App/src/main/res/layout/survey_consent_detail_fragment.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/srs_submission_strings.xml
Labels: maintainers, text change

#5731 Update thank you screen (EXPOSUREAPP-14337)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/done/SrsSubmissionDoneFragment.kt
Labels: maintainers

#5729 Update text and screens (EXPOSUREAPP-14354)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/SelfReportSubmissionConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragmentViewModel.kt
  Corona-Warn-App/src/main/res/layout/fragment_srs_submission_consent.xml
  Corona-Warn-App/src/main/res/layout/include_srs_privacy_card.xml
  Corona-Warn-App/src/main/res/values-bg/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-de/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values-ro/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values-tr/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values-uk/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/main/res/values/srs_submission_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragmentViewModelTest.kt
Labels: maintainers, text change

#5730 Update mixed up strings in statistics info screen (EXPOSUREAPP-14351)
  Corona-Warn-App/src/main/res/layout/fragment_statistics_explanation.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#5732 Fix data privacy numbered list (EXPOSUREAPP-7481)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: bug, maintainers

#5733 Bump to next Version 3.0.0.3
  gradle.properties
Labels: maintainers

#5734 Automation improvement
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers, text change

#5736 Downgrade jackson (EXPOSUREAPP-14357)
  Corona-Warn-App/build.gradle
Labels: bug, maintainers

#5735 Checkins navigation crash (EXPOSUREAPP-14361)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/onboarding/CheckInOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/onboarding/CheckInOnboardingNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/onboarding/CheckInOnboardingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/TraceLocationsFragment.kt
Labels: bug, maintainers
