Repository corona-warn-app/cwa-app-android, pull requests merged in 2022-02, with the labels that each got.

#4750 CCL wallet info binding for certificates overview screen (EXPOSUREAPP-11498)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/text/TextResource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
Labels: ui, maintainers

#4761 Zertifikatsprüfung durch Dritte
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#4760 Change term
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4752 Text formatting (EXPOSUREAPP-11503)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/assets/ccl/ccl-text-descriptor-test-cases.gen.json
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/database/DccWalletInfoDatabaseTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ccl/ui/text/TextResourceTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DummyWalletInfo.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/text/TextResource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/text/UrlResource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/ui/text/PluralFormatter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/ui/text/TextResource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/ui/text/UrlResource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/ParametersParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/ui/text/UrlResourceKtTest.kt
  Corona-Warn-App/src/test/resources/ccl/dcc_wallet_info.json
  Corona-Warn-App/src/test/resources/ccl/dcc_wallet_info_params.json
Labels: maintainers

#4763 Bump to next Version 2.17.2.0
  gradle.properties
Labels: maintainers

#4735 Configuration Update handling (EXPOSUREAPP-11292)
  Corona-Warn-App/src/main/assets/ccl/ccl-configuration.bin
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/CCLModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/CCLConfigurationModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/common/CCLConfigurationParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/model/CCLConfiguration.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/model/JsonFunctionsDescriptor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/server/CCLConfigurationApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/server/CCLConfigurationInvalidSignatureException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/server/CCLConfigurationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/storage/CCLConfigurationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/storage/CCLConfigurationStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/storage/CClConfigurationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/storage/DefaultCCLConfigurationProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/common/CCLConfigurationParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/server/CCLConfigurationServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/storage/CCLConfigurationStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/storage/DefaultCCLConfigurationProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
Labels: maintainers

#4765 Change term (EXPOSUREAPP-11520)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: text change

#4764 Booster vaccination info card shows full immunity right away (EXPOSUREAPP-11634)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPerson.kt
Labels: bug, maintainers, prio

#4766 Adjust Info Screen to announce new Release-Features for 2.18 (EXPOSUREAPP-11350)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#4767 Clean up / remove un-used code Part 1 (EXPOSUREAPP-11653)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
Labels: maintainers

#4747 Dcc wallet info calculation (EXPOSUREAPP-11480, EXPOSUREAPP-11482)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/database/DccWalletInfoDatabaseTest.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CCLTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CCLTestViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_ccl.xml
  Corona-Warn-App/src/main/assets/ccl/ccl-configuration.bin
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManager.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInputMapping.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoInput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DummyWalletInfo.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/adapter/JsonNodeAdapter.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoInputTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/serialization/adapter/JsonNodeAdapterTest.kt
  Corona-Warn-App/src/test/resources/ccl/dcc_wallet_info.json
  Corona-Warn-App/src/test/resources/ccl/dcc_wallet_info_plural_indexed.json
Labels: maintainers

#4769 Update DccWalletInfoEntity structure to prevent app crashes (DEV)
  Corona-Warn-App/schemas/de.rki.coronawarnapp.ccl.dccwalletinfo.storage.database.DccWalletInfoDatabase/1.json
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/PersonWalletInfo.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/database/DccWalletInfoConverter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/database/DccWalletInfoEntity.kt
Labels: maintainers

#4744 Booster detail screen (EXPOSUREAPP-11501, EXPOSUREAPP-11592)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/database/DccWalletInfoDatabaseTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/boosterinfodetails/BoosterInfoDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/DigitalCovidCertificateUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/boosterinfodetails/BoosterInfoDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/boosterinfodetails/BoosterInfoDetailsFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/boosterinfodetails/BoosterInfoDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/BoosterCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_booster_info.xml
  Corona-Warn-App/src/main/res/drawable/ic_booster_info.xml
  Corona-Warn-App/src/main/res/layout/fragment_booster_information_details.xml
  Corona-Warn-App/src/main/res/layout/person_details_booster_card.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/ui/text/UrlResourceKtTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
  Corona-Warn-App/src/test/resources/ccl/dcc_wallet_info.json
  Corona-Warn-App/src/test/resources/ccl/dcc_wallet_info_plural_indexed.json
Labels: ui, maintainers

#4776 Bump to next Version 2.17.2.1
  gradle.properties
Labels: maintainers

#4780 FIX: 2.17 Hotfix App Crash (EXPOSUREAPP-11675)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/ui/onboarding/CovidCertificateOnboardingViewModel.kt
Labels: bug, maintainers, prio

#4778 Fix: Root dialog (EXPOSUREAPP-11676)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/rootdetection/ui/RootDetectionDialogFragment.kt
  Corona-Warn-App/src/main/res/layout/root_detection_dialog_checkbox_view.xml
Labels: bug, maintainers

#4774 Clean up part2 (EXPOSUREAPP-11653)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/model/CCLConfiguration.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/DccWalletInfoRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/boosterinfodetails/BoosterInfoDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorageTest.kt
Labels: maintainers

#4782 CCL config tests (EXPOSUREAPP-11202)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/storage/CCLConfigurationRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/storage/CCLConfigurationRepositoryTest.kt
Labels: maintainers

#4783 Bind dccWalletInfo update trigger (EXPOSUREAPP-11481)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTrigger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/execution/TestCertificateRetrievalWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/covidcertificate/RecycledCertificatesProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/execution/TestCertificateRetrievalWorkerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/covidcertificate/RecycledCertificatesProviderTest.kt
Labels: maintainers

#4781 Fix QR scanner stuck after scanning manipulated QR code (EXPOSUREAPP-11474)
  Corona-Warn-App/build.gradle
Labels: bug, maintainers

#4773 Ccl Json Functions (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/CCLJsonFunctions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/CclDefaultInputParameters.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManager.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/CCLJsonFunctionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/CclStateMappingTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationTest.kt
Labels: maintainers

#4788 Lifecycle owner crash (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
Labels: bug, maintainers

#4787 System time dependent text formatting (EXPOSUREAPP-11509)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/proguard-rules.pro
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/database/DccWalletInfoDatabaseTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ccl/ui/text/CCLTextFormatterTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/boosterinfodetails/BoosterInfoDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CCLTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CCLTestViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_ccl.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/model/CCLConfiguration.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/DccWalletInfoCleaner.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManager.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/DccWalletInfoRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/database/DccWalletInfoDao.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTrigger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/ui/text/CCLTextFormatter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/ui/text/TextResource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/ui/text/UrlResource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/boosterinfodetails/BoosterInfoDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/BoosterCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/SerializationModule.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/common/CCLConfigurationParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/DccWalletInfoCleanerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/CCLJsonFunctionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/DccWalletInfoRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/ui/text/FaqAnchorFormattingTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/ui/text/UrlResourceKtTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
  build.gradle
Labels: maintainers

#4793 Show booster badge in conjunction with notification (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationServiceTest.kt
Labels: bug, maintainers

#4794 Align badge style (DEV)
  Corona-Warn-App/src/main/res/layout/include_certificate_overview_qr_card.xml
Labels: bug, maintainers

#4791 CCL Calc manager unit test (EXPOSUREAPP-11677)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManager.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManagerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationTest.kt
Labels: bug, maintainers

#4798 Request COVID-Certificate has wrong text(normal)
  Corona-Warn-App/src/main/res/values-de/green_certificate_strings.xml
Labels: text change

#4797 Request COVID-Certificate has wrong text (legal)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
Labels: text change

#4796 Update Text for 116117 info telephone
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4800 Fix: collapsing text (DEV)
  Corona-Warn-App/src/main/res/layout/confirmed_status_card.xml
Labels: bug, maintainers

#4807 Fix booster card subtitle style (DEV)
  Corona-Warn-App/src/main/res/layout/person_details_booster_card.xml
Labels: bug, maintainers

#4806 FIX: Certificate Export as PDF - "Country" format issue (EXPOSUREAPP-11607)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/RecoveryCertificateDrawHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/TestCertificateDrawHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/VaccinationCertificateDrawHelper.kt
Labels: bug, maintainers

#4802 Update build tool version (EXPOSUREAPP-11744)
  Corona-Warn-App/build.gradle
Labels: maintainers

#4801 FIX: Improve App Performance (EXPOSUREAPP-11707)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscSignatureValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/valueset/ValueSetsRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/valueset/internal/DccValueSetMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinOverviewViewModel.kt
Labels: bug, maintainers

#4809 Bump to next Version 2.18.0.1
  gradle.properties
Labels: maintainers

#4811 Data structures (EXPOSUREAPP-11749)
  Corona-Warn-App/proguard-rules.pro
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccadmission/model/DccAdmissionCheckScenariosInput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccadmission/model/DccAdmissionCheckScenariosOutput.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccadmission/model/DccAdmissionCheckScenariosTest.kt
Labels: maintainers

#4813 Download ccl config and booster rules again if they failed earlier today (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/server/CCLConfigurationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/storage/CCLConfigurationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/update/CCLConfigurationUpdater.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterRulesRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/repositories/UpdateResult.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/storage/CCLConfigurationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/update/CCLConfigurationUpdaterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterRulesRepositoryTest.kt
Labels: bug, maintainers

#4819 Typo new Functions " , oder" (EXPOSUREAPP-11746)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: text change

#4818 Bump to next Version 2.18.0.2
  gradle.properties
Labels: maintainers

#4810 Restoring tests over active tests will show result screen immediately (EXPOSUREAPP-11629)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningViewModel.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
Labels: bug, maintainers

#4812 FIX: Export test results shown in contact journal (EXPOSUREAPP-11441)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/exporter/ContactDiaryExporter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/ui/exporter/ContactDiaryExporterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/util/ContactDiaryData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/util/ContactDiaryExportStringsMock.kt
Labels: bug, maintainers

#4822 Fix screenshots build (DEV)
  .circleci/config.yml
Labels: bug, maintainers

#4816 Repository skeleton (EXPOSUREAPP-17753)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccadmission/model/storage/DccAdmissionCheckScenariosRepository.kt
Labels: maintainers

#4823 chore: update default CCL config to v1.0.0-rc.3
  Corona-Warn-App/src/main/assets/ccl/ccl-configuration.bin
Labels: maintainers

#4814 Calculation (EXPOSUREAPP-11757)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/model/CclDefaultInputParameters.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccadmission/calculation/DccAdmissionCheckScenariosCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/ui/text/CCLTextFormatter.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccadmission/calculation/DccAdmissionCheckScenariosTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/CclDateTimeTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationTest.kt
Labels: maintainers

#4826 Avoid logging the entire ccl config (EXPOSUREAPP-11788)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/storage/CCLConfigurationRepository.kt
Labels: bug, maintainers

#4825 Display CCL version (EXPOSUREAPP-11791)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragmentViewModel.kt
  Corona-Warn-App/src/main/res/layout/fragment_information.xml
Labels: ui, maintainers

#4837 Text changes for 116 117 phone number
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4838 Fix booster notification background trigger (EXPOSUREAPP-11804)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/update/CCLConfigurationUpdateScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/worker/WorkerBinder.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/worker/WorkerBinderTest.kt
Labels: bug, maintainers

#4830 Merge default and downloaded config (EXPOSUREAPP-11750)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/storage/CCLConfigurationMerger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/storage/CCLConfigurationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/storage/DownloadedCCLConfigurationStorage.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/storage/CCLConfigurationMergerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/storage/CCLConfigurationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/storage/DownloadedCCLConfigurationStorageTest.kt
Labels: maintainers

#4839 Bump to next Version 2.18.0.4
  gradle.properties
Labels: maintainers

#4841 Text validation result (EXPOSUREAPP-11785)
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: maintainers, text change

#4843 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#4845 Bump to next Version 2.18.0.5
  gradle.properties
Labels: maintainers

#4844 CCL not recalculated base on validuntil (EXPOSUREAPP-11850)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/update/CCLConfigurationUpdater.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/update/CCLConfigurationUpdaterTest.kt
Labels: bug, maintainers

#4831 FIX: Wong Output, when accessing OS push notification after pending test results turned positive (EXPOSUREAPP-11776)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRCoronaTestExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RapidAntigenCoronaTestExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/auto/AutoSubmission.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/task/SubmissionTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/resultready/SubmissionResultReadyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/resultready/SubmissionResultReadyViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultConsentGivenViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RapidAntigenCoronaTestExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/auto/AutoSubmissionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionViewModelTest.kt
Labels: bug, maintainers

#4835 Add scenario id (EXPOSUREAPP-11771)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CCLTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CCLTestViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_ccl.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/CWAConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CWAConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccadmission/calculation/DccAdmissionCheckScenariosCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManager.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoInput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTrigger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/AdmissionTileProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/update/CCLConfigurationUpdaterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManagerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoInputTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/AdmissionTileProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/execution/TestCertificateRetrievalWorkerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/covidcertificate/RecycledCertificatesProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/worker/WorkerBinderTest.kt
  Corona-Warn-App/src/test/resources/ccl/dcc_wallet_info_input.json
Labels: maintainers

#4827 Rapid-PCR test support (EXPOSUREAPP-11698, 11697, 11699)
  Corona-Warn-App/src/main/AndroidManifest.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/BugReportingSharedModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/RapidQrCodeCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/qrcode/CoronaTestQRCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/qrcode/rapid/RapidAntigenQrCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/qrcode/rapid/RapidPcrQrCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/qrcode/rapid/RapidQrCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRCoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRTestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/scanner/QrCodeValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/RapidQrCodeCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/qrcode/TestQrCodes.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/qrcode/rapid/RapidAntigenQrCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/qrcode/rapid/RapidPcrQrCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/storage/CoronaTestStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest2.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/scanner/QrCodeValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateViewModelTest.kt
Labels: maintainers, author merge

#4852 Remove one shot note card (EXPOSUREAPP-11838)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: bug, maintainers

#4855 Bump to next Version 2.18.1.0
  gradle.properties
Labels: maintainers

#4859 chore: update default CCL config to v1.0.0-rc.7
  Corona-Warn-App/src/main/assets/ccl/ccl-configuration.bin
Labels: maintainers

#4860 Protocol Buffer update for release 2.19.x at Sun Feb 20 16:46:40 UTC 2022
  Server-Protocol-Buffer/src/main/proto/internal/v2/dgc_parameters.proto
Labels: maintainers

#4853 Corrected text for "Warnende Personen"
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4846 Read appconfig flag to control admission scenarios (EXPOSUREAPP-11801)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CWAConfigMapper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/CWAConfigMapperTest.kt
Labels: maintainers

#4851 "Impfstatus" shows wrong infos (EXPOSUREAPP-11833)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CCLTestViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_menu.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManager.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTrigger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CertificateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/execution/TestCertificateRetrievalWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/certificateselection/DccTicketingCertificateFilter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/covidcertificate/RecycledCertificatesProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTriggerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/execution/TestCertificateRetrievalWorkerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/certificateselection/DccTicketingCertificateFilterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/covidcertificate/RecycledCertificatesProviderTest.kt
Labels: bug, maintainers, prio

#4862 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers

#4861 2.18 into 2.19 (DEV)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_menu.xml
  Corona-Warn-App/src/main/assets/ccl/ccl-configuration.bin
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManager.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTrigger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CertificateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/admission/AdmissionScenariosViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/execution/TestCertificateRetrievalWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/certificateselection/DccTicketingCertificateFilter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/covidcertificate/RecycledCertificatesProvider.kt
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTriggerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/execution/TestCertificateRetrievalWorkerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/certificateselection/DccTicketingCertificateFilterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/covidcertificate/RecycledCertificatesProviderTest.kt
Labels: maintainers, author merge

#4832 Admission scenarios screen (EXPOSUREAPP-11751)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/boosterinfodetails/BoosterInfoDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/admission/AdmissionScenariosFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestExtensions.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CclTestViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/CclModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/update/CclConfigurationUpdater.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/update/CclSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccadmission/model/DccAdmissionCheckScenariosOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/DccWalletInfoCleaner.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManager.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTrigger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/admission/AdmissionBlockingDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/admission/AdmissionScenariosFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/admission/AdmissionScenariosViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/res/color/admission_item_color.xml
  Corona-Warn-App/src/main/res/layout/admission_calculation_dialog.xml
  Corona-Warn-App/src/main/res/layout/admission_federal_state_item.xml
  Corona-Warn-App/src/main/res/layout/admission_scenario_tile.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/update/CclConfigurationUpdaterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManagerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTriggerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/admission/AdmissionScenariosViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
Labels: ui, maintainers

#4857 Fix: App crashes when certificate is scanned with malformed data (EXPOSUREAPP-11924)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/dcc/DccQrCodeCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DateFormatting.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccV1Parser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/cards/DccTicketingRecoveryCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/cards/DccTicketingTestCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/cards/DccTicketingVaccinationCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
Labels: bug, maintainers

#4865 Bump to next Version 2.19.0.1
  gradle.properties
Labels: maintainers

#4863 Refactor person settings (EXPOSUREAPP-11989)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/dcc/CwaUserCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTrigger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/DigitalCovidCertificateModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CertificatePersonIdentifier.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonSettingsDataStore.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/SettingsMap.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/CensorInjectionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/dcc/CwaUserCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTriggerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesStorageTest.kt
Labels: maintainers

#4867 Remove unused code (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPerson.kt
Labels: enhancement, maintainers

#4868 Fix: Scanner is not opening after time travel to the past (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
Labels: bug, maintainers

#4858 Fault tolerant name handling for certificates (EXPOSUREAPP-11617)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CertificatePersonIdentifier.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccMaxPersonChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/dcc/DccGroupingExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/list/ListExt.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/preferences/FlowPreference.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/holder/grouping/DccGroupingExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/holder/grouping/DccHolderComparisonTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/holder/grouping/DccHolderComparisonTestCaseProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/holder/grouping/DccHolderNameComponentsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/holder/grouping/DccHolderNameComponentsTestCaseProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/holder/grouping/TestCases.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/CertificatePersonIdentifierTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/preferences/FlowPreferenceTest.kt
  Corona-Warn-App/src/test/resources/dcc-holder-comparison.gen.json
  Corona-Warn-App/src/test/resources/dcc-holder-name-components.gen.json
Labels: maintainers

#4874 Update AGP (DEV)
  build.gradle
Labels: maintainers

#4873 Catch potential crash (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
Labels: bug, maintainers

#4871 Scrollable tile (DEV)
  Corona-Warn-App/src/main/res/layout/admission_scenario_tile.xml
Labels: maintainers

#4866 Reissuance badge (EXPOSUREAPP-11936,11937)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CclTestViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManager.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/notification/DccWalletInfoNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/DigitalCovidCertificateModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/boosterinfodetails/BoosterInfoDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/boosterinfodetails/BoosterInfoDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/notification/PersonNotificationSender.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/BoosterCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/CertificateReissuanceCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/DccReissuanceModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/notification/DccReissuanceNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentViewModel.kt
  Corona-Warn-App/src/main/res/drawable/ic_badge.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
  Corona-Warn-App/src/main/res/layout/person_details_booster_card.xml
  Corona-Warn-App/src/main/res/layout/person_details_certificate_reissuance_card.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManagerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTriggerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/PersonNotificationSenderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/notification/DccReissuanceNotificationServiceTest.kt
Labels: maintainers

#4864 Create reissuance success screen (EXPOSUREAPP-11907)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CclTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/success/DccReissuanceSuccessFragment.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_dcc_reissuance_success_illustration.xml
  Corona-Warn-App/src/main/res/drawable/ic_dcc_reissuance_success_illustration.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_reissuance_success.xml
  Corona-Warn-App/src/main/res/values-de/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_reissuance_strings.xml
  translation_v2.json
Labels: maintainers

#4875 Change app config parameter for admission scenarios (EXPOSUREAPP-12044)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CWAConfigMapper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/CWAConfigMapperTest.kt
Labels: maintainers, author merge

#4869 Consent screen (EXPOSUREAPP-11910)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceBulletPoint.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentViewModel.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_deletion.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_update.xml
  Corona-Warn-App/src/main/res/drawable/ic_deletion.xml
  Corona-Warn-App/src/main/res/drawable/ic_update.xml
  Corona-Warn-App/src/main/res/layout/dcc_reissuance_bullet_point.xml
  Corona-Warn-App/src/main/res/layout/dcc_reissuance_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_reissuance_consent.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/main/res/values-bg/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-de/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-pl/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-ro/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-tr/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/attrs.xml
  Corona-Warn-App/src/main/res/values/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccticketing/core/certificateselection/DccTicketingCertificateFilterTest.kt
Labels: maintainers, text change

#4876 DEV: censoring loop bug
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesSettings.kt
Labels: bug, maintainers

#4870 Reissuance Server Api (EXPOSUREAPP-11938)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/EnvironmentState.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_debugoptions.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/CovidCertificateConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CovidCertificateConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/DccReissuanceModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/error/DccReissuanceException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/processor/DccReissuanceProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/server/DccReissuanceApi.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/server/DccReissuanceServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/server/DccReissuanceServerModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/server/data/DccReissuanceRequestBody.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/server/data/DccReissuanceResponse.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/server/validation/DccReissuanceServerCertificateValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/check/DccTicketingServerCertificateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentSetup.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/dccreissuance/DccReissuanceCDNServerModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/dccreissuance/DccReissuanceServerURL.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/interceptor/RetryInterceptor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/covidcertificate/RecycledCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/http/OkHttpExtension.kt
  Corona-Warn-App/src/main/res/values-de/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_reissuance_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/CovidCertificateConfigMapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/environment/EnvironmentSetupTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModelTest.kt
  prod_environments.json
Labels: maintainers, author merge

#4878 Replace certificate (EXPOSUREAPP-11940)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccQrCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/RecoveryQrCodeTestData.java
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
Labels: maintainers
