Repository corona-warn-app/cwa-app-android, pull requests merged in 2022-09, with the labels that each got.

#5524 Missing connecting lines in high risk details screen (EXPOSUREAPP-9664)
  Corona-Warn-App/src/main/res/layout/tracing_details_item_behavior_increased_view.xml
Labels: bug, maintainers

#5526 Fix: Self checkin flow (EXPOSUREAPP-11253)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/onboarding/CheckInOnboardingFragment.kt
Labels: bug, maintainers

#5525 Catch error reported on Google Play (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/DccExportAllOverviewFragment.kt
Labels: bug, maintainers

#5523 UQS tooltip (EXPOSUREAPP-12295)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/installTime/InstallTimeProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/main/CWASettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/OnboardingSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest2.kt
Labels: bug, maintainers

#5527 Adapt ids (EXPOSUREAPP-13861)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/AdmissionStatusCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/MaskRequirementsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationInfoCard.kt
  Corona-Warn-App/src/main/res/layout/confirmed_status_card.xml
  Corona-Warn-App/src/main/res/layout/mask_requirements_card.xml
  Corona-Warn-App/src/main/res/layout/vaccination_info_card.xml
Labels: bug, maintainers

#5532 Update legal_strings.xml (EXPOSUREAPP-13812)
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
Labels: text change

#5531 Update risk_details_strings.xml (EXPOSUREAPP-13812)
  Corona-Warn-App/src/main/res/values-de/risk_details_strings.xml
Labels: text change

#5530 Update strings.xml (EXPOSUREAPP-13812)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#5533 Update privacy_de.html (EXPOSUREAPP-13812)
  Corona-Warn-App/src/main/assets/privacy_de.html
Labels: text change

#5534 Update strings.xml (EXPOSUREAPP-13826)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text issue

#5535 Update antigen_strings.xml
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
Labels: text issue

#5510 Adjust foreground risk calc (EXPOSUREAPP-13155)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeData.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/TracingData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/initializer/InitializerModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/TracingRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/RiskCalculationState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/TracingProgress.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/states/RiskCalculationCardState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/states/TracingStateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/risk/TracingFailedBox.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/risk/TracingProgressBox.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/homecards/TracingFailedCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/homecards/TracingProgressCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ForegroundRiskCalculationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/WatchdogService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/device/BackgroundModeStatus.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AndroidModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ProcessLifecycle.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/ViewExtensions.kt
  Corona-Warn-App/src/main/res/layout/tracing_content_failed_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_low_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_content_progress_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_item_additional_information_view.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/InitializersTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/ForegroundRiskCalculationServiceTest.kt
Labels: maintainers

#5539 Update Snakeyaml to `v1.31` (DEV)
  Corona-Warn-App/build.gradle
Labels: bug, maintainers

#5536 Sort certs for wallet assignment (EXPOSUREAPP-13503)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
Labels: maintainers

#5543 Update Google allowlist information in README (Community)
  README.md
Labels: community

#5541 Move Trace Location strings to event_registration_strings(EXPOSUREAPP-6993)
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: enhancement, maintainers

#5538 Red negative buttons (EXPOSUREAPP-13864)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/DebugLogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditLocationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditPersonsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/location/ContactDiaryAddLocationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/person/ContactDiaryAddPersonFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/ui/qrcode/ProfileQrCodeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/dialog/RecycleBinDialogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/dialog/RecycleBinDialogType.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/CheckInsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/TraceLocationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DialogHelper.kt
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
Labels: bug, maintainers

#5547 Translation Delivery (#5545)
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-pl/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-ro/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-tr/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-uk/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-uk/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-uk/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-uk/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#5546 Update strings.xml (EXPOSUREAPP-13828)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text issue

#5544 Certificate Reissuing Consent Screen has no "Further Data" indicator (EXPOSUREAPP-13313)
  Corona-Warn-App/src/main/res/layout/fragment_dcc_reissuance_consent.xml
Labels: enhancement, maintainers

#5549 Bump to next Version 2.27.0.2
  gradle.properties
Labels: maintainers

#5548 Fix App icon (EXPOSUREAPP-13890)
  Corona-Warn-App/src/main/res/drawable-v24/ic_launcher_foreground.xml
Labels: bug, maintainers

#5552 Provide installation days (EXPOSUREAPP-9825)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/states/RiskCalculationCardState.kt
Labels: bug, maintainers

#5554 Fix GH issue #5404 (DEV)
  .github/pull_request_template.md
Labels: enhancement, maintainers

#5555 Remove any reference for GH issue #332 (DEV)
  .github/pull_request_template.md
  README.md
Labels: enhancement, maintainers

#5556 User friendly version (EXPOSUREAPP-5641)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragmentViewModel.kt
Labels: enhancement, maintainers

#5551 Add missing statistics info screen strings (EXPOSUREAPP-13847)
  Corona-Warn-App/src/main/res/layout/fragment_statistics_explanation.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers, text change

#5553 Migrate to java time CCL (EXPOSUREAPP-13898)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ccl/ui/text/CclTextFormatterTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/model/CclConfiguration.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/model/CclDefaultInputParameters.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/update/CclConfigurationUpdater.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/update/CclSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccadmission/calculation/DccAdmissionCheckScenariosCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManager.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/ui/text/CclTextFormatter.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/common/CclConfigurationParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/update/CclConfigurationUpdaterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/update/CclSettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccadmission/calculation/DccAdmissionCheckScenariosCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/CclDateTimeTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManagerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationTest.kt
Labels: enhancement, maintainers

#5561 Update covid_certificate_strings.xml (EXPOSUREAPP-13924)
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#5563 Upgrade snakeyaml v1.32(EXPOSUREAPP-13926)
  Corona-Warn-App/build.gradle
Labels: bug, maintainers

#5560 RAT family registration flow (EXPOSUREAPP-13919)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentFragment.kt
Labels: bug, maintainers

#5564 Fix translation 2.27 (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/LocationTracingStatusCardBodyTextView.kt
  Corona-Warn-App/src/main/res/values-bg/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-uk/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#5558 [UI] Omitted G-status(EXPOSUREAPP-13900)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest2.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/TestData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/gstatus/notification/GStatusNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/layout/include_certificate_overview_qr_card.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/gstatus/notification/GStatusNotificationServiceTest.kt
Labels: bug, maintainers

#5570 Bump to next Version 2.27.0.3
  gradle.properties
Labels: maintainers

#5572 AGP 7.3 (DEV)
  Corona-Warn-App/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: maintainers

#5573 Add back installation counter (EXPOSUREAPP-13706)
  Corona-Warn-App/src/main/res/layout/tracing_details_item_periodlogged_view.xml
Labels: maintainers

#5574 Unify bottom buttons margins (EXPOSUREAPP-8989)
  Corona-Warn-App/src/main/res/layout/bugreporting_debuglog_fragment.xml
  Corona-Warn-App/src/main/res/layout/certificate_pdf_export_info_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_add_location_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_add_person_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_locations_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_persons_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_passed_fragment.xml
  Corona-Warn-App/src/main/res/layout/export_all_certs_pdf_info_fragment.xml
  Corona-Warn-App/src/main/res/layout/fragment_confirm_check_in.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_reissuance_consent.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_reissuance_success.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_consent_one.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_consent_two.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_ticketing_validation_result.xml
  Corona-Warn-App/src/main/res/layout/fragment_edit_check_in.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_delta_ppa.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_ppa.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_reset.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_contact.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_result_ready.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_tan.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_available.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_negative.xml
  Corona-Warn-App/src/main/res/layout/new_release_info_screen_fragment.xml
  Corona-Warn-App/src/main/res/layout/notifications_delta_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/profile_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/profile_qr_code_fragment.xml
  Corona-Warn-App/src/main/res/layout/survey_consent_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_create_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_qr_code_detail_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_qr_code_info_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_trace_locations_warn_list_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_warn_duration_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_warn_info_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_warn_tan_fragment.xml
Labels: enhancement, maintainers

#5540 PPA exposure risk metadata (EXPOSUREAPP-5863)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/risk/storage/RiskResultDatabaseTest.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/risklevel/ui/TestRiskLevelCalculationFragmentCWAViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposureriskmetadata/ExposureRiskMetadataDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/PtRiskLevelResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/storage/PresenceTracingRiskRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/CombinedEwPtRisk.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/EwRiskLevelResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/BaseRiskLevelStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/RiskLevelStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/internal/RiskResultDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/states/TracingStateProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/ExposureRiskMetadataDonorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/AnalyticsKeySubmissionCollectorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsTestResultCollectorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/changedetection/CombinedRiskLevelChangeDetectorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/storage/BaseRiskLevelStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProviderTest.kt
  Corona-Warn-App/src/testDevice/java/de/rki/coronawarnapp/test/risk/storage/DefaultRiskLevelStorageTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/risk/storage/DefaultRiskLevelStorageTest.kt
Labels: bug, maintainers

#5577 Update release_info_strings.xml
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: text change

#5571 Onboarding exposure notification popup (EXPOSUREAPP-13903)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragmentViewModel.kt
Labels: bug, maintainers

#5578 Bump to next Version 2.27.0.4
  gradle.properties
Labels: maintainers

#5579 Update release_info_strings.xml
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: text issue

#5575 Difficulties with leaving the "Enter Symptoms" screen (EXPOSUREAPP-13918)
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
Labels: bug, maintainers

#5576 Move booster rules to files dir (EXPOSUREAPP-13503)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/storage/DccBoosterRulesStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterRulesRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationCache.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/storage/DccBoosterRulesStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterRulesRepositoryTest.kt
Labels: bug, maintainers

#5582 Fix: Mask 😷 requirements (EXPOSUREAPP-13967, EXPOSUREAPP-13965)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/MaskRequirementsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/layout/include_certificate_overview_qr_card.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoParserTest.kt
Labels: bug, maintainers

#5583 Pdf export templates disclaimer (EXPOSUREAPP-13964)
  Corona-Warn-App/src/main/assets/template/rc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/tc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/vc_v4.1.svg
Labels: maintainers

#5584 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#5585 chore: update default CCL configuration to v3.3.0-rc.6
  Corona-Warn-App/src/main/assets/ccl/ccl-configuration.bin
Labels: maintainers

#5580 Fixes GH issue #5460 (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/CheckInsFragment.kt
  Corona-Warn-App/src/main/res/navigation/trace_location_attendee_nav_graph.xml
Labels: bug, maintainers

#5586 Parcelize Admission scenarios (EXPOSUREAPP-13961)
  Corona-Warn-App/proguard-rules.pro
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccadmission/storage/DccAdmissionCheckScenariosRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/admission/AdmissionScenariosSharedViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/admission/AdmissionScenariosViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/admission/model/AdmissionScenarios.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccadmission/storage/DccAdmissionCheckScenariosRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/admission/AdmissionScenariosViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
Labels: bug, maintainers, prio

#5588 Emphasize UI actions by adding arrow indicator (EXPOSUREAPP-12854)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/MoreInformationView.kt
  Corona-Warn-App/src/main/res/layout/view_more_information.xml
Labels: maintainers

#5591 Bump to next Version 2.27.1.1
  gradle.properties
Labels: maintainers

#5590 Change toggle selection key based on vaccination certificates (EXPOSUREAPP-13985)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
Labels: bug, maintainers, prio

#5592 Bump to next Version 2.27.2.0
  gradle.properties
Labels: maintainers

#5589 Process rebirth on environment change (EXPOSUREAPP-13973)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/EnvironmentSunset.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModelTest.kt
Labels: bug, maintainers

#5594 Mask Feature - Layout issue in UK (EXPOSUREAPP-13982)
  Corona-Warn-App/src/main/res/layout/mask_requirements_card.xml
Labels: bug, maintainers

#5595 Day since installation (EXPOSUREAPP-13983)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/periodlogged/PeriodLoggedBox.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers

#5596 Delete dialog missing (EXPOSUREAPP-13864)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
Labels: bug, maintainers

#5598 PPA Submission: after Risk Level Change the Database Attribute “risk_level_changed” has a wrong Value (EXPOSUREAPP-14008))
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposureriskmetadata/ExposureRiskMetadataDonor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/ExposureRiskMetadataDonorTest.kt
Labels: bug, maintainers

#5597 Change dialogs in onboarding flow (EXPOSUREAPP-13993)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragment.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph_onboarding.xml
Labels: maintainers

#5600 chore : Fix/unique name mdc
  .github/workflows/release_candidate.yml
Labels: maintainers, Fix 2.28

#5599 Use raw date values (EXPOSUREAPP-14006)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/CertificateDataInjector.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/pdf/core/CertificateDataInjectorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/DccExportAllOverviewViewModelTest.kt
Labels: bug, maintainers

#5601 Fix/tsi upload
  .github/workflows/release_candidate.yml
Labels: maintainers

#5603 Bump to next Version 2.28.0.1
  gradle.properties
Labels: maintainers

#5606 Fix/mdc version as name
  .github/workflows/release_candidate.yml
Labels: maintainers

#5608 Fix/pipeline typo
  .github/workflows/release_candidate.yml
Labels: bug
