Repository corona-warn-app/cwa-app-android, pull requests merged in 2022-03, with the labels that each got.

#4877 Certificate Reissuance wiring (EXPOSUREAPP-11939,11942)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CclTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_ccl.xml
  Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/processor/DccReissuanceProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/reissuer/DccReissuer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/reissuer/DccSwapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/server/DccReissuanceServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/server/validation/DccReissuanceServerCertificateValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentViewModel.kt
  Corona-Warn-App/src/main/res/layout/fragment_dcc_reissuance_consent.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/main/res/values-bg/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-de/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-pl/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-ro/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-tr/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccQrCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/RecoveryQrCodeTestData.java
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/core/reissuer/DccReissuerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/core/reissuer/DccSwapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentViewModelTest.kt
Labels: maintainers, text change

#4882 Fix: New line separators are not working as expected (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/ui/text/CclTextFormatter.kt
Labels: bug, maintainers

#4885 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-tr/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#4883 Adjust Info Screen To Announce New Release Features 2.19 (EXPOSUREAPP-11622)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers

#4886 Update accessibility link (EXPOSUREAPP-11968)
  Corona-Warn-App/src/main/res/values-de/links.xml
  Corona-Warn-App/src/main/res/values/links.xml
Labels: maintainers

#4872 Migration of Vaccination Storage (EXPOSUREAPP-11724)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/boosterinfodetails/BoosterInfoDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CertificateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPerson.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationMigration.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/ContainerPostProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/StoredVaccinationCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinatedPersonData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinatedPersonTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationCertificateContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationGroupingTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/scanner/QrCodeValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/covidcertificate/RecycledCertificatesProviderTest.kt
Labels: maintainers

#4887 Bump to next Version 2.19.0.2
  gradle.properties
Labels: maintainers

#4888 Replace vaccination certificate (EXPOSUREAPP-11940)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CertificateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/reissuer/DccSwapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/covidcertificate/RecycledCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationCertificateContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/core/reissuer/DccSwapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/handler/DccQrCodeHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/scanner/QrCodeValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/covidcertificate/RecycledCertificatesProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/worker/WorkerBinderTest.kt
Labels: maintainers

#4889 Dismiss dcc reissuance badge automatically (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/notification/DccReissuanceNotificationService.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/notification/DccReissuanceNotificationServiceTest.kt
Labels: bug, maintainers, prio

#4891 Protocol Buffer update for release 2.20.x at Thu Mar 3 10:36:33 UTC 2022
  Server-Protocol-Buffer/src/main/proto/internal/v2/corona_test_parameters.proto
  Server-Protocol-Buffer/src/main/proto/internal/v2/presence_tracing_parameters.proto
  Server-Protocol-Buffer/src/main/proto/internal/v2/risk_calculation_parameters.proto
Labels: maintainers

#4881 Inform user about migrated certificate grouping (EXPOSUREAPP-11988)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/MigrationCheck.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/main/CWASettings.kt
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/MigrationCheckTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
Labels: maintainers, prio, text change

#4894 Bump to next Version 2.19.0.3
  gradle.properties
Labels: maintainers

#4879 Unit tests replacement (EXPOSUREAPP-11940)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/server/validation/DccReissuanceServerCertificateValidator.kt
  Corona-Warn-App/src/main/res/layout/fragment_information.xml
  Corona-Warn-App/src/main/res/values-bg/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-pl/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-ro/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-tr/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccQrCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/RecoveryQrCodeTestData.java
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
Labels: maintainers

#4890 Reissuance Api tests (EXPOSUREAPP-12072)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/server/validation/DccReissuanceServerCertificateValidator.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/core/error/DccReissuanceExceptionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/core/processor/DccReissuanceProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/core/server/DccReissuanceServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/core/server/validation/DccReissuanceServerCertificateValidatorTest.kt
Labels: maintainers

#4898 Unit test improvements (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/MigrationCheck.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/MigrationCheckTest.kt
Labels: maintainers

#4895 Run risk calculation regardless of test result (EXPOSUREAPP-12114)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/execution/PresenceTracingWarningTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/risk/execution/PresenceTracingWarningTaskTest.kt
Labels: maintainers

#4901 Default app config adjustment (EXPOSUREAPP-12071)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CovidCertificateConfigMapper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/CovidCertificateConfigMapperTest.kt
Labels: maintainers

#4900 FIX: App crash when marking cert. as personal cert. (EXPOSUREAPP-12116)
  Corona-Warn-App/proguard-rules.pro
Labels: bug, maintainers, prio

#4896 Update config (EXPOSUREAPP-12119)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/ExposureWindowRiskCalculationConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/PresenceTracingRiskCalculationParamContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/ExposureWindowRiskCalculationConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/PresenceTracingConfigMapper.kt
Labels: maintainers

#4897 Repositories improvements (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorage.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorageTest.kt
Labels: maintainers

#4902 CertificateToReissue first (EXPOSUREAPP-12130)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/processor/DccReissuanceProcessor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/core/processor/DccReissuanceProcessorTest.kt
Labels: maintainers, prio

#4903 Bump to next Version 2.19.0.4
  gradle.properties
Labels: maintainers

#4904 Risk encounters in contact journal shouldn't be clickable (EXPOSUREAPP-12058)
  Corona-Warn-App/src/main/res/drawable/contact_diary_card_ripple.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_day_list_item_contact.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_day_list_item_risk_enf.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_day_list_item_risk_event.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_day_list_item_test_results.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_list_item.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
Labels: maintainers

#4909 Align date formatting (EXPOSUREAPP-11285)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/CwaUserCard.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/CwaUserCardKtTest.kt
Labels: bug, maintainers

#4911 Screenshot tests - Reissuance (EXPOSUREAPP-11943)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccreissuance/ui/success/DccReissuanceSuccessFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
Labels: maintainers

#4913 Addition to "Überblick" > "Infektionsrisiko" (EXPOSUREAPP-11246)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4914 Fix: badges in release build ( EXPOSUREAPP-12111, EXPOSUREAPP-12112)
  Corona-Warn-App/proguard-rules.pro
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/model/PersonSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/model/SettingsMap.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesStorageTest.kt
Labels: bug, maintainers, prio

#4899 Filter exposure windows (EXPOSUREAPP-12119)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/ENFClient.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/ENFClientTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/ExposureWindowFilterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskLevelTaskTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/nearby/modules/exposurewindow/ExposureWindowProviderTest.kt
Labels: maintainers

#4916 Order high prio certificate (EXPOSUREAPP-12163)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: maintainers

#4918 Bump to next Version 2.19.0.5
  gradle.properties
Labels: maintainers

#4848 Adapt privacy notice for 2.19 (EXPOSUREAPP-11616)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers, prio

#4915 Reissuance - additonal error handling (EXPOSUREAPP-11618)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/error/DccReissuanceException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/server/DccReissuanceServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/server/data/DccReissuanceErrorResponse.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/core/error/DccReissuanceExceptionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/core/server/DccReissuanceServerTest.kt
Labels: maintainers, prio

#4919 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#4912 Remove more positive test checks (EXPOSUREAPP-12114)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/CoronaTestRepositoryExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/execution/PresenceTracingRiskWorkScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/changedetection/CombinedRiskLevelChangeDetector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/execution/ExposureWindowRiskWorkScheduler.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/deadman/DeadmanNotificationSchedulerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskLevelTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/changedetection/CombinedRiskLevelChangeDetectorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/changedetection/EwRiskLevelChangeDetectorTest.kt
Labels: maintainers

#4910 Show high risk card when having a positive test result (EXPOSUREAPP-12115)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/CoronaTestConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CoronaTestConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/CoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RACoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/CoronaTestTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RapidAntigenCoronaTestExtensionsTest.kt
Labels: maintainers

#4922 Requesting DCC are not deletable (EXPOSUREAPP-12091)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/execution/TestCertificateRetrievalScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/execution/TestCertificateRetrievalWorker.kt
Labels: bug, maintainers

#4924 Partially untranslated screenshot of PersonOverviewFragment (EXPOSUREAPP-11996)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
Labels: bug, maintainers

#4927 Extend keycache db (EXPOSUREAPP-12212)
  Corona-Warn-App/schemas/de.rki.coronawarnapp.diagnosiskeys.storage.KeyCacheDatabase/2.json
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheDatabaseMigrationTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/CachedKeyInfo.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheDatabaseMigration1To2.kt
Labels: maintainers, Fix 2.19

#4928 Recovery Cert Change - meaningful information (EXPOSUREAPP-12063)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinOverviewFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/cards/DccTicketingRecoveryCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/res/layout/dcc_ticketing_recovery_card.xml
  Corona-Warn-App/src/main/res/layout/fragment_recovery_certificate_details.xml
  Corona-Warn-App/src/main/res/layout/recovery_certificate_card.xml
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_attribute_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: maintainers

#4923 trigger App Automation Testing
  .circleci/config.yml
Labels: maintainers

#4930 Delta key file download and submission (EXPOSUREAPP-12213)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheDatabaseTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/BaseKeyPackageSyncTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/DayPackageSyncTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/HourPackageSyncTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyPackageSyncTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/diagnosiskeyprovider/DefaultDiagnosisKeyProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/BaseKeyPackageSyncToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyPackageSyncToolTest.kt
Labels: maintainers

#4921 Show additional high risk notifications (EXPOSUREAPP-12064)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/changedetection/CombinedRiskLevelChangeDetector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/changedetection/EwRiskLevelChangeDetector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/RiskLevelStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/TracingSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeAndDateExtensions.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/changedetection/CombinedRiskLevelChangeDetectorTest.kt
Labels: maintainers, text change

#4931 Delete checked files (EXPOSUREAPP-12214)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/keydownload/ui/KeyDownloadTestFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/BaseKeyPackageSyncTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/DayPackageSyncTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/HourPackageSyncTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyDownloadTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyPackageSyncTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/CachedKeyInfo.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/BaseKeyPackageSyncToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/CommonSyncToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/DayPackageSyncToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/HourPackageSyncToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyDownloadToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyPackageSyncToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheRepositoryTest.kt
Labels: maintainers

#4936 Bump to next Version 2.19.1.0
  gradle.properties
Labels: maintainers

#4935 Update screenshots (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/TracingData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/overview/MainOverviewFragment.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProviderTest.kt
Labels: ui, maintainers

#4929 [FEATURE] ENF delta (EXPOSURAPP-12210)
  Corona-Warn-App/schemas/de.rki.coronawarnapp.diagnosiskeys.storage.KeyCacheDatabase/2.json
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheDatabaseMigrationTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheDatabaseTest.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/keydownload/ui/KeyDownloadTestFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/BaseKeyPackageSyncTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/DayPackageSyncTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/HourPackageSyncTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyDownloadTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyPackageSyncTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/CachedKeyInfo.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheDatabaseMigration1To2.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/diagnosiskeyprovider/DefaultDiagnosisKeyProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/BaseKeyPackageSyncToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/CommonSyncToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/DayPackageSyncToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/HourPackageSyncToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyDownloadToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyPackageSyncToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/storage/KeyCacheRepositoryTest.kt
Labels: maintainers, prio, Fix 2.19

#4939 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#4937 Certificate tiles spacing (DEV)
  Corona-Warn-App/src/main/res/layout/recovery_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/test_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/vaccination_certificate_card.xml
Labels: bug, maintainers

#4934 [Fix] Correct destination for warn others notification (EXPOSUREAPP-12203)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotification.kt
Labels: bug, maintainers

#4926 Notification for g status change (EXPOSUREAPP-12061)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/database/DccWalletInfoDatabaseTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/model/PersonSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/AdmissionStatusCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/gstatus/notification/GStatusNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/gstatus/ui/GStatusModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/res/layout/confirmed_status_card.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/gstatus/notification/GStatusNotificationServiceTest.kt
  Corona-Warn-App/src/test/resources/ccl/dcc_wallet_info_output.json
  Corona-Warn-App/src/test/resources/ccl/dcc_wallet_info_output_with_reissuance.json
  Corona-Warn-App/src/test/resources/ccl/dcc_wallet_info_plural_indexed.json
Labels: maintainers

#4933 Bottom bar style (EXPOSUREAPP-12225)
  Corona-Warn-App/src/main/res/layout/activity_main.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: ui, maintainers

#4941 Adjust Info Screen To Announce New Release Features 2.20 (EXPOSUREAPP-12082)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#4938 Don't trigger high-to-low-risk notification if the low-risk card is not displayed (EXPOSUREAPP-12244)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/CoronaTestRepositoryExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/CoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskCardDisplayInfo.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/changedetection/CombinedRiskLevelChangeDetector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/CoronaTestRepositoryExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/CoronaTestTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskCardDisplayInfoTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/changedetection/CombinedRiskLevelChangeDetectorTest.kt
Labels: maintainers, author merge

#4945 Bump to next Version 2.19.1.1
  gradle.properties
Labels: maintainers

#4944 Bump to next Version 2.20.0.1
  gradle.properties
Labels: maintainers

#4943 Round `normalizedTime` (EXPOSUREAPP-12211)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/DefaultRiskLevels.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/math/Math.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/math/MathTest.kt
  Corona-Warn-App/src/test/resources/exposure-windows-risk-calculation.json
Labels: bug, maintainers, prio, Fix 2.19.1

#4906 Filter checkIns by max age (EXPOSUREAPP-12120)
  Corona-Warn-App/schemas/de.rki.coronawarnapp.presencetracing.risk.storage.PresenceTracingRiskDatabase/2.json
  Corona-Warn-App/src/device/java/de/rki/coronawarnapp/risk/storage/DefaultRiskLevelStorage.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/risk/storage/DefaultRiskLevelStorage.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/presencetracing/ui/PresenceTracingTestViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/risklevel/ui/TestRiskLevelCalculationFragmentCWAViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/ConfigChangeDetector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/ExposureWindowRiskCalculationConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/ExposureStateUpdateWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/CheckInsFilter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/PtRiskLevelResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/execution/PresenceTracingWarningTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/storage/PresenceTracingRiskDaos.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/storage/PresenceTracingRiskDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/storage/PresenceTracingRiskRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/EwRiskLevelTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/ExposureWindowsFilter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/execution/ExposureWindowRiskWorkScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/BaseRiskLevelStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/RiskLevelStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/internal/RiskCombinator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/TracingRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/common/CalculationsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/ExposureRiskMetadataDonorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/risk/execution/CheckInAgeFilterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/risk/execution/PresenceTracingWarningTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/risk/storage/PresenceTracingRiskRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/CombinedEwPtRiskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/EwRiskLevelTaskConfigTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/EwRiskLevelTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/changedetection/CombinedRiskLevelChangeDetectorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/changedetection/EwRiskLevelChangeDetectorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/storage/BaseRiskLevelStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/storage/RiskStorageTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/storage/internal/PersistedRiskResultDaoTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/storage/internal/RiskCombinatorTest.kt
  Corona-Warn-App/src/testDevice/java/de/rki/coronawarnapp/test/risk/storage/DefaultRiskLevelStorageTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/risk/storage/DefaultRiskLevelStorageTest.kt
Labels: maintainers, prio

#4950 Update language and service hours of technical hotline (EXPOSUREAPP-12349)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#4948 Family Test skeleton P2 (EXPOSUREAPP-12323)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/TestRegistrationRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/qrcode/CoronaTestQRCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/CoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/FamilyTestModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/model/FamilyTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/repository/FamilyTestRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/FamilyTestUiModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/TestRegistrationStateProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/TestRegistrationStateProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
Labels: maintainers

#4955 Fix homescreen from not loading (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/repository/FamilyTestRepository.kt
Labels: maintainers, prio

#4956 Bump to next Version 2.20.0.2
  gradle.properties
Labels: maintainers

#4957 Bump to next Version 2.19.1.2
  gradle.properties
Labels: maintainers

#4960 Anonymous Rat Fix (EXPOSUREAPP-12353)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/qrcode/rapid/RapidQrCodeExtractor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/qrcode/rapid/RapidAntigenQrCodeExtractorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/qrcode/rapid/RapidPcrQrCodeExtractorTest.kt
Labels: maintainers, prio

#4958 Keep version 1.5 for kotlinx-coroutines-test (EXPOSUREAPP-12194)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/attendee/confirm/ConfirmCheckInViewModelTest.kt
Labels: maintainers

#4965 Bump to next Version 2.19.2.0
  gradle.properties
Labels: maintainers

#4962 No G status shown after grouping different names to one person (EXPOSUREAPP-12365)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManager.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManagerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentViewModelTest.kt
Labels: bug, maintainers, prio, Fix 2.19.2

#4949 PPA: do not overwrite test result received on subsequent polling (EXPOSUREAPP-12185)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/AnalyticsKeySubmissionCollector.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/AnalyticsKeySubmissionCollectorTest.kt
Labels: bug, maintainers

#4968 Bump to next Version 2.19.2.1
  gradle.properties
Labels: maintainers

#4967 FIX: Risk from high to low message shows 14 days instead of 10 (EXPOSUREAPP-12362)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
Labels: bug, maintainers, prio, text change

#4966 Fix G status badge dismiss (EXPOSUREAPP-12359)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
Labels: bug, maintainers, prio

#4970 CoronaTest refactoring (EXPOSUREAPP-12330)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultConsentGivenFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNoConsentGivenFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/CoronaTestRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/CoronaTestRepositoryExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/migration/PCRTestMigration.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/storage/CoronaTestStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/CoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/CoronaTestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRCoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRTestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RACoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RATestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/model/FamilyCoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/model/FamilyTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/repository/FamilyTestRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/coronatest/RecycledCoronaTestsProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/TestResultUIState.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/CoronaTestRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/execution/TestCertificateRetrievalSchedulerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest2.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/cleanup/RecycleBinCleanUpServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskCardDisplayInfoTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/task/SubmissionTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/testresult/pending/SubmissionTestResultPendingViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/consent/CheckInsConsentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/testavailable/SubmissionTestResultAvailableViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/yourconsent/SubmissionYourConsentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/worker/PCRResultRetrievalWorkerTest.kt
Labels: maintainers

#4973 Bump to next Version 2.20.0.3
  gradle.properties
Labels: maintainers

#4961 Add family test tile on homescreen (EXPOSUREAPP-12314)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/homecard/FamilyTestCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_family_test.xml
  Corona-Warn-App/src/main/res/drawable/ic_family_test.xml
  Corona-Warn-App/src/main/res/layout/family_test_card.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values/family_tests_strings.xml
Labels: maintainers, text change

#4969 No G status after persons merge (EXPOSUREAPP-12365)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/update/CclConfigurationUpdater.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/update/CclSettings.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/update/CclConfigurationUpdaterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/update/CclSettingsTest.kt
Labels: bug, maintainers, prio, Fix 2.19.2

#4974 Text change "Neue Funktionen"
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: text change

#4953 Request dcc family tests (EXPOSUREAPP-12355)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/execution/TestCertificateRetrievalScheduler.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/execution/TestCertificateRetrievalSchedulerTest.kt
Labels: maintainers

#4975 Skip first bulletpoint in new release screen (EXPOSUREAPP-12399)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoFragment.kt
Labels: bug, maintainers, prio

#4976 Room db upgrade (EXPOSUREAPP-12190)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposurewindows/AnalyticsExposureWindowDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/storage/PresenceTracingRiskDaos.kt
Labels: maintainers

#4978 Screenshots - x1q (DEV)
  .circleci/config.yml
Labels: maintainers

#4981 chore: update default CCL configuration to 1.2
  Corona-Warn-App/src/main/assets/ccl/ccl-configuration.bin
Labels: maintainers

#4964 Upgrade cameraX libs (EXPOSUREAPP-12189)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerPreviewView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerFragment.kt
Labels: maintainers

#4977 Update text / consent icons (EXPOSUREAPP-12313)
  Corona-Warn-App/src/main/res/drawable-night/ic_qr_1x_test.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_star_checkmark.xml
  Corona-Warn-App/src/main/res/drawable/ic_qr_1x_test.xml
  Corona-Warn-App/src/main/res/drawable/ic_star_checkmark.xml
  Corona-Warn-App/src/main/res/layout/include_submission_consent_intro.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: ui, maintainers, text change

#4988 Inserted variable
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4951 [UI] Family test selection and consent screen (EXPOSUREAPP-12316, EXPOSUREAPP-12317)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/familytest/ui/selection/TestRegistrationSelectionFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/selection/TestRegistrationSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/selection/TestRegistrationSelectionModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/selection/TestRegistrationSelectionNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/selection/TestRegistrationSelectionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/coroutine/CoronaTestQRCodeExtensions.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_family_consent_cert_item.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_family_consent_illustration.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_family_item.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_family_test_selection_item.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_person_test_selection_item.xml
  Corona-Warn-App/src/main/res/drawable/ic_family_consent_cert_item.xml
  Corona-Warn-App/src/main/res/drawable/ic_family_consent_illustration.xml
  Corona-Warn-App/src/main/res/drawable/ic_family_item.xml
  Corona-Warn-App/src/main/res/drawable/ic_family_test_selection_item.xml
  Corona-Warn-App/src/main/res/drawable/ic_person_test_selection_item.xml
  Corona-Warn-App/src/main/res/layout/fragment_family_test_consent.xml
  Corona-Warn-App/src/main/res/layout/fragment_test_registration_selection.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/coronatest/CoronaTestQRCodeExtensionsTest.kt
Labels: ui, maintainers, text change

#4990 Bump to next Version 2.20.1.0
  gradle.properties
Labels: maintainers

#4991 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#4979 Deeplinking/QRHandler - Single source of truth (EXPOSUREAPP-11884, 12331)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/handler/CoronaTestQRCodeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/coronatest/handler/CoronaTestRestoreEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/coronatest/handler/CoronaTestRestoreHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/coronatest/handler/RestoreCoronaTestConfirmationDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/MainActivityEvent.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest2.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/handler/CoronaTestQRCodeHandlerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/coronatest/handler/CoronaTestRestoreHandlerTest.kt
Labels: maintainers

#4994 Improvements (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/DccWalletInfoRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/CoronaTestRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRTestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RATestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/repository/FamilyTestRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/DccWalletInfoRepositoryTest.kt
Labels: maintainers

#4996 Revocation - API, Repository, Provider (EXPOSUREAPP-12303, 12310)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/update/CclConfigurationUpdater.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/update/CclConfigurationUpdaterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationRepositoryTest.kt
Labels: maintainers

#4989 Family Tests in recycle bin ♻️(EXPOSUREAPP-12322)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinOverviewFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/CoronaTestRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/repository/FamilyTestRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/coronatest/RecycledCoronaTestsProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/CoronaTestCard.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_family_test_recycled.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_personal_test_recycled.xml
  Corona-Warn-App/src/main/res/drawable/ic_family_test_recycled.xml
  Corona-Warn-App/src/main/res/drawable/ic_personal_test_recycled.xml
  Corona-Warn-App/src/main/res/values-de/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values/recycler_bin_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/CensorInjectionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/CoronaTestRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest2.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/coronatest/RecycledCoronaTestsProviderTest.kt
Labels: maintainers, text change

#5001 Additional MD3 updates (EXPOSUREAPP-11341)
  Corona-Warn-App/src/main/res/layout/contact_diary_day_fragment.xml
  Corona-Warn-App/src/main/res/layout/notifications_delta_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_warn_duration_fragment.xml
  Corona-Warn-App/src/main/res/layout/validation_start_fragment.xml
  Corona-Warn-App/src/main/res/values-v28/styles.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers

#4997 Family test badges (EXPOSUREAPP-12315)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/familytest/core/storage/FamilyTestDatabaseTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/CoronaTestRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/TestRegistrationRequest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/BaseCoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRCoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RACoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/model/CoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/model/FamilyCoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/repository/CoronaTestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/repository/FamilyTestRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/storage/FamilyTestDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/storage/FamilyTestStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/homecard/FamilyTestCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/coronatest/RecycledCoronaTestsProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/SerializationModule.kt
  Corona-Warn-App/src/main/res/drawable/circle_certificate_notification_badge.xml
  Corona-Warn-App/src/main/res/layout/family_test_card.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/CensorInjectionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/CoronaTestRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/storage/CoronaTestStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/familytest/core/model/FamilyCoronaTestTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/familytest/core/repository/FamilyTestRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/familytest/core/repository/FamilyTestResultChangeTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest2.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/coronatest/RecycledCoronaTestsProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateViewModelTest.kt
Labels: maintainers

#4998 Revocation - by InvalidationRules (EXPOSUREAPP-12311, 12308)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/database/DccWalletInfoDatabaseTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManager.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoInput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManagerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoInputTest.kt
Labels: maintainers, author merge

#5007 Bump to next Version 2.20.2.0
  gradle.properties
Labels: maintainers

#5005 FIX: Dcc reissuance url (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/ui/text/CclTextFormatter.kt
  prod_environments.json
Labels: bug, maintainers, prio

#5004 Map blocked state from DccWalletInfo and remove code that is now obsolete (EXPOSUREAPP-12420, EXPOSUREAPP-12308)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/database/DccWalletInfoDatabaseTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/DccWalletInfoRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/BlocklistValidator.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/BlocklistValidatorTest.kt
Labels: maintainers

#5008 Clean up outdated family tests in recycle bin on App start (EXPOSUREAPP-12481)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/familytest/core/storage/FamilyTestDatabaseTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/storage/FamilyTestDatabase.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/cleanup/RecycleBinCleanUpServiceTest.kt
Labels: maintainers

#5011 Update CclConfigurationApi (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/server/CclConfigurationApiV1.kt
Labels: maintainers

#5013 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-bg/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-pl/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-ro/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-tr/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-uk/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: text change

#5016 Bump to next Version 2.21.0.1
  gradle.properties
Labels: maintainers

#5003 Family test result change notifications (EXPOSUREAPP-12333)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/model/FamilyCoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/notification/FamilyTestNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/repository/FamilyTestRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/NotificationConstants.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/familytest/core/notification/FamilyTestResultNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/familytest/core/repository/FamilyTestRepositoryTest.kt
Labels: maintainers
