Repository corona-warn-app/cwa-app-android, pull requests merged in 2022-01, with the labels that each got.

#4636 Bump copyright year in README.md (Community)
  README.md
Labels: documentation, community

#4635 Replace information in LICENSE with placeholder (Community)
  LICENSE
  LICENSES/Apache-2.0.txt
Labels: community

#4639 Kotlin 1.6.10 / Clean up 🧹 (DEV)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/ConfirmedStatusCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/DefaultPlaybook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/organizer/submission/server/OrganizerSubmissionServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/warning/storage/TraceWarningPackageContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/server/SubmissionServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingNotificationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTestFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/items/ActiveCheckInVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/items/PastCheckInVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/items/TraceLocationVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionContactFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/resultready/SubmissionResultReadyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/submissiondone/SubmissionDoneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultConsentGivenFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/TestResultSectionView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  build.gradle
Labels: enhancement, maintainers

#4638 Links refactoring part 2 (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/StatisticsExplanationFragment.kt
  Corona-Warn-App/src/main/res/values-de/links.xml
  Corona-Warn-App/src/main/res/values-de/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/links.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: enhancement, maintainers

#4643 Fix: Remove double space (EXPOSUREAPP-11120)
  Corona-Warn-App/src/main/res/values-de/recycler_bin_strings.xml
Labels: bug, maintainers, text change

#4637 Remove `Activity.goBack()` (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTestFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragment.kt
Labels: enhancement, maintainers

#4644 VC issued by italy can be printed (EXPOSUREAPP-11155)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/CertificateExportHelper.kt
Labels: bug, maintainers

#4645 Change capitalozation of birthdate in negative RAT result (EXPOSUREAP-11159)
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
Labels: bug, maintainers

#4647 FIx: 2G+ with RAT text (EXPOSUREAPP-11153)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/ConfirmedStatusCard.kt
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: bug, maintainers, text change

#4640 Only schedule the 'warn others' notification once the user has actually viewed the test (EXPOSUREAPP-10432)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotificationService.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotificationServiceTest.kt
Labels: bug, maintainers

#4646 Correct "accept" in TR (EXPOSUREAPP-11124)
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
Labels: bug, maintainers, text change

#4653 Onboarding Notifications
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4652 Tyopos corrected
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#4651 Typo corrected
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: text change

#4648 Scanning issues - for boofCV POC (EXPOSUREAPP-11146)
  Corona-Warn-App/src/androidTest/assets/dcc-test-data/empty_image.png
  Corona-Warn-App/src/androidTest/assets/dcc-test-data/working_qr_code.png
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/qrcode/parser/QrCodeBoofCVParserTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/parser/QrCodeBoofCVParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/parser/QrCodeCameraImageParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerPreviewView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/parser/QrCodeCameraImageParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
Labels: maintainers

#4590 [Feature branch] boofCV scanner (EXPOSUREAPP-10502)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/proguard-rules.pro
  Corona-Warn-App/src/androidTest/assets/dcc-test-data/empty_image.png
  Corona-Warn-App/src/androidTest/assets/dcc-test-data/working_qr_code.png
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/qrcode/parser/QrCodeBoofCVParserTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragmentTest.kt
  Corona-Warn-App/src/main/AndroidManifest.xml
  Corona-Warn-App/src/main/assets/technical.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/parser/QrCodeBoofCVParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerPreviewView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/qrcode/QrViewfinderView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/BuildVersionWrap.kt
  Corona-Warn-App/src/main/res/layout/fragment_qrcode_scanner.xml
  Corona-Warn-App/src/main/res/layout/qr_code_scanner_preview_view.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentViewModelTest.kt
  docs/architecture-overview.md
Labels: enhancement, maintainers

#4659 Display persons count in test menu (DEV)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_menu.xml
Labels: enhancement, maintainers

#4655 Fix wrong back navigation from consent to pending test result (EXPOSUREAPP-10236)
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
Labels: bug, maintainers

#4663 Fix: App Crash when rendering Increased Risk card (EXPOSUREAPP-11213)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/TracingCardInfoRow.kt
Labels: bug, maintainers, prio

#4658 Fix cut title in certificates info screen (EXPOSUREAPP-10175)
  Corona-Warn-App/src/main/res/layout/fragment_cov_pass_info.xml
Labels: bug, maintainers

#4662 Add translation comments identifier descriptions to strings.xml (DEV)
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#4664 Bump to next Version 2.16.0.6
  gradle.properties
Labels: maintainers

#4666 Update hotline time (EXPOSUREAPP-11221)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, prio, text change

#4665 Fix: Unknown statistics type, enhance logs
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/StatisticsProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/HashExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/source/StatisticsProviderTest.kt
Labels: bug, maintainers

#4649 Restore statistics state (EXPOSUREAPP-11082)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/lists/modular/mods/SavedStateMod.kt
Labels: bug, maintainers

#4670 Bump to next Version 2.16.1.0
  gradle.properties
Labels: maintainers

#4671 Quarantine 14 --> 10 days
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#4672 FIX: low risk with exposures has encreased risk content (EXPOSUREAPP-11231)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/additionalinfos/FindDetailsInJournalBox.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/additionalinfos/FindDetailsInJournalBoxIncreasedRisk.kt
  Corona-Warn-App/src/main/res/layout/tracing_details_find_details_in_journal_increased_risk.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers, prio, text change

#4674 Camera permission handling (EXPOSUREAPP-11227)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/MainActivityEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/permission/CameraPermissionProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/permission/CameraSettings.kt
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/permission/CameraPermissionProviderTest.kt
Labels: maintainers

#4681 Adjust Info Screen to announce new Release-Features for 2.16 (EXPOSUREAPP-10768)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, prio, text change

#4679 Adjust Info Screen to announce new Release-Features for 2.17 (EXPOSUREAPP-11152)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#4661 Add social media home menu item (EXPOSUREAPP-11192)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_menu_social_media.xml
  Corona-Warn-App/src/main/res/drawable/ic_menu_social_media.xml
  Corona-Warn-App/src/main/res/menu/menu_main.xml
  Corona-Warn-App/src/main/res/values-de/links.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/links.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#4683 Remove ".de"
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/DccTicketingCoreModule.kt
Labels: maintainers

#4656 Fix text styling differences with figma for certificates (EXPOSUREAPP-10219)
  Corona-Warn-App/src/main/res/layout/fragment_vaccination_details.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
  Corona-Warn-App/src/main/res/layout/include_expiration_notice_card.xml
  Corona-Warn-App/src/main/res/layout/recovery_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/test_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/vaccination_certificate_card.xml
Labels: bug, maintainers

#4642 Add app shortcuts to primary targets (closes #2858)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/AppShortcuts.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/shortcuts/AppShortcutsHelper.kt
  Corona-Warn-App/src/main/res/drawable/ic_certificates_shortcut_icon.xml
  Corona-Warn-App/src/main/res/drawable/ic_check_ins_shortcut_icon.xml
  Corona-Warn-App/src/main/res/drawable/ic_contact_diary_shortcut_icon.xml
  Corona-Warn-App/src/main/res/drawable/ic_qr_code_scanner_shortcut_icon.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: community

#4693 Shape drawables for G status badge (EXPOSUREAPP-11402)
  Corona-Warn-App/src/main/res/drawable/ic_admission_badge_1.xml
  Corona-Warn-App/src/main/res/drawable/ic_admission_badge_2.xml
  Corona-Warn-App/src/main/res/drawable/ic_admission_badge_3.xml
Labels: maintainers, prio

#4694 Bump to next Version 2.16.2.0
  gradle.properties
Labels: maintainers

#4691 Fix: CameraX native crash + Transition (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerPreviewView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
Labels: bug, maintainers

#4680 Statistics for boosters (EXPOSUREAPP-10765)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/StatsItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/StatisticsParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsCardAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/PersonsVaccinatedWithBoosterCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/formatter/FormatterStatistics.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_vaccinated_completely.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_vaccinated_once.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_vaccinated_with_booster.xml
  Corona-Warn-App/src/main/res/drawable/ic_vaccinated_completely.xml
  Corona-Warn-App/src/main/res/drawable/ic_vaccinated_once.xml
  Corona-Warn-App/src/main/res/drawable/ic_vaccinated_with_booster.xml
  Corona-Warn-App/src/main/res/layout/fragment_statistics_explanation.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_vaccinated_with_booster_layout.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#4675 risk content better (dev)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/additionalinfos/FindDetailsInJournalBox.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/additionalinfos/FindDetailsInJournalBoxIncreasedRisk.kt
  Corona-Warn-App/src/main/res/layout/tracing_details_find_details_in_journal.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_find_details_in_journal_increased_risk.xml
Labels: maintainers

#4667 Final deletion date for Recycler Bin (EXPOSUREAPP-10766)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/cleanup/RecycleBinCleanUpService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/common/Recyclable.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/CoronaTestCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/common/RecyclerBinCertificateItemBinding.kt
  Corona-Warn-App/src/main/res/layout/recycler_bin_certificate_item.xml
  Corona-Warn-App/src/main/res/values-de/recycler_bin_strings.xml
  Corona-Warn-App/src/main/res/values/recycler_bin_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/cleanup/RecycleBinCleanUpServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/common/RecyclableTest.kt
Labels: maintainers, text change, author merge

#4696 Update CBOR lib to latest version (EXPOSUREAPP-11339)
  Corona-Warn-App/build.gradle
Labels: maintainers

#4692 Empty certirficates screen, focusable illustration (EXPOSUREAPP-8668)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/res/layout/person_overview_fragment.xml
Labels: bug, maintainers, accessibility

#4676 Text changes positive test result (EXPOSUREAPP-11128)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/submissiondone/SubmissionDoneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultKeysSharedFragment.kt
  Corona-Warn-App/src/main/res/drawable/ic_risk_details_cross.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_positive_keys_shared.xml
  Corona-Warn-App/src/main/res/layout/home_submission_pcr_status_card_positive_shared.xml
  Corona-Warn-App/src/main/res/layout/home_submission_rapid_status_card_positive_shared.xml
  Corona-Warn-App/src/main/res/layout/include_submission_behaviour_row.xml
  Corona-Warn-App/src/main/res/layout/include_submission_done_content.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#4708 Screenshot creation fix (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinOverviewFragmentTest.kt
Labels: maintainers

#4702 FIX: Incorrect display of AdmissionState badge on Person Detail View (EXPOSUREAPP-11428)
  Corona-Warn-App/src/main/res/layout/confirmed_status_card.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_overview_qr_card.xml
Labels: bug, ui, maintainers

#4703 Fix tab items low contrast (EXPOSUREAPP-9817)
  Corona-Warn-App/src/main/res/values/colors.xml
Labels: bug, maintainers, accessibility

#4711 Bump to next Version 2.17.0.1
  gradle.properties
Labels: maintainers

#4701 Improve home screen keyboard focus (EXPOSUREAPP-9695)
  Corona-Warn-App/src/main/res/color/button_back.xml
  Corona-Warn-App/src/main/res/layout/activity_main.xml
  Corona-Warn-App/src/main/res/layout/home_fragment_layout.xml
Labels: bug, maintainers, accessibility

#4698 FIX: Valid DCC cannot be registered after App Reset (EXPOSUREAPP-11349)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/ui/onboarding/CovidCertificateOnboardingViewModel.kt
Labels: bug, maintainers

#4715 QR scanner torch accessibility description (EXPOSUREAPP-8681)
  Corona-Warn-App/src/main/res/layout/fragment_qrcode_scanner.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers, accessibility, text change

#4717 Bump to next Version 2.17.0.2
  gradle.properties
Labels: maintainers

#4721 Fix typos in mock German booster message (EXPOSUREAPP-11528) (COMMUNITY)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
Labels: mirrored-to-jira, community, text change

#4726 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#4716 CCL Skeleton (EXPOSUREAPP-11478)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/CCLModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/model/CCLConfiguration.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/server/CCLConfigurationApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/server/CCLConfigurationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/storage/CClConfigurationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/update/CCLConfigurationUpdateScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/DccWalletInfoProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfo.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DummyWalletInfo.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/DccWalletInfoRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/text/TextResource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTrigger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/main/res/drawable/ic_admission_badge_1.xml
  Corona-Warn-App/src/main/res/drawable/ic_admission_badge_2.xml
  Corona-Warn-App/src/main/res/drawable/ic_admission_badge_3.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_overview_qr_card.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProviderTest.kt
  Corona-Warn-App/src/test/resources/ccl/dcc_wallet_info.json
Labels: maintainers

#4731 Include JFN jar (EXPOSUREAPP-11465)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/libs/cwa-kotlin-jfn-1.0.0-SNAPSHOT-b4cf025.jar
Labels: maintainers

#4733 Fix: Incorrect display of AdmissionState badge on Person Detail View (EXPOSUREAPP-11428)
  Corona-Warn-App/src/main/res/layout/confirmed_status_card.xml
Labels: bug, maintainers

#4737 Bump to next Version 2.17.0.3
  gradle.properties
Labels: maintainers

#4738 Word "Uhr" missing in recycle bin note
  Corona-Warn-App/src/main/res/values-de/recycler_bin_strings.xml
Labels: text change

#4736 Create default params for CCL (EXPOSUREAPP-11484)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/CclDefaultInputParameters.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculation.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/CclDateTimeTest.kt
Labels: maintainers

#4741 Upgrade agp & related to 7.1.0 (DEV)
  Corona-Warn-App/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: maintainers

#4734 Resolve url (EXPOSUREAPP-11507)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/text/UrlResource.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/text/UrlResourceKtTest.kt
Labels: maintainers

#4727 Certificates screen with loading state (EXPOSUREAPP-11502)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/res/layout/person_overview_fragment.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
Labels: maintainers, text change

#4748 Bump to next Version 2.17.1.0
  gradle.properties
Labels: maintainers

#4739 Store dcc wallet info (EXPOSUREAPP-11485)
  Corona-Warn-App/schemas/de.rki.coronawarnapp.ccl.dccwalletinfo.storage.database.DccWalletInfoDatabase/1.json
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/database/DccWalletInfoDatabaseTest.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CCLTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CCLTestModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CCLTestViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainActivityTestModule.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_ccl.xml
  Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/CCLModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/DccWalletInfoProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/PersonWalletInfo.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/DccWalletInfoRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/database/DccWalletInfoConverter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/database/DccWalletInfoDao.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/database/DccWalletInfoDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/database/DccWalletInfoEntity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/DccWalletInfoRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
Labels: maintainers

#4749 Expose DccWalletInfo (DEV)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CCLTestViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/DccWalletInfoProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/DccWalletInfoRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/DccWalletInfoRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: maintainers

#4745 Bind Dcc wallet info in person details screen (EXPOSUREAPP-11499)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CCLTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/ccl/CCLTestViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_ccl.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/text/UrlResource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/ConfirmedStatusCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationInfoCard.kt
  Corona-Warn-App/src/main/res/layout/vaccination_info_card.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: ui, maintainers
