Repository corona-warn-app/cwa-app-android, pull requests merged in 2022-12, with the labels that each got.

#5738 Update srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values-de/srs_submission_strings.xml
Labels: text change

#5739 Family Tests - RAT dates - List view vs. detail view (EXPOSUREAPP-14316)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/items/FamilyTestListCard.kt
Labels: bug, maintainers

#5742 Update antigen_strings.xml
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
Labels: text issue

#5743 Update strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text issue

#5744 Add truncated submission dialog and 429 error (EXPOSUREAPP-14366)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/error/SrsSubmissionException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/error/SrsSubmissionTruncatedException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/server/SrsSubmissionServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/dialogs/SrsSubmissionTruncatedDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionViewModel.kt
  Corona-Warn-App/src/main/res/values-bg/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values-de/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values-pl/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values-ro/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values-tr/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values-uk/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values/srs_submission_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/server/SrsSubmissionServerTest.kt
Labels: maintainers, text change

#5745 Add new pandemic radar strings (EXPOSUREAPP-14375)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/StatsItem.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#5746 Pandemic radar url language handling (EXPOSUREAPP-14375)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
Labels: maintainers

#5750 Bump to next version 3.0.0.4
  gradle.properties
Labels: maintainers

#5749 Fix checkins consent screen nav (EXPOSUREAPP-14387, 14388)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/CheckInsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/onboarding/CheckInOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/TraceLocationEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/TraceLocationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/TraceLocationsViewModel.kt
  Corona-Warn-App/src/main/res/navigation/trace_location_attendee_nav_graph.xml
Labels: bug, maintainers

#5751 Update Consent legal text of `EN` and `TR` (EXPOSUREAPP-14294)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/eventregistration/organizer/TraceLocationsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/consent/SrsConsentDetailFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragment.kt
  Corona-Warn-App/src/main/res/layout/srs_consent_detail_fragment.xml
  Corona-Warn-App/src/main/res/navigation/srs_nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: maintainers, text change

#5752 Bump to next version 3.0.0.5
  gradle.properties
Labels: maintainers

#5753 Fix: srs error(EXPOSURE-APP 14395)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/HttpModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/SrsSubmissionModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/server/SrsAuthorizationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/server/SrsSubmissionApi.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/server/SrsAuthorizationServerTest.kt
Labels: bug, maintainers

#5755 Bump to next version 3.0.0.6
  gradle.properties
Labels: maintainers

#5761 Add cancel button for srs consent screen (EXPOSUREAPP-14456)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_srs_submission_consent.xml
Labels: maintainers

#5757 Update privacy note (EXPOSUREAPP-14425)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers, text change

#5758 Reset otp after submission (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/server/SrsAuthorizationServer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepositoryTest.kt
Labels: maintainers, prio

#5762 Bump to next version 3.0.0.7
  gradle.properties
Labels: maintainers

#5760 Cert info screen not showing up after onboarding (EXPOSUREAPP-14415)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/ui/onboarding/CovidCertificateOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/ui/onboarding/CovidCertificateOnboardingViewModel.kt
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
Labels: bug, maintainers

#5765 Pandemic radar button spacing (EXPOSUREAPP-14428)
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_link_card_layout.xml
Labels: bug, maintainers

#5764 Grey arrows in dispatcher screen (EXPOSUREAPP-14430)
  Corona-Warn-App/src/main/res/layout/fragment_submission_dispatcher.xml
Labels: bug, maintainers

#5763 No srs submission retry (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/SrsSubmissionModule.kt
Labels: maintainers

#5767 Bump to next version 3.0.0.8
  gradle.properties
Labels: maintainers

#5768 Flush tek cache (EXPOSUREAPP-14490)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_submission.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/data/tekhistory/TEKHistoryUpdater.kt
Labels: bug, maintainers

#5769 Bump to next version 3.0.0.9
  gradle.properties
Labels: maintainers

#5773 Missing presence tracing (EXPOSUREAPP-14413)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/consent/CheckInsConsentViewModel.kt
Labels: bug, maintainers

#5774 Remove tan warn others (EXPOSUREAPP-14492)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/TraceLocationsFragment.kt
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_qr_code_info_fragment.xml
  Corona-Warn-App/src/main/res/menu/menu_trace_location_organizer_list.xml
Labels: maintainers

#5772 Swap faq/ok buttons in SRS error dialog (EXPOSUREAPP-144399)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionDispatcherFragment.kt
Labels: bug, maintainers

#5771 Show FAQ button in qr scanner error dialog (EXPOSUREAPP-144333)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/ui/onboarding/CovidCertificateOnboardingErrorDialogs.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/ui/onboarding/CovidCertificateOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
Labels: bug, maintainers

#5775 Fix: SRS Consent Screen text (EXPOSUREAPP-14483)
  Corona-Warn-App/src/main/res/layout/fragment_srs_submission_consent.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
Labels: bug, maintainers, text change

#5770 SRS : Teks on fly (EXPOSUREAPP-14489)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragmentTest.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_submission.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/model/TekPatch.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/vm/TeksSharedViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/data/tekhistory/TEKHistoryUpdater.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/model/TekPatchTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/ui/symptoms/calnedar/SrsSymptomsCalendarViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/ui/symptoms/introduction/SrsSymptomsIntroductionViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/data/tekhistory/TEKHistoryUpdaterTest.kt
Labels: bug, maintainers

#5776 Bump to next Version 3.0.0.10
  gradle.properties
Labels: maintainers

#5778 Add Dev menu entry for first reliable time (EXPOSUREAPP-14498)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_submission.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionFragment.kt
Labels: bug, maintainers

#5779 Privacy notice for v3.0.0 (EXPOSUREAPP-14500)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers

#5780 Firebase App Distribution(EXPOSUREAPP-12797)
  .github/workflows/release_candidate.yml
  Gemfile
  Gemfile.lock
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/groups.txt
Labels: enhancement, maintainers
