Repository corona-warn-app/cwa-app-android, pull requests merged in 2022-08, with the labels that each got.

#5374 Unresponsive UI after continuous certificate deletion (EXPOSUREAPP-13660)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/FragmentExtensions.kt
Labels: bug, maintainers

#5402 Fix badge ID (EXPOSUREAPP-13464)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
Labels: bug, maintainers

#5403 Adjust text size and spacing on person details cards (EXPOSUREAPP-8805)
  Corona-Warn-App/src/main/res/layout/confirmed_status_card.xml
  Corona-Warn-App/src/main/res/layout/cwa_user_card_item.xml
  Corona-Warn-App/src/main/res/layout/vaccination_info_card.xml
Labels: bug, maintainers

#5406 Datepicker accessibility (EXPOSUREAPP-13678)
  Corona-Warn-App/src/main/res/layout/contact_diary_person_list_fragment.xml
  Corona-Warn-App/src/main/res/layout/duration_picker.xml
  Corona-Warn-App/src/main/res/values-bg/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-pl/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-ro/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-tr/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-uk/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
Labels: maintainers, accessibility, text change

#5407 Space adjustment (EXPOSUREAPP-13693)
  Corona-Warn-App/src/main/res/layout/include_certificate_overview_qr_card.xml
Labels: bug, maintainers

#5401 Register test back navigation (EXPOSUREAPP-12901)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentNavigationEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/selection/TestRegistrationSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentBackNavArg.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionNavigationEvents.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_consent.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentViewModelTest.kt
Labels: bug, maintainers

#5405 Submission flow symptoms screens (EXPOSUREAPP-13178)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomCalendarFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomIntroFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/SubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionViewModelTest.kt
Labels: maintainers

#5384 Fix days_since_onset_of_symptoms time zone (EXPOSUREAPP-13434)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/CheckInsTransformer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/task/DaysSinceOnsetOfSymptomsVectorDeterminer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/task/ExposureKeyHistoryCalculations.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/task/TransmissionRiskVectorDeterminator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/task/TransmissionRiskVectorDeterminer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/calendar/CalendarAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/calendar/CalendarCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/calendar/CalendarDayViewHolder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/calendar/CalendarView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/JavaTimeAndDateExtenstions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/JodaMigration.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeAndDateExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/CheckInsTransformerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/task/DaysSinceOnsetOfSymptomsVectorDeterminerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/task/ExposureKeyHistoryCalculationsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/task/TransmissionRiskVectorDeterminerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/calendar/CalendarCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarViewModelTest.kt
Labels: bug, maintainers

#5413 Bump to next Version 2.26.0.1
  gradle.properties
Labels: maintainers

#5412 Test certificate sort order on pdf export (EXPOSUREAPP-13708)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/DccExportFilter.kt
Labels: bug, maintainers

#5414 QR information screen navigation (EXPOSUREAPP-13680)
  Corona-Warn-App/src/main/res/layout/fragment_qrcode_scanner.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
Labels: bug, maintainers

#5411 "Exposure check failed" without internet connection despite previous successful check (EXPOSUREAPP-13383)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/internal/RiskCombinator.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/storage/BaseRiskLevelStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/storage/RiskStorageTestData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/storage/internal/RiskCombinatorTest.kt
Labels: bug, maintainers

#5417 Reject redeemed test while registering (EXPOSUREAPP-13676)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/repository/FamilyTestRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/familytest/core/repository/FamilyTestRepositoryTest.kt
Labels: bug, maintainers

#5416 Chore : Update libs ⬆️ (DEV)
  Corona-Warn-App/build.gradle
  build.gradle
Labels: maintainers

#5418 Remove time from location start and end dates in diary (EXPOSUREAPP-6443)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/common/CheckInExtension.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/common/CheckInExtensionTest.kt
Labels: bug, maintainers

#5420 Prettify svg templates for pdf export (EXPOSUREAPP-13635)
  Corona-Warn-App/src/main/assets/template/de_rc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/de_tc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/de_vc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/rc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/tc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/vc_v4.1.svg
Labels: bug, maintainers

#5419 Sort places and persons in contact journal (EXPOSUREAPP-8280)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/location/ContactDiaryLocationListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/person/ContactDiaryPersonListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartViewModel.kt
Labels: bug, maintainers

#5421 Fix flags in Dark mode (EXPOSUREAPP-4209)
  Corona-Warn-App/src/main/res/drawable/ic_country_be.xml
  Corona-Warn-App/src/main/res/drawable/ic_country_de.xml
  Corona-Warn-App/src/main/res/layout/view_country_list_entry_flag_container.xml
Labels: bug, maintainers

#5422 Fix: Warn on behalf back (EXPOSUREAPP-9461)
  Corona-Warn-App/src/main/res/navigation/trace_location_organizer_nav_graph.xml
Labels: bug, maintainers

#5423 [Warn on behalf] Display location address (EXPOSUREAPP-9314)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/duration/TraceLocationWarnDurationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/duration/TraceLocationWarnDurationViewModel.kt
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_warn_duration_fragment.xml
Labels: bug, maintainers

#5429 Content description ignored (EXPOSUREAPP-11537)
  Corona-Warn-App/src/main/res/layout/new_release_info_screen_fragment.xml
Labels: bug, maintainers

#5428 German translation for content description (EXPOSUREAPP-11542)
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: bug, maintainers, text change

#5427 Center certificates vertically (EXPOSUREAPP-13667)
  Corona-Warn-App/src/main/assets/template/de_rc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/de_tc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/de_vc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/rc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/tc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/vc_v4.1.svg
Labels: bug, maintainers

#5424 Information menu not easy to open (EXPOSUREAPP-13721)
  Corona-Warn-App/src/main/res/layout/home_fragment_layout.xml
  Corona-Warn-App/src/main/res/layout/person_overview_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_attendee_checkins_fragment.xml
Labels: bug, maintainers

#5431 Update new release strings (EXPOSUREAPP-13715)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#5425 Fix: re-grouping schema 1.3.2 (EXPOSUREAPP-13724, 13723)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CertificatePersonIdentifier.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/list/ListExt.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/holder/grouping/DccGroupingExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/holder/grouping/DccHolderComparisonTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/holder/grouping/DccHolderNameComponentsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/holder/grouping/TestCases.kt
  Corona-Warn-App/src/test/resources/dcc-holder-comparison.gen.json
Labels: bug, maintainers, prio

#5433 Bump to next Version 2.26.0.2
  gradle.properties
Labels: maintainers

#5434 Recyclebin view accessibility (EXPOSUREAPP-11536)
  Corona-Warn-App/src/main/res/layout/recycler_bin_overview_fragment.xml
Labels: bug, maintainers, accessibility

#5435 Main user switch turns off after renewing a certificate (EXPOSUREAPP-13695)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/reissuer/DccReissuer.kt
Labels: bug, maintainers

#5437 layout focusability (EXPOSUREAPP-11538)
  Corona-Warn-App/src/main/res/layout/bugreporting_debuglog_fragment.xml
Labels: bug, maintainers, accessibility

#5436 Adjust FAB style (EXPOSUREAPP-12612)
  Corona-Warn-App/src/main/res/drawable/ic_add.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: bug, maintainers

#5441 Text change (EXPOSUREAPP-13743)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers, text change

#5442 Improve item focusability in contact journal with Talkback (EXPOSUREAPP-11543)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/day/contact/ContactAdapter.kt
Labels: bug, maintainers, accessibility

#5440 Scan tab enabled (EXPOSUREAPP-11534)
  Corona-Warn-App/src/main/res/menu/menu_bottom_nav.xml
Labels: bug, maintainers, accessibility

#5432 Title of Views not announced when opening with Talkback (EXPOSUREAPP-11540)
  Corona-Warn-App/src/main/res/layout/covid_certificate_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_dispatcher.xml
  Corona-Warn-App/src/main/res/layout/profile_create_fragment.xml
  Corona-Warn-App/src/main/res/layout/profile_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/profile_qr_code_fragment.xml
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers, accessibility, text change

#5439 Event qr preview accessibility (EXPOSUREAPP-11541)
  Corona-Warn-App/src/main/res/layout/qr_code_poster_fragment.xml
  Corona-Warn-App/src/main/res/values-bg/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-pl/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-ro/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-tr/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-uk/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
Labels: bug, maintainers, accessibility, text change

#5443 Change GA test reporter (DEV)
  .github/workflows/build_and_test.yml
Labels: enhancement, maintainers

#5446 text change (EXPOSUREAPP-13745)
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
Labels: bug, maintainers, text change

#5445 text change (EXPOSUREAPP-13744)
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
Labels: bug, maintainers, text change

#5444 Share data talkback toggle (EXPOSUREAPP-11544)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/MoreInformationView.kt
Labels: bug, maintainers, accessibility

#5448 [INTERNAL] Translation delivery: commit by LX Lab (#5447)
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-bg/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-bg/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-bg/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-pl/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-pl/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-ro/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-ro/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-tr/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-tr/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-uk/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values-uk/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-uk/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values-uk/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-uk/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-uk/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/contact_diary_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/event_registration_strings.xml
  Corona-Warn-App/src/main/res/values/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#5450 Bump to next Version 2.26.0.3
  gradle.properties
Labels: maintainers

#5449 Set ids for test automation (EXPOSUREAPP-13750)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/TraceLocationsFragment.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_fragment.xml
  Corona-Warn-App/src/main/res/values/attrs.xml
Labels: bug, maintainers

#5453 Github Actions: Split RC jobs into two flows (DEV)
  .github/workflows/ReleaseCandidate.yml
  .github/workflows/build_and_test.yml
  .github/workflows/gradle-wrapper-validation.yml
  .github/workflows/release_candidate.yml
  .github/workflows/screenshots.yml
Labels: enhancement, maintainers

#5452 Upgrade `snakeyaml` to `v1.30` - fix high vulnerability (EXPOSUREAPP-13753)
  Corona-Warn-App/build.gradle
Labels: bug, maintainers

#5454 Warning on behalf: Teletan visible in error report(EXPOSUREAPP-9808)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/server/VerificationServer.kt
Labels: bug, maintainers

#5451 Stistics accessibility focus talkback on active statistics tyle when scrolling (EXPOSUREAPP-5136)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers, accessibility

#5456 Fix/fix automation job trigger
  .github/workflows/release_candidate.yml
Labels: maintainers

#5457 Fix: Input text UI contrast (EXPOSUREAPP-11532)
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: bug, ui, maintainers

#5459 Restrict minimum typical stay of Events to `15m` (EXPOSUREAPP-6764)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/durationpicker/DurationPicker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/create/TraceLocationCreateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/create/TraceLocationCreateViewModel.kt
Labels: bug, maintainers

#5415 Schedule deadman notification when ENF is disabled (EXPOSUREAPP-13154)
  Corona-Warn-App/src/androidTest/java/testhelpers/TestAndroidModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationTimeCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AndroidModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AppInstallTime.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/deadman/DeadmanNotificationSchedulerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/deadman/DeadmanNotificationTimeCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/worker/WorkerBinderTest.kt
Labels: bug, maintainers

#5455 Bump to next Version 2.26.0.4
  gradle.properties
Labels: maintainers

#5408 Fix navigation after test scanning (EXPOSUREAPP-12985)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomCalendarFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionSymptomIntroFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultAvailableFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/selection/TestRegistrationSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/resultavailable/SubmissionTestResultAvailableFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/resultavailable/SubmissionTestResultAvailableViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/resultready/SubmissionResultReadyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/submissiondone/SubmissionDoneFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/invalid/SubmissionTestResultInvalidFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/invalid/SubmissionTestResultInvalidViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultConsentGivenFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultKeysSharedFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultKeysSharedViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultNoConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentViewModel.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/testresult/pending/SubmissionTestResultPendingViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/testavailable/SubmissionTestResultAvailableViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentViewModelTest.kt
Labels: bug, maintainers

#5461 Reasonable dcc screenshots (EXPOSUREAPP-9299)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
Labels: bug, maintainers

#5462 Refine setting of toolbar menu ids (EXPOSUREAPP-13750)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/MaterialToolbarExtensions.kt
  Corona-Warn-App/src/main/res/values/attrs.xml
Labels: bug, maintainers

#5467 Adjust statistics cards layouts to better display text with large fonts (EXPOSUREAPP-8761)
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_applied_vaccination_rates_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_incidence_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_infections_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_keysubmissions_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_local_incidence_and_hospitalization_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_occupied_intensive_care_beds.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_sevendayrvalue_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_vaccinated_completely_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_vaccinated_once_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_vaccinated_with_booster_layout.xml
Labels: bug, maintainers

#5470 [INTERNAL] Translation delivery: commit by LX Lab (#5466)
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#5465 Fix server time parser on newer Android versions (EXPOSUREAPP-9077)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/sources/remote/AppConfigServer.kt
Labels: bug, maintainers

#5471 Reduce screen start and end margins to `16dp` (EXPOSUREAPP-13777)
  Corona-Warn-App/src/main/res/layout/merge_guidelines_side.xml
Labels: bug, maintainers

#5464 Home menu item position content description (EXPOSUREAPP-11535)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/MenuAccessibilityExtensions.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers, accessibility, text change

#5473 RAT test result texts (EXPOSUREAPP-12978)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_negative.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers, text change

#5474 Skip submission if test is already submitted (EXPOSUREAPP-10947)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/task/SubmissionTask.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/task/SubmissionTaskTest.kt
Labels: bug, maintainers

#5477 Fix Rapid antigen test timestamp (EXPOSUREAPP-7528)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RapidAntigenCoronaTestExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RapidAntigenCoronaTestExtensionsTest.kt
Labels: bug, maintainers

#5480 Error time format (EXPOSUREAPP-7387)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/upload/history/HistoryItemAdapter.kt
Labels: bug, maintainers

#5458 Add local statistics card talkback (EXPOSUREAPP-8653)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/LocalIncidenceAndHospitalizationCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/stateselection/FederalStateSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
Labels: bug, maintainers, accessibility

#5483 Hide empty textview (EXPOSUREAPP-13608)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultNoConsentFragment.kt
Labels: bug, maintainers

#5486 Wallet info mask state (EXPOSUREAPP-13800)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoParserTest.kt
  Corona-Warn-App/src/test/resources/ccl/dcc_wallet_info_output_with_mask_state.json
Labels: maintainers

#5484 Update covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text issue

#5489 Common colour scheme (EXPOSUREAPP-13746)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonColorShade.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
Labels: maintainers

#5488 New feature (EXPOSUREAPP-13807)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoViewModel.kt
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-uk/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
Labels: maintainers, text change

#5490 Improve state check (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
Labels: maintainers

#5476 DccValueSets language changes with system language (EXPOSUREAPP-8864)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/ValidationResultItemCreator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/businessrule/BusinessRuleVH.kt
Labels: bug, maintainers

#5487 Add plurals handling (EXPOSUREAPP-13427)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/ValidationResultItemCreator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/LazyString.kt
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-uk/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: bug, maintainers, text change

#5472 [Dcc Validation] Save user selection(EXPOSUREAPP-8469)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/BusinessValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicEngineWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/Mappings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/ValueSetWrapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/common/exception/DccValidationException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/rule/DccValidationRule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/settings/DccValidationSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/ValidationResultItemCreator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/TechnicalValidationFailedVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/JavaTimeAndDateExtenstions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeAndDateExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/DccValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/CertLogicEngineWrapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/MappingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/validation/core/settings/DccValidationSettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/reset/ResetTestComponent.kt
Labels: bug, maintainers

#5494 Business Rules - missing "Hinweise" on Screen "Zertifikat nicht prüfbar" ("open")
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/ValidationResultItemCreator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/open/DccValidationOpenViewModel.kt
Labels: bug, maintainers

#5492 New mask tile (EXPOSUREAPP-13804)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/MaskRequirementsCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonColorShade.kt
  Corona-Warn-App/src/main/res/layout/mask_requirements_card.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers, text change

#5497 Fix privacy notes paragraphs order (EXPOSUREAPP-13558)
  Corona-Warn-App/src/main/res/layout/trace_location_privacy_card.xml
Labels: bug, maintainers

#5496 Block keyboard typing in Duration Picker (EXPOSUREAPP-13642)
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: bug, maintainers

#5499 Heading not announced in onboarding (EXPOSUREAPP-11533)
  Corona-Warn-App/src/main/res/layout/fragment_onboarding.xml
Labels: bug, maintainers, accessibility

#5500 Terms of use hyperlinks (EXPOSUREAPP-8848)
  Corona-Warn-App/src/main/assets/terms_de.html
  Corona-Warn-App/src/main/assets/terms_en.html
  Corona-Warn-App/src/main/assets/terms_tr.html
Labels: bug, maintainers

#5504 Show "Accept" button (EXPOSUREAPP-6207)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/onboarding/CheckInOnboardingFragment.kt
Labels: bug, maintainers

#5506 Consider locale in building links (EXPOSUREAPP-10072)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TextViewUrlExtensions.kt
Labels: bug, maintainers

#5508 Shows "Installed yesterday" instead of "Installed 1 day ago" (EXPOSUREAPP-9825)
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers, text change

#5507 Darkmode illustration (EXPOSUREAPP-10457)
  Corona-Warn-App/src/main/res/drawable-night/rat_profile_onboarding.xml
  Corona-Warn-App/src/main/res/layout/profile_onboarding_fragment.xml
Labels: bug, maintainers

#5512 Button text (EXPOSUREAPP-10246)
  Corona-Warn-App/src/main/res/layout/home_submission_pcr_status_card_ready.xml
  Corona-Warn-App/src/main/res/layout/home_submission_rapid_status_card_ready.xml
Labels: bug, maintainers

#5491 Export single foreign Dcc (EXPOSUREAPP-13717)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/CertificateExportErrorDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/CertificateExportHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/links.xml
  Corona-Warn-App/src/main/res/values/links.xml
Labels: enhancement, maintainers

#5502 Privacy policy not displayed correctly on old devices (EXPOSUREAPP-7268)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/html/HtmlParser.kt
Labels: bug, maintainers

#5513 Fix inconsistent strings in recycle bin (EXPOSUREAPP-13472)
  Corona-Warn-App/src/main/res/values-de/recycler_bin_strings.xml
Labels: bug, maintainers, text change

#5493 Person overview mask badge (EXPOSUREAPP-13803)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/TestData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonColorShade.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/drawable/ic_admission_badge_1.xml
  Corona-Warn-App/src/main/res/drawable/ic_admission_badge_2.xml
  Corona-Warn-App/src/main/res/drawable/ic_admission_badge_3.xml
  Corona-Warn-App/src/main/res/drawable/ic_admission_badge_green.xml
  Corona-Warn-App/src/main/res/drawable/mask_badge_bg.xml
  Corona-Warn-App/src/main/res/drawable/no_mask_badge_bg.xml
  Corona-Warn-App/src/main/res/layout/confirmed_status_card.xml
  Corona-Warn-App/src/main/res/layout/include_certificate_overview_qr_card.xml
  Corona-Warn-App/src/main/res/layout/person_overview_item.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers

#5514 Img overlap (EXPOSUREAPP-10268)
  Corona-Warn-App/src/main/res/layout/fragment_cov_pass_info.xml
Labels: bug, maintainers

#5509 Separate date and time with commas (EXPOSUREAPP-13709)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/eventregistration/organizer/TraceLocationsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/ValidationResultItemCreator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/items/TraceLocationVH.kt
  Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml
Labels: bug, maintainers, text change

#5518 Change darkmode svg size (EXPOSUREAPP-9901)
  Corona-Warn-App/src/main/res/drawable-night/ic_main_illustration_untested.xml
Labels: bug, maintainers

#5521 Update strings.xml (EXPOSUREAPP-13835)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers, text change

#5520 Bump to next Version 2.27.0.1
  gradle.properties
Labels: maintainers

#5519 Mask tweaking (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonColorShade.kt
  Corona-Warn-App/src/main/res/drawable/ic_mask.xml
Labels: bug, maintainers
