Repository corona-warn-app/cwa-app-android, pull requests merged in 2022-10, with the labels that each got.

#5610 Update default text for scenario selection (EXPOSUREAPP-13968)
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: bug, maintainers, text change

#5604 Replace dialogs in MainActivity, HomeFragment (EXPOUSREAPP-13994)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/coronatest/handler/RestoreCoronaTestConfirmationDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/dialog/RecycleBinDialogs.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/TracingExplanationDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/dialog/DialogFragmentTemplateHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/popups/DeviceTimeIncorrectDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/errors/RecoveryByResetDialogFactory.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#5609 Clean up / Upgrade outdated libs(EXPOSUREAPP-14042)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/libs/cwa-kotlin-jfn-1.0.0-SNAPSHOT-1de55db.jar
  Corona-Warn-App/libs/cwa-kotlin-jfn-1.0.0-rc.0.jar
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/presencetracing/ui/poster/QrCodePosterTestViewModel.kt
  Corona-Warn-App/src/main/AndroidManifest.xml
  Corona-Warn-App/src/main/java/android/print/FilePrinter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/location/ContactDiaryAddLocationViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/person/ContactDiaryAddPersonViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/FamilyTestListFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/FamilyTestListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/CheckInsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/TraceLocationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/adapter/SubmissionCountrySelectionAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionCountrySelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionCountrySelectViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/AppBarLayout.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/SingleLiveEvent.kt
  Corona-Warn-App/src/main/res/drawable/top_app_bar_shape.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_rule_item.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_country_selection.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_applied_vaccination_rates_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_incidence_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_infections_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_keysubmissions_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_local_incidence_and_hospitalization_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_occupied_intensive_care_beds.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_sevendayrvalue_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_vaccinated_completely_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_vaccinated_once_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_vaccinated_with_booster_layout.xml
  Corona-Warn-App/src/main/res/layout/include_submission_country_item.xml
  Corona-Warn-App/src/main/res/layout/include_submission_country_no_selection.xml
  Corona-Warn-App/src/main/res/layout/include_submission_country_selector.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/sources/fallback/DefaultAppConfigTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/signature/core/storage/DefaultDscSourceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/common/DistrictsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/locations/server/DefaultQrCodePosterTemplateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/release/NewReleaseInfoFragmentTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/presencetracing/organizer/poster/QrCodePosterViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionCountrySelectViewModelTest.kt
  build.gradle
Labels: enhancement, maintainers

#5611 Update dialogs in submission flow (EXPOSUREAPP-13995)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/TracingConsentDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/settings/TracingSettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionCancelDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/resultavailable/SubmissionTestResultAvailableFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/resultready/SubmissionResultReadyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/invalid/SubmissionTestResultInvalidFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultConsentGivenFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultKeysSharedFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultNoConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/yourconsent/SubmissionYourConsentFragment.kt
Labels: maintainers

#5613 Translation delivery
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#5618 Update dialogs in certs tab (EXPOSUREAPP-13996(
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/DccExportAllOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/poster/CertificatePosterFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/ui/onboarding/CovidCertificateOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/common/DccValidationNoInternetErrorDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartFragment.kt
Labels: maintainers

#5620 Implement new link card (EXPOSUREAPP-14075)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/LinkViewCard.kt
  Corona-Warn-App/src/main/res/drawable-night/pandemic_radar.xml
  Corona-Warn-App/src/main/res/drawable/pandemic_radar.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_link_card_layout.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#5622 Adapt Screenshot tests (EXPOSUREAPP-14076)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/statistics/Statistics.kt
Labels: maintainers

#5617 `Feature` Pandemic Radar (EXPOSUREAPP-14073)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/statistics/Statistics.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/CombinedStatisticsProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/StatsItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/StatisticsParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/StatisticsProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsCardAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/LinkViewCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/StatisticsCardItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/res/drawable-night/pandemic_radar.xml
  Corona-Warn-App/src/main/res/drawable/pandemic_radar.xml
  Corona-Warn-App/src/main/res/layout/fragment_statistics_explanation.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_link_card_layout.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/CombinedStatisticsProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/StatisticsDataTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/source/StatisticsParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/source/StatisticsProviderTest.kt
Labels: maintainers

#5624 Diary onboarding screen arrow (EXPOSUREAPP-14089)
  Corona-Warn-App/src/main/res/layout/contact_diary_onboarding_fragment.xml
Labels: bug, maintainers

#5626 Code clean up (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/TestFragment.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/Screenshot.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/upload/history/HistoryItemAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/adapter/LocationEditAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/adapter/PersonEditAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/DiaryOverviewAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/day/coronatest/CoronaTestAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/day/riskevent/RiskEventAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/admission/AdmissionScenariosAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/ui/certificateselection/DccTicketingCertificateSelectionAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/FamilyTestListAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/ui/list/ProfileListAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/release/NewReleaseInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/RecyclerBinAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsCardAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/dialog/DialogFragmentTemplate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/CheckInsAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/consent/CheckInsConsentAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/category/adapter/TraceLocationCategoryAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/TraceLocationsAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/list/TraceLocationSelectionAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/Event.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/lists/modular/mods/StableIdMod.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/SingleLiveEvent.kt
  Corona-Warn-App/src/test/java/android/util/Log.java
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/DccWalletInfoCleanerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/modules/diagnosiskeyprovider/SubmissionQuotaTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/common/RecyclableTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskCardDisplayInfoTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/flow/HotDataFlowTest.kt
Labels: enhancement, maintainers

#5625 Popup stuck in back stack (EXPOSUREAPP-14088)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/dialog/DialogFragmentTemplate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/dialog/DialogFragmentTemplateHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragment.kt
Labels: bug, maintainers

#5628 Format time instead of Date twice (EXPOSUREAPP-14091)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/duration/TraceLocationWarnDurationFragment.kt
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_warn_duration_fragment.xml
Labels: bug, maintainers

#5627 Convert png to webp (DEV)
  Corona-Warn-App/src/main/res/drawable-hdpi/ic_notification_icon_default_small.png
  Corona-Warn-App/src/main/res/drawable-hdpi/ic_notification_icon_default_small.webp
  Corona-Warn-App/src/main/res/drawable-hdpi/ic_splash_logo_round.png
  Corona-Warn-App/src/main/res/drawable-hdpi/ic_splash_logo_round.webp
  Corona-Warn-App/src/main/res/drawable-ldpi/ic_splash_logo_round.png
  Corona-Warn-App/src/main/res/drawable-ldpi/ic_splash_logo_round.webp
  Corona-Warn-App/src/main/res/drawable-mdpi/ic_notification_icon_default_small.png
  Corona-Warn-App/src/main/res/drawable-mdpi/ic_notification_icon_default_small.webp
  Corona-Warn-App/src/main/res/drawable-mdpi/ic_splash_logo_round.png
  Corona-Warn-App/src/main/res/drawable-mdpi/ic_splash_logo_round.webp
  Corona-Warn-App/src/main/res/drawable-xhdpi/ic_notification_icon_default_small.png
  Corona-Warn-App/src/main/res/drawable-xhdpi/ic_notification_icon_default_small.webp
  Corona-Warn-App/src/main/res/drawable-xhdpi/ic_splash_logo_round.png
  Corona-Warn-App/src/main/res/drawable-xhdpi/ic_splash_logo_round.webp
  Corona-Warn-App/src/main/res/drawable-xxhdpi/ic_notification_icon_default_small.png
  Corona-Warn-App/src/main/res/drawable-xxhdpi/ic_notification_icon_default_small.webp
  Corona-Warn-App/src/main/res/drawable-xxhdpi/ic_splash_logo_round.png
  Corona-Warn-App/src/main/res/drawable-xxhdpi/ic_splash_logo_round.webp
  Corona-Warn-App/src/main/res/drawable-xxxhdpi/ic_notification_icon_default_small.png
  Corona-Warn-App/src/main/res/drawable-xxxhdpi/ic_notification_icon_default_small.webp
  Corona-Warn-App/src/main/res/drawable-xxxhdpi/ic_splash_logo_round.png
  Corona-Warn-App/src/main/res/drawable-xxxhdpi/ic_splash_logo_round.webp
Labels: enhancement, maintainers

#5631 Update release text 2.28 (EXPOSUREAPP-14079)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#5630 Delete unused resources (DEV)
  Corona-Warn-App/src/main/res/drawable-night/ic_test_result_delete_test.xml
  Corona-Warn-App/src/main/res/drawable/card_white_bottom_rounded_corners.xml
  Corona-Warn-App/src/main/res/drawable/ic_rat_profile_create_card_illustration.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_details_health_department.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_details_no_lugage.xml
  Corona-Warn-App/src/main/res/drawable/ic_risk_details_shopping.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_austria.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_czech.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_denmark.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_estonia.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_italy.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_latvia.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_netherlands.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_poland.xml
  Corona-Warn-App/src/main/res/drawable/ic_submission_country_flag_spain.xml
  Corona-Warn-App/src/main/res/drawable/ic_test_result_delete_test.xml
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/links.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/main/res/values/links.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers

#5634 Update date of privacy changes (EXPOSUREAPP-14109)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: bug, maintainers

#5635 Export all certificates visible although no certificate available (EXPOSUREAPP-14111)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
Labels: bug, maintainers

#5636 Fix loading detection tracking data (EXPOSUREAPP-14112)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/detectiontracker/ExposureDetectionTrackerStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/adapter/LegacyInstantDeserializer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/modules/detectiontracker/ExposureDetectionTrackerStorageTest.kt
  Corona-Warn-App/src/test/resources/detectionJavaTime/calcuation_tracker/calculations.json
  Corona-Warn-App/src/test/resources/detectionLegacy/calcuation_tracker/calculations.json
Labels: bug, maintainers

#5638 Focus newly added local stats tile (EXPOSUREAPP-14115)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
Labels: maintainers

#5642 Pandemic radar info text change (EXPOSUREAPP-14132)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, text change

#5641 Fix statistics scroll (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
Labels: bug, maintainers

#5643 Fix spacing between Pandemicradar button icon and text (EXPOSUREAPP-14131)
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_link_card_layout.xml
Labels: bug, maintainers

#5645 Hide keyboard (EXPOSUREAPP-14119)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/tan/TraceLocationWarnTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/SubmissionTanFragment.kt
Labels: bug, maintainers

#5644 Adjust time constraint (EXPOSUREAPP-14118)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/create/TraceLocationCreateFragment.kt
Labels: bug, maintainers

#5647 Fix cancel button (EXPOSUREAPP-14137)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/CheckInsFragment.kt
Labels: bug, maintainers

#5650 Fix flags (EXPOSUREAPP-14135)
  Corona-Warn-App/src/main/res/drawable/ic_country_be.xml
  Corona-Warn-App/src/main/res/drawable/ic_country_de.xml
  Corona-Warn-App/src/main/res/layout/view_country_list_entry_flag_container.xml
Labels: bug, maintainers

#5651 Change delete button color (EXPOSUREAPP-13864)
  Corona-Warn-App/src/main/res/layout/covid_test_error_card.xml
Labels: bug, maintainers

#5653 Fix revocation list on release builds (EXPOSUREAPP-14117)
  Corona-Warn-App/proguard-rules.pro
Labels: bug, maintainers

#5649 Add/change ids for testing (EXPOSUREAPP-14120)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/eventregistration/organizer/QrCodeDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/eventregistration/organizer/TraceLocationsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/category/TraceLocationCategoryFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/category/adapter/category/TraceLocationCategoryVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/create/TraceLocationCreateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/details/QrCodeDetailFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/TraceLocationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/items/TraceLocationVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/TraceLocationWarnInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/duration/TraceLocationWarnDurationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/list/TraceLocationSelectionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/list/items/TraceLocationVH.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/tan/TraceLocationWarnTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/MaterialToolbarExtensions.kt
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_category_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_category_item.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_qr_code_detail_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_trace_locations_item.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_trace_locations_warn_item.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_warn_duration_fragment.xml
  Corona-Warn-App/src/main/res/values/attrs.xml
Labels: bug, maintainers

#5655 App includes note that health authority will ask for list of contacts (EXPOSUREAPP-14134)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers, text change

#5658 Bump to next Version 2.28.1.0
  gradle.properties
Labels: maintainers

#5657 Homescreen delete test dialog (EXPOSUREAPP-14204)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
Labels: bug, maintainers

#5659 Bump to next Version 2.28.2.0
  gradle.properties
Labels: maintainers

#5660 Fix crash / remove the faulty dialog (EXPOSUREAPP-14192)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/dialog/DialogFragmentTemplateHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentFragment.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers, prio

#5661 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: text change

#5663 Alternative to the current dialog builder using a DSL builder (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/dialog/CwaDialog.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/dialog/CwaDialogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/dialog/CwaDialogHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
Labels: maintainers

#5665 Fix: Installation time
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/installTime/InstallTimeProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AndroidModule.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/installTime/InstallTimeProviderTest.kt
Labels: bug, maintainers

#5666 Bump to next Version 2.28.3.0
  gradle.properties
Labels: maintainers

#5669 Upgrade AGP (DEV)
  build.gradle
Labels: enhancement, maintainers

#5670 Upgrade GA versions (DEV)
  .github/workflows/build_and_test.yml
  .github/workflows/gradle-wrapper-validation.yml
  .github/workflows/release_candidate.yml
  .github/workflows/screenshots.yml
Labels: enhancement, maintainers

#5671 Fix flaky test (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateViewModelTest.kt
Labels: bug, maintainers

#5667 Update hints (EXPOSUREAPP-14206)
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml
Labels: maintainers, text change

#5668 Rapid Test Profile shows mixed languages after change in locale (EXPOSUREAPP-9151)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_appconfig.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_datadonation.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_dcc_ticketing.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_deltaonboarding.xml
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_keydownload.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/SwitchRowView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataBindingAdapters.kt
  Corona-Warn-App/src/main/res/layout/cwa_user_card_item.xml
  Corona-Warn-App/src/main/res/layout/fragment_confirm_check_in.xml
  Corona-Warn-App/src/main/res/layout/switch_row.xml
  Corona-Warn-App/src/main/res/layout/view_more_information.xml
  Corona-Warn-App/src/main/res/values/styles.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataBindingAdaptersTest.kt
Labels: bug, maintainers
