Repository corona-warn-app/cwa-app-android, pull requests merged in 2022-05, with the labels that each got.

#5139 FIX: No red badge at ‘Hinweis zur Auffrischimpfung’ (EXPOSUREAPP-12966)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/BoosterCard.kt
  Corona-Warn-App/src/main/res/drawable/ic_badge_with_space.xml
  Corona-Warn-App/src/main/res/layout/person_details_booster_card.xml
Labels: bug, maintainers

#5144 Bump to next Version 2.22.1.1
  gradle.properties
Labels: maintainers

#5143 Add case for not attached dcc in FamilyTest (EXPOSUREAPP-12941)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentViewModel.kt
  Corona-Warn-App/src/main/res/layout/fragment_family_test_consent.xml
Labels: bug, maintainers

#5145 Change to plural form
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
Labels: text change

#5146 Release 2.23.x update
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/BoosterCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentViewModel.kt
  Corona-Warn-App/src/main/res/drawable/ic_badge_with_space.xml
  Corona-Warn-App/src/main/res/layout/fragment_family_test_consent.xml
  Corona-Warn-App/src/main/res/layout/person_details_booster_card.xml
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-uk/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  gradle.properties
Labels: maintainers

#5149 Version 2.23.0.0 (DEV)
  gradle.properties
Labels: maintainers

#5152 Text change (EXPOSUREAPP-12434)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers

#5151 Update expired certificate details screen with new status subtitle.
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: maintainers, text change

#5155 Removed word
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
Labels: text change

#5154 Android Support - Introduce launch argument for Mock Server (EXPOSUREAPP-12689)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/statistics/Statistics.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/EnvironmentState.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_debugoptions.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentSetup.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/launcher/LauncherParameter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/environment/EnvironmentSetupTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/launcher/LauncherActivityViewModelTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModelTest.kt
Labels: maintainers

#5163 Revocation repository exception (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/model/RevocationHashType.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/storage/DccRevocationRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/storage/DccRevocationRepositoryTest.kt
Labels: enhancement, maintainers

#5165 Bump to next Version 2.23.0.1
  gradle.properties
Labels: maintainers

#5148 Family consent viewModel tests (EXPOSUREAPP-12545)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentViewModelTest.kt
Labels: maintainers

#5161 Certificate reissuance consent screen - certificates list (EXPOSUREAPP-12862)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceItem.kt
  Corona-Warn-App/src/main/res/layout/dcc_reissuance_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_reissuance_consent.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentViewModelTest.kt
Labels: maintainers

#5167 Task Controller Test (EXPOSUREAPP-13013)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/task/TaskControllerTest.kt
  Corona-Warn-App/src/test/java/testhelpers/coroutines/TestExtensions.kt
Labels: maintainers

#5164 Refactoring navigation (EXPOSUREAPP-12690)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/res/menu/menu_bottom_nav.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/navigation/status_nav_graph.xml
  build.gradle
Labels: maintainers

#5153 Change padding info button (EXPOSUREAPP-11516)
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
Labels: bug, maintainers

#5159 Submit analytics date conversion (EXPOSUREAPP-12616)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposureriskmetadata/ExposureRiskMetadataDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeAndDateExtensions.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/ExposureRiskMetadataDonorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/TimeAndDateExtensionsTest.kt
Labels: bug, maintainers

#5160 Trigger wallet calculation once (EXPOSUREAPP-13009)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/update/CclSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTrigger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/qrcode/DccQrCode.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/qrcode/QrCodeString.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/admission/AdmissionScenariosViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/reissuer/DccReissuer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/configuration/update/CclSettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTriggerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/admission/AdmissionScenariosViewModelTest.kt
Labels: maintainers

#5174 Update reissuance 429 error text (EXPOSUREAPP-13059)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/error/DccReissuanceException.kt
  Corona-Warn-App/src/main/res/values-de/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_reissuance_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/core/error/DccReissuanceExceptionTest.kt
Labels: maintainers, text change

#5173 Rework soon expiring text (EXPOSUREAPP-13017)
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: maintainers, text change

#5172 Fix certificate tiles look in DCC reissuance (DEV)
  Corona-Warn-App/src/main/res/layout/dcc_reissuance_certificate_card.xml
Labels: maintainers

#5170 Fix delete family test (EXPOSUREAPP-13053)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/FamilyTestListEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/FamilyTestListFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/FamilyTestListViewModel.kt
  Corona-Warn-App/src/main/res/layout/family_rapid_test_card_outdated.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/familytest/ui/testlist/FamilyTestListViewModelTest.kt
Labels: bug, maintainers

#4685 Add app shortcuts to primary targets (EXPOSUREAPP-5414)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultAvailableFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingsResetViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/resultavailable/SubmissionTestResultAvailableFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultNoConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/AppShortcuts.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/shortcuts/AppShortcutsHelper.kt
  Corona-Warn-App/src/main/res/drawable/ic_certificates_shortcut_icon.xml
  Corona-Warn-App/src/main/res/drawable/ic_check_ins_shortcut_icon.xml
  Corona-Warn-App/src/main/res/drawable/ic_contact_diary_shortcut_icon.xml
  Corona-Warn-App/src/main/res/drawable/ic_qr_code_scanner_shortcut_icon.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
Labels: enhancement, maintainers

#5176 Update CertLogic fork to use Jackson 2.13 (EXPOSUREAPP-13088)
  Corona-Warn-App/build.gradle
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-67-078243e/dgc-certlogic-android-light-1.0.0-67-078243e.aar
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-67-078243e/dgc-certlogic-android-light-1.0.0-67-078243e.aar.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-67-078243e/dgc-certlogic-android-light-1.0.0-67-078243e.aar.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-67-078243e/dgc-certlogic-android-light-1.0.0-67-078243e.aar.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-67-078243e/dgc-certlogic-android-light-1.0.0-67-078243e.aar.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-67-078243e/dgc-certlogic-android-light-1.0.0-67-078243e.pom.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-67-078243e/dgc-certlogic-android-light-1.0.0-67-078243e.pom.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-67-078243e/dgc-certlogic-android-light-1.0.0-67-078243e.pom.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-67-078243e/dgc-certlogic-android-light-1.0.0-67-078243e.pom.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be-sources.jar
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be-sources.jar.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be-sources.jar.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be-sources.jar.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be-sources.jar.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.aar
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.aar.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.aar.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.aar.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.aar.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.pom
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.pom.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.pom.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.pom.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.pom.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml.sha512
Labels: enhancement, maintainers

#5178 Cleanup some build warnings (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/DefaultConfigMapping.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/boosterinfodetails/BoosterInfoDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/valueset/valuesets/TestCertificateValueSets.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/storage/ProfileDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/internal/RiskResultDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataBindingAdapters.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/device/ForegroundState.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/AndroidModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/qrcode/coil/BitMatrixDecoder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/ViewExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/viewmodel/CWAViewModelFactoryProvider.kt
Labels: enhancement, maintainers

#5177 Upgrade libs versions (DEV)
  Corona-Warn-App/build.gradle
Labels: enhancement, maintainers

#5179 Adjust Info Screen to announce new Release-Features for 2.23 (EXPOSUREAPP-12857)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#5184 Replace JodaTime in Censoring (EXPOSUREAPP-13095)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/family/FamilyTestCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/profile/ProfileCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/PcrQrCodeCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/RACoronaTestCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/RapidQrCodeCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/qrcode/rapid/RapidQrCodeExtractor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/TestRegistrationStateProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/JodaMigration.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/RapidQrCodeCensorTest.kt
Labels: maintainers

#5185 Faq links in dark mode (EXPOSUREAPP-12577)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/TravelNoticeView.kt
  Corona-Warn-App/src/main/res/layout/confirmed_status_card.xml
Labels: bug, maintainers

#5171 Reissuance: Accompanying certificates screen (EXPOSUREAPP-13068)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/DccReissuanceUiModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/acccerts/DccReissuanceAccCertsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/acccerts/DccReissuanceAccCertsFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/acccerts/DccReissuanceAccCertsViewModel.kt
  Corona-Warn-App/src/main/res/layout/fragment_dcc_reissuance_acc_certs.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_reissuance_consent.xml
  Corona-Warn-App/src/main/res/layout/fragment_family_test_list.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/main/res/values-de/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_reissuance_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/ui/consent/acccert/DccReissuanceAccCertsViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/ui/consent/acccert/SortTest.kt
  Corona-Warn-App/src/test/resources/ccl/dcc_wallet_info_output_with_reissuance.json
  Corona-Warn-App/src/test/resources/ccl/dcc_wallet_info_output_with_reissuance_legacy.json
Labels: maintainers, text change

#5190 Bump to next Version 2.23.0.2
  gradle.properties
Labels: maintainers

#5187 replace JodaTime in bugreporting (EXPOSUREAPP-13102)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/event/BugEvent.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/event/BugEventEntity.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/event/DefaultBugEvent.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/bugreporting/processor/DefaultBugProcessor.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/crash.ui/CrashReportAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/LogLine.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/internal/LogSnapshotter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/DebugLogFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/upload/history/HistoryItemAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/history/LogUpload.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/server/LogUploadServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/server/auth/LogUploadAuthorizer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/server/auth/LogUploadOtp.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/JavaTimeAndDateExtenstions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeStamper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/database/CommonConverters.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/SerializationModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/adapter/JavaInstantAdapter.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/BugReportSettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/debuglog/internal/LogSnapshotterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/SnapshotUploaderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/server/LogUploadServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/server/auth/LogUploadAuthorizerTest.kt
Labels: maintainers

#5186 Top margin certificate details (EXPOSUREAPP-13101)
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
Labels: bug, maintainers

#5191 Adapted time frame for certificate renewal
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#5192 Changes to "About the app" text
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#5188 Screenshot (EXPOSUREAPP-12864)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccreissuance/ui/consent/acccerts/DccReissuanceAccCertsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/acccerts/DccReissuanceAccCertsViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/CertificateReissuanceExtensionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/ui/consent/acccert/DccReissuanceAccCertsViewModelTest.kt
Labels: maintainers

#5196 Change reissuance success message
  Corona-Warn-App/src/main/res/values-de/dcc_reissuance_strings.xml
Labels: text change

#5195 Reissuance fixes (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/reissuer/DccReissuer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/acccerts/DccReissuanceAccCertsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/acccerts/DccSorting.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccSortingTest.kt
Labels: maintainers, prio

#5194 Update reissuance legal text (EXPOSUREAPP-12863)
  Corona-Warn-App/src/main/res/values-de/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: maintainers, prio, text change

#5197 Unit test reissuer (DEV)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/core/reissuer/DccReissuerTest.kt
Labels: maintainers

#5200 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-bg/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-uk/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-uk/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: text change

#5202 Bump to next Version 2.23.0.3
  gradle.properties
Labels: maintainers

#5204 Terminology changed (EXPOSUREAPP-13125)
  Corona-Warn-App/src/main/res/values-de/dcc_reissuance_strings.xml
Labels: text change

#5203 Text change to plural form (EXPOSUREAPP-13125)
  Corona-Warn-App/src/main/res/values-de/dcc_reissuance_strings.xml
Labels: text change

#5201 Changed last bullet point on reissuance consent screen (EXPOSUREAPP-13118)
  Corona-Warn-App/src/main/res/values-de/dcc_reissuance_strings.xml
Labels: text change

#5205 Hyphenation (EXPOSUREAPP-11250)
  Corona-Warn-App/src/main/res/layout/fragment_interoperability_configuration.xml
Labels: bug, maintainers

#5206 Update expiry notice (EXPOSUREAPP-13111)
  Corona-Warn-App/src/main/res/layout/include_expiration_notice_card.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: bug, maintainers, text change

#5212 Addition to note about soon expiring certificates
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#5208 Add back missing title and badge in certificate details (EXPOSUREAPP-13108)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
Labels: bug, maintainers

#5207 Fix reissuance back nav on error(EXPOSUREAPP-13135)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentViewModel.kt
Labels: bug, maintainers

#5209 Fix standard header bg (EXPOSUREAPP-13116)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeStamper.kt
Labels: bug, maintainers

#5214 Expired Certificates - only yyyy.mm.dd considered - hh:mm ignored (EXPOSUREAPP-13146)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationChecker.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationCheckerTest.kt
Labels: bug, maintainers

#5217 Drop expiry notification in favor of reissuance notification (EXPOSUREAPP-13143)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccValidityStateChangeObserver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccValidityStateNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationCertificateContainer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccValidityStateChangeObserverTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccValidityStateNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonCertificatesData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
Labels: maintainers, prio

#5211 Fix expired certificate icons (EXPOSUREAPP-13128)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/acccerts/DccReissuanceAccCertsViewModel.kt
  Corona-Warn-App/src/main/res/layout/dcc_reissuance_certificate_card.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/ui/consent/acccert/DccReissuanceAccCertsViewModelTest.kt
Labels: bug, maintainers

#5193 Family cards (EXPOSUREAPP-12614)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/familytest/ui/testlist/FamilyTestListFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/BaseCoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRCoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RACoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/model/CoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/FamilyTestListAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/FamilyTestListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/items/FamilyPcrTestInvalidCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/items/FamilyPcrTestNegativeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/items/FamilyPcrTestPendingCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/items/FamilyPcrTestPositiveCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/items/FamilyRapidTestInvalidCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/items/FamilyRapidTestNegativeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/items/FamilyRapidTestPendingCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/items/FamilyRapidTestPositiveCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/items/FamilyTestListCard.kt
  Corona-Warn-App/src/main/res/layout/family_pcr_test_card_invalid.xml
  Corona-Warn-App/src/main/res/layout/family_pcr_test_card_negative.xml
  Corona-Warn-App/src/main/res/layout/family_pcr_test_card_pending.xml
  Corona-Warn-App/src/main/res/layout/family_pcr_test_card_positiv.xml
  Corona-Warn-App/src/main/res/layout/family_pcr_test_card_redeemed.xml
  Corona-Warn-App/src/main/res/layout/family_rapid_test_card_negative.xml
  Corona-Warn-App/src/main/res/layout/family_rapid_test_card_outdated.xml
  Corona-Warn-App/src/main/res/layout/family_rapid_test_card_pending.xml
  Corona-Warn-App/src/main/res/layout/family_rapid_test_card_positiv.xml
  Corona-Warn-App/src/main/res/layout/family_rapid_test_card_redeemed.xml
  Corona-Warn-App/src/main/res/layout/family_test_list_card.xml
  Corona-Warn-App/src/main/res/layout/fragment_family_test_list.xml
Labels: bug, maintainers

#5218 Add title and badge to revoked certs (EXPOSUREAPP-13108)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
Labels: bug, maintainers

#5219 Fix censor (EXPOSUREAPP-13127)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/dcc/DccQrCodeCensor.kt
Labels: bug, maintainers

#5220 Bump to next Version 2.23.0.4
  gradle.properties
Labels: maintainers

#5213 Fix large font UI (EXPOSUREAPP-11531,EXPOSUREAPP-12669)
  Corona-Warn-App/src/main/res/layout/fragment_qrcode_scanner.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_tracing.xml
  Corona-Warn-App/src/main/res/layout/home_faq_card_layout.xml
  Corona-Warn-App/src/main/res/layout/person_overview_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_attendee_checkins_fragment.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
Labels: bug, maintainers

#5227 Unify text style on test & recovery details screens (EXPOSUREAPP-10219)
  Corona-Warn-App/src/main/res/layout/fragment_recovery_certificate_details.xml
  Corona-Warn-App/src/main/res/layout/fragment_test_certificate_details.xml
Labels: bug, maintainers

#5225 Tech dept P2 (EXPOSUREAPP-13177)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/server/auth/LogUploadAuthorizer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/migration/PCRTestMigration.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deniability/BackgroundNoiseOneTimeWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/server/DiagnosisKeyApiV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/warning/download/TraceWarningPackageSyncTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/InsufficientStorageException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/TracingRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/TracingSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/SubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/SubmissionSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/task/SubmissionTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/riskdetails/DetailsLowRiskBox.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/poster/QrCodePosterFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/WatchdogService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/encryptionmigration/EncryptedPreferencesMigration.kt
Labels: enhancement, maintainers

#5221 Use DataStore Approach - Part #1 (EXPOSUREAPP-13157)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/proguard-rules.pro
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/bugreporting/DebugLogFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/BugReportingSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/BugReportingSharedModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/DebugLogViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/upload/history/HistoryItemAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/upload/history/LogUploadHistoryViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/SnapshotUploader.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/history/LogUpload.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/history/UploadHistory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/history/model/LogUpload.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/history/model/UploadHistory.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/history/storage/UploadHistorySerializer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/history/storage/UploadHistoryStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/history/storage/UploadHistoryStorageModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/server/LogUploadServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/datastore/BaseJsonSerializer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/datastore/DataStoreExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/SerializationModule.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/BugReportSettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/SnapshotUploaderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/history/storage/UploadHistorySerializerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/history/storage/UploadHistoryStorageModuleTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/history/storage/UploadHistoryStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/server/LogUploadServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/datastore/DataStoreExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/reset/ResetTestComponent.kt
  Corona-Warn-App/src/testShared/java/testhelpers/preferences/FakeTypedDataStore.kt
Labels: enhancement, maintainers, author merge

#5222 FIX: LogUploadAuthorizer (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/server/auth/LogUploadAuthorizer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/debuglog/upload/server/auth/LogUploadAuthorizerTest.kt
Labels: bug, maintainers

#5223 Fetching state for test on home screen (EXPOSUREAPP-10746)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/CoronaTestRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/PersonalCoronaTestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRCoronaTestExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRTestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RATestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RapidAntigenCoronaTestExtensions.kt
Labels: bug, maintainers

#5230 change reissue text
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: text change

#5199 replace JodaTime in analytics (EXPOSUREAPP-13114)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/datadonation/analytics/storage/DefaultLastAnalyticsSubmissionLogger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/OTPAuthorizationResult.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/OneTimePassword.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/Analytics.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/common/Calculations.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposurewindows/AnalyticsExposureWindowRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/AnalyticsKeySubmissionCollector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/AnalyticsKeySubmissionDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/AnalyticsKeySubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsTestResultCollector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsTestResultDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsTestResultSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/storage/AnalyticsSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/storage/LastAnalyticsSubmission.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/worker/DataDonationAnalyticsTimeCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/worker/DataDonationAnalyticsWorkBuilder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNet.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/survey/Surveys.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/OnboardingSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/JavaTimeAndDateExtenstions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/JodaMigration.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/encryptionmigration/EncryptedPreferencesMigration.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/AnalyticsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/common/CalculationsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/common/PpaDataExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/exposurewindows/AnalyticsExposureWindowsRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/AnalyticsKeySubmissionCollectorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/AnalyticsPCRKeySubmissionDonorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/AnalyticsRAKeySubmissionDonorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsPCRTestResultDonorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsRATestResultDonorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsTestResultCollectorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsTestResultSettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNetTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/storage/OTPRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/survey/SurveySettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/survey/SurveysTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/encryptionmigration/EncryptedPreferencesMigrationTest.kt
Labels: maintainers

#5224 Pay technical dept of AppConfig (EXPOSUREAPP-13168)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/appconfig/ui/AppConfigTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/risklevel/ui/TestRiskLevelCalculationFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/risklevel/ui/TestRiskLevelCalculationFragmentCWAViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_risk_level_calculation.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/internal/AppConfigSource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/ConfigMapping.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/ConfigParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/DefaultConfigMapping.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/ConfigParserTest.kt
Labels: enhancement, maintainers

#5231 Provide notification type to notification sender (EXPOSUREAPP-13183)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/notification/DccWalletInfoNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/notification/PersonNotificationSender.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/notification/DccReissuanceNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/gstatus/notification/GStatusNotificationService.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/PersonNotificationSenderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/notification/DccReissuanceNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/gstatus/notification/GStatusNotificationServiceTest.kt
Labels: bug, maintainers

#5198 Certificate details screen after scan (EXPOSUREAPP-12991)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccValidityStateNotification.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateRepositoryTest.kt
Labels: bug, maintainers

#5234 Bump to next Version 2.23.0.5
  gradle.properties
Labels: maintainers

#5233 FIX: Fix time issue (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/DebugLogFragment.kt
Labels: bug, maintainers

#5240 Fix/improve whats new
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: text change

#5239 Certificate card swipe to delete fix (EXPOSUREAPP-12987,13098)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
Labels: bug, maintainers

#5242 Bump to next Version 2.23.1.0
  gradle.properties
Labels: maintainers

#5241 Family test screen rat (EXPOSUREAPP-13191)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/items/FamilyTestListCard.kt
Labels: bug, maintainers, prio

#5243 Fix expired and expiring soon text (EXPOSUREAPP-13196, 13182)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: bug, maintainers, prio

#5238 Upgrade to AGP 7.2.1 (DEV)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/contactdiary/storage/ContactDiaryDatabaseMigrationTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/risk/storage/RiskResultDatabaseMigrationTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/statistics/Statistics.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/BaseTestInstrumentation.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/JUnitTree.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/MockFlowPreference.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/TestDispatcherProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/holder/grouping/DccGroupingExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/holder/grouping/DccHolderComparisonTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/holder/grouping/DccHolderNameComponentsTest.kt
  Corona-Warn-App/src/test/java/testhelpers/IsAUnitTest.kt
  Corona-Warn-App/src/test/java/testhelpers/TestDispatcherProvider.kt
  Corona-Warn-App/src/test/java/testhelpers/logging/JUnitTree.kt
  Corona-Warn-App/src/test/java/testhelpers/preferences/FakeDataStore.kt
  Corona-Warn-App/src/test/java/testhelpers/preferences/FakeTypedDataStore.kt
  Corona-Warn-App/src/test/java/testhelpers/preferences/MockFlowPreference.kt
  Corona-Warn-App/src/test/java/testhelpers/preferences/MockSharedPreferences.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/nearby/modules/exposurewindow/ExposureWindowProviderTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/api/ui/TestForApiFragmentViewModelTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModelTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/risk/storage/DefaultRiskLevelStorageTest.kt
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, maintainers

#5237 Badge consistency (EXPOSUREAPP-13144)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/notification/DccReissuanceNotificationService.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/notification/DccReissuanceNotificationServiceTest.kt
Labels: maintainers

#5210 replace JodaTime in AppConfig (EXPOSUREAPP-13141)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/appconfig/ui/AppConfigTestFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/AppConfigModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/ConfigData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/CoronaTestConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/CovidCertificateConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/ExposureDetectionConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/KeyDownloadConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/devicetime/DeviceTimeHandler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/internal/AppConfigSource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/internal/ConfigDataContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/internal/InternalConfigData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CoronaTestConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CovidCertificateConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/ExposureDetectionConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/KeyDownloadParametersMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/sources/fallback/DefaultAppConfigSource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/sources/local/AppConfigStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/sources/remote/AppConfigServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RACoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNet.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyDownloadTool.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/model/CoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/FamilyTestListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/main/CWASettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/detectiontracker/DefaultExposureDetectionTracker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/risk/execution/PresenceTracingWarningTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/warning/download/TraceWarningPackageDownloader.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/EwRiskLevelTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskCardDisplayInfo.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/JodaMigration.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/adapter/JavaDurationAdapter.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/AppConfigProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/internal/AppConfigSourceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/internal/ConfigDataContainerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/CoronaTestParametersDistinctTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/CovidCertificateConfigMapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/DownloadConfigMapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/ExposureDetectionConfigMapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/sources/fallback/DefaultAppConfigSourceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/sources/local/AppConfigStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/sources/local/LocalAppConfigSourceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/sources/remote/AppConfigServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/sources/remote/RemoteAppConfigSourceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RapidAntigenCoronaTestExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateProcessorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/safetynet/CWASafetyNetTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/DayPackageSyncToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/HourPackageSyncToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/diagnosiskeys/download/KeyDownloadToolTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/CWASettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/modules/detectiontracker/DefaultExposureDetectionTrackerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/nearby/windows/ExposureWindowsCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/EwRiskLevelTaskTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskCardDisplayInfoTest.kt
Labels: maintainers
