Repository corona-warn-app/cwa-app-android, pull requests merged in 2022-04, with the labels that each got.

#5022 Protocol Buffer update for release 2.22.x at Fri Apr 1 06:17:20 UTC 2022
  Server-Protocol-Buffer/src/main/proto/internal/dgc/revocation_chunk.proto
  Server-Protocol-Buffer/src/main/proto/internal/dgc/revocation_kid_list.proto
  Server-Protocol-Buffer/src/main/proto/internal/dgc/revocation_kid_type_index.proto
Labels: maintainers

#5021 Revocation - improvement for testset (EXPOSUREAPP-12208)
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/DccWalletInfoRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckerTest.kt
  Corona-Warn-App/src/test/resources/ccl/dcc_wallet_info_output_with_certificatesRevokedByInvalidationRules.json
Labels: maintainers

#5020 Family tests fixes (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/FamilyTestListFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/adapter/CoronaTestCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/invalid/SubmissionTestResultInvalidFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultConsentGivenFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultKeysSharedFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/TestResultSectionView.kt
  Corona-Warn-App/src/main/res/layout/fragment_family_test_list.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_consent_given.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_invalid.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_negative.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_pending.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_positive_keys_shared.xml
  Corona-Warn-App/src/main/res/values-de/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values/family_tests_strings.xml
Labels: maintainers

#5025 Adapt privacy notice for Release 2.21 (EXPOSUREAPP-12465)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers

#5026 Remove "thanks for warning" text from positive family test (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultKeysSharedFragment.kt
Labels: maintainers

#5027 Fix: Family test members sorting (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/FamilyTestListViewModel.kt
Labels: bug, maintainers

#5023 Legal text change consent screen (EXPOSUREAPP-12463)
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: maintainers, text change

#5024 Adjust Info Screen to announce new Release-Features for 2.21 (EXPOSUREAPP-12249)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#5028 Adapt screenshots for result screens (EXPOSUREAPP-12324)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultConsentGivenFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNegativeFragmentTest.kt
Labels: maintainers

#5034 Bump to next Version 2.21.0.2
  gradle.properties
Labels: maintainers

#5018 Poll family test results (EXPOSUREAPP-12328)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/familytest/core/storage/FamilyTestDatabaseTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/repository/FamilyTestRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/storage/FamilyTestDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/storage/FamilyTestStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/worker/FamilyTestResultRetrievalScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/worker/FamilyTestResultRetrievalWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/worker/WorkerBinder.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/CoronaWarnApplicationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/familytest/core/repository/FamilyTestRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/familytest/worker/FamilyTestResultRetrievalSchedulerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/familytest/worker/FamilyTestRetrievalWorkerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/worker/WorkerBinderTest.kt
Labels: maintainers

#5035 No PPA collection for family test (EXPOSUREAPP-12334)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/resultavailable/SubmissionTestResultAvailableViewModel.kt
Labels: maintainers

#5047 Bump to next Version 2.21.0.3
  gradle.properties
Labels: maintainers

#5046 Bump to next Version 2.20.4.0
  gradle.properties
Labels: maintainers

#5042 Typo corrected
  Corona-Warn-App/src/main/res/values-de/green_certificate_strings.xml
Labels: text change

#5050 Fix: Support `UK` 🇺🇦 lang (EXPOSUREAPP-12625)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/configuration/model/CclDefaultInputParameters.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/util/CWADateTimeFormatPatternFactory.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/SupportedLocalesTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/util/CWADateTimeFormatPatternFactoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/util/ContactDiaryDateFormatterExtensionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/util/ContactDiaryExtensionsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/release/NewReleaseInfoFragmentTest.kt
Labels: bug, maintainers, prio

#5052 Fix reissuance button (EXPOSUREAPP-12619)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentFragment.kt
Labels: bug, maintainers

#5057 Bump to next Version 2.21.0.4
  gradle.properties
Labels: maintainers

#5043 Batch delete/update (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/familytest/core/storage/FamilyTestDatabaseTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/repository/FamilyTestRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/storage/FamilyTestDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/core/storage/FamilyTestStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/testlist/FamilyTestListViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/familytest/core/repository/FamilyTestRepositoryTest.kt
Labels: maintainers

#5055 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-bg/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-bg/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-pl/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-ro/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-tr/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-uk/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-uk/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-uk/release_info_strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: text change

#5053 Bind test type (EXPOSUREAPP-12621)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNegativeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeViewModel.kt
Labels: bug, maintainers

#5054 Profile skeleton (EXPOSUREAPP-12664)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/antigen/profile/VCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/model/Profile.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/storage/ProfileRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragmentViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/antigen/profile/VCardTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileDataCreateFragmentViewModelTest.kt
Labels: maintainers

#5056 Update zip4j, jackson-databind (EXPOSUREAPP-12453)
  Corona-Warn-App/build.gradle
Labels: maintainers

#5062 Notification trigger adjustments (EXPOSUREAPP-12484)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CertificateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationChangeObserver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/CoronaWarnApplicationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckSchedulerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccExpirationChangeObserverTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
Labels: maintainers, prio

#5063 Fix: App crash randomly (EXPOSUREAPP-12682)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
Labels: bug, maintainers

#5048 Updated texts for rapid test onboarding screen (EXPOSUREAPP-12605)
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
Labels: maintainers, text change

#5067 Revocation calculations adjustments (EXPOSUREAPP-12553)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/calculation/RevocationCalculation.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/calculation/RevocationCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/calculation/RevocationCalculationTestCase.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/calculation/RevocationCalculationTestCaseProvider.kt
Labels: maintainers

#5066 Fix: Reminder-Notification (EXPOSUREAPP-12685)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotification.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/GeneralNotifications.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/NotificationConstants.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/NotificationReceiver.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/notification/ShareTestResultNotificationServiceTest.kt
Labels: bug, maintainers, prio

#5068 FIX: Broken TAN flow (EXPOSUREAPP-12699)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/SubmissionTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/tan/SubmissionTanViewModel.kt
Labels: bug, maintainers, prio

#5070 Bump to next Version 2.21.0.5
  gradle.properties
Labels: maintainers

#5064 Revocation - data structures & error codes (EXPOSUREAPP-12552)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/calculation/RevocationCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/error/RevocationException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/model/RevocationChunk.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/model/RevocationEntryCoordinates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/model/RevocationHashType.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/model/RevocationKidList.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/model/RevocationKidTypeIndex.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/storage/RevocationRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/calculation/RevocationCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/model/RevocationHashTypeTest.kt
Labels: maintainers

#5058 Add revoked state (EXPOSUREAPP-12558)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNegativeFragmentTest.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dsc/ui/DscTestViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInputMapping.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoInput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificateUI.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccValidityStateChangeObserver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccValidityStateNotification.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccValidityStateNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/StoredRecoveryCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/BaseTestCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/GenericTestCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/PCRCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/types/RACertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/StoredVaccinationCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
  Corona-Warn-App/src/main/res/layout/person_overview_item.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/CoronaWarnApplicationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/CclStateMappingTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckWorkerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccValidityStateChangeObserverTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccValidityStateNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccValidityStateNotificationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonCertificatesData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/worker/WorkerBinderTest.kt
Labels: maintainers, text change

#5065 Adapt CollapsingToolbarLayout to end at half height (EXPOSUREAPP-12346)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/res/layout/person_details_fragment.xml
Labels: bug, maintainers

#5071 Travelbutton wrongly active (EXPOSUREAPP-12659)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/ProgressLoadingButton.kt
Labels: bug, maintainers

#5074 Profile repository and migration (EXPOSUREAPP-12664)
  Corona-Warn-App/schemas/de.rki.coronawarnapp.profile.storage.ProfileDatabase/1.json
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/profile/storage/ProfileDatabaseTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/antigen/profile/RATProfileSettingsDataStore.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/ProfileModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/model/Profile.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/storage/ProfileDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/storage/ProfileRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/antigen/profile/VCardTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/profile/storage/ProfileMigrationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/profile/storage/ProfileRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileDataCreateFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
Labels: maintainers

#5073 Revocation check (EXPOSUREAPP-12557)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dsc/ui/DscTestViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/CovidCertificateConfig.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/CovidCertificateConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/DccWalletInfoCleaner.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/DccWalletInfoRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccValidityMeasuresObserver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/expiration/DccValidityStateNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/calculation/RevocationCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/check/DccRevocationChecker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/check/RevocationCheck.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/model/RevocationChunk.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscDataParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscSignatureList.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscSignatureValidator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/storage/DefaultDscSource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/storage/LocalDscStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/appconfig/mapping/CovidCertificateConfigMapperTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/storage/DccWalletInfoRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckSchedulerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateCheckerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccValidityMeasuresObserverTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccValidityStateNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/calculation/RevocationCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/calculation/RevocationCalculationTestCaseProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/check/DccRevocationCheckerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscSignatureListParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscSignatureValidatorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateRepositoryTest.kt
Labels: maintainers

#5077 Rapid Test Profile List Screen (EXPOSUREAPP-12606)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/storage/ProfileRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/RATProfileUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/CreateRATProfileNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/list/ProfileListAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/list/ProfileListEvent.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/list/ProfileListFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/list/ProfileListFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/list/ProfileListViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/list/items/ProfileCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/list/items/ProfileListItem.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/onboarding/RATProfileOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionDispatcherViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionNavigationEvents.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_dispatcher.xml
  Corona-Warn-App/src/main/res/layout/profile_card_item.xml
  Corona-Warn-App/src/main/res/layout/profile_list_fragment.xml
  Corona-Warn-App/src/main/res/menu/menu_profile_list.xml
  Corona-Warn-App/src/main/res/navigation/rapid_antigen_test_profile_nav_graph.xml
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileDataCreateFragmentViewModelTest.kt
Labels: maintainers

#5072 Fix screenshots (EXPOSUREAPP-12783)
  .circleci/config.yml
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/familytest/ui/testlist/FamilyTestListFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinOverviewFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTanFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNoConsentGivenFragmentTest.kt
Labels: maintainers

#5088 Bump to next Version 2.21.1.0
  gradle.properties
Labels: maintainers

#5087 Family test censor (EXPOSUREAPP-12785)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/BugReportingSharedModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/family/FamilyTestCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/CensorInjectionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/family/FamilyTestCensorTest.kt
Labels: bug, maintainers

#5086 Update scheduler (EXPOSUREAPP-12556)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dsc/ui/DccStateValidationTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dsc/ui/DccStateValidationTestModule.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dsc/ui/DccStateValidationTestViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/ui/main/MainActivityTestModule.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_state_validation_dcc.xml
  Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CertificateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/storage/RevocationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/update/RevocationListUpdateWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/update/RevocationListUpdater.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/update/RevocationUpdateScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/update/RevocationUpdateSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/update/RevocationUpdater.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/worker/WorkerBinder.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/update/RevocationListUpdaterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/update/RevocationUpdateSchedulerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/update/RevocationUpdateSettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/worker/WorkerBinderTest.kt
Labels: maintainers

#5082 Profile navigation (EXPOSUREAPP-12683)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/model/Profile.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/storage/ProfileDatabase.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/storage/ProfileRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrCodeScannerFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/QrcodeSharedViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/CreateRATProfileNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/ProfileQrCodeNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/qrcode/RATProfileQrCodeFragmentViewModel.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/navigation/rapid_antigen_test_profile_nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/profile/storage/ProfileRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileDataCreateFragmentViewModelTest.kt
Labels: maintainers

#5097 Adapt screenshots to not show unplanned feature (EXPOSUREAPP-12726)
  Corona-Warn-App/src/main/res/layout/person_overview_fragment.xml
Labels: bug, maintainers

#5095 Adjust Info Screen to announce new Release-Features for 2.22 (EXPOSUREAPP-12651)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers, text change

#5098 Profile censor (EXPOSUREAPP-12827)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/BugReportingSharedModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/family/FamilyTestCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/profile/ProfileCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/RatProfileCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/coronatest/rat/profile/create/RATProfileCreateFragmentViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/CensorInjectionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/profile/ProfileCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/submission/RatProfileCensorTest.kt
Labels: maintainers

#5084 Fix Menu color (EXPOSUREAPP-11515)
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_qr_code_poster.xml
  Corona-Warn-App/src/main/res/layout/home_fragment_layout.xml
  Corona-Warn-App/src/main/res/layout/person_overview_fragment.xml
  Corona-Warn-App/src/main/res/layout/qr_code_poster_fragment.xml
  Corona-Warn-App/src/main/res/layout/recycler_bin_overview_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_attendee_checkins_fragment.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: bug, maintainers

#5085 User overview: Support a third certificate (EXPOSUREAPP-12062)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/layout/include_certificate_overview_qr_card.xml
Labels: maintainers

#5102 Reduce logs (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/appconfig/mapping/PresenceTracingConfigMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/valueset/valuesets/TestCertificateValueSets.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/valueset/valuesets/VaccinationValueSets.kt
Labels: maintainers

#5104 Revocation of single certs - storage, repo, updateservice (EXPOSUREAPP-12555, 12826)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/RevocationReset.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/model/RevocationKidList.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/server/RevocationApi.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/server/RevocationParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/server/RevocationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/storage/RevocationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/storage/RevocationStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/update/RevocationListUpdater.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/update/RevocationUpdateService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/update/RevocationUpdateSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/collections/CollectionsExtension.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/RevocationResetTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/server/RevocationParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/server/RevocationServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/storage/RevocationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/update/RevocationListUpdaterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/update/RevocationUpdateSettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
Labels: maintainers

#5110 Revocation - scheduler adjustment (EXPOSUREAPP-12881)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CertificateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/repository/CertificatesHolder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificatesHolder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/model/RevocationChunk.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/model/RevocationEntryCoordinates.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/storage/RevocationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/update/RevocationListUpdater.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/update/RevocationUpdateService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificatesHolder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificatesHolder.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/flow/FlowExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/SerializationModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/jackson/ByteStringSerializer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/storage/RevocationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/update/RevocationListUpdaterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateRepositoryTest.kt
Labels: maintainers

#5109 Bump to next Version 2.22.0.1
  gradle.properties
Labels: maintainers

#5117 Changes for Schnelltest-Profil
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
Labels: text change

#5115 Fix: Wrong time format in print Certificate(EXPOSUREAPP-12046)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/TestCertificateDrawHelper.kt
Labels: bug, maintainers

#5108 Certificate Overview UI Fix (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
Labels: ui, maintainers

#5111 FIX: Low risk with exposures shows wrong details
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsItemProviderTest.kt
Labels: maintainers

#5121 FIX: screenshot fix (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentFragmentTest.kt
Labels: bug, maintainers

#5120 Bump to next Version 2.22.0.2
  gradle.properties
Labels: maintainers

#5096 Swipe to delete for certificates (EXPOSUREAPP-11224)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CertificateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: maintainers

#5123 Bump to next Version 2.22.0.3
  gradle.properties
Labels: maintainers

#5093 Profile screenshots (EXPOSUREAPP-12673)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/profile/ui/list/ProfileListFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
Labels: maintainers

#5122 Revocation of single certificate - missing unit tests & some pr comments (EXPOSUREAPP-12560)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/dsc/ui/DccStateValidationTestViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/DigitalCovidCertificateModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccValidityMeasuresObserver.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/DccRevocationModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/DccRevocationReset.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/calculation/DccRevocationCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/error/DccRevocationException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/model/RevocationKidList.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/model/RevocationKidTypeIndex.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/server/DccRevocationApi.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/server/DccRevocationParser.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/server/DccRevocationServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/storage/DccRevocationRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/update/DccRevocationListUpdateWorker.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/update/DccRevocationListUpdater.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/update/DccRevocationUpdateScheduler.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/update/DccRevocationUpdateService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/revocation/update/DccRevocationUpdateSettings.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/DataReset.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/jackson/ByteStringSerializer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/worker/WorkerBinder.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/CoronaWarnApplicationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/CovidCertificateTestComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccValidityMeasuresObserverTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/DccRevocationResetTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/calculation/DccRevocationCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/calculation/DccRevocationCalculationTestCase.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/calculation/DccRevocationCalculationTestCaseProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/check/DccRevocationCheckerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/server/DccRevocationParserTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/server/DccRevocationServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/storage/DccRevocationRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/update/DccRevocationListUpdaterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/update/DccRevocationUpdateSchedulerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/update/DccRevocationUpdateServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/revocation/update/DccRevocationUpdateSettingsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/DataResetTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/collections/CollectionsExtensionTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/serialization/jackson/ByteStringSerializationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/worker/WorkerBinderTest.kt
Labels: maintainers

#5126 Corrected Spelling
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: text change

#5127 Changed rat_profile_open_card_title to plural form
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
Labels: text change

#5125 Navigation on back press in submission flow (EXPOSUREAPP-12904)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/ui/qrcode/ProfileQrCodeFragment.kt
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
Labels: bug, maintainers

#5103 Fix certificate deletion app crash (EXPOSUREAPP-12875)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/BoosterCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
Labels: bug, maintainers

#5131 Typo "faq zur druckversion"
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#5132 Adjust negative RAT test screen (EXPOSUREAPP-12933)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/NegativeRapidTestResultView.kt
  Corona-Warn-App/src/main/res/drawable/card_counter_green.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_antigen_test_result_negative.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_negative.xml
  Corona-Warn-App/src/main/res/layout/personal_rapid_test_result_negative.xml
  Corona-Warn-App/src/main/res/layout/time_counter.xml
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-uk/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
Labels: maintainers

#5135 Certificate details missing (EXPOSUREAPP-12934)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
Labels: maintainers

#5137 FIX: global layout listener in PersonDetailsFragment (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
Labels: bug, maintainers

#5138 FIX: reduce app crashes when cert error (EXPOSUREAPP-12872,12873,12874)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/VaccinationCertificateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationCertificateContainer.kt
Labels: bug, maintainers
