Repository corona-warn-app/cwa-app-android, pull requests merged in 2022-06, with the labels that each got.

#5247 Reissuance icon vaccination incomplete (EXPOSUREAPP-13128)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceCertificateCard.kt
Labels: bug, maintainers

#5244 Fix tests for screenshots (EXPOSUREAPP-11295)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/TracingData.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/TracingDetailsFragmentTest.kt
  Corona-Warn-App/src/main/res/layout/include_submission_behaviour_row.xml
Labels: bug, maintainers

#5249 Test result when tracing declined (EXPOSUREAPP-13127)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/data/tekhistory/TEKHistoryUpdater.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/resultavailable/SubmissionTestResultAvailableViewModel.kt
Labels: bug, maintainers

#5252 Update covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
Labels: text change

#5254 Add padding on bottom of certificate cards (EXPOSUREAPP-13193)
  Corona-Warn-App/src/main/res/layout/recovery_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/test_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/vaccination_certificate_card.xml
Labels: bug, maintainers

#5262 Update release notes 2.24 (EXPOSUREAPP-13265)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers

#5256 Reissuance certificate pinning (EXPOSUREAPP-13207)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/server/DccReissuanceServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/server/DccReissuanceServerModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/core/server/validation/DccReissuanceServerCertificateValidator.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/core/server/DccReissuanceServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/dccreissuance/core/server/validation/DccReissuanceServerCertificateValidatorTest.kt
Labels: bug, maintainers, prio

#5266 DCC export filter and sorting (EXPOSUREAPP-13311)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/DccExportFilter.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/pdf/core/DccExportFilterTest.kt
Labels: maintainers

#5267 Unify flag SVG paths (EXPOSUREAPP-13310)
  Corona-Warn-App/src/main/assets/template/de_rc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/de_tc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/de_vc_v4.1.svg
Labels: maintainers

#5250 Enable export of all certificates of a CWA user (EXPOSUREAPP-13018)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/risklevel/ui/TestRiskLevelCalculationFragmentCWAViewModel.kt
  Corona-Warn-App/src/main/assets/template/de_rc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/de_tc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/de_vc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/rc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/tc_v4.1.svg
  Corona-Warn-App/src/main/assets/template/vc_v4.1.svg
  Corona-Warn-App/src/main/java/android/print/FilePrinter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/DigitalCovidCertificateUIModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CertificateProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/DccExportFilter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/TestCertificateDrawHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/ExportAllCertsPdfInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/DccExportAllOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/DccExportAllOverviewModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/DccExportAllOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/helper/CertificateDataInjector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/helper/CertificateTemplate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/helper/HtmlTemplate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/listitem/AffectedFieldsMapper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/storage/OnboardingSettings.kt
  Corona-Warn-App/src/main/res/drawable/ic_export_all.xml
  Corona-Warn-App/src/main/res/drawable/ic_export_info.xml
  Corona-Warn-App/src/main/res/layout/export_all_certs_pdf_info_fragment.xml
  Corona-Warn-App/src/main/res/layout/export_tooltip.xml
  Corona-Warn-App/src/main/res/layout/fragment_dcc_export_all_overview.xml
  Corona-Warn-App/src/main/res/layout/person_overview_fragment.xml
  Corona-Warn-App/src/main/res/menu/menu_person_overview.xml
  Corona-Warn-App/src/main/res/navigation/covid_certificates_graph.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/links.xml
  Corona-Warn-App/src/main/res/values/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/pdf/core/DccExportFilterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonCertificatesData.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
Labels: enhancement, maintainers

#5268 Bump to next Version 2.24.0.1
  gradle.properties
Labels: maintainers

#5270 Fix acc dcc screenshots (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccreissuance/ui/consent/acccerts/DccReissuanceAccCertsFragmentTest.kt
Labels: maintainers

#5269 Certificate export - unit tests (EXPOSUREAPP-13330)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/helper/CertificateDataInjector.kt
  Corona-Warn-App/src/main/res/menu/menu_person_overview.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/DccExportAllOverviewViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/helper/CertificateDataInjectorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/helper/CertificateTemplateTest.kt
Labels: maintainers

#5273 Upgrade CertLogic `v1.0.0-70-c90c97f` (EXPOSUREAPP-13344)
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.aar
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.aar.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.aar.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.aar.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.aar.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.pom.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.pom.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.pom.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-68-60787be/dgc-certlogic-android-light-1.0.0-68-60787be.pom.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-70-c90c97f/dgc-certlogic-android-light-1.0.0-70-c90c97f-sources.jar
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-70-c90c97f/dgc-certlogic-android-light-1.0.0-70-c90c97f-sources.jar.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-70-c90c97f/dgc-certlogic-android-light-1.0.0-70-c90c97f-sources.jar.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-70-c90c97f/dgc-certlogic-android-light-1.0.0-70-c90c97f-sources.jar.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-70-c90c97f/dgc-certlogic-android-light-1.0.0-70-c90c97f-sources.jar.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-70-c90c97f/dgc-certlogic-android-light-1.0.0-70-c90c97f.aar
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-70-c90c97f/dgc-certlogic-android-light-1.0.0-70-c90c97f.aar.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-70-c90c97f/dgc-certlogic-android-light-1.0.0-70-c90c97f.aar.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-70-c90c97f/dgc-certlogic-android-light-1.0.0-70-c90c97f.aar.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-70-c90c97f/dgc-certlogic-android-light-1.0.0-70-c90c97f.aar.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-70-c90c97f/dgc-certlogic-android-light-1.0.0-70-c90c97f.pom
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-70-c90c97f/dgc-certlogic-android-light-1.0.0-70-c90c97f.pom.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-70-c90c97f/dgc-certlogic-android-light-1.0.0-70-c90c97f.pom.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-70-c90c97f/dgc-certlogic-android-light-1.0.0-70-c90c97f.pom.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/1.0.0-70-c90c97f/dgc-certlogic-android-light-1.0.0-70-c90c97f.pom.sha512
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml.md5
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml.sha1
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml.sha256
  local-maven-repo/dgca/verifier/app/dgc-certlogic-android-light/maven-metadata.xml.sha512
Labels: maintainers

#5271 Refactor exporting individual certificates to use SVG approach (EXPOSUREAPP-13341)
  Corona-Warn-App/src/main/assets/recovery_certificate_template.pdf
  Corona-Warn-App/src/main/assets/test_certificate_template.pdf
  Corona-Warn-App/src/main/assets/vaccination_certificate_template.pdf
  Corona-Warn-App/src/main/java/android/print/FilePrinter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/CertificateDataInjector.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/CertificateDrawHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/CertificateTemplate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/ExportCertificateModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/HtmlTemplate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/PdfGenerator.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/PdfTemplateRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/RecoveryCertificateDrawHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/TestCertificateDrawHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/TextArea.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/Utils.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/VaccinationCertificateDrawHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/CertificateExportHelper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/WebView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/DccExportAllOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/DccExportAllOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/helper/HtmlTemplate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/poster/CertificatePosterFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/poster/CertificatePosterViewModel.kt
  Corona-Warn-App/src/main/res/layout/certificate_poster_fragment.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/links.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/links.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/pdf/core/CertificateDataInjectorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/pdf/core/CertificateTemplateTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/pdf/core/PdfTemplateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/pdf/core/UtilsKtTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/pdf/core/UtilsTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/DccExportAllOverviewViewModelTest.kt
Labels: enhancement, maintainers, text change

#5283 Bump to next Version 2.24.0.2
  gradle.properties
Labels: maintainers

#5281 Tracing switch (EXPOSUREAPP-11519)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/GeneralTracingStatus.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/settings/TracingSettingsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/settings/TracingSettingsFragmentModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/settings/TracingSettingsFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/settings/SettingFragmentsModule.kt
  Corona-Warn-App/src/main/res/layout/fragment_tracing_settings.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
Labels: maintainers

#5279 Update dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-de/dcc_reissuance_strings.xml
Labels: text change

#5289 Bump to next Version 2.24.0.3
  gradle.properties
Labels: maintainers

#5290 Adjust scanner binding to prevent crash (EXPOSUREAPP-13396)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/qrcode/OrganizerWarnQrCodeScannerFragment.kt
Labels: bug, maintainers, prio

#5288 Update certificate details screenshots (EXPOSUREAPP-11270)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragmentTest.kt
Labels: bug, maintainers

#5285 Fix order of certificates in person details screen (EXPOSUREAPP-13186)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTrigger.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTriggerTest.kt
Labels: bug, maintainers

#5291 Certificates PDF Export is not displayed properly (EXPOSUREAPP-13370)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/HtmlTemplate.kt
Labels: bug, maintainers

#5293 Remove CI prefix on PDF Exports (EXPOSUREAPP-13429)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/core/CertificateDataInjector.kt
Labels: bug, maintainers

#5286 Wallet assignment (EXPOSUREAPP-13204)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/test/ui/TestCertificateDetailsFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/StoredRecoveryCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/StoredVaccinationCertificateData.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/gstatus/notification/GStatusNotificationService.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/expiration/DccValidityStateNotificationServiceTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProviderTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/RecoveryCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/test/core/TestCertificateRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationStorageTest.kt
Labels: bug, maintainers

#5295 bump to next version 2.24.0.4
  gradle.properties
Labels: maintainers

#5298 Change text for key risk_details_information_body_period_logged
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: maintainers, text change

#5292 Export tooltip layout and colors
  Corona-Warn-App/src/main/res/layout/export_tooltip.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: maintainers

#5305 Remove margin (EXPOSUREAPP-13459)
  Corona-Warn-App/src/main/res/layout/recovery_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/test_certificate_card.xml
  Corona-Warn-App/src/main/res/layout/vaccination_certificate_card.xml
Labels: bug, maintainers

#5307 Test menu config (EXPOSUREAPP-13458)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/appconfig/ui/AppConfigTestFragment.kt
Labels: maintainers

#5306 Fix back navigation when coming from validity check (EXPOSUREAPP-13428)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/failed/DccValidationFailedFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/open/DccValidationOpenFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/passed/DccValidationPassedFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/passed/DccValidationPassedViewModel.kt
Labels: bug, maintainers

#5308 Update dcc_reissuance_strings.xml
  Corona-Warn-App/src/main/res/values-de/dcc_reissuance_strings.xml
Labels: text issue

#5299 Adjust Navigation for PDF Export (EXPOSUREAPP-13438, EXPOSUREAPP-13439)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/exportAll/DccExportAllOverviewFragment.kt
Labels: bug, maintainers
