Repository corona-warn-app/cwa-app-android, pull requests merged in 2022-07, with the labels that each got.

#5315 text change red tile (increased risk) remove free test hint (EXPOSUREAPP-13456)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers, text change

#5321 Bump to next Version 2.24.1.1
  gradle.properties
Labels: maintainers

#5323 Add possibility to navigate back on consent fragments (EXPOSUREAPP-12901)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/selection/TestRegistrationSelectionFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_family_test_consent.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_consent.xml
Labels: bug, maintainers

#5311 Change mainOverviewSegmentBody text (EXPOSUREAPP-13471)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/overview/MainOverviewFragment.kt
Labels: bug, maintainers, text change

#5309 Negative test result, remove certificate info (EXPOSUREAPP-13465, EXPOSUREAPP-13433)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
  Corona-Warn-App/src/main/res/drawable/ic_faq_information.xml
Labels: bug, maintainers

#5310 Correct FAQ link hc_already_registered (EXPOSUREAPP-13218) (COMMUNITY) (closes #5099)
  Corona-Warn-App/src/main/res/values-de/links.xml
  Corona-Warn-App/src/main/res/values/links.xml
Labels: mirrored-to-jira, community

#5312 Remove headline (EXPOSUREAPP-12546)
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_negative.xml
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-uk/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
Labels: bug, maintainers, text change

#5322 No TEK caching from test menu (EXPOSUREAPP-13461)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/TEKExport.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/TEKHistoryItem.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_submission.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/data/tekhistory/TEKHistoryUpdater.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/resultavailable/SubmissionTestResultAvailableViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/data/tekhistory/TEKHistoryUpdaterTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/testavailable/SubmissionTestResultAvailableViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/submission/warnothers/SubmissionResultPositiveOtherWarningNoConsentViewModelTest.kt
Labels: maintainers

#5326 Include an extra check before sending the booster notification (EXPOSUREAPP-13503)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManager.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationService.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/booster/BoosterNotificationServiceTest.kt
Labels: bug, maintainers, prio

#5328 Add back line and add more logs (EXPOSUREAPP-13503)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTrigger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/calculation/DccWalletInfoCalculationManagerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTriggerTest.kt
Labels: bug, maintainers, prio

#5331 Bump to next version 2.24.2.1
  gradle.properties
Labels: maintainers

#5325 Extend notes for certificate verification by third parties (EXPOSUREAPP-13387)
  Corona-Warn-App/src/main/res/layout/fragment_cov_pass_info.xml
  Corona-Warn-App/src/main/res/values-bg/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-pl/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-uk/covid_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
Labels: maintainers, text change

#5337 Update release info strings (EXPOSUREAPP-13566)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers

#5340 Remove faq link from app info menu (EXPOSUREAPP-13334)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_information.xml
Labels: bug, maintainers

#5338 Revert navigation changes from (EXPOSUREAPP-12901)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/selection/TestRegistrationSelectionFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_family_test_consent.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_consent.xml
Labels: bug, maintainers

#5344 New new release strings (EXPOSUREAPP-13566)
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
Labels: maintainers

#5342 New risk texts (EXPOSUREAPP-13607)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/behavior/BehaviorIncreasedRiskBox.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/behavior/BehaviorInfoRow.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/periodlogged/PeriodLoggedBox.kt
  Corona-Warn-App/src/main/res/layout/fragment_tracing_details_home.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_item_behavior_increased_view.xml
  Corona-Warn-App/src/main/res/layout/tracing_details_item_periodlogged_view.xml
  Corona-Warn-App/src/main/res/values-bg/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/links.xml
  Corona-Warn-App/src/main/res/values/risk_details_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#5341 Change invalid family test screen (EXPOSUREAPP-13433)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/invalid/SubmissionTestResultInvalidFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_invalid.xml
Labels: bug, maintainers

#5345 Illustration update
  Corona-Warn-App/src/main/res/drawable/ic_illustration_hygiene_rules.xml
  Corona-Warn-App/src/main/res/drawable/ic_illustration_stay_at_home.xml
Labels: maintainers

#5343 Negative test result detail page pending state (EXPOSUREAPP-13465)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_negative.xml
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-uk/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
Labels: bug, maintainers

#5348 bump to next version 2.25.0.1
  gradle.properties
Labels: maintainers

#5360 Update strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text issue

#5358 Upgrade libs (DEV)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/OccupiedIntensiveCareCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/PersonsVaccinatedCompletelyCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/PersonsVaccinatedOnceCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/PersonsVaccinatedWithBoosterCard.kt
  build.gradle
Labels: maintainers

#5357 Fix certificate details default look (EXPOSUREAPP-13281)
  Corona-Warn-App/src/main/res/layout/include_certificate_qrcode_card.xml
Labels: bug, maintainers

#5362 Update illustrations dark mode (DEV)
  Corona-Warn-App/src/main/res/drawable-night/ic_illustration_hygiene_rules.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_illustration_stay_at_home.xml
Labels: maintainers

#5349 Refactor `ProgressLoadingButton` (EXPOSUREAPP-12993)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationstart/ValidationStartFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccreissuance/ui/consent/DccReissuanceConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/create/TraceLocationCreateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/warn/tan/TraceLocationWarnTanFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/covidcertificate/RequestCovidCertificateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/qrcode/consent/SubmissionConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/ProgressLoadingButton.kt
  Corona-Warn-App/src/main/res/layout/fragment_family_test_consent.xml
  Corona-Warn-App/src/main/res/layout/fragment_request_covid_certificate.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_consent.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_deletion_warning.xml
  Corona-Warn-App/src/main/res/layout/trace_location_create_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_warn_tan_fragment.xml
  Corona-Warn-App/src/main/res/layout/validation_start_fragment.xml
  Corona-Warn-App/src/main/res/layout/view_progress_loading_button.xml
  Corona-Warn-App/src/main/res/values/colors.xml
Labels: maintainers

#5365 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-pl/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-ro/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-tr/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-uk/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/antigen_strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers, text change

#5367 v2.25.0.2 version bump (DEV)
  gradle.properties
Labels: maintainers

#5359 Adapt screenshot tests (EXPOSUREAPP-11295)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/TracingDetailsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/ui/details/home/HomeRulesFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/ui/details/hygiene/HygieneRulesFragmentTest.kt
  Corona-Warn-App/src/main/res/layout/fragment_tracing_details_home.xml
  Corona-Warn-App/src/main/res/layout/fragment_tracing_details_hygiene.xml
Labels: bug, maintainers

#5353 Don't show new release screen with every patch update (EXPOSUREAPP-13581)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingLoadingViewModel.kt
Labels: bug, maintainers

#5352 Disable menu items on empty screen / data (EXPOSUREAPP-13615)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditLocationsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditPersonsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/CheckInsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/organizer/list/TraceLocationsFragment.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_locations_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_edit_persons_fragment.xml
  Corona-Warn-App/src/main/res/layout/recycler_bin_overview_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_attendee_checkins_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_trace_locations_list_fragment.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewViewModelTest.kt
Labels: maintainers

#5372 Missing Link in pl Language (EXPOSUREAPP-13670)
  Corona-Warn-App/src/main/res/values-pl/strings.xml
Labels: bug, maintainers, text change

#5371 Change duration calculation (EXPOSUREAPP-11549)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/checkout/ContactJournalCheckInEntryCreator.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/checkins/checkout/ContactJournalCheckInEntryCreatorTest.kt
Labels: bug, maintainers

#5364 X-Button on Infoscreen in "Send error report" cannot be clicked (EXPOSUREAPP-12971)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/legal/DebugLogLegalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/legal/DebugLogLegalModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/legal/DebugLogLegalViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragmentModule.kt
Labels: bug, maintainers

#5361 Update dates in journal (EXPOSUREAPP-13578)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/ContactDiaryOverviewViewModel.kt
Labels: bug, maintainers

#5366 Difficulty dismissing UQS scanner pop-up (EXPOSUREAPP-12295)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/installTime/InstallTimeProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/main/res/layout/export_tooltip.xml
  Corona-Warn-App/src/main/res/layout/fab_tooltip.xml
  Corona-Warn-App/src/main/res/values/styles.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest2.kt
Labels: bug, maintainers

#5376 Onboarding fragment - show url in all langauges (EXPOSUREAPP-10220)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingFragment.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/onboarding/EasyLanguageLinkTest.kt
Labels: bug, maintainers

#5377 Replace Redeemed the days in the Text from 21 days to 2 days
  Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
  Corona-Warn-App/src/main/res/values-de/family_tests_strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers, text change

#5375 Update DetailsLowRiskBox data (EXPOSUREAPP-11295)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/tracing/TracingData.kt
Labels: bug, maintainers

#5379 Toggle button design (EXPOSUREAPP-13220)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
Labels: bug, maintainers

#5335 Reuse tan if submission fails (EXPOSUREAPP-13477)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/CoronaTestCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/CoronaTestRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/BaseCoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/PersonalCoronaTestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRCoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/pcr/PCRTestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RACoronaTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/rapidantigen/RATestProcessor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/BackgroundNoise.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/DefaultPlaybook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/Playbook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/playbook/PlaybookModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/submission/task/SubmissionTask.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/di/ApplicationComponent.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/CoronaTestCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/coronatest/CoronaTestRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/http/playbook/PlaybookTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest2.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/submission/task/SubmissionTaskTest.kt
Labels: bug, maintainers, prio

#5381 Darkmode link color (EXPOSUREAPP-13195)
  Corona-Warn-App/src/main/res/layout/vaccination_info_card.xml
Labels: bug, maintainers

#5382 Delete Circle CI (DEV)
  .circleci/config.yml
  .github/workflows/build_and_test.yml
  README.md
Labels: maintainers

#5385 Privacy submisson translation (EXPOSUREAPP-7951)
  Corona-Warn-App/src/main/res/layout/fragment_request_covid_certificate.xml
  Corona-Warn-App/src/main/res/values-bg/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-pl/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-ro/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values-uk/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/green_certificate_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: bug, maintainers, text issue, text change

#5389 Remove fake exposure window without scanInstances (EXPOSUREAPP-12169)
  Corona-Warn-App/src/deviceForTesters/assets/exposure-windows-increased-risk-random.json
Labels: bug, maintainers

#5383 Support DCC Schema 1.3.2 (EXPOSUREAPP-13684)
  Corona-Warn-App/build.gradle
  Corona-Warn-App/src/main/assets/jsonschema-dcc-8b5f5ee.json
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/dcc/CwaUserCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CertificatePersonIdentifier.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CwaCovidCertificate.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccJsonSchema.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/DccV1.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/pdf/ui/poster/CertificatePosterViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/MigrationCheck.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/core/storage/RecoveryCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/core/storage/TestCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/repository/storage/VaccinationCertificateContainer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/validation/JsonSchemaSource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/serialization/validation/JsonSchemaValidator.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/dcc/DccQrCodeCensorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/serialization/validation/JsonSchemaValidatorTest.kt
Labels: enhancement, maintainers

#5388 Hide subheading when empty (EXPOSUREAPP-13194)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationInfoCard.kt
  Corona-Warn-App/src/main/res/layout/vaccination_info_card.xml
Labels: bug, maintainers

#5395 GA - run on push (DEV)
  .github/workflows/build_and_test.yml
Labels: enhancement, maintainers

#5398 https link to RKI STIKO (EXPOSUREAPP-13687)
  Corona-Warn-App/src/main/res/values/links.xml
Labels: bug, maintainers

#5393 Fix screenobject-IDs issues for test automation (EXPOSUREAPP-13699)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/ContactDiaryCommentInfoFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/edit/ContactDiaryEditPersonsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/onboarding/ContactDiaryOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/checkins/CheckInsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/MaterialToolbarExtensions.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_comment_info_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/person_overview_fragment.xml
  Corona-Warn-App/src/main/res/layout/trace_location_attendee_checkins_fragment.xml
  Corona-Warn-App/src/main/res/values/attrs.xml
Labels: maintainers

#5392 "2G+"-function shows vaccination certificate although "Test Certificate" is highlighted (EXPOSUREAPP-12158)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
Labels: bug, maintainers

#5394 Color of UI elements in dark mode (EXPOSUREAPP-9566)
  Corona-Warn-App/src/main/res/drawable/contact_diary_duration_background_selected.xml
  Corona-Warn-App/src/main/res/drawable/ic_unselected.xml
  Corona-Warn-App/src/main/res/layout/duration_picker.xml
  Corona-Warn-App/src/main/res/layout/trace_location_attendee_checkins_item_active.xml
  Corona-Warn-App/src/main/res/layout/trace_location_organizer_trace_locations_item.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: bug, maintainers

#5399 Fix back navigation for UQS when opened from dispatcher fragment (EXPOSUREAPP-10004)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionDispatcherFragment.kt
Labels: bug, maintainers
