Repository corona-warn-app/cwa-app-android, pull requests merged in 2023-02, with the labels that each got.

#5822 Fix: blank screen on main page when defined scrolling happens (EXPOSUREAPP-14613)
  Corona-Warn-App/src/main/res/layout/tracing_content_low_view.xml
Labels: bug, maintainers

#5823 Bump to next Version 3.1.0.5
  gradle.properties
Labels: maintainers

#5828 Update strings.xml (EXPOSUREAPP-14558)
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: text change

#5825 Remove comma at end of journal text (EXPOSUREAPP-14677)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/day/contact/ContactAdapter.kt
Labels: maintainers

#5829 Ppa Analytics (EXPOSUREAPP-14695)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/datadonation/ui/DataDonationTestFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/Analytics.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/AnalyticsKeySubmissionStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/server/DataDonationAnalyticsServer.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/AnalyticsKeySubmissionStorageTest.kt
Labels: bug, maintainers

#5830 Fix: submitted_after_symptom_flow (EXPOSUREAPP-14703)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/introduction/SubmissionSymptomIntroductionViewModel.kt
Labels: bug, maintainers

#5832 Tweak EOL Card (EXPOSUREAPP-14699)
  Corona-Warn-App/src/main/res/layout/home_ramp_down_notice_card.xml
  Corona-Warn-App/src/main/res/values/colors.xml
Labels: bug, maintainers

#5833 Error report censoring (EXPOSUREAPP-14698)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/censors/submission/RapidQrCodeCensor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/qrcode/rapid/RapidQrCodeExtractor.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/bugreporting/censors/RapidQrCodeCensorTest.kt
Labels: bug, maintainers

#5834 Ppa (EXPOSUREAPP-14713)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/srs/AnalyticsSrsKeySubmissionRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/srs/AnalyticsSrsKeySubmissionRepositoryTest.kt
  gradle.properties
Labels: bug, maintainers

#5835 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#5837 Use appScope (14703)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarViewModel.kt
Labels: bug, maintainers

#5838 Fix: Symptoms race conditions (EXPOSUREAPP-14740)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/symptoms/calendar/SubmissionSymptomCalendarViewModel.kt
Labels: bug, maintainers

#5840 testResultMetadataSet for positive RAT is missing in PPA submission
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsTestResultSettings.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/testresult/AnalyticsTestResultSettingsTest.kt
Labels: bug, maintainers

#5841 AGP `v7.4.1` (DEV)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/ui/input/AnalyticsUserInputViewModel.kt
  build.gradle
Labels: maintainers

#5827 Update screenshot tests (EXPOSUREAPP-6946)
  .github/workflows/build_and_test.yml
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccticketing/ui/consent/one/DccTicketingConsentOneFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/dccticketing/ui/consent/two/DccTicketingConsentTwoFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/presencetracing/attendee/checkins/CheckInsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/presencetracing/attendee/confirm/ConfirmCheckInFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/profile/ui/list/ProfileListFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/srs/ui/done/SrsSubmissionDoneFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/eventregistration/organizer/QrCodeDetailFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/eventregistration/organizer/TraceLocationCategoryFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/eventregistration/organizer/TraceLocationCreateFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/eventregistration/organizer/TraceLocationData.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/eventregistration/organizer/TraceLocationsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeData.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/presencetracing/organizer/poster/QrCodePosterFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultKeysSharedFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultNegativeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionTestResultPendingFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/confirm/ConfirmCheckInFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/presencetracing/attendee/confirm/ConfirmCheckInViewModel.kt
  Corona-Warn-App/src/main/res/layout/fragment_submission_done.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/presencetracing/attendee/confirm/ConfirmCheckInViewModelTest.kt
Labels: maintainers

#5843 Fix person details blue background overlay overlap (EXPOSUREAPP-14709)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragment.kt
Labels: bug, maintainers

#5844 UI gets corrupted for large Font Sizes (EXPOSUREAPP-11531)
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_list_item.xml
  Corona-Warn-App/src/main/res/layout/fragment_qrcode_scanner.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_link_card_layout.xml
Labels: bug, maintainers

#5847 Fix header date height (EXPOSUREAPP-11531)
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_list_item.xml
Labels: bug, maintainers

#5846 EOL - Recycle Bin (EXPOSUREAPP-14793)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinOverviewViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/recyclebin/ui/RecyclerBinOverviewViewModelTest.kt
Labels: maintainers

#5849 EOL - certificates (EXPOSUREAPP-14790)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/details/RecoveryCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/test/ui/details/TestCertificateDetailsViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/ui/details/VaccinationDetailsViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsViewModelTest.kt
Labels: maintainers

#5852 EOL - Background Work (EXPOSUREAPP-14794)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTrigger.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/retention/ContactDiaryRetentionCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/initializer/AppStarter.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/CoronaWarnApplicationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/update/DccWalletInfoUpdateTriggerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/initializer/AppStarterTest.kt
Labels: maintainers

#5851 EOL - onboarding (EXPOSUREAPP-14788)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingPrivacyViewModel.kt
Labels: maintainers

#5848 Testresult detail text (EXPOSUREAPP-14381)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/negative/SubmissionTestResultNegativeFragment.kt
Labels: bug, maintainers

#5853 Eol bottom bar (EXPOSUREAPP-14791)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/UIExtensions.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
Labels: maintainers

#5856 Fix: Legal text TR (EXPOSUREAPP-14378)
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
Labels: text issue

#5855 EOL - Disable deep-links (EXPOSUREAPP-14796)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/MainActivityViewModelTest2.kt
Labels: maintainers

#5857 EOL - error logs (EXPOSUREAPP-14837)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/eol/AppEol.kt
Labels: maintainers

#5854 EOL - notifications (EXPOSUREAPP-14795)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/RecoveryCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/TestCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/VaccinationCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesProviderTest.kt
Labels: maintainers

#5859 EOL - Shortcuts (EXPOSUREAPP-14804)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/eol/AppEol.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeStamper.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/shortcuts/AppShortcutsHelper.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/eol/AppEolTest.kt
Labels: maintainers

#5861 EOL- Test Menu - allow logger to work after EOL (EXPOSUREAPP-14849)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragment.kt
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModel.kt
  Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_debugoptions.xml
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/eol/AppEol.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/eol/EolSetting.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/eol/AppEolTest.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModelTest.kt
Labels: maintainers

#5865 Add accessibility label to duration picker in journal (EXPOSUREAPP-14782)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/day/tabs/location/DiaryLocationViewHolder.kt
Labels: maintainers

#5863 EOL - Add FAQ back (EXPOSUREAPP-14785)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
Labels: bug, maintainers

#5862 EOl - env wru-z (EXPOSUREAPP-14853)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/environment/EnvironmentSetup.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/environment/EnvironmentSetupTest.kt
Labels: maintainers

#5864 EOL - default stats (EXPOSUREAPP-14836)
  Corona-Warn-App/src/main/assets/default_stats/default_stats.bin
  Corona-Warn-App/src/main/assets/default_stats/default_stats.sha256
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/DefaultStatsSource.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/StatisticsCache.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/StatisticsProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/statistics/source/StatisticsCacheTest.kt
Labels: maintainers

#5866 Bump to next Version 3.2.0.2
  gradle.properties
Labels: maintainers

#5868 Fix: Device time check dialog after EOL (EXPOSUREAPP-14862)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
Labels: bug, maintainers

#5871 Fix: Missing bindings (EXPOSUREAPP-14868)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/risk/IncreasedRiskBox.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/risk/TracingDisabledBox.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/risk/TracingFailedBox.kt
Labels: bug, maintainers

#5870 Fix: Update button based on background modes (EXPOSUREAPP-14864)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/TracingDetailsFragment.kt
Labels: bug

#5874 Fix click and double tap to activate (EXPOSUREAPP-14780)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/DispatcherCardView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/InformationRowView.kt
  Corona-Warn-App/src/main/res/layout/dispatcher_card_layout.xml
  Corona-Warn-App/src/main/res/layout/information_row_layout.xml
Labels: bug, maintainers, prio

#5872 Accessibility - fix image description and focusability for different fragments (EXPOSUREAPP-14781)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/overview/MainOverviewFragment.kt
  Corona-Warn-App/src/main/res/layout/contact_diary_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/fragment_main_overview.xml
  Corona-Warn-App/src/main/res/layout/fragment_uqs_info.xml
  Corona-Warn-App/src/main/res/layout/notifications_delta_onboarding_fragment.xml
Labels: bug, maintainers

#5875 Fix : close X button in dcc validation screens (EXPOSUREAPP-14870)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/passed/DccValidationPassedFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/CovidCertificateValidationResultView.kt
Labels: bug, maintainers
