Repository corona-warn-app/cwa-app-android, pull requests merged in 2023-03, with the labels that each got.

#5876 Fix: EOL - Background Activity Popup after App Reset/EOL/new onboarding (EXPOSUREAPP-14884)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivityViewModel.kt
Labels: bug, maintainers

#5877 Fix : EOL - information screen (EXPOSUREAPP-14883)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationFragment.kt
Labels: bug, maintainers

#5879 Refactoring issues (EXPOSUREAPP-14867)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/passed/DccValidationPassedFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/information/InformationLegalFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/CertificateOverviewQrCardView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/SettingsRowView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/SwitchRowView.kt
  Corona-Warn-App/src/main/res/layout/admission_federal_state_item.xml
  Corona-Warn-App/src/main/res/layout/age_warning_layout.xml
  Corona-Warn-App/src/main/res/layout/bugreporting_legal_fragment.xml
  Corona-Warn-App/src/main/res/layout/bulletpoint_data_privacy_layout.xml
  Corona-Warn-App/src/main/res/layout/certificate_overview_qr_card_layout.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/contact_diary_overview_list_item.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_onboarding_fragment.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_passed_fragment.xml
  Corona-Warn-App/src/main/res/layout/federal_state_input_adapter_item.xml
  Corona-Warn-App/src/main/res/layout/fragment_confirm_check_in.xml
  Corona-Warn-App/src/main/res/layout/fragment_edit_check_in.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_notifications.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_ppa.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_test.xml
  Corona-Warn-App/src/main/res/layout/fragment_ppa_more_info.xml
  Corona-Warn-App/src/main/res/layout/fragment_settings_privacy_preserving_analytics.xml
  Corona-Warn-App/src/main/res/layout/fragment_srs_submission_consent.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_consent.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_done.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_no_consent_positive_other_warning.xml
  Corona-Warn-App/src/main/res/layout/fragment_tracing_settings.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_applied_vaccination_rates_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_incidence_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_infections_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_keysubmissions_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_link_card_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_occupied_intensive_care_beds.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_vaccinated_completely_layout.xml
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_vaccinated_once_layout.xml
  Corona-Warn-App/src/main/res/layout/onboarding_tracing_consent_layout.xml
  Corona-Warn-App/src/main/res/layout/person_overview_item.xml
  Corona-Warn-App/src/main/res/layout/view_expanding_diary_listitem.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/attrs.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: bug, maintainers

#5882 EOL: Update Date (EXPOSUREAPP-14886)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/eol/EolSetting.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/eol/AppEolTest.kt
Labels: maintainers

#5883 Add extra space below card (EXPOSUREAPP-14867)
  Corona-Warn-App/src/main/res/layout/bugreporting_legal_fragment.xml
Labels: bug, maintainers

#5881 Fix: Submission consent screen last bullet point (EXPOSUREAPP-14867)
  Corona-Warn-App/src/main/res/layout/fragment_submission_consent.xml
  Corona-Warn-App/src/main/res/values-de/legal_strings.xml
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
  Corona-Warn-App/src/main/res/values/legal_strings.xml
Labels: bug, maintainers

#5885 Fix: Info transition, Update EOL text (EXPOSUREAPP-14888,14839)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewFragment.kt
  Corona-Warn-App/src/main/res/layout/home_eol_card_layout.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
Labels: bug, maintainers

#5886 Add talkback label when recycle bin is empty (EXPOSUREAPP-14778)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/reyclebin/ui/RecyclerBinOverviewFragment.kt
Labels: bug, maintainers

#5887 Fix censor error report (EXPOSUREAPP-14698)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/storage/CoronaTestStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/flow/FlowExtensions.kt
Labels: bug, maintainers

#5889 EOL: Clear DccWalletInfo (EXPOSUREAPP-14895)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/items/PersonCertificateCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/eol/AppEol.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/CertificateOverviewQrCardView.kt
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/person/ui/overview/PersonOverviewViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/eol/AppEolTest.kt
Labels: bug, maintainers

#5888 Fix: Offline onboarding (EXPOSUREAPP-14893)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/interoperability/InteroperabilityConfigurationFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingDeltaInteroperabilityFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/onboarding/OnboardingTracingFragment.kt
  Corona-Warn-App/src/main/res/layout/fragment_interoperability_configuration.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_delta_interoperability.xml
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_tracing.xml
  build.gradle
Labels: bug, maintainers

#5893 Translation Delivery
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: maintainers

#5892 Remove extra space QrCode (EXPOSUREAPP-13693)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/CertificateOverviewQrCardView.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CertificateStateHelper.kt
Labels: bug, maintainers

#5891 Fix: Several Design-Issues on the screen of Certificate check (EXPOSUREAPP-8802)
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_fragments.xml
  Corona-Warn-App/src/main/res/layout/covid_certificate_validation_result_header_item.xml
Labels: bug, maintainers

#5890 Settings – Position in list is not spoken (EXPOSUREAPP-11535)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/res/menu/menu_main.xml
Labels: bug, maintainers

#5894 Improve talkback in statistics (EXPOSUREAPP-8653)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/IncidenceAndHospitalizationCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/cards/LinkViewCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/res/layout/home_statistics_scrollcontainer.xml
Labels: bug, maintainers

#5895 Update EOL Card (EXPOSUREAPP-14915)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/items/EolCard.kt
  Corona-Warn-App/src/main/res/layout/home_eol_card_layout.xml
  Corona-Warn-App/src/main/res/values-de/links.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values/links.xml
Labels: maintainers, text change

#5899 Bump to next Version 3.2.0.9
  gradle.properties
Labels: maintainers

#5900 Fix: Increased Risk Detail screen `i` (EXPOSUREAPP-14961)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/behavior/BehaviorInfoRow.kt
Labels: bug

#5901 Tweak rampdown details screen (EXPOSUREAPP-14967)
  Corona-Warn-App/src/main/res/layout/fragment_rampdown_notice.xml
Labels: bug

#5903 Fix button width in onboarding screens (EXPOSUREAPP-14970)
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_test.xml
Labels: bug, maintainers

#5904 Fix statistics tiles height with different font sizes (EXPOSUREAPP-14969)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsHomeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/homecards/StatisticsLayoutManager.kt
  Corona-Warn-App/src/main/res/layout/home_statistics_cards_link_card_layout.xml
Labels: bug, maintainers

#5906 Update privacy notice for EOL (EXPOSUREAPP-14955)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: maintainers, text change

#5907 Fix privacy notes (DEV)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
Labels: maintainers, text change

#5908 Fix pandemic radar eol (EXPOSUREAPP-14984)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/source/StatisticsProvider.kt
Labels: bug, maintainers

#5909 Fix wrong state of restored test (EXPOSUREAPAP-11629)f
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/deletionwarning/SubmissionDeletionWarningViewModel.kt
Labels: bug, maintainers

#5912 Fix invalid certs wru z (EXPOSUREAPP-14998)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModel.kt
  Corona-Warn-App/src/testDeviceForTesters/java/de/rki/coronawarnapp/test/debugoptions/ui/DebugOptionsFragmentViewModelTest.kt
Labels: bug, maintainers

#5913 Enable rampdown notice in screenshots (DEV)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
Labels: bug, maintainers
