Repository corona-warn-app/cwa-app-android, pull requests merged in 2023-01, with the labels that each got.

#5783 Bump copyright year in README.md (COMMUNITY)
  README.md
Labels: community

#5782 Buttons spacings (EXPOSUREAPP-14411)
  Corona-Warn-App/src/main/res/layout/fragment_onboarding_tracing.xml
  Corona-Warn-App/src/main/res/layout/fragment_srs_submission_consent.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_done.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_pending.xml
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_positive_no_consent.xml
  Corona-Warn-App/src/main/res/values/styles.xml
Labels: bug, maintainers

#5784 Consent Dark Icons (EXPOSUREAPP-14523)
  Corona-Warn-App/src/main/res/drawable-night/ic_srs_clock.xml
  Corona-Warn-App/src/main/res/drawable-night/ic_srs_virus.xml
Labels: bug, maintainers

#5785 key truncation leads to no entry in the contact journal (EXPOSUREAPP-14524)
  Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/submission/ui/SubmissionTestFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/error/SrsSubmissionTruncatedException.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/model/SrsSubmissionResponse.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/playbook/SrsPlaybook.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/server/SrsSubmissionServer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionNavigation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionViewModel.kt
  Corona-Warn-App/src/main/res/navigation/srs_nav_graph.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/playbook/SrsPlaybookTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/server/SrsSubmissionServerTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/ui/symptoms/calnedar/SrsSymptomsCalendarViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/ui/symptoms/introduction/SrsSymptomsIntroductionViewModelTest.kt
Labels: bug, maintainers, prio

#5786 Submission flow target screens (EXPOSUREAPP-14240)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/invalid/SubmissionTestResultInvalidFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/positive/SubmissionTestResultKeysSharedFragment.kt
Labels: bug, maintainers

#5788 Srs type selection missing text (EXPOSUREAPP-14527)
  Corona-Warn-App/src/main/res/layout/fragment_srs_type_selection.xml
  Corona-Warn-App/src/main/res/values-de/srs_submission_strings.xml
  Corona-Warn-App/src/main/res/values/srs_submission_strings.xml
Labels: bug, maintainers, prio, text change

#5791 Remove superfluous string (EXPOSUREAPP-14381)
  Corona-Warn-App/src/main/res/layout/fragment_submission_test_result_negative.xml
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers, text change

#5789 Add clickable blog link to whole text (EXPOSUREAPP-14348)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/StatisticsExplanationFragment.kt
  Corona-Warn-App/src/main/res/values-bg/strings.xml
  Corona-Warn-App/src/main/res/values-de/strings.xml
  Corona-Warn-App/src/main/res/values-pl/strings.xml
  Corona-Warn-App/src/main/res/values-ro/strings.xml
  Corona-Warn-App/src/main/res/values-tr/strings.xml
  Corona-Warn-App/src/main/res/values-uk/strings.xml
  Corona-Warn-App/src/main/res/values/strings.xml
Labels: bug, maintainers

#5792 Contact Journal 14 days overview - wrong font regarding entered note (EXPOSUREAPP-7783)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/overview/adapter/day/contact/ContactAdapter.kt
Labels: bug, maintainers

#5795 Protocol Buffer update for release 3.1.x at Tue Jan 10 14:30:14 UTC 2023
  Server-Protocol-Buffer/src/main/proto/internal/ppdd/ppa_data.proto
Labels: maintainers

#5796 Extend Ppa for Srs (EXPOSUREAPP-14321)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/AnalyticsModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/AnalyticsKeySubmissionDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/AnalyticsKeySubmissionModule.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/srs/AnalyticsSrsKeySubmissionDonor.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/srs/AnalyticsSrsKeySubmissionRepository.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/srs/AnalyticsSrsKeySubmissionStorage.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/presencetracing/checkins/CheckInsTransformer.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepository.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/srs/AnalyticsSrsKeySubmissionDonorTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/srs/AnalyticsSrsKeySubmissionRepositoryTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/srs/AnalyticsSrsKeySubmissionRepositoryTest2.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/datadonation/analytics/modules/keysubmission/srs/AnalyticsSrsKeySubmissionStorageTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepositoryTest.kt
Labels: maintainers

#5797 Correct introductory text on consent screen (warn others) (EXPOSUREAPP-14378)
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
Labels: bug, maintainers, text change

#5798 Add/change test accessibility ids (EXPOSUREAPP-14304)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/ui/create/ProfileCreateFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/ui/list/ProfileListFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/ui/onboarding/ProfileOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/profile/ui/qrcode/ProfileQrCodeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionDispatcherFragment.kt
  Corona-Warn-App/src/main/res/layout/profile_qr_code_fragment.xml
  Corona-Warn-App/src/main/res/values/attrs.xml
Labels: bug, maintainers

#5800 Bump to next Version 3.0.1.0
  gradle.properties
Labels: maintainers

#5799 Fix: Resetting checkins race conditions (EXPOSUREAPP-14556)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/calendar/SrsSymptomsCalendarViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/ui/symptoms/intro/SrsSymptomsIntroductionViewModel.kt
Labels: bug, maintainers

#5801 Srs screenshot tests (EXPOSUREAPP-14546)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/srs/ui/checkins/SrsCheckinsFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/srs/ui/consent/SrsSubmissionConsentFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/srs/ui/done/SrsSubmissionDoneFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/srs/ui/typeselection/SrsTypeSelectionFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/submission/SubmissionDispatcherFragmentTest.kt
  Corona-Warn-App/src/androidTest/java/testhelpers/FragmentTestModuleRegistrar.kt
Labels: bug, maintainers

#5804 Upgrade AGP 7.4 (DEV)
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: maintainers

#5803 Rampdown notice UI (EXPOSUREAPP-14571)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/rampdown/calculation/RampDownCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/rampdown/ui/RampDownNoticeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/rampdown/ui/RampDownNoticeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_rampdown_notice.xml
  Corona-Warn-App/src/main/res/drawable/ic_rampdown_notice.xml
  Corona-Warn-App/src/main/res/layout/fragment_rampdown_notice.xml
  Corona-Warn-App/src/main/res/layout/home_ramp_down_notice_card.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/navigation/status_nav_graph.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
Labels: maintainers

#5802 Ramp Down Notice (EXPOSUREAPP-14422)
  Corona-Warn-App/proguard-rules.pro
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/rampdown/calculation/RampDownCalculation.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/rampdown/model/RampDownInput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/rampdown/model/RampDownOutput.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/rampdown/ui/RampDownNoticeCard.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/rampdown/ui/RampDownNoticeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeAdapter.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentEvents.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/HomeFragmentViewModel.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/rampdown/RampDownDataProvider.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/rampdown/RampDownNotice.kt
  Corona-Warn-App/src/main/res/drawable-night/ic_rampdown_notice.xml
  Corona-Warn-App/src/main/res/drawable/ic_rampdown_notice.xml
  Corona-Warn-App/src/main/res/layout/fragment_rampdown_notice.xml
  Corona-Warn-App/src/main/res/layout/home_ramp_down_notice_card.xml
  Corona-Warn-App/src/main/res/navigation/nav_graph.xml
  Corona-Warn-App/src/main/res/navigation/status_nav_graph.xml
  Corona-Warn-App/src/main/res/values-night/colors.xml
  Corona-Warn-App/src/main/res/values/colors.xml
  Corona-Warn-App/src/main/res/values/dimens.xml
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/rampdown/calculation/RampDownCalculationTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/main/home/HomeFragmentViewModelTest.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/main/home/rampdown/RampDownDataProviderTest.kt
Labels: maintainers

#5805 Privacy notice issues (EXPOSUREAPP-14560)
  Corona-Warn-App/src/main/assets/privacy_de.html
  Corona-Warn-App/src/main/assets/privacy_en.html
  Corona-Warn-App/src/main/assets/privacy_tr.html
Labels: bug, maintainers

#5806 Correct introductory text on consent screen (warn others) (EXPOSUREAPP-14378)
  Corona-Warn-App/src/main/res/values-tr/legal_strings.xml
Labels: text issue

#5808 Navigate to contact diary app launcher menu (EXPOSUREAPP-14555)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainActivity.kt
Labels: bug, maintainers

#5811 Fix rat malformed error (EXPOSUREAPP-14611)
  Corona-Warn-App/proguard-rules.pro
Labels: bug, maintainers

#5810 Release screen 3.1 (EXPOSUREAPP-14607)
  Corona-Warn-App/src/main/res/drawable/ic_new_release_info_3_0.xml
  Corona-Warn-App/src/main/res/layout/new_release_info_screen_fragment.xml
  Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
  Corona-Warn-App/src/main/res/values/release_info_strings.xml
Labels: maintainers

#5809 Fix app crash when first scanning a certificate (EXPOSUREAPP-14612)
  Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/ui/vaccination/CovidCertificateOnboardingFragmentTest.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/ui/onboarding/CovidCertificateOnboardingFragment.kt
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/ui/onboarding/CovidCertificateOnboardingViewModel.kt
Labels: bug, maintainers

#5812 Dialog causes crash when put in background (EXPOSUREAPP-14569)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/srs/core/repository/SrsSubmissionRepository.kt
Labels: bug, maintainers

#5815 Contact Diary Alert Popup Wrong Delete Location Button Text (EXPOSUREAPP-14620)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/ui/location/ContactDiaryAddLocationFragment.kt
Labels: bug, maintainers

#5816 Gradle 7.5.1 (DEV)
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: maintainers

#5818 Gson refactoring issues (EXPOSUREAPP-14616,14626)
  Corona-Warn-App/proguard-rules.pro
Labels: bug, maintainers

#5820 Bump to next Version 3.0.2.0
  gradle.properties
Labels: maintainers

#5819 Trigger calc on configuration loading (EXPOSUREAPP-14631)
  Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/home/rampdown/RampDownDataProvider.kt
  Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ui/main/home/rampdown/RampDownDataProviderTest.kt
Labels: bug

#5821 Add new Pins (EXPOSUREAPP-14648)
  Corona-Warn-App/src/main/res/xml/network_security_config.xml
Labels: maintainers
